### ISSUE TITLE
Positional arguments don't work for run-remote-script (v. 0.6.0)

### ISSUE THREAD

**Issue by dennybaa** [StackStorm/st2#1029]
Maybe same on later, I haven't checked.

```
MESSAGE: Additional properties are not allowed (u'cmd' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'additionalProperties': False,
...
```

**Comment by Kami** [comment]
Can you please include the whole metadata file?

**Comment by Kami** [comment]
Actually, nvm. That's intentional - you can specify `cmd` argument with a remote runner.

Remote runner directly runs the script so specifying `cmd` doesn't make sense in that context.

**Comment by dennybaa** [comment]
@Kami here's it https://gist.github.com/3425dbcd7a42d5cbdbd2.

Here's the command `st2 run chef.ohai hosts=st2_agent_1 etc/passwd/root`.

* run-remote accepts positional parameter, this nice okay.
* **strange** if there's no such optional positional argument provided, argv is:  "['/tmp/54cd2f7d2481ed03171ba4c9/chef_ohai.py', 'None'].. ?
* Why run-remote-script should not support positional arguments? This is unclear...

**Comment by dennybaa** [comment]
Maybe just in 0.6.0 positional arguments are not supported for remote scripts. Because if we look at https://github.com/StackStorm/st2/blob/master/st2actions/st2actions/runners/fabricrunner.py#L155 in master. It should pass positional parameters... Or not?

**Comment by dennybaa** [comment]
Here's also the code (https://github.com/dennybaa/st2contrib/blob/chef-pack/packs/chef/actions/chef_ohai.py#L13) which looks a bit ugly because:
* I've got to use run-remote because of lacking of positional arguments in run-remote-script.
* As I use run-remote, it's meant to be run with command, but in my case command might be missing and  I've got to filter **None** value on the command line.

**Comment by Kami** [comment]
@dennybaa 

Sorry, let me try to clarify it.

Position arguments are supported to make re-using and porting existing scripts easier. They have nothing do do with the CLI syntax, but they tell the runner how to pass parameters to the script aka how to call the script. 

When you specify the parameters using CLI, you need to always use `parameter=value` syntax. If you specify `position` attribute in the metadata definition, this parameter value is then passed to the script as a positional argument.

You can find an example of that here - http://docs.stackstorm.com/actions.html#update-argument-parsing-in-the-script

Hopefully that clears it up.

**Comment by Kami** [comment]
And as far as your ohai example goes, you would call the action like this:

```bash
st2 run chef.ohai hosts=st2_agent_1 path=/etc/passwd/root
```

Which would be converted to the following line when calling the script:

```bash
chef_ohai.py /etc/passwd/root
```

**Comment by dennybaa** [comment]
Thanks for clarification, I've read that doc but maybe not careful enough about positional arguments. So we are going to stick to such behavior with the explicit parameter name should exist as I understand?
It's generally okay. But it seems a bit clumsy, how ever it might be inspired by python "explicit is better than implicit" approach :)

**Comment by Kami** [comment]
Closing since this has been resolved (not an issue, just the documentation wasn't clear enough).
