### ISSUE TITLE
0.8dev-38 breaks web

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2#1032]
Just want to file this here...

one of these changes:
- https://github.com/StackStorm/st2/pull/1030
- https://github.com/StackStorm/st2/pull/1028

Has rendered the UI broken. Just hangs. Reverted back to `0.8dev-36` to get moving again.

/cc @Kami @enykeev

**Comment by Kami** [comment]
Hm, I don't think any of those changes should affect the UI.

It it possible that a change in webui repo broke it?

**Comment by jfryman** [comment]
@Kami it's weird, right? Well, I think it's something there... it's brittle. I tried a two revs of `st2web` (`master` and `v0.6.0`), both failed. The former at least said there was a network problem, but logs would see the request and just end.

Rolling back from Rev 38 to Rev 36 fixed it right up for both revs of `st2web`

**Comment by manasdk** [comment]
@jfryman Can you make sure that https://github.com/StackStorm/st2/blob/master/conf/st2.conf#L31is correctly set.

**Comment by jfryman** [comment]
Even after setting `api_base`, I still had problems. Looks like it is was a CORS issue. Fixed by setting the `allow_origin` setting in `/etc/st2/st2.conf` to `*`. I'll change this for a production node, but should be good for dev.

**Comment by manasdk** [comment]
@jfryman I guess you mean `api_url` to be specified https://github.com/StackStorm/st2/blob/master/conf/st2.conf#L31

**Comment by jfryman** [comment]
@manasdk Yes sir! Thanks for the help.
