### ISSUE TITLE
In rule criteria, handle null/undef payload

### ISSUE THREAD

**Issue by dzimine** [StackStorm/st2#1115]
> The one fix/feature we are really looking for right now is the ability to have triggers treat unset payload variables as “null/undef”, yet still run. A situation we run in to is having a pair of triggers, where we want one to match if a particular payload variable was set to true (ie. payload.whatever=true), otherwise match a different trigger criteria(ie. payload.whatever != true which also means unset or undef). Right now, if the payload does not contain a payload variable mentioned in the criteria, it will never match. 

Something like 'empty' or 'not_empty', or 'exists' / 'not_exists'... 
https://github.com/StackStorm/st2/blob/master/st2common/st2common/operators.py#L115-L137

**Comment by jfryman** [comment]
I vote for `exists`/`notexists|nexist`. The negative should be consistent with the pattern we're already using.

**Comment by dzimine** [comment]
Fix committed, please confirm it makes you happy. https://github.com/StackStorm/st2/pull/1117#issuecomment-75939132
cc @Kami

**Comment by Kami** [comment]
Fix has been merged so I'm closing this issue.
