### ISSUE TITLE
Fix / update linux.scp action

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#1236]
Currently, `linux.scp` action is mostly useless if you want to download files from a remote server to a local one since it expects a `dest_server` argument.

We have a couple of ways to solve this:
1. Make `scp` action "desination agnostic" - instead of taking `dest_server` parameter, make it just take `source` and `destination` arguments. This way it works both ways (upload, download) since source and destination can either be a remote host with a path or just a path.
2. Rename existing `scp` action to `scp_upload` and add a new inverse `scp_download` action.

**Comment by jfryman** [comment]
I like the idea of `upload`/`download` personally. This feels more like a generic action (get file, put file) that could switch backends if need be (FTP, FTPS, maybe CIFS/NFS), and would make actions more interchangeable. I see this as being some cases with ETL that we will have come up before long.

**Comment by Kami** [comment]
Resolved by #3335 #3463
