### ISSUE TITLE
Document the upgrade from 0.7 to 0.8

### ISSUE THREAD

**Issue by dzimine** [StackStorm/st2#1245]
### A) re-provision an st2 box, and copy the context:
1. provision a new box
1. from the old box, copy the content of /opt/stackstorm/ to the new box (we recommend to keep all the content in SCM like git)
1. Copy  your configuration from /etc/st2/st2.conf to the new box
1. install st2 0.8 on a new box
1. run `st2ctl reload —register-all && st2ctl restart`

### B) Upgrade on the same box: 

1. while on 0.7, run [the cleanup script from here](https://gist.github.com/m4dcoder/6d1f7cbdc5faa7fa7634)
1. [install st2](http://docs.stackstorm.com/install/index.html) 0.8 using `st2_deploy.sh` 

### Notes

0.8 contains some changes in DB schema changes and API. 

StackStorm follows "infrastructure as code": all the content and artifacts are files on disk; the database is just a content 'cache' + current state, for efficient implementation. Thus the backup, restore, and upgrade, is all about working with the file based content.

When database is dropped, the execution history won't longer be seen via st2; however it is saved in the `audit` files under `/var/log/st2`, we recommend integration with logstash / splunk / etc. for working with accumulated history data.

**Comment by Kami** [comment]
Closing since 0.8 is not supported anymore now that 0.9 and 0.10 are out.
