### ISSUE TITLE
Refactor and improve st2ctl

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#1344]
Currently, st2ctl is a hard to maintain mess. The problem is that we are keep adding stuff without refactoring it.

We could make the whole script 10 times easier to read and maintain if we just refactored the code a bit and do things:

1. Use arrays and for loops (get rid of nasty hard-coded ifs)
2. Reduce 4 levels of if nesting (use return early approach)
3. Reduce duplicated code

**Comment by manasdk** [comment]
Don't see us getting this done in 0.10. I vote for pushing it out as there is no user impact.

**Comment by Kami** [comment]
Yeah, that's fine. We can move it to the next release.
