### ISSUE TITLE
Installation script bug: `st2_deploy.sh latest`

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#1446]
According to [Installation Docs](http://docs.stackstorm.com/install/index.html#installation) It's possible to pass `latest` parameter to [installation script](https://downloads.stackstorm.net/releases/st2/scripts/st2_deploy.sh).

```sh
sudo ./st2_deploy.sh latest
sudo ./st2_deploy.sh stable
```
However it doesn't work.
The reason is that `$LATEST` (or `$STABLE`) from st2_deploy.sh looks like: 
```sh
LATEST=`curl -Ss -q https://downloads.stackstorm.net/deb/pool/trusty_unstable/main/s/st2api/ | grep 'amd64.deb' | sed -e "s~.*>st2api_\(.*\)-.*<.*~\1~g" | sort | uniq`
echo "$LATEST"
0.10dev
0.9
0.9.0
0.9dev
```
which generates incorrect download URL:
`https://downloads.stackstorm.net/releases/st2/0.10dev 0.9 0.9.0 0.9dev/debs/st2_deploy.sh`

Also: https://downloads.stackstorm.net/releases/st2/0.9/debs/st2_deploy.sh - 404

**Comment by Kami** [comment]
Thanks for the report. We are looking into a fix.

**Comment by Kami** [comment]
As per @DoriftoShoes, this has not been resolved. Thanks again for the report.
