### ISSUE TITLE
EPOLL_CTL_ADD failed

### ISSUE THREAD

**Issue by jamiees2** [StackStorm/st2#1534]
I am trying to use the `windows-script` runner to execute a PowerShell script, but i continually get the following error:
```
{
    "message": "Failed to retrieve absolute path for share "C$"",
    "traceback": "  File "/usr/lib/python2.7/site-packages/st2actions/container/base.py", line 100, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/usr/lib/python2.7/site-packages/st2actions/runners/windows_script_runner.py", line 91, in run
    base_path = self._get_share_absolute_path(share=self._share)
  File "/usr/lib/python2.7/site-packages/st2actions/runners/windows_script_runner.py", line 231, in _get_share_absolute_path
    raise Exception(msg + stdout + stderr)
"
}
```

Some additional debugging (printing stdout) showed this error:
```
Unknown parameter encountered: "max log size"
Ignoring unknown parameter "max log size"
Unknown parameter encountered: "passdb backend"
Ignoring unknown parameter "passdb backend"
Unknown parameter encountered: "load printers"
Ignoring unknown parameter "load printers"
Unknown parameter encountered: "cups options"
Ignoring unknown parameter "cups options"
Unknown parameter encountered: "writable"
Ignoring unknown parameter "writable"
Unknown parameter encountered: "guest ok"
Ignoring unknown parameter "guest ok"
Unknown parameter encountered: "writable"
Ignoring unknown parameter "writable"
tevent: EPOLL_CTL_ADD failed (Operation not permitted) - falling back to select()
```
I also made it print out the command it was trying to execute, and tried manually executing the outputted command, which works as expected. Any ideas?

**Comment by jamiees2** [comment]
To add, this is running on CentOS 7, installed from `st2_deploy.sh`

**Comment by jamiees2** [comment]
I found that the issue has to do with winexe not having a TTY, http://lists.wpkg.org/pipermail/wpkg-users/2011-March/007293.html

How did you guys get it working?

**Comment by Kami** [comment]
I believe this is the same issue @dzmine encountered and https://github.com/StackStorm/st2/pull/1427 fixed it for him.

This fix should already be included in the latest stable 0.9.x release though.

I will try to reproduce the bug myself by running thr action runner in a non-tty myself and see what happens.

**Comment by jamiees2** [comment]
I am running v0.9.0.11 if that helps, perhaps i'll try updating.

**Comment by Kami** [comment]
You can try upgrading to v0.9.2, but I believe the fix should already be included in v0.9.0.

**Comment by jamiees2** [comment]
Upgrading to v0.9.2 does not seem to have fixed it, I noticed however that i am running winexe v1.00, but  that is the version as installed by `st2_deploy.sh`. The guide says to use v1.1, but I can't find it in any package repository.

Running `yum info winexe` gives:
```
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.t.is
 * epel: www.fedora.is
 * extras: centos.t.is
 * updates: centos.t.is
Installed Packages
Name        : winexe
Arch        : x86_64
Version     : 1.00
Release     : 2.4
Size        : 6.3 M
Repo        : installed
From repo   : st2-f20-deps
Summary     : winexe
License     : GPL3
Description : winexe
```

**Comment by Kami** [comment]
Yeah, it should also work with winexe_1.00.1-1 (that's the one we tested it with), but I will also look into building packages for the latest version.

**Comment by jamiees2** [comment]
I managed to get it working with winexe 1.1, but with one caveat: the --password option seems to have been removed in the latest version or something.

Perhaps it has to do with the build, but I had to change `windows_runner.py` to instead use the `-U` version.

Winexe v1.00 supports the `-U` option containing passwords aswell, so perhaps a change might be considered?

**Comment by Kami** [comment]
@jamiees2 Yeah, I will look into using an alternative syntax for specifying the credentials. I believe we already use that syntax for the smbclient.

**Comment by Kami** [comment]
And yeah, I just checked the source code and confirmed that the "--password" option was indeed removed in the latest version.

**Comment by jamiees2** [comment]
I changed it locally, and it works there, and you have a pull request :) #1535

To install winexe 1.1, I had to go through the Fedora package repos, and ran this to get the RPM:

`wget http://download.opensuse.org/repositories/home:/GRNET:/synnefo/Fedora_21/x86_64/winexe-1.1pre_20140109-28.1.x86_64.rpm`

In general, this issue seems to be fixed, and I'm closing.

**Comment by Kami** [comment]
Great, thanks!

I will also work with @DoriftoShoes and make sure we build and provide packages for latest version of winexe since it contains some other fixes and improvements as well :)

**Comment by jamiees2** [comment]
Great! Will this be in a minor release or in v0.10?

**Comment by Kami** [comment]
I will talk with the team, but I think it's reasonable to spin up v0.9.3 with this change.

In any case, v0.10.0 should hopefully also be out in a couple of weeks.
