### ISSUE TITLE
Issue with alias and default value

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2#1537]
Some bugs with aliases and default values -

```
---
name: "google_query"
action_ref: "google.get_search_results"
formats:
  - "google {{query}} {{count=10}}"
```

`google test count=10` - works
`google test` - fails

needs to be fixed.

**Comment by jtopjian** [comment]
Thanks, @manasdk. Just to be explicit, the result of running:

```
!google foobar
```

Should be translated into:

```
google.get_search_results query=foobar count=10
```

**Comment by manasdk** [comment]
@jtopjian Thanks for the clarification!

**Comment by Kami** [comment]
This is fixed now.

Thanks for the report and @manasdk for fixing it :P
