### ISSUE TITLE
Pack deploy sub-tree option not supported in install action-chain

### ISSUE THREAD

**Issue by joecise** [StackStorm/st2#1616]
Support for/requirement to use the subtree flag was added as part of https://github.com/StackStorm/st2/commit/fd279244aa68ed74a1449915b9a8d2801ec660e5. But the install action-chain (https://github.com/StackStorm/st2/blob/master/contrib/packs/actions/install.meta.yaml) was not updated to also support it.

**Comment by Kami** [comment]
#1623 should resolve it.

**Comment by joecise** [comment]
Thanks!
