### ISSUE TITLE
st2ctl should validate if mistral/component is installed. if not skip warning.

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#1643]
Reported by: @skarmark on freenode.

```
17:07:24 <hikertechy> lol. For me, whatever lets me install and start without mistral is good..since, it is not a requirement for other services :)
17:07:32 <hikertechy> warning is fine as well
```

**Comment by skarmark** [comment]
Another maybe related and unrelated problem. st2ctl start should not start duplicate services when the st2 services are already running -

https://gist.github.com/skarmark/4fe81ba2b7d353a09432

**Comment by lakshmi-kannan** [comment]
@skarmark Created a different issue for dupe processes. https://github.com/StackStorm/st2/issues/1652

**Comment by lakshmi-kannan** [comment]
With new st2ctl, st2ctl outsources things to init systems.
