### ISSUE TITLE
st2ctl shouldn't start processes if they are already started. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#1652]
https://gist.github.com/skarmark/4fe81ba2b7d353a09432

Reported by: @skarmark on freenode.

**Comment by armab** [comment]
Obsolete.
`st2ctl` is now a wrapper over real/normal linux services and doesn't control/kill processes directly.

No problems with existing `sysV`, `upstart`, `systemd` startup scripts at the moment.
