### ISSUE TITLE
When triggering action chain from chatops, it would be cool to inject the channel name as an action param to the chain. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#1715]
Reported by: eMptywee on IRC

**Comment by manasdk** [comment]
Ahem ... probably won't happen exactly like that but if required we can pass that value in by making it available in the context for the action.

**Comment by emptywee** [comment]
Yeah, the more things about conditions and circumstances the action was triggered under the better. Knowing more about environment is always good.

**Comment by emptywee** [comment]
@manasdk It looks like this has been implemented and released into stable. Could you update docs or drop a usage example here? My memory is short :) Thanks.

**Comment by manasdk** [comment]
@emptywee Yeah good point. Will add docs.

**Comment by lakshmi-kannan** [comment]
@emptywee Docs being added as part of https://github.com/StackStorm/st2/pull/1755. Feel free to comment on that PR.
