### ISSUE TITLE
st2-self-check is broken. Claims success even when tests fail.

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#1740]
See https://gist.github.com/lakshmi-kannan/3ae8af1b1be9f078b2e9

**Comment by DoriftoShoes** [comment]
What version of st2?  I believe this is fixed in master.

**Comment by lakshmi-kannan** [comment]
/V/s/s/st2workroom git:fix_ip ❯❯❯ cat hieradata/workroom.yaml                                                                                                                                                                       ✭
### User configurable settings
## Place any user-configurable settings here.

## StackStorm Versions
st2::version: 0.12dev
st2::mistral_git_branch: st2-0.9.0

**Comment by lakshmi-kannan** [comment]
I assume nothing about this was fixed in last couple of days?

**Comment by DoriftoShoes** [comment]
I'll have to look in to it but this should catch it:
https://github.com/StackStorm/st2/blob/master/tools/st2-self-check#L63

**Comment by DoriftoShoes** [comment]
LOL
I see it.  Will fix.
