### ISSUE TITLE
TestLocalShellRunner fails if stanley user is not available

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2#1743]
https://github.com/StackStorm/st2/blob/78ea95791b24f34ab6f113b176ae0de7497ad4c1/st2actions/tests/integration/test_localrunner.py#L32

Either the test should guarantee the user or have a way to easily provide an alternate user. Assuming `stanley` becomes messy.

**Comment by Kami** [comment]
I thought this was a known pre-requisite since integration tests have many other pre-requisites as well (MongoDB needs to be running, etc.).

In any case, that's something we should make explicit in the docs.

**Comment by manasdk** [comment]
> I thought this was a known pre-requisite

Not saying user will not be provided just that the user has to be `stanley` would be an issue.

**Comment by Kami** [comment]
@manasdk That's fair.

It sounds like we should use the value from the tests configuration?

**Comment by manasdk** [comment]
> It sounds like we should use the value from the tests configuration?

Yes. That would work.

**Comment by LindsayHill** [comment]
Doesn't seem to be relevant any more.
