### ISSUE TITLE
St2ctl stop will exit with 1 if you dont have mistral installed

### ISSUE THREAD

**Issue by Itxaka** [StackStorm/st2#1776]
As far as I understand mistral is optional, so st2ctl should not exit with a failure if mistral is not installed as it makes it very difficult to use with automated provisioning.

On chef we need to do:
```
execute 'Stop StackStorm' do
  command "st2ctl stop; exit 0"
  ignore_failure true
end
```

in order to have the deploy work. st2ctl should either autodetect what services are installed or ignore optional components.

May also affect st2web.

**Comment by lakshmi-kannan** [comment]
Related: https://github.com/StackStorm/st2/issues/1643

**Comment by armab** [comment]
closed by https://github.com/StackStorm/st2/pull/2049
