### ISSUE TITLE
Slack channel requires a stackstorm email address

### ISSUE THREAD

**Issue by robzienert** [StackStorm/st2#1803]
I tried to sign into the slack community chat today and wasn't allowed in because I don't have an @stackstorm email address.

**Comment by Kami** [comment]
You can sign up here - https://stackstorm.typeform.com/to/K76GRP and an invite should automatically be sent to your email address.

You can then use this invite to join http://stackstorm-community.slack.com Slack instance

**Comment by lakshmi-kannan** [comment]
@robzienert You should have an invite now. The problem was not with non stackstorm email address. We have a sensor that links typeform to invites. It appears typeform APIs were returning 5XXs and our sensor crashed. It couldn't respawn because this https://github.com/StackStorm/st2/pull/1798 is not deployed to that box yet. We'll work on upgrading the box to latest st2. Thanks for the bug report and apologies for the delay in the invite. I just got my invite for a non-stackstorm email. LMK if you don't have the invite and I can debug further. Logs show you were sent out an invite.

**Comment by Kami** [comment]
Heh, I assumed something like this might be going on, but I wasn't sure that the form was used, so I rather asked :)

In any case, it might be worth adding some text to that form which says you should contact us and include your email address if you don't receive an invite in an hour or something along those lines.

**Comment by lakshmi-kannan** [comment]
That server is now running the latest version of st2. 

```
root@pinkiepie:/home/lakshmi/st2incubator# st2 sensor list
+-------------------------------------+----------+----------------------------+-----------------------+
| ref                                 | pack     | name                       | trigger_types         |
+-------------------------------------+----------+----------------------------+-----------------------+
| linux.FileWatchSensor               | linux    | FileWatchSensor            | linux.file_watch.line |
| typeform.TypeformRegistrationSensor | typeform | TypeformRegistrationSensor | typeform.registration |
+-------------------------------------+----------+----------------------------+-----------------------+
root@pinkiepie:/home/lakshmi/st2incubator# less /var/log/st2/st2sensorcontainer.log
root@pinkiepie:/home/lakshmi/st2incubator# ps auxww | grep typeform
root      4143  2.8  1.0 193976 41364 pts/4    S    23:40   0:01 /opt/stackstorm/virtualenvs/typeform/bin/python /usr/lib/python2.7/dist-packages/st2reactor/container/sensor_wrapper.py --pack=typeform --file-path=/opt/stackstorm/packs/typeform/sensors/registration_sensor.py --class-name=TypeformRegistrationSensor --trigger-type-refs=typeform.registration --parent-args=["--config-file", "/etc/st2/st2.conf"] --poll-interval=30
root      4235  0.0  0.0  10460   940 pts/4    S+   23:41   0:00 grep --color=auto typeform
root@pinkiepie:/home/lakshmi/st2incubator# st2 --version
st2 ('0.13dev.179',)
root@pinkiepie:/home/lakshmi/st2incubator#
```

With this, I also picked up the bug fixes for the typeform sensor https://github.com/StackStorm/st2incubator/pull/238. 

Closing issue. Will open another issue for adding text to contact us on invite SLA breach.
