### ISSUE TITLE
Webhook notification from travis_ci to stackstorm

### ISSUE THREAD

**Issue by johnugeorge** [StackStorm/st2#1813]
In Travis ci, web hooks are delivered using url encoded string while stackstorm expects this to be a json. 
http://docs.travis-ci.com/user/notifications/#Webhooks-Delivery-Format
This causes "Invalid Json" error when stackstorm receives the notification . 

In the current enviroment, how does everyone integrate travis_ci and stackstorm  in the environment. Is there any other way to solve it ? Using the current travis_ci packs, I could also see that travis_ci builds can't be started from stackstorm.  The ideal environment would be,  whenever there is a github pull request, from stackstorm we should be able to start the build, get the build notification status and restart the build if needed.
Is it possible now?

**Comment by Kami** [comment]
One option would be for us to support multiple content types for the payload which is sent via webhook (IIRC, we already talked about this in the past).

To begin with, we can support JSON and URL encoded form data. Other option would be to use a sensor or a similar approach, but imo, this is less than ideal. Supporting and maintaining a sensor is way more complicated than supporting multiple content types in the webhook handler.

**Comment by johnugeorge** [comment]
I agree.  I don't understand why Travis_ci sticks to this strange format.  Is there any workaround for this?. And Travis being a popular platform, how is it currently used with stackstorm if notifications from travis are broken ?

**Comment by Kami** [comment]
### Starting a Travis CI build

I believe this is just a missing action in travis_ci pack right now. If Travis CI exposes an API for starting a build (I'm pretty sure it does), it should be relatively easy to write a new action which does that.

/cc @Aamir-raza-1

### Receiving Travis CI build notifications

A solution for now would be to write a new TravisCI build sensor which exposes an HTTP server which knows how to handle Travis CI payload format.

It's not ideal and means more code and configuration to maintain (and another port to whitelist on the firewall side), but some other sensors also do a similar thing right now (a bit complex example of that is existing NewRelic sensor - https://github.com/StackStorm/st2contrib/blob/master/packs/newrelic/sensors/newrelic_application_sensor.py).

I will also brainstorm with other co-workers (/cc @manasdk @lakshmi-kannan and others) and try to come up with a better solution which doesn't require a sensor.

**Comment by johnugeorge** [comment]
Thanks!

**Comment by Aamir-raza-1** [comment]
@Kami, The actions for starting and canceling  a Travis build have been already written.

**Comment by Kami** [comment]
@Aamir-raza-1 I thought so as well, but then I checked the st2contrib repo and I didn't find start action (there only is cancel and restart) - https://github.com/StackStorm/st2contrib/tree/master/packs/travis_ci/actions

**Comment by Aamir-raza-1** [comment]
The start and restart are the same, it has the same API call of `restart build` to start the travis build. I have seen its documentation it doesnot mention start the build instead `restarting` the build has been listed.
http://docs.travis-ci.com/api/#builds

**Comment by enykeev** [comment]
Looks like the problem was resolved in v2.0.1 (https://github.com/StackStorm/st2/pull/2477). Please reopen if the issue persists.
