### ISSUE TITLE
API should return proper content type for errors

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2#1819]
Currently, if you try to get the list of actions without providing a token on `auth: true` host, you'll get a json formatted error message `{"faultstring": "unauthorized"}`, but headers would say this is `Content-Type: text/plain` preventing most of the clients (incuding st2client.js) from automatically parsing it.

If we respond with json, we need to properly announce that through content-type header.

Place in code likely requiring the change: https://github.com/StackStorm/st2/blob/4f1ac919f6c1220d03e9098e4d6949013331ddc7/st2common/st2common/hooks.py#L138-L141

**Comment by Kami** [comment]
Good catch.

Will push a fix.
