### ISSUE TITLE
cli should have an easy way to enable/disable rule

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2#1827]
something like 

`st2 rule enable/disable <rule_id>`

Perhaps it could be extended to actions even -

`st2 action enable/disable <action_id> `

**Comment by Kami** [comment]
I've opened a PR for this many months ago, but we decided against merging it because of the whole file sync issues (next time the content is loaded from disk, this value would be overridden with the value from file).

**Comment by manasdk** [comment]
@Kami Right. I am pretty sure I must've been the one to complain about the file sync issue.

**Comment by Kami** [comment]
Just FYI, this is that PR - #940.

If we are fine with that limitation for now, I can revive it and get it merged (hopefully, content distribution story will get sorted in the near future).

**Comment by Kami** [comment]
#940 has been merged, closing this issue.
