### ISSUE TITLE
st2ctl should not explode if Mistral is not installed

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#1851]
As described here - https://github.com/StackStorm/st2/issues/1841#issuecomment-132733960 st2ctl should handle Mistral not being installed more gracefully.

This means the should only try to manage Mistral service (start, restart, etc.) if Mistral is installed and available (we will need to do some "is installed" detection in the script).

**Comment by lakshmi-kannan** [comment]
Related: https://github.com/StackStorm/st2/issues/1776

**Comment by armab** [comment]
closed by https://github.com/StackStorm/st2/pull/2049
