### ISSUE TITLE
When use_paramiko_ssh_runner = True, remote-shell-cmd incorrectly handling user permissions 

### ISSUE THREAD

**Issue by Heshuge** [StackStorm/st2#1899]
While debugging some remote scripts I ran into a strange user permission error when running a remote-shell-cmd.

This was shortly after updating to version 0.13, so in order to check if the paramiko runner was causing the issue, I disabled it in st2.conf and restarted st2.

After restarting, the remote-shell-cmd worked again, as it had done before the update.

This first screenshot is of the failing action when using use_paramiko_ssh_runner = True

![screen shot 2015-08-27 at 4 23 34 pm](https://cloud.githubusercontent.com/assets/4655474/9532324/fdc5b976-4cd8-11e5-84f7-e94cfab071c1.png)

This second screenshot is of the 'passing' action when using use_paramiko_ssh_runner = False
![screen shot 2015-08-27 at 4 23 59 pm](https://cloud.githubusercontent.com/assets/4655474/9532371/43743358-4cd9-11e5-952f-fad583be7a9f.png)

**Comment by lakshmi-kannan** [comment]
:cry:

**Comment by lakshmi-kannan** [comment]
@Heshuge: Bug fix PR is out https://github.com/StackStorm/st2/pull/1903. I also wrote some documentation to clear things up https://github.com/StackStorm/st2/pull/1903/files#diff-2fc5c0de2b7bedc6d17e213779785a79R1. Feel free to comment.

**Comment by Heshuge** [comment]
Thanks!
