### ISSUE TITLE
st2 command displays requests warning

### ISSUE THREAD

**Issue by powellchristoph** [StackStorm/st2#1923]
When running the st2 command, you are spammed with warnings from the requests library. It would be nice to disable these as it make reading/parsing the output difficult.

This was installed on Ubuntu 14.04.03 LTS with the All-In-One-Installer.

```
root@stackstorm-test:~# st2 action list --pack=core
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
+------------------+------+-------------+----------------------------------------------+
| ref              | pack | name        | description                                  |
+------------------+------+-------------+----------------------------------------------+
| core.http        | core | http        | Action that performs an http request.        |
| core.local       | core | local       | Action that executes an arbitrary Linux      |
|                  |      |             | command on the localhost.                    |
| core.local_sudo  | core | local_sudo  | Action that executes an arbitrary Linux      |
|                  |      |             | command on the localhost.                    |
| core.remote      | core | remote      | Action to execute arbitrary linux command    |
|                  |      |             | remotely.                                    |
| core.remote_sudo | core | remote_sudo | Action to execute arbitrary linux command    |
|                  |      |             | remotely.                                    |
| core.sendmail    | core | sendmail    | This sends an email                          |
| core.windows_cmd | core | windows_cmd | Action to execute arbitrary Windows command  |
|                  |      |             | remotely.                                    |
+------------------+------+-------------+----------------------------------------------+
```

```
# uname -ra
Linux stackstorm-test 3.13.0-62-generic #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Kami** [comment]
I don't get those locally so it could be something related to your installation. Which installation method did you use?

As far as simply disabling those warnings - we could definitely do that, but I don't think that's the right thing to do since it masks potential security issues.

Edit: I just checked around and it looks like you get those warnings if you use Python < 2.7.9. You can get rid of them by upgrading to the latest version of Python 2.7.x or by installing "requests[security]" package - `pip install requests[security]`.

As far as installing `pip install requests[security]` by default goes - I would need to have a look since it has some pre-requisites such as openssl dev headers, etc.

**Comment by jfryman** [comment]
@Kami This is via the All-in-one installer, which creates a Self-Signed SSL certificate unless the user provides their own. So, this will be a common experience for folks trying us out.

**Comment by Kami** [comment]
@jfryman ah, thought it could be something like that.

Since it's all running on the same box, we could easily add that self-generated certificate to the requests trust chain for st2client.

I could add a new option to the st2client config file and then we would populate it with a path to the CA cert when we generate it.

**Comment by jfryman** [comment]
> I could add a new option to the st2client config file and then we would populate it with a path to the CA cert when we generate it.

I'll have to change this up a bit. Right now, I only create a self-signed cert w/o CA, so I'll need to re-work a bit of logic. I have most of it setup, but I'll make a point to fix this today.

**Comment by Kami** [comment]
Alright, sounds good.

Feel free to create a Github issue for the st2client part of it and assign it to me.

**Comment by lakshmi-kannan** [comment]
I think this is fixed now. Closing.
