### ISSUE TITLE
hubot !help not lining up with reality with "restart"

### ISSUE THREAD

**Issue by mamercad** [StackStorm/st2#1952]
Hubot's `! help` menu (with a bot named 'stanley') shows:
```
! stanley restart - Restart stanley
! stanley restart on {{hosts}} - Restart stanley
```
Issuing `! stanley restart` seemingly does nothing, but `! hubot restart` restarts the bot.

**Comment by emedvedev** [comment]
Fixed with the `hubot-help` patch.
