### ISSUE TITLE
Local action runner does not honor /etc/environment

### ISSUE THREAD

**Issue by tedwards** [StackStorm/st2#1988]
Commands run under `core.local` run with the environment variables provided by upstart job for `st2actionrunner`, which is a very minimal environment.  

It would be handy if the `st2actionrunner-worker` upstart jobs sourced the /etc/environment definitions, or perhaps if `ActionRunner` sourced them when defining the `os.environ` for the command subprocess.

**Comment by Kami** [comment]
Thanks for the report.

You are right - currently local runner actions which result in the sudo being user don't run using a login shell (http://docs.stackstorm.com/latest/config/config.html?highlight=setenv#sudo-access - I will add this note here).

It looks like changing the sudo command to use `-i` flag should do the trick, but we would obviously need to test this and make sure it doesn't break something :)

Right now we are very busy with working on the 1.0 release, but that's something we will look into after the 1.0 release.

**Comment by armab** [comment]
This works with the [new packages](https://github.com/StackStorm/st2-packages/tree/master/packages/st2) now.

As it should be with accordance to Linux practices: 
- [`/etc/sysconfig/st2actionrunner`](https://github.com/StackStorm/st2-packages/blob/0cedcc2046f5b3d05175265a70d7f9b84713512b/packages/st2/rpm/st2actionrunner%40.service#L12) - sourced by init in redhat family systems
- [`/etc/default/st2actionrunner`](https://github.com/StackStorm/st2-packages/blob/0cedcc2046f5b3d05175265a70d7f9b84713512b/packages/st2/debian/st2.st2actionrunner-worker.upstart#L17-L21) - sourced by init in debian family systems


Tested & verified.
