### ISSUE TITLE
cannot import name strip_last_newline_char

### ISSUE THREAD

**Issue by DoriftoShoes** [StackStorm/st2#1994]
Reported by community user.  `packs.reload` failed with the following error:

"traceback": "  File \"/usr/lib/python2.7/dist-packages/st2actions/worker.py\", line 106, in _run_action\n    result = self.container.dispatch(liveaction_db)\n  File \"/usr/lib/python2.7/dist-packages/st2actions/container/base.py\", line 55, in dispatch\n    runner = get_runner(runnertype_db.runner_module)\n  File \"/usr/lib/python2.7/dist-packages/st2actions/runners/__init__.py\", line 50, in get_runner\n    raise ActionRunnerCreateError(e)\n",
        "error": "cannot import name strip_last_newline_char”

**Comment by lattwood** [comment]
Community user reporting in.

Here's my `/usr/lib/python2.7/dist-packages/st2common/util/misc.py`

https://gist.github.com/lattwood/24de666b15e39dffff17

**Comment by manasdk** [comment]
Running `st2ctl restart` fixed the issue. The odd part is that `st2actionrunners` were running new code but the referenced method from `st2common` was missing i.e. still old code. This should not really happen but it oddly did - how could we end up in this situation where `st2action` module is updated but `st2common` is not?

**Comment by lattwood** [comment]
It was updated @manasdk. I believe `st2ctl restart` wasn't issued during the setup wizard in the web gui after the stackstorm packages were updated.

```
Start-Date: 2015-09-15  21:21:12
Commandline: /usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install st2common=0.13.2-5
Upgrade: st2common:amd64 (0.13.1-4, 0.13.2-5)
End-Date: 2015-09-15  21:21:13
```

```
Start-Date: 2015-09-15  21:21:25
Commandline: /usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install python-st2client=0.13.2.5-1
Upgrade: python-st2client:amd64 (0.13.1.4-1, 0.13.2.5-1)
End-Date: 2015-09-15  21:21:25
```

**Comment by lakshmi-kannan** [comment]
Closing. If this happens again, please re-open. I believe this has been fixed in recent installer versions.
