### ISSUE TITLE
Notifications are not being sent with AC workflows

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2#2018]
Reported version: 0.13.2-5

User is unable to receive return notifications via ChatOps when executing ActionChain workflows. Works just fine for single actions. When executed, notification route sent is `notify.default`, as opposed to the user-requested channel of `hubot`.

This occurs when user attempts to replicate http://docs.stackstorm.com/actionchain.html in an ActionChain workflow. Workflow succeeds. https://stackstorm-community.slack.com/archives/community/p1443453092002165

Debugging attempts:

Attempted to debug by increasing logging to `actionrunner` subsystem, and reviewing output.
https://gist.github.com/chilicat/df3c30347d3a7a3cd008

Behavior occurs regardless if `routes` are set explicitly in the action metadata (https://stackstorm-community.slack.com/archives/community/p1443454875002202) or not.

/cc https://stackstorm-community.slack.com/archives/community/p1443451685002154

**Comment by chilicat** [comment]
In the action chain I have no access to the source_channel
the action_context in the action chain is:

``` {'parent': {u'user': u'testu', 'execution_id': '560928c2c0a2406d33c858f5'}} ```

This issue is probable related to the general issue.

**Comment by lakshmi-kannan** [comment]
I tried to repro this and did repro it. I then realized it is working as per design. If you want chatops notification, you need to comment out the notify section in the echochain meta. Any notification setting in the meta will override other notifications. 

For example, with ```root@ubuntu1404:/home/vagrant# cat /opt/stackstorm/packs/test/actions/echochain.meta.yaml
---
# Action definition metadata
name: "echochain"
description: "Simple Action Chain workflow"

# `runner_type` has value `action-chain` to identify that action is an ActionChain.
runner_type: "action-chain"

# `entry_point` path to the ActionChain definition file, relative to the pack's action directory.
entry_point: "chains/echochain.yaml"

enabled: true
parameters:
  skip_notify:
    default:
      - c2
# notify:
#   on-complete:
#     message: "\"@channel: Action succeeded.\""
#     routes:
#       - "slack"
root@ubuntu1404:/home/vagrant#```

Here is the screenshot!

https://www.evernote.com/l/ANE0bVz1rZZNj7sPhq8024eejpLE-TV9pYwB/image.png

Let me know if I can help with other questions. While chasing this, I found a minor cosmetic issue in logging. I'll tag this issue in that PR.

**Comment by lakshmi-kannan** [comment]
Closing! Please re-open if you need help!

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1493104625518864
