### ISSUE TITLE
action core.remote fails with 'invalid or unsupported key' when username and private_key specifed

### ISSUE THREAD

**Issue by tomzo** [StackStorm/st2#2023]
When I have paramiko enable in configuration:
```
use_paramiko_ssh_runner = True
```

Then running
```
stanley@stackstorm:~$ st2 run core.remote cmd=echo hosts=host1 username=user1 private_key=/tmp/id_rsa 
```

Fails with
```
.
id: 560a792802ebd547018c93ea
status: failed
result: 
{
    "traceback": "  File "/usr/lib/python2.7/dist-packages/st2actions/container/base.py", line 99, in _do_run
    runner.pre_run()
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/ssh/paramiko_ssh_runner.py", line 130, in pre_run
    connect=True
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/ssh/parallel_ssh.py", line 55, in __init__
    connect_results = self.connect(raise_on_any_error=raise_on_any_error)
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/ssh/parallel_ssh.py", line 85, in connect
    raise NoHostsConnectedToException(msg)
", 
    "error": "Unable to connect to any one of the hosts: [u'host1'].

 connect_errors={
  "host1": {
    "failed": true, 
    "traceback": "  File \"/usr/lib/python2.7/dist-packages/st2actions/runners/ssh/parallel_ssh.py\", line 239, in _connect\n    client.connect()\n  File \"/usr/lib/python2.7/dist-packages/st2actions/runners/ssh/paramiko_ssh.py\", line 122, in connect\n    conninfo['pkey'] = self._get_pkey_object(key=self.key_material)\n  File \"/usr/lib/python2.7/dist-packages/st2actions/runners/ssh/paramiko_ssh.py\", line 482, in _get_pkey_object\n    raise paramiko.ssh_exception.SSHException(msg)\n", 
    "return_code": 255, 
    "succeeded": false, 
    "error": "Cannot connect to host. Invalid or unsupported key type"
  }
}"
}
```

But after disabling paramiko `use_paramiko_ssh_runner = False` it works (the same key file, permissions and user)

```
.
id: 560a7abe02ebd5056c8cb17f
status: succeeded
result: 
{
    "host1": {
        "failed": false, 
        "stderr": "", 
        "return_code": 0, 
        "succeeded": true, 
        "stdout": ""
    }
}
```

I have found an old issue on paramiko https://github.com/paramiko/paramiko/issues/340 . So I tried chaning format of rsa key to remove leading  and trailing `..KEY..` parts, but with no luck.

**Comment by Kami** [comment]
Please use:

```bash
st2 run core.remote cmd=echo hosts=host1 username=user1 @private_key=/tmp/id_rsa 
```

`private_key` parameter needs to contain contents of a private key and not a path. Putting `@` in front of the parameter allows you to specify a path to a file which content is then read and stored in the parameter value.

**Comment by tomzo** [comment]
@Kami thank you for your help.

I tried with @ just now, and the error is the same.

I have also tried to assign contents of the key with
```
KEY=$(cat /tmp/id_rsa)
```
Then
```
st2 run core.remote cmd=echo hosts=backup.ai-traders.com username=aitbackup private_key=$KEY
```

Still the same.

**Comment by Kami** [comment]
Can you please gist the output of the following command:

```bash
st2 --debug run core.remote cmd=echo hosts=host1 username=user1 @private_key=/tmp/id_rsa 
```

Keep in mind that this will include the raw content of the private key file in the log, but at this point it looks like it's something weird going on we the key so we need to check that. The best thing to do is to generate a one-time key you will use for debugging.

**Comment by tomzo** [comment]
Sure. Here is the command and output https://gist.github.com/tomzo/5c4c79c0a576cde1a95f

host and username is little different than what I said so far.
I am just trying out stackstorm, there are no sensitive information there, key is a dummy anyway.

**Comment by tomzo** [comment]
OK. Sorry. Now I see myself. The key was still missing the trailing and leading `--- Key ---` elements after my initial experiments.

It works with @ now.

Thanks for help.

**Comment by Kami** [comment]
Np :)

I also pushed a change which will throw a more user-friendly exception is user passes in something which looks like a path and not key material (https://github.com/StackStorm/st2/pull/2024).
