### ISSUE TITLE
Packs deploy doesn't work with repo_url

### ISSUE THREAD

**Issue by thomaspicquet** [StackStorm/st2#2052]
![alt text](http://i.imgur.com/SqBjv30.png "pack deploy from repo_url")

Hubot's help gives me the alias "pack deploy {{packs}} from {{repo_url}}" but it never sees the repo_url.
I want to use that to update the pack I'm working, I'll use the command line for now

Version of st2:
```# st2 --version
st2 ('0.13.2.5',)```

**Comment by thomaspicquet** [comment]
nevermind I got it to work
`pack deploy sctr-chatops from repo_url=sctr/sctr-chatops`
the help was confusing

**Comment by dzimine** [comment]
The help needs to be fixed.

**Comment by jfryman** [comment]
This has been fixed and update will be available in the latest dev packages, and will be bundled into the upcoming release.
