### ISSUE TITLE
Feature request - Expand actions to set parameters in flow

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2#2066]
In the actions page within the current UI, when you select an action, there is context around the inputs, the description, the default values.

In the action runner UI, you get context and help. But in the flow editor you have to use the autocomplete function on the input: settings, which doesn't tell you what is required, what is optional, etc.

It would be much better to be able to expand the action and show the same parameter prompts that you get in the action runner, here is a crude mock.

![crude_mockup_st2_flow_edit](https://cloud.githubusercontent.com/assets/1532417/10419969/c40c45f6-70d2-11e5-84fe-f352508af188.png)

**Comment by dzimine** [comment]
Thanks @tonybaloney for the suggestion. We know we need to do something like this, and will take your idea into the design, as an option.

**Comment by tonybaloney** [comment]
Might close this as it's been 6 years ;-)
