### ISSUE TITLE
Digital Ocean support for All in One installer

### ISSUE THREAD

**Issue by kevinSuttle** [StackStorm/st2#2083]
Just a heads up: none of the installers work on Digital Ocean. Ubuntu 14.04 droplet.

**Comment by dzimine** [comment]
Thanks for the report Kevin,
were you trying 0.13 or latest aka 0.14dev? 

once we stabilize 0.14dev installer, we will test on digital ocean (or ask you to try again).

**Comment by kevinSuttle** [comment]
The "All in One"  
`curl -sSL https://raw.githubusercontent.com/StackStorm/st2workroom/master/script/bootstrap-st2express | sh` 

Comes back with `sh: 1: Not: not found`.

**Comment by kevinSuttle** [comment]
I should note that 0.13 works.

**Comment by dzimine** [comment]
Kevin you need an elevated user, either do `sudo su`, then run the command above, or do this (note sudo): 

```
curl -sSL https://stackstorm.com/install.sh | sudo sh
```
this is shortcut to the same:
```
curl -sSL https://raw.githubusercontent.com/StackStorm/st2workroom/master/script/bootstrap-st2express | sudo sh
```

**Comment by Kami** [comment]
From the error you posted it looks like `sh` shell is not available (that's possible, but not likely).

In any case, try using bash instead:

```bash
curl -sSL https://raw.githubusercontent.com/StackStorm/st2workroom/master/script/bootstrap-st2express | sudo bash
```

**Comment by kevinSuttle** [comment]
Thanks, I'll give that a shot.
