### ISSUE TITLE
Action executions hang when the mistral process is down

### ISSUE THREAD

**Issue by withrocks** [StackStorm/st2#2091]
Reproduction:
I have an action that starts a Mistral workflow after being triggered by a sensor. This runs every 60 seconds. If I kill the Mistral process, the executions will hang in the running state. I would have expected the executions to go directly (or within a short amount of time) into the failed state. They hang like this for at least 10 minutes.

I get an indication (traceback in the action output) in the first execution that Mistral is down, but the execution doesn't go directly into the failed state. The following executions don't have any output, nor do they go into the failed state.

st2 --version: 0.13.2.5

**Comment by m4dcoder** [comment]
@withrocks: There are retries in case of communication failure with mistral. You can read up on the configuration options at http://docs.stackstorm.com/config/config.html#configure-mistral. Currently, the default options are max_attempts = 180 and retry_wait = 5; this equates to retrying for up to 900 seconds. You should be able to scale that down as needed.

**Comment by withrocks** [comment]
@m4dcoder Thanks. That will resolve this for us for now, as we can just fail our execution if mistral is down.

However, it would be really great to get an indication of the failure in the UI.

**Comment by Kami** [comment]
I believe we do mark action as failed if the timeout has been reached - IIRC, we just re-throw the original exception which might be something like "Connection refused" or similar which might not make it immediately obvious why the action has failed.

@m4dcoder If that's indeed the case, it would be great if we can make this a bit more user-friendly (throw a timeout exception with a friendlier message and a bit more details).

**Comment by withrocks** [comment]
It would be awesome to get information earlier, i.e. before the timeout has been reached.

**Comment by Kami** [comment]
That's actually a bit hard / impossible right now since we don't have a concept for this - right now action is in "running" state until it completes (either succeeds or fails, timeout is also considered a failure) or it's canceled.

One thing you can do is tail / check the action runner logs - we log the connection error before we retry.

**Comment by withrocks** [comment]
I see. Adding a log alert sounds like a viable alternative. Thanks.
