### ISSUE TITLE
send_mail : Accept FROM argument, remove mentions of "Stanley"

### ISSUE THREAD

**Issue by pixelrebel** [StackStorm/st2#2096]
I'd like access to a custom 'from' field.  Also, I would suggest removing any mention of "Stanley" (from, footer) as this name can be arbitrary to the recipient who may not know anything about StackStorm.

**Comment by m4dcoder** [comment]
Thanks for bringing this to our attention. I think we can add an optional "from" field in the send_mail action and if it's not provided, we leave it with the current default.

**Comment by pixelrebel** [comment]
Thanks!

**Comment by Kami** [comment]
Agreed, I'm +1 on making `From` header field configurable by adding new `from` action parameter and defaulting to the current value (stanley@localhost).

@pixelrebel This should be a simple change so if you feel adventurous you can make the change and submit a PR.

To get you started - you need to add new `from` parameter here https://github.com/StackStorm/st2/blob/master/contrib/core/actions/sendmail.yaml and then you need to update the action to use value of that parameter - https://github.com/StackStorm/st2/blob/master/contrib/core/actions/send_mail/send_mail

**Comment by pixelrebel** [comment]
@kami Thanks for the PR opportunity.  I'll submit one shortly.

**Comment by pixelrebel** [comment]
Created pull request: https://github.com/StackStorm/st2/pull/2097

**Comment by Kami** [comment]
#2097 has been merged, closing.
