### ISSUE TITLE
Button links do not have an href on https://stackstorm.com/

### ISSUE THREAD

**Issue by cpitkin** [StackStorm/st2#2098]
In the main banner there are two buttons:
- Install StackStorm Community
- Try StackStorm Enterprise

Neither of these anchor tags have an href to take me to an information page or install page.

**Comment by jfryman** [comment]
@cpitkin Would you mind sharing a few extra details. We're having a bit of an issue reproducing this.

OS and Browser version?

**Comment by dzimine** [comment]
@cpitkin once you click on these buttons and either submit your data, or opt out, it'll redirect you to the docs. The docs are at docs.stackstorm.com/install.html

**Comment by cpitkin** [comment]
Google Chrome
Version 46.0.2490.71 (64-bit)
![image](https://cloud.githubusercontent.com/assets/1606945/10651800/2914fcb8-7817-11e5-91b4-808c3a45d0e6.png)

**Comment by jfryman** [comment]
Very curious! By any chance does the same happen with Safari or Firefox?

From our end, it looks like you're getting an older version of the site for some reason. It see if that may be the problem, we're also about to clear our CDN cache just to ensure that everything is above board.

Thanks again for the report! Let us know that you see.

**Comment by cpitkin** [comment]
I just tried it on safari, firefox, and chrome and it all seems to work now. I think clearing the cache in the CDN must have done it.

**Comment by jfryman** [comment]
@cpitkin Great to hear! Let us know if you run into any other issues, and we'll be glad to take a look.

Cheers!
