### ISSUE TITLE
core.remote requires user to be sudoer?

### ISSUE THREAD

**Issue by dakl** [StackStorm/st2#2103]
When I run 

~~~
st2 run core.remote hosts='my.remote.server.com' username='remote_user' password='user_pwd' -- hostname
~~~

I get the unexpected answer: 

~~~
..
id: 5628b1c19ffd460d38381edd
status: failed
result: 
{
    "my.remote.server.com": {
        "failed": true, 
        "stderr": "remote_user is not in the sudoers file.  This incident will be reported.", 
        "return_code": 1, 
        "succeeded": false, 
        "stdout": ""
    }
}
~~~

I would expect it for `core.remote_sudo`, but not for `core.remote`. My bad, or a bug? 

cheers

**Comment by Kami** [comment]
Thanks for the report.

I believe there was a bug in the new paramiko based remote runner which we fixed just recently - https://github.com/StackStorm/st2/pull/2044.

If you are using a latest version which uses paramiko runner I would recommend updating to the latest development build (`0.14dev` - `./st2_deploy.sh v014.dev` should do it if you used st2_deploy.sh) where this issue has been addressed.

This build is indeed a development one, but right as we speak we are working on 1.1 release which will be stable and include a fix for this issue. This release should be out very shortly :)

**Comment by Kami** [comment]
@dakl When you have a time to check it out, please let us know if the latest release mentioned above fixes that issue.

Thanks.

**Comment by withrocks** [comment]
We've run into the same issue.

Would setting `use_paramiko_ssh_runner = False` (which fixes this) be a recommended quick fix until the bug has been resolved?

**Comment by Kami** [comment]
@withrocks Yeah, this should do it, or as mentioned above (https://github.com/StackStorm/st2/issues/2103#issuecomment-150206199) you can upgrade to v0.14dev which will soon turn into 1.1 stable.

**Comment by withrocks** [comment]
@Kami Sounds good. I will go for the quick fix for now.

**Comment by lakshmi-kannan** [comment]
@withrocks @dakl Closing. Please re-open if issue persists even after upgrade.
