### ISSUE TITLE
Rules validation fails on yaml lists of one item

### ISSUE THREAD

**Issue by Itxaka** [StackStorm/st2#2137]
With this rule.yaml:

```
---
  name: example
  description: this rule wont be validated
  enabled: true
  trigger:
    type: "core.st2.generic.notifytrigger"
  criteria:
  - trigger.event:
      type: "eq"
      pattern: hallo
  action:
    ref: hubot.post_message
    parameters:
      message: hallo
      channel: stackstorm
```

the rule validator will fail to parse the ```trigger.event``` type

```
15-10-28 15:05:57,299 DEBUG [-] Loading rule from /opt/stackstorm/packs/default/rules/example.yaml.
2015-10-28 15:05:57,305 ERROR [-] Failed registering rule from /opt/stackstorm/packs/default/rules/example.yaml.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2reactor/bootstrap/rulesregistrar.py", line 109, in _register_rules_from_pack
    rule_api.validate()
  File "/usr/lib/python2.7/dist-packages/st2common/models/api/base.py", line 65, in validate
    VALIDATOR(getattr(self, 'schema', {})).validate(vars(self))
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/validators.py", line 123, in validate
    raise error
ValidationError: [{'trigger.event': {'pattern': 'hallo', 'type': 'eq'}}] is not of type 'object'

Failed validating 'type' in schema['properties']['criteria']:
    {'default': {}, 'type': 'object'}

On instance['criteria']:
    [{'trigger.event': {'pattern': 'hallo', 'type': 'eq'}}]
```

The problem seems to be that the criteria is a list of just one item? removing the ```-``` from ```trigger.event``` makes it work with no issues.

Tested the yaml on python with pyaml  and could load it no problems, also tested a couple of online validators and everything seems ok.

Put a dump of the object being validated against the schema and this is what it returns:
```
{'name': 'example', 'enabled': True, 'trigger': {'type': 'core.st2.generic.notifytrigger'}, 'criteria': [{'trigger.event': {'pattern': 'hallo', 'type': 'eq'}}], 'action': {'ref': 'hubot.post_message', 'parameters': {'message': 'hallo', 'channel': 'stackstorm'}}, 'pack': 'default', 'description': 'this rule wont be validated'}
```

As you can see ```criteria``` is a list and in the schema it is expecting an object.

Removing the ```-``` results in the following data:
```
{'name': 'example', 'enabled': True, 'trigger': {'type': 'core.st2.generic.notifytrigger'}, 'criteria': {'trigger.event': {'pattern': 'hallo', 'type': 'eq'}}, 'action': {'ref': 'hubot.post_message', 'parameters': {'message': 'hallo', 'channel': 'stackstorm'}}, 'pack': 'default', 'description': 'this rule wont be validated'}
```

Now its a dictionary so it passes the validation.

So it seems that only dictionaries are allowed for a list of criteria if Im not mistaken? Is there any reason for this?

No real bug thougth, just a question :)

**Comment by manasdk** [comment]
Yes criteria is an object therefore it does not support lists. I think a part of this was the simplicity of the criteria section. Making a list forces everything in the property block to be an object.

The downside of our choice is that the same criteria key cannot be reused as the entire section is a dictionary

**Comment by Itxaka** [comment]
Great to hear the confirmation @manasdk!
