### ISSUE TITLE
If a local-shell-script action gets called with a parameter that contains a space, it will not be quoted when calling the actual script

### ISSUE THREAD

**Issue by jonico** [StackStorm/st2#2143]
Let's say you like to connect an action-alias with two parameters - title and description - to an action that is run by the local-shell-script runner. In this case, the script would expect title in its first argument and description in its second. This works as long as there is no space as part of the variable content. In the moment there is a space, this will not be quoted by the local-shell-runner and as result the shel script will be called with more than two arguments (a space is a separator). Would like to know whether there is a possibility to quote parameters before they get passed to the script.

**Comment by lakshmi-kannan** [comment]
I think this was addressed. https://github.com/StackStorm/st2/blob/master/st2common/tests/unit/test_shell_action_system_model.py#L140

Feel free to reopen if you still find an issue! cc: @jonico
