### ISSUE TITLE
Better support for SSH Bastion Hosts

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2#2144]
In scenarios where a user is required to have a bastion host to access private resources (for example, AWS VPCs), then it can be cumbersome to manage the security of these nodes. Where do the keys live? Is there a good way to actually keep a wall of security versus having to find awkward ways to punch holes in security design.

Something to consider, as a request from @lattwood in community.

**Comment by lakshmi-kannan** [comment]
Closing! Looks like this was addressed by @lattwood
