### ISSUE TITLE
Upgrade documentation

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2194]
Per @lakshmi-kannan request I am filing this request to have upgrade steps documented. In the docs we can find how to install the st2, but nothing tells us how to upgrade it correctly without overwriting configs, packs and other customizations.

**Comment by lakshmi-kannan** [comment]
Just to make sure, this is for release 1.1 onwards.

**Comment by emedvedev** [comment]
We have upgrade notes and KB articles now, so I'm closing this one.
