### ISSUE TITLE
extra line feeds in cli output

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2201]
```
$ st2 run st2-epsibot.mktempinv group=test hostlist=host1,host2
.
id: 5644ba408e326f4b7fb0703c
status: succeeded
parameters:
  group: test
  hostlist: host1,host2
result:
  failed: false
  return_code: 0
  stderr: ''
  stdout: 'Group: test

    Host: host1

    Host: host2'
  succeeded: true
```

```
$ perl mktempinv.pl --group=test --hostlist=test1,test2
Group: test
Host: test1
Host: test2
```

kami [10:21 AM] 
In [7]: yaml.dump({"a:" "test\nv"}, default_flow_style=False)
Out[7]: "!!set\n? 'a:test\n\n  v'\n: null\n"

kami [10:21 AM]
yeah, it's yaml thing

enykeev [10:23 AM] 
thing is, it seems to me that if you put this cli output back into yaml parser, you would not get what you expect...

enykeev [10:25 AM]
@emptywee: could you please file a bug. Not promise we get to it soon, but this for sure doesn’t look right.

manas [10:27 AM] 
Well the yaml parser does these kinda quirky things. I played around with options and tried to hack at it but eventually it got pointless. I would welcome others to try - as long as we don’t end up writing a custom yaml parser

enykeev [10:28 AM] 
we can probably reuse the formatter I’ve done today for chatops. It doesn’t suffer from that problem and returns almost the same output

**Comment by LindsayHill** [comment]
This should no longer be an issue. There were some cleanups with CLI & newline handling around 2.6 timeframe.
