### ISSUE TITLE
Visual Flow doesn't save meta on disk

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2202]
Hello,

Under some circumstances (perhaps my setup or I do something wrong, though I didn't actually do anything unusual, so in my case it's always) Flow doesn't save workflow meta data on disk. It does save the workflow itself under workflows/ directory though.

@DoriftoShoes asked to create an issue so he can investigate when he has time.

**Comment by LindsayHill** [comment]
Validated: This behavior exists on 2.3.1.

Steps to reproduce:
- Install BWC
- Login to Web UI and go to Actions tab
- Click '+' button, to launch Workflow Designer 
- Drag a couple of actions onto the canvas
- Go to settings, give action a name, e.g. `test_save_to_disk`, leave it in pack `default`.
- Save workflow
- Login to BWC server via SSH, go to `/opt/stackstorm/packs/default/actions`
- Run `ls` and `ls workflows`. Observe that `/opt/stackstorm/packs/default/actions/workflows/test_save_to_disk.yaml` exists, but `/opt/stackstorm/packs/default/actions/test_save_to_disk.yaml` does *NOT* exist.

Workaround: 
Run `st2 action get default.test_save_to_disk -y`, and export the action metadata to YAML, which can then be saved to `/opt/stackstorm/packs/default/actions/test_save_to_disk.yaml`.

I'll log an issue against the st2flow repo, referring to this.

**Comment by LindsayHill** [comment]
Resolved in 3.0
