### ISSUE TITLE
Mistral concurrency length validation issues

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#2222]
Per @emptywee on Slack - 

"I also noticed one thing, which is probably a bug too. When I set `concurrency: 2` for an action in the mistral workflow, but the array I am iterating has only 1 item, it just hangs up indefinitely (well, until it timeouts) when it comes to that action."

**Comment by lakshmi-kannan** [comment]
@m4dcoder FYI. Please rephrase the description if needed.

**Comment by m4dcoder** [comment]
https://github.com/openstack/mistral/commit/433d8e7e994744a38ffe515b4d19095eeaa215ac
