### ISSUE TITLE
Feature request - reverse proxy st2auth and st2api so the web UI runs completely on 443

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2#2228]
Currently the web UI runs on port 443, the auth API on 9100 and the API on 9101.

It would be great if you could use a reverse proxy configuration on nginx to have

https://normal-web/api/auth and https://normal-web/api/api to reverse proxy to 9100 and 9101 internally. That way
* you dont need to expose 9101 and 9100 publically
* you dont have the annoying issue with untrusted certs disallowing you from logging in on safari
* clients dont have to setup ACL rules for 9100 and 9101

**Comment by enykeev** [comment]
Thanks for the report.

We're implementing this feature as we speak. You can monitor the progress by watching this two PRs: https://github.com/StackStorm/st2workroom/pull/268 and https://github.com/StackStorm/st2client.js/pull/47

**Comment by emedvedev** [comment]
It's enabled by default starting with 1.2.0 as `/auth` and `/api`. Closing the issue.
