### ISSUE TITLE
Feature request - list_available added to packs

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2#2234]
add list_available action to the "packs" pack. similar to install, *actually the download part.

clones destination
- looks into repo
- opens pack.yaml
- lists packs available on that repo

and then what would be great is having a UI for that, with the names, description and icons.

**Comment by Kami** [comment]
That's a reasonable request, we could even implement `packs.search` based on the name, keywords and description fields in `pack.yaml`.

Right now we don't have a proper pack registry and pack management API yet so the whole thing would be a bit inefficient and slow (as you have said, we would need to clone the repo, open every pack.yaml file, etc.).

As far as the UI goes - that's our current "UI" - https://github.com/StackStorm/st2contrib#available-packs (the README is auto-generated based on the repo contents).

Our long-term plan definitely is to implement a proper pack management API and an actual pack registry (with a nice UI and everything).

**Comment by enykeev** [comment]
This is a part of pack management changes from 2.1. Stay tuned.

**Comment by LindsayHill** [comment]
Pack search options were added in 2.1. Not sure how we missed closing this old issue!
