### ISSUE TITLE
Failure to configure all-in-one using AWS Marketplace AMI

### ISSUE THREAD

**Issue by djpmm** [StackStorm/st2#2241]
Following the "all-in-one" instructions, when I attempt to create an all-in-one instance using the AWS AMI found in the Marketplace and authored by Stackstorm I encounter the following:
* I cannot access the setup UI at "https://[PUBLIC_IP]/setup" 
* SSHing into the box is required after first boot to start services that were not started by default
* After attempting a restart the UI at "https://[PUBLIC_IP]/setup" is still not reachable however "http://[PUBLIC_IP]:8080" is (this address is given after the restart completes). Unfortunately when I enter in the default admin credentials (as per the docs) I receive the following error: Unable to reach auth service. [auth:https://:9100]

Any help would be much appreciated!

**Comment by manasdk** [comment]
It seems you looked up the AMI from AWS marketplace if I am not mistaken. 

Did you follow instructions from http://docs.stackstorm.com/install/all_in_one.html#amazon-web-services-aws by any chance and ended up with these issues?

**Comment by djpmm** [comment]
Correct. I actually tried both: 
* Starting from the recommended ubuntu AMI and then following the all-in-one instructions (this actually resulted in an error caused by a timeout on a key fetch)
* Provisioning the StackStorm AMI available in the AWS EC2 marketplace

I was unable to get it working with either method unfortunately. 

I'm really just trying to evaluate the product at stage so whatever help you could provide in standing up the all-in-one would be amazing!

**Comment by manasdk** [comment]
Thanks for the clarification.

Lets try getting the ubuntu AMI + all-in-one installer to work. The StackStorm AMI in AWS EC2 marketplace is not recommended any longer and I am not certain it works.

> this actually resulted in an error caused by a timeout on a key fetch

Please share the full log stored in `/var/log/puppet.log` to help debug this further.

Take a look at http://docs.stackstorm.com/install/all_in_one.html#installation-fails-oh-no. Not sure if you had a chance to try any of the retry steps.

Also, do join our community channel https://stackstorm.typeform.com/to/K76GRP. Often it is easier to help with issues via community channel a lot quicker.

**Comment by djpmm** [comment]
I must have missed something the first time! My fault!

I tried a clean all-in-one installation from scratch again on a clean AWS Ubuntu 14.04 image and it worked!

Sorry to bother you with this! I really appreciate the rapid responses!

**Comment by lakshmi-kannan** [comment]
Closing issue. Please re-open if you are blocked. Alsom hope to see you on slack community!

**Comment by manasdk** [comment]
> Sorry to bother you with this! I really appreciate the rapid responses!

Not an issue :)

Glad it got resolved for you. Also, now that you have StackStorm running do join the slack community!
