### ISSUE TITLE
Self-signed certificate is broken

### ISSUE THREAD

**Issue by ramelito** [StackStorm/st2#2242]
$ sudo dpkg-reconfigure ca-certificates
Processing triggers for ca-certificates (20141019ubuntu0.14.04.1) ...
Updating certificates in /etc/ssl/certs... unable to load certificate
140168073868960:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:asn1_lib.c:150:
WARNING: StackStorm_Auto-Generated_Trusted_CA.pem does not contain a certificate or CRL: skipping
WARNING: Skipping duplicate certificate st2_root_ca.pem
WARNING: Skipping duplicate certificate st2_root_ca.pem

**Comment by lakshmi-kannan** [comment]
@ramelito Do you have more logs? I'll try to repro myself. If not, more logs would help.

**Comment by ramelito** [comment]
Well, this output is from Ubuntu box when i tried to update ca-certificates with st2_root_ca.crt i have downloaded from WebUI install page. So i dont think i have more logs. I have deleted /etc/ssl/st2/* certificates and start update-system to generate certificates once again, they are generated ok, but i still cannot to add them to Ubuntu, same error.

**Comment by lakshmi-kannan** [comment]
When you do ls -l /etc/ssl/st2, do you see a st2.key file and is > 0 bytes? We are talking about this on slack community. Feel free to signup stackstorm.com/community-signup.

**Comment by jfryman** [comment]
Hi @ramelito!

Sorry you're running into issues. It looks like that we needed to push a small fix to get the proper SSL CA into the trusted cert store. That was pushed in https://github.com/StackStorm/st2workroom/pull/272.

Would you try re-running `update-system` and reporting back? Also, not a bad idea to manually delete `/usr/local/ca-certificates/StackStorm_Auto-Generated_Trusted_CA.pem`

Let us know how it goes!

**Comment by ramelito** [comment]
Hi, @jfryman 
Here is the output from update-system
Error: /Stage[main]/Profile::St2server/Ca_cert::Ca[stackstorm-ca]/File[stackstorm-ca.crt]: Could not evaluate: Could not retrieve file metadata for : Cannot find file: Invalid mount ''
Notice: /Stage[main]/Ca_cert::Update/Exec[ca_cert_update]: Dependency File[stackstorm-ca.crt] has failures: true
Warning: /Stage[main]/Ca_cert::Update/Exec[ca_cert_update]: Skipping because of failed dependencies
Notice: /Stage[main]/Profile::St2server/Ca_cert::Ca[stackstorm-ca]/Anchor[ca_cert::ca::stackstorm-ca]: Dependency File[stackstorm-ca.crt] has failures: true

Meanwhile file StackStorm_Auto-Generated_Trusted_CA.pem absent in /usr/local/ca-certificates/

**Comment by jfryman** [comment]
@ramelito ok. Check this out. https://github.com/StackStorm/st2workroom/pull/273. Looks like the fat finger monster got me. Tested this locally, and looks like it works. Would you confirm for me?

**Comment by ramelito** [comment]
hi, @jfryman this time the cert smoothly installed 
$ ls -l /etc/ssl/certs/stackstorm-ca.pem 
lrwxrwxrwx 1 root root 50 дек.   1 12:29 /etc/ssl/certs/stackstorm-ca.pem -> /usr/local/share/ca-certificates/stackstorm-ca.crt
but python still does not recognize it
$ st2 auth admin
Password: 
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

**Comment by jfryman** [comment]
@ramelito This is something we're still looking into, because as we know and understand, the CA is in the right place and being installed and registered by the OS. However, we're still getting errors.

In the meantime, if you'd like to disable those settings, take a look at this article that should get you going.

https://stackstorm.reamaze.com/kb/general/insecure-certificate-warning-when-using-cli
