### ISSUE TITLE
GitHub Enterprise support?

### ISSUE THREAD

**Issue by kevinSuttle** [StackStorm/st2#2278]
I can't seem to find this anywhere. Am I missing it? I see a couple of references to GitHub [here](https://docs.stackstorm.com/webhooks.html?highlight=github#authentication), but nothing specific in terms of Enterprise, or integration details.

**Comment by DoriftoShoes** [comment]
Is there a particular feature you are looking for?  Interacting with GitHub Enterprise within StackStorm should be basically the same as GitHub.  For packs, provide the full URL to access the repo as the `repo_url`.

**Comment by kevinSuttle** [comment]
The usual webhooks for GitHub events + 

Admin events https://developer.github.com/v3/enterprise/management_console/
and org management https://developer.github.com/v3/enterprise/orgs/

**Comment by DoriftoShoes** [comment]
We don't have an integration pack for that yet, it appears.  Contributions are more than welcome though!

You can get a lot of good info about writing actions here:
https://docs.stackstorm.com/actions.html#writing-custom-actions

I would lean towards using Python, myself:
https://docs.stackstorm.com/actions.html#writing-custom-python-actions

Also, the StackStorm community Slack channels are a great resource for getting started:
http://stackstorm.com/community-signup

**Comment by kevinSuttle** [comment]
Thanks.
