### ISSUE TITLE
Incorrect aliases parsing

### ISSUE THREAD

**Issue by letchik** [StackStorm/st2#2293]
I'm trying to use stackstorm with hubot, slack and ansible.

I created some ansible aliases with chatops like [!ansible {args}, !ansible provision] and now any command that contains the word ansible is tried to use ansible local command.
For now with any command, for example !pack deploy bla-bla-bla repo_url=bla_bla/ansible in slack chat I get 
https://gist.github.com/letchik/aca39098c6c5c73f87d2

st2 version: 1.2.0.8
hubot-stackstorm version: 0.3.1-rc2

st2 action-alias list
st2 action-alias get ansible-aliases.chatops.ansible_local
st2 action-alias get ansible-aliases.chatops.provision
in the gist
https://gist.github.com/letchik/95090c2edbcfb047dcb4

I've just created one alias and it breaks everything :) but in web interface I still can use !pack command etc.

**Comment by Kami** [comment]
Thanks for the report.

We will look into it and get back to you when we figure out what is going on.

**Comment by Kami** [comment]
This is an old issue and a lot of things with regards to alias parsing have changed (and been improved) so I will close this issue.

If the issue still exists with the latest version, please open a new ticket and we will have a look.
