### ISSUE TITLE
action alias regex fails to evaluate null optional arguments when type is not string

### ISSUE THREAD

**Issue by pixelrebel** [StackStorm/st2#2295]
For example, something like:  `update {{hostname}}( {{count}} times)?` 
Works for `!update myhost 2 times`
Fails for `!update myhost`
Error: `(invalid literal for int() with base 10: '')`
So the workaround is to change the type of `count` from integer to string.
Or @emedvedev provides another workaround:
```
- update {{ hostname }} {{ count }} times
- update {{ hostname }}
```

Start from the most explicit.

**Comment by Kami** [comment]
I believe you could also specify a default value for the count parameter, so something like `{{count=0}}`.

@emedvedev Please correct me if I'm wrong and we don't support default values anymore.

**Comment by pixelrebel** [comment]
Well, that fun!  Thanks @emedvedev!

**Comment by emedvedev** [comment]
You're welcome :)
