### ISSUE TITLE
Add validation for `-` in Action parameter names

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#2303]
Currently it's possible to create Action with dashes in parameter names.
Since `v1.2` it hangs somewhere in new ChatOps aliases.
Ex: `-` is executed as substraction operator in Jinja.

We should add strict validation to catch `-` in param names and show readable error message.

See issue https://github.com/StackStorm/st2/issues/2280 and discussion https://github.com/StackStorm/st2contrib/pull/340#issuecomment-164138788

**Comment by emptywee** [comment]
If it comes live, the openstack pack at https://github.com/StackStorm/openstack should be fixed as well, e.g. https://github.com/StackStorm/openstack/blob/master/actions/server.list.yaml#L7
Probably all actions should be regenerated bearing in mind that dashes are not permitted anymore.

**Comment by manasdk** [comment]
@emptywee Thanks for point the openstack pack issue out. I will create a bug in that pack to track it there.

**Comment by enykeev** [comment]
Assigning to myself to triage the root cause more carefully. Have a deep feelings for `-`.

**Comment by armab** [comment]
Closing as resolved.

`-` are not allowed in packs anymore and there is strict validation for that.
