### ISSUE TITLE
ChatOps params from the installer UI are not being escaped

### ISSUE THREAD

**Issue by st2stanley** [StackStorm/st2#2327]
An example: if your Hubot password has `&` in it, it'll break the init script.

**Comment by Kami** [comment]
Good catch.

P.S. If those tickets are created from chat, it would also be a good idea to include the name of the person who created / reported the ticket somewhere.

**Comment by emedvedev** [comment]
Created a PR in Installer, so I'm going to close this issue. `st2` is a wrong repo for this anyway. :)
