### ISSUE TITLE
Action metadata file uses "parameters" and action chain itself uses "params". This is really confusing!

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#2337]
https://stackstorm-community.slack.com/archives/community/p1451501940009873

Reported by: Fabio Brito on Slack.

**Comment by Kami** [comment]
Agreed.

I had the same complaint quite a long time ago, but I don't remember why we didn't change it back then.

In any case, to begin with and make the change backward compatible, we could start with supporting both - `params` and `parameters` attribute. And to avoid confusion and make it explicit, if both are specified we should throw.

**Comment by manasdk** [comment]
Yup +1 on the change. It was a mistake in the first place should simply be `parameters` everywhere.

I can pick up the change.
