### ISSUE TITLE
Remote command action failing due to missing entry to known_hosts

### ISSUE THREAD

**Issue by alghanmi** [StackStorm/st2#2338]
After properly configuring the system user, I found that I am unable to run the `core.remote` action and I get the following error from running `st2 run core.remote hosts=100.73.114.124 whoami`:

```
.
id: 56847659a8479506930a36d7
status: failed
parameters: 
  cmd: whoami
  hosts: 100.73.114.124
result: 
  error: "Unable to connect to any one of the hosts: [u'100.73.114.124'].

 connect_errors={
  "100.73.114.124": {
    "failed": true, 
    "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/st2actions/runners/ssh/parallel_ssh.py\", line 238, in _connect\n    client.connect()\n  File \"/usr/lib/python2.7/site-packages/st2actions/runners/ssh/parami$o_ssh.py\", line 135, in connect\n    self.client = self._connect(host=self.hostname, socket=self.bastion_socket)\n  File \"/usr/lib/python2.7/site-packages/st2actions/runners/ssh/paramiko_ssh.py\", line 549, in _connect\n    client.connect(**conninfo)\n  File \"/usr/lib/python2.7/site-packages/paramiko/client.py\", line 251, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/usr/lib/python2.7/site-packages/paramiko/util.py\", line 270, in retry_on_signal\n    return function()\n  Fil$ \"/usr/lib/python2.7/site-packages/paramiko/client.py\", line 251, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/usr/lib/python2.7/site-packages/eventlet/greenio/base.py\", line 254, in connect\n    socket_checkerr(fd)\n  File $"/usr/lib/python2.7/site-packages/eventlet/greenio/base.py\", line 44, in socket_checkerr\n    raise socket.error(err, errno.errorcode[err])\nerror: [Errno 111] ECONNREFUSED\n", 
    "timeout": false, 
    "succeeded": false, 
    "stdout": "", 
    "stderr": "", 
    "error": "Cannot connect to host. [Errno 111] ECONNREFUSED: ", 
    "return_code": 255
  }
}"
  traceback: "  File "/usr/lib/python2.7/site-packages/st2actions/container/base.py", line 102, in _do_run
    runner.pre_run()
  File "/usr/lib/python2.7/site-packages/st2actions/runners/ssh/paramiko_ssh_runner.py", line 145, in pre_run
    connect=True
  File "/usr/lib/python2.7/site-packages/st2actions/runners/ssh/parallel_ssh.py", line 58, in __init__
    connect_results = self.connect(raise_on_any_error=raise_on_any_error)
  File "/usr/lib/python2.7/site-packages/st2actions/runners/ssh/parallel_ssh.py", line 88, in connect
    raise NoHostsConnectedToException(msg)
```

I was able to fix this by using any of the following:
1. logging in as the system user, running the ssh command and adding the host to the `know_hosts` of the system user.
2. Setting `use_ssh_config` to True and adding the following entry to the `~/.ssh/config` file (of course you can change the host regex to fit your needs):

```
Host 100.73.114.0.*
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
```

It would be great if disabling strict host checking was an option exposed in `/etc/st2/st2.conf`

**Comment by Kami** [comment]
First thanks for the report.

As far as I know, we already default to the policy which disables strict host checking in the new runner (https://github.com/StackStorm/st2/blob/master/st2actions/st2actions/runners/ssh/paramiko_ssh.py#L548) and we did the same in the old, Fabric based runner. 

From the error you posted (connection refused), it seems like a different issue - runner was unable to connect to the SSH server (e.g. SSH server was offline, firewall, etc.).

In any case, I will dig in (maybe there is some edge case which we don't correctly handle).

**Comment by Kami** [comment]
I had a look and the code looks fine to me:

* Here `client.connect` is called - https://github.com/StackStorm/st2/issues/2338
* `client.connec`t calls `_connect` (https://github.com/StackStorm/st2/blob/master/st2actions/st2actions/runners/ssh/paramiko_ssh.py#L135) which correctly initializes the host key policy - https://github.com/StackStorm/st2/blob/master/st2actions/st2actions/runners/ssh/paramiko_ssh.py#L548

On top of that, many other users (including ourselves) also use this runner and no one has reported this issue yet - this means it's likely that something else, unrelated to the host key checking is going on.

I would suggest you to also try to use this runner on a different remote host and try to reproduce the issue.

**Comment by Kami** [comment]
Also, looking at the issue description again - in the remote runner action you use `100.73.114.124` for the hostname, but value from ssh config uses `100.73.114.0` for the host (it's actually a glob, but a glob looks a bit weird since IPv4 address consists from four octets, but glob specifies `*` for the fifth octet). Is it possible that this was a typo or similar?

**Comment by lakshmi-kannan** [comment]
@alghanmi Could you look into kami's comments?

**Comment by alghanmi** [comment]
@Kami When I was looking at the code, I reached the same conclusion you did. However, I was still unable to connect until I updated the SSH Config file as noted in the issue. I may be able to reproduce the issue.

Also, `100.73.114.0` is a valid IP address and not a glob. Its just we are subnetting like crazy :).

**Comment by LindsayHill** [comment]
@alghanmi I'm cleaning up a few old issues. Is this still a problem/reproducible for you?

And looking back at the initial report, I think @Kami was referring to this section of `~/.ssh/config` as looking wrong:
```
Host 100.73.114.0.*
```

Looks like it should be either `Host 100.73.114.*` or `Host 100.73.114.0`?

Don't think it's relevant to the issue though.
