### ISSUE TITLE
Move "common" pack code from st2reactor and st2actions to st2common package

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#2339]
## Problem

Currently, common code used by packs (sensors and Python runner actions) lives in `st2reactor` and `st2actions` packages which causes nested virtualenv issues with the new packages (with new packages, to make virtualenvs works, it means st2actions, st2reactor and st2common packages need to be installed on the same server and it breaks "service / package per container" model).
## Proposed Solution

To fix this issue, I propose moving the following stuff to st2common package:
- `st2actions.runners.pythonrunner.Action`
- `st2reactor.sensor.base.{Sensor,PollingSensor}`

This would fix virtualenv issues and it it means only `st2reactor` + `st2common` package needs to be installed inside the sensor container container and `st2actions` + `st2common` in the action runner container.

The problem with this change is that it's backward incompatible. There are two approaches I can think of top of my head to make it work:
1. Use Python import hooks and redirect "old" locations to the new one - not a fan, hacky, hard to debug and not so obvious)
2. Maintain the same code in two places - one in the old location and one in the new one. This approach is also not ideal since it means we need to maintain the same code in two places, but we can automate this with some "cp" Makefile foo.

In addition to that, we would of course also update all the affected code in `st2contrib` to use the new location (we would probably do this incrementally since we don't have pack versioning story in place yet which means it would break it for people using old versions of StackStorm).

Feedback? Opinions?

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1451893685019730

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1452025897020010

**Comment by manasdk** [comment]
I do not understand the problem statement. 

> common code used by packs (sensors and Python runner actions) lives in `st2reactor` and `st2actions`

What common code?

From solution -
> To fix this issue, I propose moving the following stuff to st2common package:
st2actions.runners.pythonrunner.Action
st2reactor.sensor.base.{Sensor,PollingSensor}

Without getting the problem I guess this does not really resonate. Gut feeling is that this would be incorrect since there is no real reason to move these modules out when they seem to be in the right place.

**Comment by Kami** [comment]
Yeah, I did a bit of a bad job of explaining the problem.

I will get some sleep, sync with @dennybaa again when he's available and update it with a better problem description.

**Comment by armab** [comment]
Related to: https://github.com/StackStorm/st2-packages/issues/53

**Comment by LindsayHill** [comment]
@Kami we've had a lot of changes since this issue was first logged. I think this is probably not relevant any more?

**Comment by Kami** [comment]
Yeah, I would say 90% of that was resolved (moved / refactored) so I will close this issue.
