### ISSUE TITLE
It would be nice to support notifications from within rules.

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#2342]
Tying notifications to rules make more sense in some use cases. Think about this. 

Reported by: logikal on slack.

**Comment by manasdk** [comment]
Yeah does make sense.

We could do this by making a `core.notify` action. This way we would not be breaking the trigger -> action paradigm.

**Comment by Kami** [comment]
I like the action idea, but I wonder if that solves original "problem" / use case the user had.

On a related note - we should also classify issue important with label ("nice to have at some point in the future" vs "must have because we can't do XXX without that / because it's breaking").

**Comment by logikal** [comment]
Let's close this one for now. I think this may have been my not fully thinking through the paradigm.

**Comment by lakshmi-kannan** [comment]
Closing as per reporter.
