### ISSUE TITLE
Action chain should allow one to print all variables that can be used in jinja templating. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#2344]
This is required when we are debugging things. 

Reported by: lakstorm on slack.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1451939867019775

**Comment by Kami** [comment]
Yeah, I mentioned this multiple times already - we should also automatically generate a table or similar and include it in the docs which lists all the variable which are available in each context (triggered via ChatOps, via API, etc.).

This would of course only include "static" variables which are known to be available during run time. For the actual "live print" of all the available variables at that time, we need some more code changes, yeah.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1452026720020048
