### ISSUE TITLE
Issue with action-chain notify not deleting properly

### ISSUE THREAD

**Issue by charlottestjohn** [StackStorm/st2#2378]
Issue with action-chain notify not deleting properly

Ways to reproduce: 

Create a simple action chain like this: https://gist.github.com/charlottestjohn/3d965e0b4bca4cdd1cbd (we needed a custom notify rule to work w/ hipchat)

st2ctl reload --register-all; sudo /etc/init.d/docker-hubot restart

Run the action, verify that it comes back with the alias notify response

Update the chain's meta to add a notify portion, like so: https://gist.github.com/charlottestjohn/bdf790740661be658fc3

st2ctl reload --register-all; sudo /etc/init.d/docker-hubot restart

Run the action, verify that the notify portion is the only one that comes back in chat.

Delete the notify section

st2ctl reload --register-all; sudo /etc/init.d/docker-hubot restart

Run the action, at this point, assumption would be that the notify portion of the alias would take over - howeever the chain's old meta notify still is in effect.

For further curiosity: 
Change the name of the chain, and change what the alias points to, like so: 

st2ctl reload --register-all; sudo /etc/init.d/docker-hubot restart

Changing the name appears to let it actually pick up the new changes. If you change the name back, it will go right back to the old deleted notify.

**Comment by lakshmi-kannan** [comment]
@charlottestjohn Confirmed there is a bug somewhere in action not getting updated. Was able to repro in dev environment. https://gist.github.com/lakshmi-kannan/54c68d42f61b6626ac3c

Thanks for the report and repro steps. Much appreciated. Will get back to you with a fix.

**Comment by emedvedev** [comment]
Fixed by #2389
