### ISSUE TITLE
New st2ctl needs more advanced service handling

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#2409]
For now new `st2ctl {start|stop|restart}` works for small range of tested distros, but sooner or later there will be problems with different less popular/custom systems/configurations.

Current basic "best guess" check is: https://github.com/StackStorm/st2/blob/master/st2common/bin/st2ctl#L70

Examples to reuse: https://github.com/StackStorm/st2-packages/blob/master/packages/st2actions/bin/runners.sh to enhance it.

To do basic verification at least for (to avoid surprises later): 
* [ ] Ubuntu Trusty
* [ ] Debian Wheezy or Jessie
* [ ] CentOS6
* [ ] RHEL6 AWS
* [ ] CentOS7
* [ ] RHEL7 AWS
* [x] Ubuntu Trusty (Docker)
* [x] Debian Wheezy or Jessie (Docker)
* [x] CentOS6 (Docker)
* [x] CentOS7 (Docker)

**Comment by armab** [comment]
Another catch https://gist.github.com/lakshmi-kannan/890933d2823b541701e7
when running `st2ctl` under the Docker.

**Comment by lakshmi-kannan** [comment]
:+1: on creating a tracking issue!

**Comment by armab** [comment]
Closed by https://github.com/StackStorm/st2/pull/2490
