### ISSUE TITLE
Chatops replies to HipChat via hubot do not appear in the hipchat rooms.

### ISSUE THREAD

**Issue by StuartWhelan** [StackStorm/st2#2425]
I am running on Centos 7 64 bit, running on a fresh VM and setup using the AIO installer with enterprise options enabled.

We have an internal hipchat server.

The ST2 hubot can connect to the server. It joins all the rooms.

If you issue !help it replies in the room.

If you issue !st2 list actions, it replies in the room with Let me get right on that. Remember 56a6c480c969751d92e1c5c1 as your execution ID .....

But the result of the list rule gets sent to a room with the wrong xmpp domain.

The previous messages going to the room are sent by hubot to hipchat with an xmpp domain of  'conf.btf.hipchat.com', but the final result message is being sent by hubot to hipchat with a xmpp domain of conf.hipchat.com.

I will send an email to the support email address with some log files.

**Comment by m4dcoder** [comment]
@emedvedev: Can you take a look at this? There are more logs in support email. Thanks!

**Comment by emedvedev** [comment]
Fixed by https://github.com/StackStorm/hubot-stackstorm/pull/83
