### ISSUE TITLE
Jinja2 Custom Filters not supported in the format_execution_result action

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2430]
m4dcoder [2:09 PM] 
@emptywee: the format_execution_result action does not currently support our custom jinja filters.  please raise the issue in the st2 repo and we'll figure it out in the next release.

_Background information:_
I get `jinja2.exceptions.TemplateAssertionError: no filter named 'regex_replace'` when I use it
`format_execution_result` traps with this error
I use this filter in result format of one of the aliases I have.

In the action alias 
```
result:
  format:
```
I have something like this:
```...
          {% if task.tasks[0].result[0].exit_code == 1 %}
     ! Failed: {{ task.tasks[0].result[0].stderr | regex_replace('^.*?&& ','"') }}
          {%endif %}
...

**Comment by emedvedev** [comment]
Fixed by https://github.com/StackStorm/st2/pull/2433
