### ISSUE TITLE
Problem with packs.install in 1.3

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2#2438]
packs.install is not working in 1.3

{
  "traceback": "  File \"/usr/lib/python2.7/dist-packages/st2actions/container/base.py\", line 102, in _do_run\n    except:\n  File \"/usr/lib/python2.7/dist-packages/st2actions/runners/actionchainrunner.py\", line 248, in pre_run\n    except json_schema_exceptions.ValidationError as e:\n",
  "error": "Additional properties are not allowed ('parameters' was unexpected)\n\nFailed validating 'additionalProperties' in schema['properties']['chain']['items'][0]:\n    {'additionalProperties': False,\n     'description': 'Node of an ActionChain.',\n     'properties': {'name': {'description': 'The name of this node.',\n                             'required': True,\n                             'type': 'string'},\n                    'notify': {'additionalProperties': False,\n                               'description': 'Notification settings for action.',\n                               'properties': {'on-complete': {'additionalProperties': False,\n                                                              'properties': {'channels': {'description': 'Channels to post notifications to.',\n                                                                                          'type': 'array'},\n                                                                             'data': {'description': 'Data to be sent as part of notification',\n                                                                                      'type': 'object'},\n                                                                             'message': {'description': 'Message to use for notification',\n                                                                                         'type': 'string'},\n                                                                             'routes': {'description': 'Channels to post notifications to.',\n                                                                                        'type': 'array'}},\n                                                              'type': 'object'},\n                                              'on-failure': {'additionalProperties': False,\n                                                             'properties': {'channels': {'description': 'Channels to post notifications to.',\n                                                                                         'type': 'array'},\n                                                                            'data': {'description': 'Data to be sent as part of notification',\n                                                                                     'type': 'object'},\n                                                                            'message': {'description': 'Message to use for notification',\n                                                                                        'type': 'string'},\n                                                                            'routes': {'description': 'Channels to post notifications to.',\n                                                                                       'type': 'array'}},\n                                                             'type': 'object'},\n                                              'on-success': {'additionalProperties': False,\n                                                             'properties': {'channels': {'description': 'Channels to post notifications to.',\n                                                                                         'type': 'array'},\n                                                                            'data': {'description': 'Data to be sent as part of notification',\n                                                                                     'type': 'object'},\n                                                                            'message': {'description': 'Message to use for notification',\n                                                                                        'type': 'string'},\n                                                                            'routes': {'description': 'Channels to post notifications to.',\n                                                                                       'type': 'array'}},\n                                                             'type': 'object'}},\n                               'type': 'object'},\n                    'on-failure': {'default': '',\n                                   'description': 'Name of the node to invoke on failure of action executed for this node.',\n                                   'type': 'string'},\n                    'on-success': {'default': '',\n                                   'description': 'Name of the node to invoke on successful completion of action executed for this node.',\n                                   'type': 'string'},\n                    'params': {'default': {},\n                               'description': 'Parameter for the execution.',\n                               'type': 'object'},\n                    'publish': {'description': 'The variables to publish from the result. Should be of the form name.foo. o1: {{node_name.foo}} will result in creation of a variable o1 which is now available for reference through remainder of the chain as a global variable.',\n                                'patternProperties': {'^\\\\w+$': {}},\n                                'type': 'object'},\n                    'ref': {'description': 'Ref of the action to be executed.',\n                            'required': True,\n                            'type': 'string'}},\n     'title': 'Node',\n     'type': 'object'}\n\nOn instance['chain'][0]:\n    {'name': 'download',\n     'on-success': 'virtualenv_prerun',\n     'parameters': {'branch': '{{branch}}',\n                    'packs': '{{packs}}',\n                    'repo_url': '{{repo_url}}',\n                    'subtree': '{{subtree}}'},\n     'ref': 'packs.download'}"
}

**Comment by tonybaloney** [comment]
[blerg.txt](https://github.com/StackStorm/st2/files/110702/blerg.txt)

**Comment by manasdk** [comment]
This basically means that new 1.3 code was present on disk but services were not restarted on the box by the installer.

`st2ctl restart` should fix the issue.
