### ISSUE TITLE
Support for basic auth in core.http action

### ISSUE THREAD

**Issue by satyababu** [StackStorm/st2#2442]
Currently there is no way to pass credentials (username and password) either in the header or in the command instead of hard coded Authorization value?

Sample cmd:  current supported version
st2 run core.http url="https://downloads.stackstorm.net" headers='{"Authorization": "Basic C2F0eWIxMg=="}'

In curl it is possible to pass credentials:
curl -X GET -u 'username:password' http://server:51527/api/v1/processes

Same like curl, if core.http supports that feature, It would be great 

Reported by: Satyababu in slack

**Comment by Kami** [comment]
Thanks for the report / feature request.

I first thought we support it, but I glanced over code and it looks like we don't. We do support `auth` parameter, but the value can only be a string so I believe this won't work for traditional username and password basic / digest authentication.

@manasdk et al, please correct me if I'm wrong.

**Comment by warrenvw** [comment]
Merged to st2 with commit 71b7359bd014a789de325104f7213ab85ddba633.
