### ISSUE TITLE
chatops pack not upgraded when ST2 is upgraded

### ISSUE THREAD

**Issue by dhgwilliam** [StackStorm/st2#2460]
I have upgraded ST2 from 1.12 to 1.13 to 1.13.0.2 (I believe) but I'm still running have outdated code from the chatops pack present on my system. This probably should not be possible, since the `chatops` pack is part of the base release.

**Comment by dzimine** [comment]
Thank you for reporting; 
While we are looking at the bug, had you been helped to fix your problem? LMK if not and I'll walk you through the steps to get the updated chatops pack on your system.

**Comment by lakshmi-kannan** [comment]
Closing. We've switched to using native packages and upgrades should now work.
