### ISSUE TITLE
File content gets logged on GET to /packs/view/file

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2#2476]
We need to blacklist the related endpoints in https://github.com/StackStorm/st2/blob/33320e2e06882e58b83b92a94140a7eb3c7072f6/st2common/st2common/hooks.py#L49.

**Comment by Kami** [comment]
Does this also happen under INFO log level or only under DEBUG?

**Comment by enykeev** [comment]
Under INFO too, this is why I spotted it.
