### ISSUE TITLE
Reliability issues with docker-hubot service

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2#2500]
The docker-hubot service is still quite temperamental on 1.3.

There are 2 issues:
* The bot isn't connected to the slack room after an amount of time. 
* The bot is connected but stops responding

In both cases restarting the docker-hubot service fixes the issue.

This happens maybe twice a week. The docker-hubot service internally needs a supervisord type watcher for it's status to make sure it's functioning correctly.

In both cases, docker logs hubot shows nothing. It just stops logging data.

**Comment by dzimine** [comment]
Thanks for noting. Any hubot logs prior to the "failure"? Is it known if hubot was up inside the container once it stop responding? 

FWIW, in our internal infra, we have hubot dying at about the same period (no docker), and ended up doing sensu-> rule->restart_hubot auto-remediation.

Brings a philosophical discussion on "is it right to patch the problem" (and what is "right") :)

**Comment by tonybaloney** [comment]
how do you extract the hubot logs? I ran `docker logs hubot` which dumps the logs from the service. I've got hubot configured in debug mode so I get detailed accounts of everything.

**Comment by lakshmi-kannan** [comment]
We are no longer using docker-hubot. Closing.
