### ISSUE TITLE
Feature request: realtime output of actions

### ISSUE THREAD

**Issue by jmound** [StackStorm/st2#2531]
It would be useful, especially for long running tasks, to see action output as it occurs. At it's simplest, something similar to the output of `st2 run`, just as it occurs.

**Comment by jmound** [comment]
There may be a similar feature request out there, but I couldn't find it.

**Comment by Kami** [comment]
Thanks for the feature report.

You are correct, there is already an issue for that - https://github.com/StackStorm/st2/issues/2175

One of the workarounds you could do in the mean time (I know some users did that) is to use `tee` and also redirect action / command output to a file and then you can tail this file.

I will close this issue and let's continue the discussion in #2175.

**Comment by jmound** [comment]
:+1:
