### ISSUE TITLE
All-in-one installer does not properly configure the firewall in CentOS 7

### ISSUE THREAD

**Issue by stevemuskiewicz** [StackStorm/st2#2533]
When using the latest (1.3) all-in-one installer on a CentOS 7(.2) system, it appears that it doesn't properly configure a permanent rule for access to the https port.  Everything initially works fine, but then once the system is rebooted, you can no longer access the web UI and things like the hubot container throw errors like : 

`[Thu Feb 25 2016 18:14:28 GMT+0000 (UTC)] ERROR Failed to authenticate: connect EHOSTUNREACH 172.17.42.1:443`

The workaround is simply `firewall-cmd --add-service https --permanent` (and restarting st2 containers)

Looks like the installer is trying to use iptables commands instead of `firewall-cmd` to configure permanent firewall access rules.  I did chase back into the installer output and found this:

> Notice: /Stage[main]/Profile::St2server/File[/etc/facter/facts.d/st2_ip.txt]/ensure: defined content as '{md5}1ef55105d3dc540019356ee3c767e900'
> Notice: /Stage[main]/Profile::St2server/Firewall[100 allow HTTP/HTTPS/ST2 Access]/ensure: created
> Warning: Firewall\[100 allow HTTP/HTTPS/ST2 Access](provider=iptables): Unable to persist firewall rules: Execution of '/usr/libexec/iptables/iptables.init save' returned 1: 
> Notice: this is a dummy systemd service block
> Notice: /Stage[main]/Profile::St2server/Notify[this is a dummy systemd service block]/message: defined 'message' as 'this is a dummy systemd service block'

**Comment by lakshmi-kannan** [comment]
All in one is now deprecated. Closing.
