### ISSUE TITLE
Unable to write st2auth.uwsgi.log to different directory

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2535]
I'd like to write files to our standard logging directory which is attached to a different disk. I've updated the handler_fileHandler and handler_auditHandler blocks in /etc/st2auth/logging.conf and made sure this was the configured logging file in /etc/st2/st2.conf for st2auth. The st2auth.log and st2auth.audit.log file appear in the new directory, but the st2auth.uwsgi.log is still being writtein in the original /var/log/st2 location.

If this is possible, I'm not sure where or which config to change.

https://stackstorm-community.slack.com/archives/community/p1456442112003820

**Comment by codyaray** [comment]
Okay, found that this is configured by `/etc/uwsgi.d/st2auth.ini`. Restarting the st2auth service picks up this change. Will my config changes get wiped out by puppet if I run `update-system` though? Is this still the recommended approach? I ask because the top of the file says

```
# This file is managed by puppet class 'uwsgi::app'
#
# uwsgi app config for 'st2auth'
```

Thanks

**Comment by lakshmi-kannan** [comment]
@codyaray Sorry I couldn't get back to you on the logging thing and glad you figured it out yourself. Unfortunately, update-system will replace the file. So please back up your configuration. It's hard to fix the installer to not do this. We are migrating away to our new packaging story. So installer only gets minimal bug fixes.
