### ISSUE TITLE
Rule criteria needs more regex operators

### ISSUE THREAD

**Issue by pixelrebel** [StackStorm/st2#2557]
Need support for a case-insensitive `imatchregex` operator.

Additionally, the `matchregex` operator searches from the start of a string.  So support for `re.search` is also necessary.  I propose adding `searchregex` and `isearchregex` operators too.

**Comment by pixelrebel** [comment]
Here's the PR:  https://github.com/StackStorm/st2/pull/2558

**Comment by pixelrebel** [comment]
Merged, Thanks!

**Comment by Kami** [comment]
Thank you :)
