### ISSUE TITLE
provide ssl functionality for rabbitmq

### ISSUE THREAD

**Issue by tombin** [StackStorm/st2#2562]
There does not currently appear to be an implementation in the [messaging] section of /etc/st2/st2.conf to allow rabbitmq messages to flow over ssl.  Can you please add functionality so rabbitmq messages are not sent over clear-text.

**Comment by manasdk** [comment]
@tombin 

The library we use support the `ssl` as query parameters. Therefore `amqp://guest:guest@127.0.0.1:5672//?ssl=1` should work as per http://docs.celeryproject.org/projects/kombu/en/latest/userguide/connections.html#urls.

If you need support for passing in a special CA bundle etc then that will require work.

**Comment by enykeev** [comment]
Can confirm the issue resolved. TCP dumps for `url = amqp://guest:guest@127.0.0.1:5672/` and `url = amqp://guest:guest@127.0.0.1:5671/?ssl=1`: https://gist.github.com/enykeev/cd47081adf6fd86c9a37a009f448c31d
