### ISSUE TITLE
st2ctl clean isn't really working because mongo not found

### ISSUE THREAD

**Issue by ilkirk** [StackStorm/st2#2567]
Running st2ctl clean returns the following and ultimately does not clean the history.

This will drop the database and delete all logs.  Are you sure [y/n]?
y
st2actionrunner stop/waiting
st2api stop/waiting
st2auth stop/waiting
st2sensorcontainer stop/waiting
st2rulesengine stop/waiting
st2web stop/waiting
mistral stop/waiting
st2resultstracker stop/waiting
st2notifier stop/waiting
st2garbagecollector stop/waiting
Dropping Database...
/usr/bin/st2ctl: line 357: mongo: command not found

**Comment by manasdk** [comment]
@ilkirk Are you on ubuntu 14.04? By any chance did you install StackStorm and its dependencies by hand or did you use one of our scripted installs?

If you are using ubuntu 14.04 you will also need `mongodb-clients` to be installed. Btw, we require mongodb 2.4 and running `apt-get install mongodb-server` should also pull `mongodb-clients` as a dependency on ubuntu.

**Comment by ilkirk** [comment]
@manasdk I used a scripted install on ubuntu 14.04.  
https://docs.stackstorm.com/install/all_in_one.html

I ran the apt-get you mentioned and it looks good now!  Thanks for the quick response!!

**Comment by manasdk** [comment]
Cool. Yeah AIO did install the right packages and am unsure what happened. Btw, going forward we are recommending package-based installers https://docs.stackstorm.com/install/deb.html. Something to keep in mind going forward.
