### ISSUE TITLE
Python actions not seeing environment variables

### ISSUE THREAD

**Issue by saahn** [StackStorm/st2#2629]
After confirming that my action runners run as the st2 user, I did the following:

1. Log in as the st2 user (first had to modify create its home dir and modify /etc/passwd, as its shell is set to /bin/false by default)
2. Source an file with the environment variable exports.
3. Confirmed environment variables had been declared with `export`
4. Added `import os` and `print os.environ` in my action code
5. Ran my action via `st2 run`

The execution results showed that my env vars were not seen by my action.

**Comment by lakshmi-kannan** [comment]
``export`` just applies that variable to that particular login shell. If you need the variables to be available system wide, then you need to set them in /etc/environment for st2 user. Using config.yml to set these as config parameters as opposed to using env vairables is a better approach. Alternatively, you could pass the file name containing env variables to the action and use os.environ.set() inside the action. I am not sure why you would do that but that is an option :)

**Comment by lakshmi-kannan** [comment]
Closing as per offline discussion with saahn.

**Comment by Alan-R** [comment]
Should the approaches @lakshmi-kannan suggested work?

- setting in /etc/environment for st2 user
- setting them in config.yml
