### ISSUE TITLE
Allow user to specify a list of mongo db addresses to connect for HA reasons

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#2636]
Reported by: @jsjeannotte

**Comment by manasdk** [comment]
Let's talk about this as mongo itself suggest using mongos and a proxy or load balancer fronting mongos

**Comment by manasdk** [comment]
I am on board with supporting connections to replicasets http://docs.mongoengine.org/guide/connecting.html#replicasets

**Comment by LindsayHill** [comment]
Supported & documented here: https://docs.stackstorm.com/install/config/config.html#configure-mongodb
