### ISSUE TITLE
Use same approach for launching the different st2 components (st2sensorcontainer, st2actionrunner, ...) in Trusty

### ISSUE THREAD

**Issue by jsjeannotte** [StackStorm/st2#2639]
st2sensorcontainer uses 'exec' to launch the st2sensorcontainer binary, but st2actionrunner uses 'start' to launch the st2actionrunner-worker's. Would it be possible to use 'exec' here?

The issue is that 'start' doesn't pass the environment, so if a user adds custom environment variables in /etc/default/st2actionrunner, they are not passed down to the action runner.

**Comment by manasdk** [comment]
Yup. We just noticed as well :)

**Comment by LindsayHill** [comment]
Just had a look on my trusty system, looks like it's using `exec` there, so this must have been fixed at some point.
