### ISSUE TITLE
apt-get install st2

### ISSUE THREAD

**Issue by murgurgula** [StackStorm/st2#2646]
I've upgraded from 1.3.2 to 1.4.
It worked perfectly and everything is working. 
However, I've found a little bug, which is not critical, but confusing.
The package is updated, but while running "st2 --version", the old number shows.

root@stackstorm01:~# dpkg -l | egrep -i 'st2|st2mistral|st2web'
ii  st2                                  1.4.0-7                          amd64        StackStorm Event-driven automation
ii  st2mistral                           1.4.0-7                          amd64        St2 Mistral workflow service
ii  st2web                               1.4.0-1                          amd64        St2Web - StackStorm Web UI
root@-stackstorm01:~# st2 --version
st2 ('1.3.2.16',)

**Comment by lakshmi-kannan** [comment]
Most probably you have an old st2client. Can you do a 

```
which st2
```
?

**Comment by murgurgula** [comment]
did a pip install st2client --upgrade
`/opt/stackstorm/packs/dd/actions# pip install st2client --upgrade
Requirement already up-to-date: st2client in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: jsonpath-rw>=1.3.0 in /usr/local/lib/python2.7/dist-packages (from st2client)
Requirement already up-to-date: prettytable in /usr/lib/python2.7/dist-packages (from st2client)
Downloading/unpacking python-dateutil from https://pypi.python.org/packages/33/68/9eadc96f9899caebd98f55f942d6a8f3fb2b8f8e69ba81a0f771269897e9/python_dateutil-2.5.3-py2.py3-none-any.whl#md5=dbcd46b171e01d4518db96e3571810db (from st2client)
  Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201kB): 201kB downloaded
Requirement already up-to-date: pyyaml>=3.11,<4.0 in /usr/local/lib/python2.7/dist-packages (from st2client)
Requirement already up-to-date: requests>=2.7.0,<3.0 in /usr/local/lib/python2.7/dist-packages (from st2client)
Requirement already up-to-date: six==1.9.0 in /usr/local/lib/python2.7/dist-packages (from st2client)
Requirement already up-to-date: ply in /usr/local/lib/python2.7/dist-packages (from jsonpath-rw>=1.3.0->st2client)
Requirement already up-to-date: decorator in /usr/local/lib/python2.7/dist-packages (from jsonpath-rw>=1.3.0->st2client)
Installing collected packages: python-dateutil
  Found existing installation: python-dateutil 2.5.2
    Uninstalling python-dateutil:
      Successfully uninstalled python-dateutil
Successfully installed python-dateutil
Cleaning up...
`
# which st2
/usr/local/bin/st2
# st2 --version
st2 ('1.3.2.16',)
