### ISSUE TITLE
st2 command return auth failed in CLI when auth backend is ldap

### ISSUE THREAD

**Issue by tenyearslater** [StackStorm/st2#2652]
If I set the auth backend = ldap, then I can't run `st2 action list` in the CLI.

```
# st2 action list
Failed to authenticate with credentials provided in the config.
ERROR: 401 Client Error: Unauthorized
MESSAGE: Invalid or missing credentials for url: https://10.3.2.237/auth/tokens
```
How to solve this problem ?

**Comment by Kami** [comment]
I would recommend you to do the following.

1. Make sure enterprise bits are install (st2enterprise package) so ldap backend is available
2. Make sure ldap backend is correctly configured - https://docs.stackstorm.com/authentication.html?highlight=ldap#ldap-enterprise-edition (also see https://github.com/StackStorm/st2/blob/master/CHANGELOG.rst)
3. Make sure you are using right credentials

I would imagine it's probably related to configuration. The best way to see what is going on is to check the st2auth service log (`/var/log/st2/st2auth.log`). You might also need to start the service in the foreground with the `--debug` flag to also see debug level log messages.

**Comment by tenyearslater** [comment]
I think that my LDAP config is OK, because I can log in on the web ui.
I use the st2-auth-backend-ldap ( https://github.com/StackStorm/st2-auth-backend-ldap ).

It seems that st2 uses LDAP to authenticate.
But when I run command on the CLI, it uses the local user "root_cli" to authenticate.
The "root_cli" is not exist on the AD.
So it failed.

Is there a way to run st2 command on the CLI with user root when the auth backend is ldap ?

**Comment by lakshmi-kannan** [comment]
https://github.com/StackStorm/st2-auth-backend-ldap is unsupported and SLAs are not same as enterprise LDAP. Would appreciate if you could dig into the code and try fix it.

**Comment by Kami** [comment]
@tenyearslater ah, yeah, so it sounds like it's using `root_cli` user specified in the CLI config (`~/.st2/config`) - that's the default user account and credentials generated by the installer.

If you want CLI to use a different credentials to authenticate (the new ones you use with the WebUI), you should update the CLI config (`~/.st2/config`).

If it still doesn't work after you have done that, make sure to delete the old cached token files (`rm ~/.st2/token-*`)

**Comment by tenyearslater** [comment]
I modified `~/.st2/config` and it worked.
Thank you.
