### ISSUE TITLE
Allow multiple evaluations of the same field in a rule

### ISSUE THREAD

**Issue by lmarty** [StackStorm/st2#2656]
When writing rules, gui or CLI, if I try to evaluate {{ trigger.body }} with a contains and an additional ncontains, only one of the criteria is saved.  It would be VERY handy to be able to do 2 or more criteria evals on the same field.

**Comment by lakshmi-kannan** [comment]
@lmarty You can achieve by writing another rule. This is intentionally designed that way so rules are simple to grok. Nevertheless, good feedback.

**Comment by Kami** [comment]
@lmarty do you mean something like `OR` operator (by default, if you have multiple conditions, it behaves as `AND`).

If you indeed mean `OR`, you can achieve that, as @lakshmi-kannan has pointed out, by using multiple rules.

If that behavior is not documented yet, or documented poorly, we should make it more explicit in the documentation.

**Comment by lmarty** [comment]
So I need to create a workflow if I want to evaluate message bodies for multiple criteria?  That seems off to me, with the way the GUI is laid out.  We can click to add AND criteria, no mention of limits there or in the docs.  
  @Kami, I am not looking for an OR, definitely an AND. For example, an Amazon SQS message triggers an event.  I first want to evaluate trigger.body of that event and make sure it is the type of event I am looking for, then, I want to check to make sure it did not originate from an expected source.  ie: Message contains text X AND ncontains text Y.  Both of those data points being in trigger.body.  If this is truly by design, it should definitely be called out in the docs/tooltips/help/somewhere.

**Comment by Kami** [comment]
@lmarty Looks like I misunderstood you then.

If you are looking for AND, this should work out of the box just fine - you simple need to add multiple criteria expressions.

In your case, it would look something like that:

```yaml
criteria:
    trigger.body:
        type: "contains"
        pattern : "X"
    trigger.body:
        type: "ncontains"
        pattern : "Y"
...
```

You can also add more criteria expressions if needed.

**Comment by lmarty** [comment]
Thanks Kami!  Unfortunately, when I do as described above, via the GUI or the CLI, it only takes and displays the last criteria element.  So in the above case, the "contains" criteria would be dropped and the "ncontains" would be the only active element.  I'm on st2 1.4, and I've rebuilt the box fresh to validate the behavior.

**Comment by Kami** [comment]
@lmarty You are welcome.

This actually sounds like a WebUI bug. It should work just fine if you create rule using the CLI (st2 rule create path/to/rule/file.yaml and then st2 rule get <rule id> to verify the criteria).

/cc @enykeev

**Comment by Kami** [comment]
@lmarty Actually, sorry, I was wrong (I just noticed it now).

Now I see why the example I posted above won't work - `criteria` is a dictionary which means you can't reference the same key / field (in this case `trigger.body`) twice.

That's an unfortunate limitation and one of the workarounds you can probably use is a regex operator and regular expression which fits your criteria.

/cc @lakshmi-kannan @manasdk et. al. this seems a pretty unfortunate limitation, we should discuss how to fix it.

One option would be to allow body of a single criteria expression to be a list of dictionaries, but for backward comparability we would also allow plain dictionaries, or something along those lines.

**Comment by lakshmi-kannan** [comment]
>Now I see why the example I posted above won't work - criteria is a dictionary which means you can't reference the same key / field (in this case trigger.body) twice.

This is indeed a limitation.

**Comment by lmarty** [comment]
I knew I wasn't crazy.   Bummer guys! This would be a _very_ handy feature to have for us.  Keep me in the loop as you move forward.  I'll try and find a way around this with other sources of unique in my event stream in the meantime.

**Comment by manasdk** [comment]
My guess is that this would need some sort of schema change to do this the right way.

**Comment by manasdk** [comment]
Took a closer look at this today and the only reasonable approach would require a schema change of the criteria field in rules; move it from `dictionary` to `list`. This ofcourse has right upto what we save in the DB so would require migration scripts etc.

**Comment by erceth** [comment]
Any update on this? I would like to do something like the following:
```
"trigger.body.data.latitude": {
  "type": "lessthan",
  "pattern": "30"
},
"trigger.body.data.latitude": {
  "type": "greaterthan",
  "pattern": "50"
},
"trigger.body.data.longitude": {
  "type": "greaterthan",
  "pattern": "-90"
},
"trigger.body.data.longitude": {
  "type": "lessthan",
  "pattern": "-100"
},
```
Sort of a geo-fence. I get the same problem described above, only the latest key is kept.
