### ISSUE TITLE
Mistral task changes for accessing result breaks packs.deploy workflow

### ISSUE THREAD

**Issue by jjm** [StackStorm/st2#2660]
Today, I spotted that my pack auto-deployment was no working following my upgrade to ST2 1.4. The workflow was failing with the following error:

```json
"state_info": "Failure caused by error in tasks: do_manual_install\n\n  do_manual_install [task_ex_id=37a099a8-9510-40d6-a0e7-bd91e9d06b7a] -> Can not evaluate YAQL expression:  $.do_manual_install.repo_url <deleted>"
    "state": "ERROR"
 ```

I remembered something about a breaking change being mentioned on the slack community. And the following sort of change is needed:

```yaml
        publish:
-          repo_url: <% $.expand_repo_name.result.repo_url %>
-          subtree: <% $.expand_repo_name.result.subtree %>
+          repo_url: <% task(expand_repo_name).result.result.repo_url %>
+          subtree: <% task(expand_repo_name).result.result.subtree %>
```

I'll be doing a PR very shortly.

**Comment by Kami** [comment]
Yep, need to use `task` function with the new version of Mistral which ships with StackStorm v1.4.

And thanks for the future PR :)

**Comment by jjm** [comment]
You should have a PR shortly ;-) just finished my testing ;-)

**Comment by jjm** [comment]
There you go, PR opened and tests are currently running. I'll keep and eye on them.

**Comment by jjm** [comment]
The fix has been merged, so I'll just close.
