### ISSUE TITLE
st2 client ignoring timezones.

### ISSUE THREAD

**Issue by murgurgula** [StackStorm/st2#2665]
When doing execution list or other commands, UTC timezone is used instead America/Montreal from the config file.

Also, are the timezones implemented in the UI? 
Thanx.

Config:
=================================
[general]
base_url = http://127.0.0.1
api_version = v1
cacert =
timezone = America/Montreal

[cli]
debug = True
cache_token = True
timezone = America/Montreal

[credentials]
username = someuser
password = somepassword

[api]
url = http://127.0.0.1:9101/v1

[auth]
url = http://127.0.0.1:9100/
=================================

**Comment by m4dcoder** [comment]
Unable to reproduce problem.

**Comment by murgurgula** [comment]
are there any requirements for this to work?
PS: my installation is an upgrade from 1.3, not a fresh install.

**Comment by Kami** [comment]
As @m4dcoder has said, this should work fine.

Only requirement is you are using StackStorm v1.4 and the latest version of st2client which is part of StackStorm v1.4.
