### ISSUE TITLE
show "paused" status of mistal workflow correctly in st2 command

### ISSUE THREAD

**Issue by mt5225** [StackStorm/st2#2672]
mistal workflow is in "paused" state, while st3 execution command still shows workflow in  "running" state. 

note: workflow is in paused state if includes  "pause-before: true" in a task. 
reference:  http://docs.openstack.org/developer/mistral/dsl/dsl_v2.html#workflows

**Comment by LindsayHill** [comment]
Has been lots of overhaul of pause/resume behavior. Don't think this applies any more.
