### ISSUE TITLE
Document Best Practices for Monitoring your StackStorm Cluster

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2681]
Follow-up to our Slack discussion:

https://stackstorm-community.slack.com/archives/community/p1463072370004154
- Are any actions repeatedly executing?
- Do I have too many long-running executions?
- Are my executions requested/pending for too long?
- When do I need to scale out the number of action runners?
- Which executions are killing my CPU/memory/etc?
- How do I know that all the executions I expected (cron) actually ran? (Sometimes I've noticed that jobs don't show in UI if they fail "early enough"(?) but I see them only in the CLI/API)
- Have any of my processes died? Are they automatically respawned (using upstart or other supervisor) already? Do I need to monitor these?
- Other system-oriented things like lengths of queues in rabbit, mongo optime/heartbeats, etc?
- What things should we be most concerned about operationally? (I've got a mongo replica set, but mongo RS's can get jacked up pretty easily still)
- Probably some stuff about backing up mongo/postgres if that's important. (Again, it is mongo :))

I know some heavyweights like Netflix are already using this in production. (Who else?) How are they monitoring their systems in production?

(Okay, maybe Netflix is a bad example. They have a lot of custom tooling special for micro-services oriented ecosystems. And not everybody wants to adopt the #NetflixOSS)

**Comment by codyaray** [comment]
https://stackstorm-community.slack.com/archives/community/p1466700736001489

RabbitMQ lengths:
* `st2.actionrunner.req` for Requested actions
* `st2.actionrunner.work` for Scheduled actions
* `st2.actionrunner.canel` [sic] for Canceling actions

**Comment by Kami** [comment]
Thanks for opening this issue.

I totally agree that we should provide more operational metrics directly from StackStorm. Some of the things you have described are not really responsibility of StackStorm, but we should definitely provide some kind of health endpoint with high-level app specific metrics (how many pending executions, etc.).

**Comment by codyaray** [comment]
This was more of a "tell me what to monitor" than a "make a monitoring solution for me". Of course, I do really like apps that have monitoring endpoints that spit out a bunch of operational metrics as JSON over HTTP. (Of course, this only tells you how its performing _if_ its performing; only the absence of data tells you of downtime.) There's definitely room for both.

**Comment by LindsayHill** [comment]
This is a good topic @codyaray (and near to my heart, since I've spent a lot of time with monitoring systems over the years). I think it's a combination thing. We need to:
* Make sure that ST2 makes it easy to get access to key operational status/metrics
* Publish guidelines on what to monitor & how to get access to that data 
* (Possibly) Create a template/plugin for some monitoring toolset that monitors key ST2 metrics - e.g. publish a Zabbix template.
There's a related topic here around analytics too.

**Comment by codyaray** [comment]
Likewise - I'm putting together some logstash configs for parsing all the st2 logs right now. These are likely going to stay "community" but even having them is a big help.

**Comment by LindsayHill** [comment]
Good stuff. There's some existing logstash stuff here https://github.com/StackStorm/st2contrib/tree/master/extra/logstash, but it looks like it could do with an update.

**Comment by jjm** [comment]
I'm also rather interested in how to monitor ST2, I'll have a look at the logstash stuff and think some about how we should monitoring our platform.

**Comment by LindsayHill** [comment]
Monitoring guidelines published here: https://docs.stackstorm.com/reference/monitoring.html
