### ISSUE TITLE
Process the triggers folder like actions and sensors

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2682]
Follow-up issue to StackStorm/st2contrib#475.

We should support registering triggers which don't belong to the any sensor. Creating webhooks means creating standalone triggers. The most obvious convention would be to process YAML files in each pack's `<pack name>/triggers/` directory like we do with sensors, actions, rules, etc.

Acceptance Criteria:
* `st2ctl reload --register-triggers` new command exists 
* `st2ctl reload --register all` command also registers triggers

There's probably more. I'm not sure what is run for testing packs, but I'd also include whatever that mechanism is (to close StackStorm/st2contrib#475) in the acceptance criteria. :)

**Comment by Kami** [comment]
Thanks for opening this ticket.

We've briefly talked about this in the past and I'm +1 on that change (this way we can stop "abusing" the API in some scenarios like sensu pack, etc.).

**Comment by Kami** [comment]
This has been addressed by #2752.

Closing & thanks!
