### ISSUE TITLE
Request: Ability to migrate api keys to new installs

### ISSUE THREAD

**Issue by sixth** [StackStorm/st2#2692]
Hi there, 

As stackstorm is going through updating its installation and upgrade processes, I've been having to create fresh new st2 instances as a fix for different issues i've encountered. 

My production stackstorm instance is mostly used via its webhook and accessed through an api key. Since at most times the api key is hardcoded to my developer's code, It would be a nice feature to have a way to migrate the api keys between different st2 instances.

Keep up the great work!
-E

**Comment by manasdk** [comment]
### Extract API keys
`st2 apikey list -dj/-dy`

### Upload API keys
`st2 apikey create -f apikeys.json/apikeys.yaml`

**Comment by lakshmi-kannan** [comment]
@manasdk Can you document this in st2docs?

**Comment by manasdk** [comment]
> Can you document this in st2docs?

Sure, once I implement it :)

**Comment by manasdk** [comment]
Done.
