### ISSUE TITLE
st2 execution get -j and st2 execution get -dj differences make it hard for people to debug a loop in workflow

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#2702]
See this gist from codyaray https://gist.github.com/codyaray/4be049203d9036954f0caa547ede4836

**Comment by lakshmi-kannan** [comment]
@Kami Mind looking into whether this is an actual issue?

**Comment by manasdk** [comment]
I suspect the `tasks` section was removed from the `-dj` output.  I am not quite certain if there is anything for us to fix in this case.

**Comment by LindsayHill** [comment]
Don't know when this was fixed, but in 2.7.2, if I use `st2 execution get -dj`, it shows the tasks for a workflow.
