### ISSUE TITLE
Add another "timestamp" attribute to the execution object when represents a time execution has been started

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#2706]
Right now we have `start_timestamp` which is set when an execution is scheduled (aka requested by the API or other service) and `stop_timestamp` which is set by the runner container when execution finishes.

There could be a delay (for whatever reason) between when execution is scheduled (`start_timestamp`) and when it actually starts being executed by the runner. We should add another timestamp attribute to the `ActionExecutionDB` model (dunno, `execution_start_timestamp` or similar, but ideally we would probably rename existing `start_timestamp` to `scheduled_timestamp`, but this is a bit of a painful change) which indicates a timestamp when action execution has been started by the runner.

Originally reported by Sayli K. on Slack.

**Comment by manasdk** [comment]
I cannot help but agree with @enykeev. We need some sort of audit-trail of activities on a single execution.

**Comment by Kami** [comment]
I agree, ideally we would log all the state transitions and events related to executions.

We already kinda do that in the logs, but it's not really in a consistent and structured format and that makes it hard to use and query.

In any case, I think this additional timestamp would still be beneficial, even if we had this even stream, or whatever we want to call it.

**Comment by enykeev** [comment]
Note that we change status to `running` when we dispatch it to MQ [[1]](https://github.com/StackStorm/st2/blob/b74067d4afd9f871f42876e93c633883fa38af68/st2actions/st2actions/worker.py#L107-L107) and there is really no limit on how long it might be there before it gets picked up by the worker. Also note that the way st2 is designed, worker has a pretty decent chance to be running on the different machine with local time being skewed one way or the other.

So where exactly do we want to sample this execution_timestamp for it to be useful for debugging purposes? On dispatch, on worker run or on both? Do we want to start solving the problem if we're pretty much agree we can't solve it good enough without per-execution event log?

**Comment by lakshmi-kannan** [comment]
>Do we want to start solving the problem if we're pretty much agree we can't solve it good enough without per-execution event log?

We can punt it but I am pretty sure we won't work on event log in next few months. I'd rather have a timestamp now and build event log later. As far as where you should start ticking the time for running, it looks like we actually have a bug that we set status to ``running`` even before dispatching. So I think we need a new state ``dispatched``. This is anyways needed and the right thing to do. We should mark the action as running when the worker picked it up. I know this is more work but I don't think it's a week of work. Thoughts everyone?

**Comment by Kami** [comment]
This has been resolved by #2718, closing.
