### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by geovanisouza92** [StackStorm/st2#2749]
Hello, this seems to be a nice project.

There is any plan or WIP to create a Docker installation (maybe with Docker Compose)?

**Comment by manasdk** [comment]
We do have plans for this stuff for sure.  One such QIP example is https://github.com/enykeev/st2box/blob/master/docker-compose.yaml and https://github.com/StackStorm/st2-dockerfiles/blob/master/docker-compose.yml

We really have not spent time in supporting any of these but plan is to eventually have full-fledged docker support.

**Comment by geovanisouza92** [comment]
Ok, I'll take a look at this. Thanks for now.

**Comment by admdwrf** [comment]
+1

**Comment by AndyMoore111** [comment]
+1

**Comment by armab** [comment]
This is implemented a while ago, see

- https://stackstorm.com/2017/04/21/official-stackstorm-docker-image-here/
- https://github.com/stackstorm/st2-docker
