### ISSUE TITLE
st2actionrunner upstart script fails to stop all running instances

### ISSUE THREAD

**Issue by nzlosh** [StackStorm/st2#2778]
The current st2actionrunner upstart script starts X number of st2actionrunner processes, where X is based on the number of processors available on the system.

For systems with more than 10 processors available, `service st2actionrunner stop` doesn't iterate over all of the started st2actionrunner processes.

**Comment by Kami** [comment]
Good catch and thanks for reporting it.

I believe you mentioned on Slack that you have a fix, if you do, it would be great if you can submit PR with it :)

**Comment by Kami** [comment]
#315 has been merged, thanks!
