### ISSUE TITLE
High availability architecture

### ISSUE THREAD

**Issue by tenyearslater** [StackStorm/st2#2789]
I deploy stackstorm on two servers behind the load balance. 
And deploy mongodb and rabbitmq on another server.
The stackstorm on the two servers connect to the mongodb and rabbitmq on the third server.
The mistral on the two servers connect to the rabbitmq on their own server.
The two servers behind the load balance share the storage where /opt/stackstorm/packs and /opt/stackstorm/virtualenvs are on the storage.
It works.

But I have a problem.
If I deploy a sensor that run every some seconds, it will run twice every time because the sensor is on the two servers.

So, Is there a documentation for how to deploy high availability architecture in stackstorm ?
How to solve this problem ?

**Comment by LindsayHill** [comment]
Answered on #community, but following up here in case someone else is looking. Docs are here: https://docs.stackstorm.com/reference/ha.html
