### ISSUE TITLE
Doco referencing old component name

### ISSUE THREAD

**Issue by chris-hailstorm** [StackStorm/st2#2793]
This doc page:
    https://docs.stackstorm.com/0.5.1/packs.html

Currently says:
    st2 run packs.restart_component servicename=**sensor_container**

Should say:
    st2 run packs.restart_component servicename=**st2sensorcontainer**

**Comment by Kami** [comment]
@chris-hailstorm 

Thanks for the report.

Those are docs for a very old version of StackStorm (v0.5.1) and they represent state for that version.

For the latest stable version, please see https://docs.stackstorm.com/ / https://docs.stackstorm.com/1.5/

**Comment by chris-hailstorm** [comment]
Understood.  It would be helpful if the older doco included a warning / pointer to the latest doco -- 0.5.1 is the version that came up via  Google search.  Thank you for the quick response.

**Comment by Kami** [comment]
Agreed - we will be looking into adding some banner which says "You are not viewing the latest version" or similar.

Sadly this means we need to re-built all the old docs and this might be a bit painful.

**Comment by lakshmi-kannan** [comment]
@Kami Or we can actively purge those buckets so people can't even read old docs :)

**Comment by LindsayHill** [comment]
We have added warning banners to older versions going back to 1.4.

We also made a bunch of other changes to our canonical_url settings and added some redirects, so almost all Google searches should now return the current docs.

Agreed with above that we should purge the older buckets.
