### ISSUE TITLE
html5lib missing from virtual-env

### ISSUE THREAD

**Issue by knowledgewarrior** [StackStorm/st2#2796]
Error: 
"bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?"

Default fresh installation following instructions for both RHEL7 and Ubuntu.  Add Google Pack.  Perform google search in Chatops (Slack).  

Resolution:
sudo source /opt/stackstorm/st2/bin/activate
sudo pip install html5lib

**Comment by Kami** [comment]
Thanks for the report.

Looks like bs4 declares this package in `extra_require` section it's not installed by default and looks like the behavior in the google library we use has change to require this package.

I will update requirements.txt in google pack to also install this package.

**Comment by Kami** [comment]
Actually, I just installed google pack from scratch and I couldn't reproduce this issue.

Are you sure that the libxml and other system-level package dependency were installed on the system when you installed that pack? 

If they weren't, this would most likely cause those issues...

**Comment by knowledgewarrior** [comment]
I followed the Ubuntu instructions exactly.  I used Ubuntu 14.04 on AWS.

**Comment by Kami** [comment]
@knowledgewarrior Yeah, the installer and system packages only include component-level dependencies.

Packs are standalone and only include pack-level (Python dependencies), so it's up to the user to install any system-level package dependencies required by the pack.

In any case, I will update the documentation and make this more explicit and clear in the ChatOps documentation.

**Comment by Kami** [comment]
In any case, I also pushed this change to st2contrib - https://github.com/StackStorm/st2contrib/commit/63b2094fdaf587656a345afc8db4d7832effcc4c (it might help).

Thanks again for reporting this.

**Comment by Kami** [comment]
I'm going to close that since I believe the commit in st2contrib should resolve this issue.

If you experience similar issues again in the future, please open a new ticket.

Thanks again for reporting this.
