### ISSUE TITLE
Make datastore templates work in sensor config

### ISSUE THREAD

**Issue by cbrenton** [StackStorm/st2#2798]
In an action, workflow, or rule config file, I can reference a datastore value with "{{system.key_name}}". However, when I use this template format in a sensor config file, it doesn't get evaluated. It would be helpful to be able to use this template format in sensors as well.

**Comment by Kami** [comment]
We just recently in StackStorm v1.5, introduced support for improved pack configuration.

With this new configuration you can now reference datastore items inside the config. For more information, please see https://stackstorm.com/2016/06/30/improved-pack-configuration-user-scoped-datastore-items-secure-secrets-store/ and https://docs.stackstorm.com/pack_configs.html.

If you have any specific questions about it, please feel free to join us on Slack and / or open a new ticket for a specific issue / problem.
