### ISSUE TITLE
Systemd service file missingst2actionrunner@.service is missing in Debian package

### ISSUE THREAD

**Issue by moritz** [StackStorm/st2#2799]
On Debian Jessie, with st2 version 1.5.0-7 from https://packagecloud.io/StackStorm/staging-stable/debian/ and installed via the `mrlesmithjr.stackstorm` ansible role, I get this behavior:

```
root@stackstorm01vt:/lib/systemd/system#  /etc/init.d/st2actionrunner status
● st2actionrunner.service - LSB: StackStorm st2actionrunner
   Loaded: loaded (/etc/init.d/st2actionrunner)
   Active: active (exited) since Fri 2016-07-08 13:50:50 UTC; 13min ago
  Process: 6851 ExecStop=/etc/init.d/st2actionrunner stop (code=exited, status=0/SUCCESS)
  Process: 6996 ExecStart=/etc/init.d/st2actionrunner start (code=exited, status=0/SUCCESS)

Jul 08 13:50:50 stackstorm01vt st2actionrunner[6996]: Failed to start st2actionrunner@1.service: Unit st2actionrunner@1.service failed to load: No such file or directory.
Jul 08 13:50:50 stackstorm01vt st2actionrunner[6996]: Failed to start st2actionrunner@2.service: Unit st2actionrunner@2.service failed to load: No such file or directory.
Jul 08 13:50:50 stackstorm01vt st2actionrunner[6996]: Failed to start st2actionrunner@3.service: Unit st2actionrunner@3.service failed to load: No such file or directory.
Jul 08 13:50:50 stackstorm01vt st2actionrunner[6996]: Failed to start st2actionrunner@4.service: Unit st2actionrunner@4.service failed to load: No such file or directory.
Jul 08 13:50:50 stackstorm01vt st2actionrunner[6996]: Failed to start st2actionrunner@5.service: Unit st2actionrunner@5.service failed to load: No such file or directory.
Jul 08 13:50:50 stackstorm01vt st2actionrunner[6996]: Failed to start st2actionrunner@6.service: Unit st2actionrunner@6.service failed to load: No such file or directory.
Jul 08 13:50:50 stackstorm01vt st2actionrunner[6996]: Failed to start st2actionrunner@7.service: Unit st2actionrunner@7.service failed to load: No such file or directory.
Jul 08 13:50:50 stackstorm01vt st2actionrunner[6996]: Failed to start st2actionrunner@8.service: Unit st2actionrunner@8.service failed to load: No such file or directory.
Jul 08 13:50:50 stackstorm01vt st2actionrunner[6996]: Failed to start st2actionrunner@9.service: Unit st2actionrunner@9.service failed to load: No such file or directory.
Jul 08 13:50:50 stackstorm01vt st2actionrunner[6996]: Failed to start st2actionrunner@10.service: Unit st2actionrunner@10.service failed to load: No such file or directory.
```

And indeed, there is no `st2actionrunner@.service` file installed that would allow loading of these services.

```
root@stackstorm01vt:~# dpkg -L st2|grep -F 'st2actionrunner@'|wc -l
0
```

**Comment by armab** [comment]
Thanks for the report!

The correct `stable` repo is https://packagecloud.io/StackStorm/stable/ without `staging`, where debian wheezy/jessie packages absent.
It means for the moment between .deb packages `ubuntu trusty` is only officially supported.

Making this more productive, possible options: 
* we assume that `systemd` uses `systemV` scripts for backwards compatibility at `debian jessie`. You can dig into `/etc/init.d/st2actionrunner`, these scripts worked before under the `jessie`. See: https://github.com/StackStorm/st2-packages/blob/master/packages/st2/debian/st2.st2actionrunner-worker.init and https://github.com/StackStorm/st2-packages/blob/master/packages/st2/debian/st2.st2actionrunner.init
* There are `systemd` configs that we ship for `centos7`, you can port them for deb. See: https://github.com/StackStorm/st2-packages/blob/master/packages/st2/rpm/st2actionrunner.service and https://github.com/StackStorm/st2-packages/blob/master/packages/st2/rpm/st2actionrunner%40.service

Whatever option you choose, PR in [st2-packages](https://github.com/StackStorm/st2-packages/) is very welcome!

**Comment by moritz** [comment]
@armab basing the st2 packages on systemd files would make them incompatible with wheezy/oldstable. Is that an acceptable tradeoff?

**Comment by armab** [comment]
@moritz Got you. I think there should be some conditional `.deb` magic to avoid incompatibilities, like in `.rpm` example: https://github.com/StackStorm/st2-packages/blob/03b1d151dd1af3d94a3773490ed69d29475a8932/packages/st2/rpm/st2.spec#L79-L101
Needs more researching.

cc @enykeev to keep in mind, since he's working on https://github.com/StackStorm/st2-packages/issues/296 and probably has in plans to ship `systemd` service units for `Ubuntu16`.

**Comment by berendt** [comment]
File is still missing in the packages, even the file is available in the repository (https://github.com/StackStorm/st2-packages/blob/master/packages/st2/debian/st2actionrunner%40.service). On Ubuntu 16.04 I placed this file in /lib/systemd/system and reloaded systemd, afterwards it was possible to start the st2actionrunner service.

**Comment by armab** [comment]
Closed via https://github.com/StackStorm/st2-packages/issues/365
