### ISSUE TITLE
Feature: watch progress of long-running actions

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2804]
I've heard this asked about a number of times in #community but these conversations keep rolling off the archives. Creating a Feature Request for tracking.

When I have a long-running action, we don't know what's going on until the action has completely finished executing. Ideally, I'd be able to watch the stdout/stderr in (near) real time or have other visibility into what's going on with the action.

**Comment by armab** [comment]
Original Proposal is described in this Issue: https://github.com/StackStorm/st2/issues/2175

> Off-topic: Thinking when Github will introduce some voting mechanism to know what Issues requested most.

**Comment by codyaray** [comment]
Ah thanks. Didn't find that one before. Closing this as a duplicate. :)
