### ISSUE TITLE
Flow does not make use of default values in parameter list, after a change in parameters setup

### ISSUE THREAD

**Issue by lbogardi** [StackStorm/st2#2809]
Hi All,

I noticed, that using the Flow, to create a workflow, and setting up parameter list is fine, but when I change any of the parameters, and try to execute the workflow, I have to refill all the values, however default values are already filled in.
![screenshot from 2016-07-13 12-12-00](https://cloud.githubusercontent.com/assets/8155496/16800020/8326e588-48f3-11e6-8f69-cb96093fbfb3.png)
![screenshot from 2016-07-13 12-11-26](https://cloud.githubusercontent.com/assets/8155496/16800026/8deca930-48f3-11e6-9fb9-50d76722dd78.png)

Any question, let me know,
Cheers

**Comment by enykeev** [comment]
Thanks for the report!

I believe @emedvedev already explained it so I just put it here for the reference.

Right now, if parameter is required, web UI won't allow you to send the form unless the field has a valid value. In a practical sense it means that your parameter should either be required or have a default value and in case it has both, `required` would have a precedence.

Although, seeing how this confuses our users, we may change that in the future and ignore required property on parameters with default value.

**To everyone:** 👍/👎  or chime in if you have stronger preference on the matter.
