### ISSUE TITLE
Deleted policies continue to be evaluated

### ISSUE THREAD

**Issue by bri365** [StackStorm/st2#2813]
Deleting a policy from a pack does not remove it from the database (mongo st2.policy_d_b).  Even with PR #2812, if an enabled policy is removed from a pack, and the pack is reloaded, the policy remains in the database and continues to be evaluated.

[deleted-policies-remain.txt](https://github.com/StackStorm/st2/files/361878/deleted-policies-remain.txt)

**Comment by codyaray** [comment]
This is actually a larger problem with "content management" in stackstorm. Deleting anything from disk and then reloading doesn't actually remove it from mongo. This applies not only to policies but also to actions, triggers, etc. The StackStorm team is working on a larger "content management" story to address this and other issues. I'll let them chime in here now. ;)

**Comment by lakshmi-kannan** [comment]
@codyaray is right. Content management is being though through for next milestone. We are planning to make progress on this issue and agree current state is nasty :).

**Comment by bri365** [comment]
is it [relatively] safe to manually remove them from mongo in the short term?  Beats the heck out of a fresh reinstall...

**Comment by lakshmi-kannan** [comment]
@bri365 should be fine. You can also write a script along the lines of https://github.com/StackStorm/st2/blob/master/st2common/bin/st2-purge-executions. Might just be easier to use mongo CLI and do it.

**Comment by Kami** [comment]
What @lakshmi-kannan said, usually the pattern also is to use CLI to delete the resource one definition has been removed from disk.
