### ISSUE TITLE
Can not verify existing webhook

### ISSUE THREAD

**Issue by evguenig** [StackStorm/st2#2825]
Created custom webhook:

# curl -H "St2-Api-Key: MDQ2Y2FmOGExNWU1NTA3YTRmZDIwNTMxYmE2M2NkNWI3ZTcwZTMwODBkMDJmYzAwZDg5NzNiNTdiNDEwMzdiZg" https://localhost/api/v1/webhooks/st2-trigger-build -k
{"uid": "trigger:core:d7c0dde6-272d-4230-80e6-29eb1b5c2950:37a1b5f1d879c35beee4cbf61b555819", "parameters": {"url": "st2-trigger-build"}, "ref_count": 1, "name": "d7c0dde6-272d-4230-80e6-29eb1b5c2950", "pack": "core", "type": "core.st2.webhook", "id": "57915e0bc4da5f04822fb0d6", "description": null}

But then it fails;
curl -X POST https://68.140.242.46/api/v1/webhooks/st2 -trigger-build -H "St2-Api-Key : MDQ2Y2FmOGExNWU1NTA3YTRmZDIwNTMxYmE2M2NkNWI3ZTcwZTMwODBkMDJmYzAwZDg5NzNiNTdiNDEwMzdiZg" -H "Content-Type: application/json" --data '{"trigger": "core.st2.webhook", "payload": {"attribute1": "value1"}}' -k
{
   "faultstring": "Unauthorized - One of Token or API key required."
} - doesn't work

The trigger seems to be fine:
# st2 rule list |grep build
| default.st2-trigger-build               | default  | trigger build from gitlab                     | True    |

**Comment by LindsayHill** [comment]
You have a space between "St2-Api-Key" and ":" - wonder if that is causing the problem?

**Comment by evguenig** [comment]
Ye that was an issue user error.

**Comment by evguenig** [comment]
Closing issue
