### ISSUE TITLE
st2ctl restart should reload nginx 

### ISSUE THREAD

**Issue by puneetk** [StackStorm/st2#2833]
please

**Comment by armab** [comment]
I'm not sure if that's a good idea for `st2ctl` to reload nginx.

As noted in #community, that's because instead of `nginx` there could be ​_any_​ other replacement like apache or whatever proxy.
Brings more freedom on user's side.

**Comment by armab** [comment]
Apart of that, this issue reminds me discussions about including `nginx` as a dependency for `st2web` package.

We had pretty hot discussions about that. I remember @enykeev and @emedvedev wanted to do this. While it wasn't good time to do that before (too early), maybe it's good time to reconsider it.

Nowadays `nginx` feels like pretty much native part of the system, however bringing it to packaging right & less error-prone would be hard, considering certificates stuff, nginx configs, existing nginx installation cases and so on permutations (but doable).

-----
^^ Probably good food for discussion in https://github.com/stackstorm/st2-packages

**Comment by armab** [comment]
Closing, as said `nginx` is just a proxy and could be replaced with any other service.
Because of that, at the moment there is no reason to hardcode it in `st2ctl`.
