### ISSUE TITLE
How to make use of the commands of docker or openstack packs installed in st2 on remote hosts? 

### ISSUE THREAD

**Issue by anpodila** [StackStorm/st2#2846]
How to make use of the commands of docker or openstack packs installed in st2 on remote hosts?

**Comment by anpodila** [comment]
How to make use of the commands of docker or openstack packs installed in st2 on remote hosts?  I believe it is not required to install packages like Docker or Openstack on st2 server.

**Comment by lakshmi-kannan** [comment]
What exactly are you trying to achieve as an outcome? Perhaps if you give us more info, we can guide you through it.

**Comment by anpodila** [comment]
Hi Lakshmi,

Thank you for the response.

I have docker installed on different server and want to execute the
commands from st2 which are included in docker pack.

These docker commands are executed locally.  Want to execute same on remote
server actually they are working if I mention " st2 run core.remote
hosts='chatops1' -- 'docker images'" but this is making use of the
core.remote pack not the docker pack.

[root@chatops1 ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED
VIRTUAL SIZE

[root@chatops1 ~]# st2 run docker.pull_image 'repo=busybox:latest'

[root@chatops1 ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED
VIRTUAL SIZE
busybox             latest              b05baf071fd5        6 weeks ago
1.093 MB

Want to execute similar commands on remote hosts in which docker is
installed either by specifying hosts='hostname' option.

Same manner Openstack commands on the openstack server from st2 openstack
pack. I believe usually docker, openstack all those things will not be
installed on the same server where st2 is running.


Regards,
Anuradha Podila

**Comment by anpodila** [comment]
Hi Team,

Anyone has idea to execute docker pack and openstack commands on remote servers?

**Comment by Kami** [comment]
@anpodila One way to achieve that would be to deploy StackStorm action runner processes on the sever where you want those commands executed. Right now this means you need to deploy all action runners on that server since we don't support runner affinity (yet).

Another option would be to use remote runner and execute commands on remote servers using SSH.

**Comment by anpodila** [comment]
Hi @Kami ,

Thank you for the response.   Sure, will use remote runner.

**Comment by Kami** [comment]
@anpodila No problem and great that this solves it for you :)
