### ISSUE TITLE
CLI: `--attr` couldn't retrieve result attributes

### ISSUE THREAD

**Issue by vaishalipavashe** [StackStorm/st2#2858]
Reference: https://docs.stackstorm.com/cli.html
Steps with Screenshots:
- Execute local action
![image](https://cloud.githubusercontent.com/assets/10110869/17518893/b5646370-5e17-11e6-837f-e7648a9bdf6b.png)

- Use `-k` to retrieve result attribute, which works without any issues:
![image](https://cloud.githubusercontent.com/assets/10110869/17518932/e0804542-5e17-11e6-8407-731bec68bec4.png)

- As per documentation, we can use `-attr` to retrieve execution attributes:

![image](https://cloud.githubusercontent.com/assets/10110869/17519113/8b6845f4-5e18-11e6-9ade-a28b73f26b5d.png)

- In my case it prints whole result set with `--attr` but fails when I try to retrieve result attributes individually. It prints `None`:

![image](https://cloud.githubusercontent.com/assets/10110869/17519061/5b54fba0-5e18-11e6-89ec-fe166cc547c2.png)

**Comment by Kami** [comment]
Thanks for the report.

Right now we don't support dotted notation for `execution get` because it uses a special formatter, but we do support for for `execution list`.

**Comment by Kami** [comment]
If you want to retrieve a value of a specific attribute in the result object you can use the `-k` option.

For example:

```python
python ./st2client/st2client/shell.py execution get 57bb3f0f0640fd0ab60d896a -k stderr 
```

Will update documentation to reflect this.

**Comment by Kami** [comment]
It turns out this was indeed a bug which I introduced when adding various CLI performance improvements a while back.

PR #2887 fixes it

Thanks again and a good catch!

**Comment by Kami** [comment]
Also, it was a bit nasty bug and not immediately obvious since it wasn't an actual bug in the CLI formatting code but in the way we handle exclude attributes and in the response API returns...
