### ISSUE TITLE
Removing a trigger can break st2 rule list

### ISSUE THREAD

**Issue by DoriftoShoes** [StackStorm/st2#2869]
ERROR: 400 Client Error: Bad Request
MESSAGE: Missing TriggerDB object for rule 57ae57614f83fa2f415b0556 for url: http://127.0.0.1:9101/v1/rules/?limit=50

The above is an example message.  If a user removes a pack with packs.uninstall and that removes a trigger, any existing rules that reference that trigger will cause st2 rule list as well as the rules pane of the UI to break.

**Comment by Kami** [comment]
Thanks for the report.

It looks like this is a related issue - https://gist.github.com/Kami/a7279dc3f0b3acb07436b161f309da78.

I will look into it next week - API needs to be made a but more robust so it doesn't break if some data is missing or similar.

**Comment by Kami** [comment]
This has been fixed and fix included in v2.0.0.
