### ISSUE TITLE
Cache filters API response for web UI

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2876]
As the number of actions, rules, etc has grown in our StackStorm cluster, the UI is becoming slower. In particular, the filters view (which we rely on heavily with this many executions) is very slow to become visible and usable. It might help to cache this `/api/v1/executions/views/filters` API response and asynchronously reload this value outside of the request thread, since this is slowly-changing data.

Our typical workflow is to
1. load the main execution page
2. wait for the filters to appear
3. apply some set of filters
4. wait for the next page to load

Here's a waterfall showing a 20s load time for the filters response. This is pretty common for us now.
![screen shot 2016-08-22 at 12 20 14 pm](https://cloud.githubusercontent.com/assets/44062/17864407/8c624f68-6863-11e6-8557-c5fbe4d23e9f.png)

For reference, we have 572 rules, 1200 actions, 143 triggers, 19 trigger types, and 600k+ executions.

**Comment by codyaray** [comment]
This filters call is now timing out in the UI and thus the filters are never appearing. =(

**Comment by codyaray** [comment]
This is super painful now. I'm hoping increasing the memory after-hours will help. Are there any ideas on the code front that could help?

**Comment by codyaray** [comment]
This is still a big issue. I can't evangelize this through the team if they can't search through stuff. Help?

(To even find the rule names, I'm resorting to searching mongo and manually constructing URLs. Not exactly how I want to teach others to use StackStorm.)

**Comment by codyaray** [comment]
Still slow, but purging the execution history helped a lot. Configuring auto-purge now.

**Comment by codyaray** [comment]
@Kami any feedback on this issue? Still a problem here.

**Comment by enykeev** [comment]
@codyaray I'm very sorry it took us so long to get to that issue. Have you tried adding more indexes to mongo's action_execution_db? The `.explain()` shows most of the time is spent on "COLLSCAN". I'll share the actual numbers with you as soon as I get them and will create a PR. I believe that using indexes may end up being much more flexible solution for us rather than caching controller response. Quite frankly, the idea we've missed that part confuses the hell out of me. As I said, very sorry.

**Comment by enykeev** [comment]
^^ the PR should solve the problem for a very long time. The only thing that I can say in our defense is that prior to switching to Mongo 3.2 it would have been much harder to debug this issue.
