### ISSUE TITLE
Rules UI in 2.0 fails when auto-selected fields aren't overridden.

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2#2889]
In 2.0, the rules UI will preselect an enumerated option and show the first option, but it doesn't populate the model. So even though it looks like you have selected the field, it gives an error.

I think the issue is that (you can see in the snapshot) the first dropdown is selected but the bound data model in angular isn't being populated.
![image](https://cloud.githubusercontent.com/assets/1532417/18303785/2611ce48-7522-11e6-89c8-70dae56e5768.png)

The error from the API was:
{
    "faultstring": "'unit' is a required property\n\nFailed validating 'required' in schema['properties']['unit']:\n    {'additionalProperties': False,\n     'properties': {'delta': {'required': True, 'type': 'integer'},\n                    'timezone': {'type': ['string', 'null']},\n                    'unit': {'enum': ['weeks',\n                                      'days',\n                                      'hours',\n                                      'minutes',\n                                      'seconds'],\n                             'required': True}},\n     'type': 'object'}\n\nOn instance['unit']:\n    {u'delta': 1}"
}

**Comment by pietervogelaar** [comment]
I experience the same problem, it's really annoying. Please give this some more prio.

**Comment by winem** [comment]
This is no longer an issue with st2 & st2web 3.5.0. Defaults are shown in the UI and populated in the model. Same for #3205
