### ISSUE TITLE
Web GUI action field populated but not included in HTTP post

### ISSUE THREAD

**Issue by efenian** [StackStorm/st2#2891]
Steps to reproduce go to bwc-topology.fabric_add in Web GUI enter name in fabric field and click Run.

Switch to bwc-topology.fabric_config_add action and fabric field stays populated with fabric name entered for fabric_add however is not included in http post resulting in error until fabric name is deleted and re-typed.

![fabric_add](https://cloud.githubusercontent.com/assets/20911579/18373338/5a209c92-7611-11e6-8e4d-89e22a78a273.png)

![fabric_config_add](https://cloud.githubusercontent.com/assets/20911579/18373361/7e430dbc-7611-11e6-9ce5-1f4138d8529d.png)

**Comment by Kami** [comment]
Thanks for reporting this.

PR which supposed to fix it has been merged, we will make sure that the change is included in the upcoming release (v2.0.1).
