### ISSUE TITLE
RBAC does not apply to actions used transitively

### ISSUE THREAD

**Issue by akabraab** [StackStorm/st2#2909]
Currently, the RBAC on actions is only checked at the API level when a user requests to execute an action.  Since actions can compose other actions a user could inadvertently execute an action that they may not be authorized to for direct execution via the API.  Ideally, all action executions should be checked for permissions before executing the action regardless of how they get executed, directly or as a task in another action.

**Comment by akabraab** [comment]
Based on actual testing of actions composing other actions, this issue is now resolved.  We have established that all action executions via the API are indeed checked for RBAC regardless.  As such, I am closing this issue.

**Comment by Kami** [comment]
Thanks for confirming and closing this.
