### ISSUE TITLE
"st2 key delete" does not obey interface and populate user query params

### ISSUE THREAD

**Issue by gaberger** [StackStorm/st2#2921]
st2 --debug  key delete  -s user -u stanley netdev_servicewrapper_address
2016-09-23 17:13:48,545  DEBUG - Using cached token from file "/home/vagrant/.st2/token-st2admin"

curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.11.1' -H  'X-Auth-Token: 235ca028e8e545efbd28806090ca3bd6' 'http://127.0.0.1:9101/v1/keys/netdev_servicewrapper_address?scope=user'

{
    "faultstring": "KeyValuePair with name: st2admin:netdev_servicewrapper_address and scope: user not found in db."
}

**Comment by Kami** [comment]
Thanks for opening this issue, will look into it.

On a side note - do you use RBAC?

**Comment by Kami** [comment]
Good catch.

Fix is in #2925 and will be included in v2.0.1

Thanks again!
