### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED via st2 pack

### ISSUE THREAD

**Issue by cmatthews-ww** [StackStorm/st2#2922]
I am seeing the following error via CLI and via calling hubot in slack.

Creating an issue per @m4dcoder via slack

`st2  run st2.actions.list limit=10`

> id: 57e555674e174cc42fbf8204
> status: failed
> parameters:
>   limit: 10
> result:
>   exit_code: 1
>   result: None
>   stderr: "st2.actions.python.St2ActionsListAction: DEBUG    Calling client method "get_all" with kwargs "{'limit': 10}"
> Traceback (most recent call last):
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 211, in <module>
>     obj.run()
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 126, in run
>     output = action.run(**self._parameters)
>   File "/opt/stackstorm/packs/st2/actions/actions_list.py", line 27, in run
>     'exclude_attributes': exclude
>   File "/opt/stackstorm/packs/st2/actions/lib/action.py", line 102, in _run_client_method
>     result = method(**method_kwargs)
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 38, in decorate
>     return func(_args, *_kwargs)
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 190, in get_all
>     response = self.client.get(url=url, params=params, *_kwargs)
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 33, in decorate
>     return func(_args, *_kwargs)
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 51, in decorate
>     return func(_args, *_kwargs)
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 75, in get
>     response = requests.get(self.root + url, *_kwargs)
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 70, in get
>     return request('get', url, params=params, *_kwargs)
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 56, in request
>     return session.request(method=method, url=url, *_kwargs)
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, *_send_kwargs)
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 177, in resolve_redirects
>     *_adapter_kwargs
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
>     r = adapter.send(request, **kwargs)
>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
> "
>   stdout: '' 

`cat /opt/stackstorm/packs/st2/config.yaml and`

> api_url: ""
> auth_url: ""
> # API key used to authenticate against st2.
> # Note: This only needs to be specified if you want to use a custom API key.
> # By default, this pack will use temporary authentication token which is
> # generated by the runner and is available to the action during execution.
> 
> api_key: ""
> # If this setting is provided, server certertificate validation is performed.
> # By default, client assumes self-signed cert and doesn't perform certificate
> # validation.
> # This value can either contain path to the CA_BUNDLE file with certificates
> # of trusted CAs or "True" to use CAs from the system trust store. If not
> # provided, no validation is performed.
> 
> cacert: ""

`st2 --print-config`

> [credentials]
> username = <user>
> password = <password>
> api_key = None
> [api]
> url = None
> [cli]
> debug = False
> timezone = UTC
> cache_token = True
> [auth]
> url = None
> [general]
> cacert = None
> base_url = None
> api_version = None
> silence_ssl_warnings = True

`st2 --version`
st2 2.0.0

**Comment by enykeev** [comment]
Never seen anything like that. My assumption is that it either misconfigured nginx or some problem with system dependencies (a fancy version of nss, for example). We'll keep an eye for issues like that in the future, but unless it happens periodically and can be reliably reproduced, don't see what else can be done.
