### ISSUE TITLE
Basic mistral workflow example 400 response

### ISSUE THREAD

**Issue by rasathus** [StackStorm/st2#2942]
Hi, Im not sure whether this is the correct place to post, but I've tried IRC and email with no success.

I’ve been trying to evaluate stackstorm for a future project, and have been attempting to work through the basic mistral workflow example here ... https://docs.stackstorm.com/mistral.html 

Unfortunately when running the 'st action create' command I get a 400 response ... 
```
vagrant@stackstorm:~$ cat /opt/stackstorm/packs/examples/actions/mistral-basic.yaml
version: '2.0'

examples.mistral-basic:
    description: A basic workflow that runs an arbitrary linux command.
    type: direct
    input:
        - cmd
    output:
        stdout: <% $.stdout %>
    tasks:
        task1:
            action: core.local cmd=<% $.cmd %>
            publish:
                stdout: <% task(task1).result.stdout %>
                stderr: <% task(task1).result.stderr %>

vagrant@stackstorm:~$ st2 action create /opt/stackstorm/packs/examples/actions/mistral-basic.yaml
ERROR: 400 Client Error: Bad Request
MESSAGE: Additional properties are not allowed ('examples.mistral-basic', 'version' were unexpected) for url: http://127.0.0.1:9101/v1/actions

vagrant@stackstorm:~$ st2 --version
st2 2.0.0
```
 
I’m running it on a fresh Ubuntu 14.04 box run up via vagrant, and have installed stackstorm via the one liner on the installation doc ... https://docs.stackstorm.com/install/index.html#installation
 
Any help or direction would be most appreciated.

**Comment by emedvedev** [comment]
Hi! I remember your e-mail, and we did reply on the same day IIRC, but just in case it got lost in the spam folder—it happens!—here it is:

> Hi Chris,
> 
> Sorry to hear you're having problems! Let me help you by clarifying a few things that may not be immediately clear from the docs.
> 
> The cause of this error is quite simple. A StackStorm action usually consists of two files: a metadata file describing the action, and the code itself (for some actions a metadata file is enough).
> 
> For mistral-basic, the example you're trying, here's the metadata file (note that it's stored in `actions/`): github.com/StackStorm/st2/blob/master/contrib/examples/actions/mistral-basic.yaml
> 
> The second file is the workflow itself, stored in `actions/workflows/` (the metadata file has its path under "entry_point"): github.com/StackStorm/st2/blob/master/contrib/examples/actions/workflows/mistral-basic.yaml
> 
> From your gist, I can see that you have the workflow inside the `actions/` dir, where the metadata file should be. Move that workflow file to `actions/workflows/`, put its metadata file into `actions/`, and everything will be working just fine.
> 
> Lastly, sorry we're not active in IRC anymore! We've moved from IRC to Slack, and we maintain a public community which is very much alive. I encourage you to sign up: stackstorm.com/community-signup
> 
> Have fun with StackStorm! Let me know if the solution above doesn't fix your problem.

**Comment by rasathus** [comment]
oh, ok.  I got a weird bounce back from the email ...

```
Delivery has failed to these recipients or groups:

DL-GRP-GS-TAC-L3AllBWC@Brocade.com
Your message wasn't delivered due to a permission or security issue. It may have been rejected by a moderator, the address may only accept e-mail from certain senders, or another restriction may be preventing delivery.

Diagnostic information for administrators:

Generating server: BRMWP-EXMB12.corp.brocade.com

DL-GRP-GS-TAC-L3AllBWC@Brocade.com
#< #5.7.1 smtp;550 5.7.1 RESOLVER.RST.AuthRequired; authentication required> #SMTP#
...
```

I'll go make the path corrections, and try again.

Thanks for the assistance,  I'll try Slack in future.

**Comment by emedvedev** [comment]
We did have an issue with one of the forwarding DLs, but it wasn't critical. Admittedly, it's a weird message to get in response for a support e-mail though! As far as I'm aware, it's all fixed now, but still, really sorry for the hiccup.

Let me know how it goes. I hope your issue gets resolved :)

**Comment by rasathus** [comment]
That seems to have resolved the issue, thanks for the comprehensive response.

Im just working my way though some of the videos, and getting my head around the mistral DSL.

Thanks
