### ISSUE TITLE
DELETE /v1/executions/57fee1b6c506f479b9c58e97 returns 200 even if already canceled

### ISSUE THREAD

**Issue by dbavery** [StackStorm/st2#2946]
I found that issuing a cancel execution rest call to an execution which is already canceled returns a 200 response code ("OK") even though it also sends back a faultstring. 

In this case the fault string make sense - you attempted to do something but we are not going to do it since we are already canceled. 

However the return code of 200 implies that we attempted to issue the cancel and that it worked. 

I think a response code of 409 would be more appropriate if we determine that we can even attempt what is being requested.

```
409 Conflict
Indicates that the request could not be processed because of conflict in the request, such as an edit conflict between multiple simultaneous updates.
```

The 409 in this case would imply that we took no action because we were not in a valid state for the given request.

If folks feel that it should really stay in the 2xx, then 202 might be more appropriate to imply that we accept the request and it may or may not be appropriate. Even then, if you know enough to send back a failure case as part of the request, then I would expect a "failure" return code.

Here is the curl output illustrating.

```
~>curl -X DELETE -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.11.1' -H  'X-Auth-Token: c64c7c82be38408f9dc406ceb2640d77' -H  'Content-Length: 0' http://127.0.0.1:9101/v1/executions/57fee1b6c506f479b9c58e97
{
    "faultstring": "Action is already in \"canceled\" state."
}~>
~>
~>curl -I -X DELETE -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.11.1' -H  'X-Auth-Token: c64c7c82be38408f9dc406ceb2640d77' -H  'Content-Length: 0' http://127.0.0.1:9101/v1/executions/57fee1b6c506f479b9c58e97
HTTP/1.1 200 OK
Server: gunicorn/19.6.0
Date: Thu, 13 Oct 2016 01:27:58 GMT
Connection: keep-alive
Content-Type: application/json
Content-Length: 65
Access-Control-Allow-Origin: http://127.0.0.1:3000
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Headers: Content-Type,Authorization,X-Auth-Token,St2-Api-Key,X-Request-ID
Access-Control-Expose-Headers: Content-Type,X-Limit,X-Total-Count,X-Request-ID
X-Request-ID: d4f4c75c-5b6a-42f2-bfe9-406277615861
```

**Comment by Mierdin** [comment]
@dbavery Thanks for reporting this issue. I think the consensus thus far is to maintain the same error code, but to return the entire execution object in JSON in the API response. I'll get a PR together in the next few days to address this

**Comment by dbavery** [comment]
@Mierdin If I understand correctly instead of returning a fault string you would just return the status of the execution, which would tell you that it was cancelled. Repeat calls would get the same execution object which shows it is canceled. I agree that would cover our scenario. I still think a 202 might be a better error in general (as it implies that some additional processing needs to happen). But either way that proposed solution is better than just getting the fault string.

Thank you!
