### ISSUE TITLE
Feature request - A mechanism to generate template files of pack

### ISSUE THREAD

**Issue by userlocalhost2000** [StackStorm/st2#2963]
Hi, thank you for providing so exciting software.

This is an idea to create pack easily.

It's not easy for me, and maybe also others, to create pack according to following.
https://docs.stackstorm.com/reference/packs.html

If the `st2` command had a mechanism to generate template files to develop pack, like [`rails new` command](http://guides.rubyonrails.org/getting_started.html#creating-the-blog-application)), all developer would be fun to develop it.

Thank you.

**Comment by emedvedev** [comment]
Hi! You have perfect timing, actually: this feature is in active development right now. Please stay tuned. :)

**Comment by emedvedev** [comment]
In the meantime, you're welcome to use the `cookiecutter` template by @tonybaloney: https://github.com/tonybaloney/stackstorm-template. 

Just install cookiecutter (`pip install cookiecutter`) and use the template whenever you need a pack:
```
cookiecutter https://github.com/tonybaloney/stackstorm-template
```

**Comment by userlocalhost2000** [comment]
Thank you for your reply and telling me `cookiecutter `.

> this feature is in active development right now.

Fantastic, I'm looking forward to it!

**Comment by userlocalhost2000** [comment]
I confirmed this requirement is satisfied by [st2sdk](https://github.com/StackStorm/st2sdk).

Thank you!
