### ISSUE TITLE
Sensor fails to retrieve kv object after some time.

### ISSUE THREAD

**Issue by pixelrebel** [StackStorm/st2#2983]
st2 2.0.1
mongo 3.2.10

I have a polling sensor that queries an ES database and when a datapoint crosses a threshold, it sends an alert.  Once alerted, it stores a key with a 24-hour ttl so that the sensor knows to skip alerts for the rest of the day.  I also have a mechanism for silencing alerts with the same approach.  This used to work well before I upgraded st2, but now after a few days of running st2 the sensor keeps alerting even though there’s an `alerted` key in the keystore.  When I restart st2 everything goes back to normal for a few days then the problem comes back.   

I can probably get permission to publish my entire pack, but here's the gist of the dispatch_trigger logic in my sensor:

https://gist.github.com/pixelrebel/240ca95c480d1377175b3667de0411cb

And here's the gist of my action chain that sets the `alerted` key.

https://gist.github.com/pixelrebel/6def658dfd2ee43fe71ce7735db76b29

**Comment by bigmstone** [comment]
I believe I've run this issue down. It would appear we're grabbing a temporary token [here](https://github.com/StackStorm/st2/blob/master/st2common/st2common/services/datastore.py#L198) and creating a `Client` with it, but the `Client` will never get unset if the token has expired. So after a day it will continue to use `Client` with the expired token. To add insult to injury we also [catch any exceptions](https://github.com/StackStorm/st2/blob/master/st2common/st2common/services/datastore.py#L93) and don't log it. Working on a fix and will test it. Will keep you posted.
