### ISSUE TITLE
New `pack register` syntax

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#3001]
With the new pack management `pack register` has the following syntax with `flags`:

```sh
st2 pack register --packs github st2 --types actions aliases
```
while for example for `pack install` we have the following with positional arguments: 
```sh
st2 pack install github st2
```

Is there any specific reason why `--packs` flag is needed and we can't use positional arguments for pack names?

Or we can just go with more consistent way, similar to other new nicely looking commands.

Example without `--packs` flag: 
```sh
# register all:
st2 pack register
# register all in `st2` pack:
st2 pack register st2
# register everything in `st2` and `github` packs
st2 pack register st2 github
# register actions and aliases for st2 and github packs:
st2 pack register st2 github --types actions aliases
```

> @emedvedev said @enykeev knows the reason.

**Comment by armab** [comment]
So as @enykeev noted, the problem case with making `packs` positional is: 
```sh
st2 pack register --types actions aliases pack1 pack2`
```

So maybe instead of `--types actions aliases` we can bring [old-style flags](https://github.com/StackStorm/st2/blob/8faea560b1d7ad2363b866cedd975c99a6574a1b/st2common/bin/st2ctl#L29-L36): 
`--with-actions --with-aliases --with-rules`?


So resulting `CLI`: 
```sh
st2 pack register --with-actions --with-aliases st2 github trello
```

**Comment by emedvedev** [comment]
`--with-actions --with-aliases --with-rules` looks kinda odd. What about `--actions` and `--aliases`?

`st2 pack register st2 github trello --actions --aliases`

`st2 pack register --actions --aliases st2 github trello`

**Comment by emedvedev** [comment]
Addressed in https://github.com/StackStorm/st2/pull/3020. `st2 pack register st2 github trello --types=rule,action` should be fine, as well as `st2 pack register st2 github trello --types rule action`. `st2 pack register --types rule` should also work. I'll verify and make sure it has sufficient coverage.
