### ISSUE TITLE
Actions canceled by Policy within a Mistral workflow result in workflow never exiting

### ISSUE THREAD

**Issue by andrew-regan** [StackStorm/st2#3026]
Found this in StackStorm 1.6. It may be related to these:
* Issue https://github.com/StackStorm/st2/issues/2923
* PR https://github.com/StackStorm/st2/pull/2916 

When a Mistral workflow is run it kicks of Actions in StackStorm that are asynchronous. StackStorm has a mechanism to notify Mistral of the Actions completion, but this does not occur when a policy that cancels an Action kicks in. 

The high level flow for notifying Mistral is:
* `st2actions/st2actions/worker.py`: For Actions that aren't canceled `_run_action()` calls `RunnerContainer:dispatch()`
* `st2actions/st2actions/container/base.py`: `RunnerContainer:dispatch()` calls `_do_cancel()` or `_do_run()` which both call `runner.post_run()`
* `st2actions/st2actions/runners/__init__.py`: `ActionRunner::post_run()` issues the callbacks for the Action
* `st2actions/st2actions/handlers/mistral.py` `MistralCallbackHandler::callback()` calls Mistral's REST API to complete the Action Execution

In the case of an Action that gets canceled the RunnerContainer is never created so Mistral is never notified of the Canceled action so it spins waiting forever for an update on the Action that was canceled in StackStorm.

**Comment by andrew-regan** [comment]
Snippet of when an Action is run from Mistral and performs the callback:
```
2016-11-14 19:59:34,626 140674325731440 DEBUG base [-] Updated liveaction after run (liveaction_db={'status': 'succeeded', 'runner_info': {u'hostname': u'c7b54e322015', u'pid': 3562}, 'parameters': {}, 
'action_is_workflow': False, 'start_timestamp': '2016-11-14 19:59:32.946858+00:00', 'callback': {u'url': u'http://0.0.0.0:8989/v2/action_executions/53bd4390-f6e0-4185-b473-f49db35cd612', u'source': u'mi
stral'}, 'notify': None, 'result': {'stdout': '', 'exit_code': 0, 'stderr': '', 'result': [{u'host': u'172.25.139.60', u'use_cdp': False}]}, 'context': {u'user': u'stanley', u'parent': {u'execution_id':
 u'582a17a442871d0aa5086db9', u'trigger_instance': {u'id': u'582a17a442871d0aa5086db6', u'name': None}, u'trace_context': {u'id_': u'582a17a442871d0aa5086db7', u'trace_tag': u'trigger_instance-582a17a44
2871d0aa5086db6'}, u'rule': {u'id': u'582a15d942871d0b3058bf5f', u'name': u'sensor_started_enable_auto_discovery'}, u'user': u'stanley'}, u'mistral': {u'action_execution_id': u'53bd4390-f6e0-4185-b473-f
49db35cd612', u'task_id': u'c7d4c040-5ba7-476a-a258-5bbc1afb09c2', u'workflow_name': u'vsphere.enable_discovery_protocol_for_all_vspheres.main', u'workflow_execution_id': u'514bfa10-00b5-49e8-9508-32fa1
f6729bc', u'task_tags': None, u'task_name': u'get_auto_discovery_configs', u'callback_url': u'/v2/action_executions/53bd4390-f6e0-4185-b473-f49db35cd612'}}, 'action': u'vsphere.get_vsphere_auto_discover
y_configurations', 'id': '582a17a442871d0a351b8448', 'end_timestamp': '2016-11-14 19:59:34.549558+00:00'})

2016-11-14 19:59:34,640 140674325731440 DEBUG base [-] Performing post_run for runner: 2544f934-1de6-49e3-b580-9557a77445f3

2016-11-14 19:59:34,642 140674325731440 INFO mistral [-] Sending callback to http://0.0.0.0:8989/v2/action_executions/53bd4390-f6e0-4185-b473-f49db35cd612 with data {'output': '{"result": [{"host": "172.25.139.60", "use_cdp": false}], "exit_code": 0, "stderr": "", "stdout": ""}', 'state': 'SUCCESS'}.
```

**Comment by andrew-regan** [comment]
Wonder if a potential fix for this is to have the Policy set the Action to `LIVEACTION_STATUS_CANCELING` instead of `LIVEACTION_STATUS_CANCELED`?

**Comment by andrew-regan** [comment]
Any thoughts on whether I triaged this correctly? 😃

**Comment by m4dcoder** [comment]
Can you clarify what you mean by cancellation policy?  We only have concurrency and retry policies.  https://github.com/StackStorm/st2/tree/master/st2actions/st2actions/policies

**Comment by andrew-regan** [comment]
Sorry. You can specify that a concurrency policy cancels actions. See: https://docs.stackstorm.com/reference/policies.html

```
parameters:
    action: cancel
```

**Comment by andrew-regan** [comment]
Full example:
```
---
  name: enable_discovery_protocol.concurrency
  description: Limit concurrent executions of enable_discovery_protocol
  enabled: true
  resource_ref: vsphere.enable_discovery_protocol
  policy_type: action.concurrency.attr
  parameters:
    action: cancel
    threshold: 1
    attributes:
      - vsphere_host
```

**Comment by m4dcoder** [comment]
@andrew-regan Thanks for the clarification. On tracing the code, it looks like a bug. Good catch. We are very near v2.1 release at this point so we'll include this bug fix in the next patch release following.

**Comment by m4dcoder** [comment]
@andrew-regan now that we got v2.1 out of the way, i'll start looking at closing some of these issues next week. so, if not other issues, we should include it in one of the 2.1.x patches.

**Comment by m4dcoder** [comment]
Fix @ https://github.com/StackStorm/st2/pull/3125. Just missed the v2.1.1 deadline. Oh well.

**Comment by andrew-regan** [comment]
No worries. We'll pick up the fix once the PR merges in.

**Comment by m4dcoder** [comment]
Fix is merged into master
