### ISSUE TITLE
Executions API filtering to exclude attribute `result` does not work. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3042]

**Comment by lakshmi-kannan** [comment]
John Welborn on slack: 

&exclude_attributes=result&exclude_attributes=trigger_instance
vs
&exclude_attributes=result%2Ctrigger_instance

only the second way works

I'm passing params to requests.get where its a dict that contains 'exclude_attributes' which is ['result', 'trigger_instance'] when it should be 'result,trigger_instance' for it to work

**Comment by lakshmi-kannan** [comment]
We not parsing query parameters correctly might have something to do with Pecan. We can revisit this as part of V2 APIs we are building. cc: @enykeev.

**Comment by LindsayHill** [comment]
Now that we've released 2.3, with v2 APIs, might be time to test/revisit this?

**Comment by LindsayHill** [comment]
Did some tests with 2.10.3.

Using `/v1/executions/?limit=1&exclude_attributes=result%2Cstatus` works.

Using `/v1/executions/?limit=1&exclude_attributes=result&exclude_attributes=status` will only exclude `status`, not `result`

Flipping it around to `http://127.0.0.1:9101/v1/executions/?limit=1&exclude_attributes=status&exclude_attributes=result` will exclude `result`, not `status`.

But looking at what we way in our API docs:

> exclude_attributes    array[string] List of attributes to exclude

I don't think this is a priority to change the behavior.
