### ISSUE TITLE
Necessity of 'number' type in schema

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm/st2#3099]
(Maybe this is related with #2943)

According to [this definition](https://github.com/StackStorm/st2/blob/master/st2common/st2common/util/schema/__init__.py#L58-L67), `type` parameter can take the `number`.

But I don't know how to use the type of `number` and `integer` differently.

In what cases does it take a `number` type value, or vice versa?

Thank you.

**Comment by Kami** [comment]
Here is the difference:

* `number` type supports whole numbers and decimal numbers (e.g. 2, 2.0, 3.333, etc.)
* `integer` type only supports whole numbers (e.g. 2, 10, 100, etc).

So you would use `integer` when you only want to support whole numbers and `number` when you want to support both (whole numbers and decimal numbers).

**Comment by userlocalhost** [comment]
Thank you for your prompt reply!
I got it.

**Comment by Kami** [comment]
You are welcome.

I also also add this note to the documentation in the place where we document `type` attribute for action parameter.
