### ISSUE TITLE
Support MongoDB 3.4

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#3100]
MongoDB 3.4 is the current latest stable release and we should eventually add support for it.

Sadly it won't be totally straight- forward, because that version includes some backward incompatible changes and we make sure it doesn't break stuff for existing users (for new installations it will probably be easier although there are still some pymongo changes we need to evaluate).

**Comment by andrew-regan** [comment]
+1

**Comment by Kami** [comment]
If everything goes according to plan, https://github.com/StackStorm/st2/pull/3185 will be merged in time for v2.2.0 release and as such, MongoDB 3.4 will also be supported in this upcoming release.

**Comment by andrew-regan** [comment]
@Kami any upgrade implications on the StackStorm side going from 2.1 --> 2.2 with this fix? Looks like the Mongo upgrade from 3.2 --> 3.4 should be straight forward: https://docs.mongodb.com/manual/release-notes/3.4-upgrade-standalone/

**Comment by bigmstone** [comment]
@andrew-regan there shouldn't be. The biggest change from 2.1 -> 2.2 is we're back in sync with mistral upstream, but we take great care in making sure upgrades work as expected. Not to say it's devoid of bugs, but when we release we expect it to work fine for you - and testing upgrade is part of our CI process.

**Comment by Kami** [comment]
@andrew-regan Yeah, what @bigmstone said - MongoDB 3.4 StackStorm code changes are also fully backward compatible and work with MongoDB 3.2.
