### ISSUE TITLE
pack install does not register rules in 2.1

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#3112]
@bigmstone asked me to file an issue about it.
`st2 pack install <git repo url>` does not register rules. 

Either documentation should mention it, or user should be allowed to add some argument to the install command (like we had register=all option before), or explicitly tell users to use the `st2 pack register <packname>` command if you want anything other than actions to get [re]registered.

**Comment by Kami** [comment]
@bigmstone This is the same "issue" as the one I mentioned on Slack and here - https://github.com/StackStorm/st2/pull/3108.

As far as I know, it's not related to v2.1.0, but the same behavior existed before. By default, `packs.load` command only loads actions aliases and sensors - https://github.com/StackStorm/st2/blob/master/contrib/packs/actions/load.yaml#L10.

We intentionally didn't load rules by default in the past because rules usually need to be configured and enabled by the users before they make sense (they are more installation specific then other resources).

If we all agree that for some reason we should need load rules by default (at the very least we should fix it to register triggers by default - I got this), I'm fine with making the change, but it should probably be part of v2.2 or similar.

**Comment by armab** [comment]
Since with a new pack management we register content per-pack now (which is a big improvement), maybe it's a good time to register all content coming with a pack?

This always was confusing for users and they kept asking over and over and created duplicated Issues.

**Comment by armab** [comment]
If registering rules by default, we maybe should double-check that all packs in `Exchange` have `disabled` flag for rules. So the transition will be safer.

At the same time, with change like that, users may have better infra as a code and better flexibility.
They can place "enabled" rules in custom packs and assume that everything is registered, eg. no futher steps needed like `register`.
Better and more predictable deployments, especially when using configuration management tools.

**Comment by Kami** [comment]
@armab We have many discussion in the past but perhaps it's not bad to re-evaluate the decision.

Most rule actually do ship disabled by default this days so it might be OK to just register them on install. It would only be problematic with rules which refer to triggers from other packs, but I don't think we actually have any such rules in Exchange (we do have them in st2cd and st2ci though).

/cc @lakshmi-kannan @dzimine

**Comment by LindsayHill** [comment]
Not sure exactly which change it came in, but it appears that rules are now registered by default.
e.g.
```bash
vagrant@bwcvagrant:/opt/stackstorm/packs$ st2 --version
st2 2.4.1
vagrant@bwcvagrant:/opt/stackstorm/packs$ st2 pack install twitter

For "twitter" pack following content will be registered:

rules     |  1
sensors   |  2
triggers  |  0
actions   |  3
aliases   |  0

Installation may take a while based on number of items.

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[ succeeded ] register pack

+-------------+--------------------------------------------------+
| Property    | Value                                            |
+-------------+--------------------------------------------------+
| name        | twitter                                          |
| description | st2 content pack containing twitter integrations |
| version     | 0.3.0                                            |
| author      | StackStorm, Inc.                                 |
+-------------+--------------------------------------------------+
vagrant@bwcvagrant:/opt/stackstorm/packs$ st2 rule list -p twitter
+------------------------------+---------+-----------------------------------+---------+
| ref                          | pack    | description                       | enabled |
+------------------------------+---------+-----------------------------------+---------+
| twitter.relay_tweet_to_slack | twitter | Relay Tweet to the Slack channel. | True    |
+------------------------------+---------+-----------------------------------+---------+
vagrant@bwcvagrant:/opt/stackstorm/packs$
```
So in that example the rule is automatically registered & enabled.
