### ISSUE TITLE
systemd privateTmp stops data being shared between actions in a workflow

### ISSUE THREAD

**Issue by AndyMoore111** [StackStorm/st2#3122]
in ubuntu 16.04 systemd's privateTmp is being enforced more rigidly than in previous versions

We previously (st2 2.0.1 with U14) had workflows where action1 will download something (to /tmp), action2 will modify it, and action3 will use it - this behaviour no longer works

as discussed on slack with @bigmstone this behaviour change should be checked to see whether its expected/desired, and if so documented that this pattern won't work going forward

fwiw using ~stanley seems to work perfectly well (and as such we'll probably move our workflows to use a derivative of that, but you lose the side bonus of tmpwatch)

**Comment by armab** [comment]
Right, `PrivateTmp=true` flag is set in systemd unit files: https://github.com/StackStorm/st2-packages/blob/27927f8c1dcc8111db13a1bc9bda71d5f2ad92af/packages/st2/debian/st2actionrunner%40.service#L15

Here is a good reading about this security improvement introduced in `systemd`: 
https://access.redhat.com/blogs/766093/posts/1976243

Not sure about effects if we consider changing it, but it's definitely a good recommendation to use that flag for security reasons.
Anyways, definitely something that's good to discuss in terms of pros/cons.

**Comment by armab** [comment]
Implemented in https://github.com/StackStorm/st2-packages/pull/458, thanks tot @enykeev  for finding the `JoinsNamespaceOf` systemd option and will be available in next stable release (you can test unstable now).
