### ISSUE TITLE
Elaborate on some error messages when possible

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2#3139]
I had a typo in my NAPALM pack action's metadata file, which effectively pointed to a python script for this action that didn't exist. As a result, I got this error when trying to run it:
```
(virtualenv)vagrant@st2dev:~/st2$ st2 run napalm.napalm_load_config driver=junos hostname=10.12.0.1 username=root password=Juniper port=2222 config="hostname test_device"
.
id: 5859c0a232ed350a5c154b2e
status: failed
parameters:
  config: hostname test_device
  driver: junos
  hostname: 10.12.0.1
  password: '********'
  port: '2222'
  username: root
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/home/vagrant/st2/st2common/st2common/runners/python_action_wrapper.py", line 242, in <module>
    obj.run()
  File "/home/vagrant/st2/st2common/st2common/runners/python_action_wrapper.py", line 153, in run
    action = self._get_action_instance()
  File "/home/vagrant/st2/st2common/st2common/runners/python_action_wrapper.py", line 191, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File "/home/vagrant/st2/st2common/st2common/util/loader.py", line 155, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
IOError: [Errno 2] No such file or directory
```

In retrospect, this error does indeed describe the problem, but to a new user this is somewhat insufficient. This stack trace doesn't include any of my code, and it doesn't say what file it wasn't able to find.

As an example, when I write a playbook with Ansible and screw up some YAML somewhere, it doesn't just throw a parsing error - it intercepts such errors and attempts to interpret them into plain English about what the problem is and how to fix it. (i.e. "This error usually means you forgot to encapsulate a {{ variable }} in quotes")

Similarly, we should do something like that here, such as catching the IOError, and reading the message "No such file or directory", and providing output to the user that says something like "usually, this means the metadata file is referring to a Python script that doesn't exist. Please make sure your metadata file is accurate".

**Comment by Kami** [comment]
Agreed - we should do a very similar thing we already do for sensors in the sensor container - https://github.com/StackStorm/st2/pull/3132

**Comment by armab** [comment]
+1 on ^^ thoughts.

I have exactly the same vision, described here: [User-friendly Error Reporting #2320](https://github.com/StackStorm/st2/issues/2320)

**Comment by bigmstone** [comment]
Wow. Crazy it got reported again one day shy of exactly a year.

**Comment by armab** [comment]
lol, I didn't notice the day :calendar: 

Anyways it's another good reminder for everyone to follow better Error Reporting in StackStorm core in general, more Friendly Messages for users and overall better experience.

It's never-ending process of improvement we should keep in mind during development :+1:
