### ISSUE TITLE
Getting an error while passing a single rbridge_id value as input

### ISSUE THREAD

**Issue by poorani612** [StackStorm/st2#3157]
Getting an error while passing a single rbridge_id value as input. rbridge_id type is array and legnth of the array is 1.  I am not getting any error while running the same action with single element in Web UI.

```
st2 run network_essentials.modify_arp_nd_aging_ve mgmt_ip=10.20.34.46 arp_aging_type=arp_aging vlan_id=10 rbridge_id=52
ERROR: 400 Client Error: Bad Request
MESSAGE: 52 is not of type 'array', 'null' for url: http://127.0.0.1:9101/v1/executions
```

**Comment by Mierdin** [comment]
I am noting that @poorani612 also mentioned that this behavior is new to 2.1 - this worked in 2.0.1. I'm looking over the `st2client` code today to see if I can identify what changed

**Comment by Mierdin** [comment]
@poorani612 The parsing of these parameters occurs in https://github.com/StackStorm/st2/commits/master/st2client/st2client/commands/action.py and this file hasn't been changed since before the 2.0.1 release

Have you been able to confirm that this worked in a previous release?

**Comment by poorani612** [comment]
Everyone upgraded to 2.1 and not able to verify in 2.0 :-(

**Comment by Mierdin** [comment]
@poorani612 no problem - based on my findings I'm guessing this has always existed. Regardless, thanks for the find, and watch #3159 for the fix
