### ISSUE TITLE
Upgrade version of six to 1.10.0

### ISSUE THREAD

**Issue by samirsss** [StackStorm/st2#3166]
Currently st2client is still on 1.9.0, which is causing CI to fail for bwc-topology and all the candy-factory repos where this is a dependency. We might want to upgrade the version of six to a newer version.

https://github.com/StackStorm/st2/blob/master/st2client/setup.py#L60

**Comment by Kami** [comment]
I'm fine with that as long as it doesn't break other stuff.

In the past, when st2 wasn't isolated inside a virtual environment we had some issues with six version on RHEL, but this shouldn't be a problem anymore.

**Comment by samirsss** [comment]
I will try and see if this change breaks the CI. If it doesnt will just submit the PR for review.

**Comment by bigmstone** [comment]
@samirsss Is this what you're seeing?

`error: The 'six==1.9.0' distribution was not found and is required by st2client`

**Comment by samirsss** [comment]
Yep thats the error I am seeing. Since setuptools 34.1.1 now needs six>1.10.0 and that's what gets installed
