### ISSUE TITLE
Mattermost: Invalid message

### ISSUE THREAD

**Issue by livelace** [StackStorm/st2#3176]
Hello. I cannot get a big message in Mattermost. 

Good message: https://paste.fedoraproject.org/542532/48597115/
Bad message: https://paste.fedoraproject.org/542531/85970852/
Debug log of Mattermost during appearing of the bad message: https://paste.fedoraproject.org/542529/96987314/

**Comment by DoriftoShoes** [comment]
This isn't an ST2 issue. It is due to a hard limit of 4000 chars in Mattermost: http://forum.mattermost.org/t/mattermost-message-size-limit/637/3

**Comment by livelace** [comment]
Forgot to mention that chatops.post_result is in succeed state. Is it normal ?

**Comment by livelace** [comment]
@DoriftoShoes Yes, you are right. Thanks.
