### ISSUE TITLE
[Feature] Allow Jinja filters in Packs

### ISSUE THREAD

**Issue by peschmae** [StackStorm/st2#3179]
It would be great to be able to provide custom Jinja filters, with a Stackstorm Pack.

We're using Ansible for lots of our ChatOps commands, since we want to be able to reuse those commands/tasks outside of Stackstorm.

Displaying the Output of a Ansible command using Action-Aliases results in a load of duplicate Code, since we basically always need to get a Task from the JSON, and display stdout/stdout_lines.

It would also allow for easier error handling based on the Stats Ansible return.

I propose to namespace the jinja filter, similar to how action-aliases are namespaced, this would allow reuse in different packs, and should avoid conflicts between packs, using similar filter names.

**Comment by peschmae** [comment]
I've dug through the code, and currently a fixed list of filters is included from Stackstorm, and without hacking the core, and placing files into a directory that most likely get's overwritten during the next update, doesn't make sense.

It might make sense, to add the filters to the pack.yaml, instead of loading just all files in a filters directory within the packs.

**Comment by armab** [comment]
@peschmae Thanks for a feature request!

There is similar issue for custom Jinja filters, take a look: https://github.com/StackStorm/st2/issues/2956

**Comment by peschmae** [comment]
True, that's a duplicate of #2956

I'm going to add my thoughts there, and close this one.
