### ISSUE TITLE
Parameters can't be ordered in the UI if no positional argument are used

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2#3206]
It's possible to use the position property for actions. But the position property causes that a positional argument is passed to the action script. But I would like to use --parameter=somevalue, instead of a positional argument. In that case it would still be nice if parameters could be ordered in the UI.

**Comment by pietervogelaar** [comment]
Even just showing the parameters without a position property alphabetically would be an improvement. At the moment it's random.

**Comment by bigmstone** [comment]
@pietervogelaar Can you provide a little more info? You should be able to provide arguments by name even w/ position set.

**Comment by armab** [comment]
Regarding  parameter ordering in the `Web UI`, I think this is what really meant: https://github.com/StackStorm/st2web/issues/154 (we have an issue for that).

@pietervogelaar You can :+1: there to bring more attention.

**Comment by pietervogelaar** [comment]
Thanks that's indeed what I meant!

**Comment by armab** [comment]
Thanks for bumping that thread!  :+1: 
The feedback is really important to bring more priority to different issues based on user's requests.

So I'm closing this in favor of https://github.com/StackStorm/st2web/issues/154
