### ISSUE TITLE
Getting Failed to find action [action_name=st2.action] in mistral workflow

### ISSUE THREAD

**Issue by parveenksofc** [StackStorm/st2#3209]
Gist: https://gist.github.com/parveenksofc/52716e687690447a4b9ee7733d862ab2
What I am missing?

/// The meta yaml

---
description: Run a series of simulated actions for fqdn down event.
enabled: true
entry_point: workflows/fqdn_down_workflow.yaml
name: fqdn_down_workflow
pack: Mypack
parameters:
  fqdn:
    required: true
    type: string
  workflow:
    default: Mypack.fqdn_down_workflow.main
    immutable: true
    type: string
runner_type: mistral-v2

/// The yaml file in workflows 

version: "2.0"
name: Mypack.fqdn_down_workflow
description: A workflow that demonstrates nest fqdn down workflow

workflows:

    main:
        type: direct
        input:
            - fqdn
        tasks:
            get_url_status:
                action: Mypack.jsonFromUrl
                input:
                    urlName: "<% $.fqdn %>" 
                publish:
                    status: '% task(get_url_status).result.result.status %'
                    firstip: '% task(get_url_status).result.result.IpAddr[0] %'

///
Mypack.jsonFromUrl  is a python-script action working like charm.

Error

tasks:
  - created_at: '2017-02-10 11:03:45.794123'
    id: c1e92328-e74a-4898-8cb5-f9ef28e3a019
    input: null
    name: get_url_status
    published: {}
    result: []
    state: ERROR
    state_info: Failed to find action [action_name=st2.action]
    updated_at: '2017-02-10 11:03:45.817688'
    workflow_execution_id: 7a34cbaf-0d5f-4a98-9359-04eb370f2e1a
    workflow_name: Mypack.fqdn_down_workflow.main

**Comment by Kami** [comment]
It looks like an incomplete installation aka StackStorm mistral actions weren't (correctly) installed (https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-deb.sh#L478).

How did you install StackStorm?

**Comment by parveenksofc** [comment]
You are a saviour @Kami 


Installed by following steps mentioned [https://docs.stackstorm.com/install/rhel7.html](url)  but somehow missed step
`/opt/stackstorm/mistral/bin/mistral-db-manage --config-file /etc/mistral/mistral.conf populate`


Restarting st2 after executing this step resulted in successful execution of mistral workflow.

Thanks.

**Comment by Kami** [comment]
Glad to hear you got it resolved :+1:
