### ISSUE TITLE
Getting stderr of failed task(s) in a common on-error condition task in mistral workflow. 

### ISSUE THREAD

**Issue by parveenksofc** [StackStorm/st2#3240]
Hi,

I'm working with a mistral workflow and on any **on-error** condition I'm calling a task **calling_on_error** in the workflow on any on-error and want to pass **stderr**  of failed task in the **calling_on_error**.

Publishing is not working as it only works when a task succeeded and [not in case of failure](https://github.com/StackStorm/st2/issues/3224).

Is there any way I can have stderr of previous task to **calling_on_error**  task as I want to pass this another subsequent task for say for sending email notification.

<% task(**Name_of_Task**).result.stderr %> 

will not help as my **Name_of_Task** will keep changing.

Thanks,
Parveen Sharma

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1492117899815875

**Comment by xydinesh** [comment]
+1 this is very helpful for debugging workflows.
