### ISSUE TITLE
Execution user can't be retrieved and hangs a Mistral workflow

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2#3267]
In an action chain I can use {{ action_context.parent.user }} as action parameter value.

If I try to use this in a mistral workflow, it will hang the corresponding action. The workflow just won't finish.

I'm running the latest StackStorm version 2.2.0.

**Comment by LindsayHill** [comment]
See https://docs.stackstorm.com/mistral_yaql.html#mistral for how to access items such as `parent.user` from a Mistral workflow.

Similar syntax here for Jinja https://docs.stackstorm.com/mistral_jinja.html#mistral
