### ISSUE TITLE
How to get core.remote stdout in a mistral workflow?

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2#3289]
I have a mistral workflow and one task called “cleanup”:

Task definition:
```cleanup:
  action: core.remote
  input:
    hosts: example.org
    cmd: 'date'
  publish:
    job_stdout: "{{ task(cleanup).values()[0]['stdout'] }}"
    job_stderr: "{{ task(cleanup).values()[0]['stderr'] }}"
```

The execution history:

```{
  "tasks": [
    {
      "state_info": null,
      "name": "cleanup",
      "created_at": "2017-03-02 13:59:01.672551",
      "updated_at": "2017-03-02 13:59:04.350903",
      "id": "4fc10792-d6a5-4874-bc4d-7000795d7b66",
      "workflow_execution_id": "8793b1bb-2681-47dd-a634-4b39f8f1f030",
      "state": "SUCCESS",
      "result": {
        "example.org": {
          "failed": false,
          "stderr": "",
          "return_code": 0,
          "succeeded": true,
          "stdout": ""
        }
      }
    }
  ]
}
```

Because the core.remote action can execute a command on several hosts, there is no result.stdout like core.local, but a stdout per host.

This  {{ task(cleanup).values()[0]['stdout'] }} works in an action chain to get the stdout of the first host, but I can’t figure out what the correct syntax is for a mistral worflow. Can anybody help me?

**Comment by LindsayHill** [comment]
I think the syntax is something like this https://github.com/StackStorm/st2cd/blob/master/actions/workflows/st2_get_installed_version.yaml#L24

**Comment by sidkrishna** [comment]
This syntax works.. :+1:  I just verified it with one of my mistral workflows where I was trying to do that same.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1501771621123095
