### ISSUE TITLE
Action status stays "Scheduled"

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2#3320]
I have StackStorm running fine in a production environment. The same setup runs in the test environment. However, every time I execute an action in the test environment the action status stays "Scheduled". All the processes seem to run normally, no strange things in the logging.

Wat could be the problem that the action is not picked up? I do see action runner processes running.

As example, core.local action with cmd parameter value "date", just stays on status "Scheduled".

**Comment by bigmstone** [comment]
Is the action actually executing and displaying "scheduled" or is it not running at all? Can you give me the output of your `actionrunner` logs as well as `st2api` logs in a gist?

I'm particularly interested in the `actionrunner` logs. If you can do a `tail -f /var/log/st2/st2actionrunner.*.log` and let it settle out tailing all the files then execute your action while nothing else is being requested this should be fairly revealing.

**Comment by pietervogelaar** [comment]
Today I had time to look at this again. But actions just run normally now.

However I saw that the actions that had the status "Scheduled" were eventually finished with the status "Succeeded". But the action below core.local with the command "date" took about 30 minutes.

```
Succeeded
Execution ID: 58dd0bef4fd897166eb07324
Started: Thu, 30 Mar 2017 13:45:19 UTC
Finished: Thu, 30 Mar 2017 14:16:30 UTC
```

So that's still very strange...

**Comment by pietervogelaar** [comment]
When I redeploy one of the two puppetized StackStorm servers, I get similar behaviour again. This time the status stays "Requested". When I execute on both servers `tail -f /var/log/st2/st2actionrunner.*.log` and then execute an action no new information is logged.

**Comment by pietervogelaar** [comment]
Also no logging when debug is set to `True` in `/etc/st2/st2.conf`:

```
[system]
debug = True
```

**Comment by armab** [comment]
@pietervogelaar Any specifiic conditions when you're getting this state?
What OS is that?
RabbitMQ version?
Memory/CPU resources on the machine?

For example if you experiencing this issue immediately after st2 startup on Ubuntu Xenial, it could be related to https://github.com/StackStorm/st2/issues/3290

**Comment by pietervogelaar** [comment]
OS: RHEL 7.3
RabbitMQ: 3.6.2
Erlang 18.3
Memory: 4GB
CPU: 2
Average load (from top): 0.10

**Comment by cognifloyd** [comment]
If you are still experiencing this with version 3.5, please file a new issue.
Thanks!
