### ISSUE TITLE
Request for improvement

### ISSUE THREAD

**Issue by fabriziotorelli-wipro** [StackStorm/st2#3327]
I need to apply an automation to vagrant for RancherOS. If you need some more material about I can send you some materials, else-way I am requiring if you have any plan for pull requests.

Thanks,

Fabrizio Torelli
(https://github.com/fabriziotorelli-wipro)

**Comment by LindsayHill** [comment]
It would be helpful if you described what improvement you want. It's unclear what ST2 components you're referring to. 

Pull requests are always welcome.
