### ISSUE TITLE
Searching for a string with `:` in it in YAQL does not work

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3345]
For example, this snippet:

```
- found: <% "FAIL: something" in $.echo_output %>
- notfound: <% not "FAIL: something" in $.echo_output %>
```

complains `mapping values are not allowed here`.

Escaping the `:` does not work as in both these variables evaluate to True.
```
- found: <% "FAIL:\ something" in $.echo_output %>
- notfound: <% not "FAIL:\ something" in $.echo_output %>
```
when 
```
"echo_output": "FAIL: something"
```

Regex works according to john.welborn on slack

```
- found: <% regex('.*FAIL:\ something.*').search($.echo_output) %>
```

**Comment by m4dcoder** [comment]
The colon is being interpreted by YAML safe load as part of the YAML text.  If you put a double quote around the YAQL expression, YAML will load this correctly. The correction is posted below.

```
- found: "<% 'FAIL: something' in $.echo_output %>"
- notfound: "<% not 'FAIL: something' in $.echo_output %>"
```

If this problem persists for you, please reopen this issue.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1491853765137460
