### ISSUE TITLE
rule create using existing rule name gives 500 server error with no details

### ISSUE THREAD

**Issue by stevemuskiewicz** [StackStorm/st2#3354]
While attempting to add a new rule with `st2 rule create <yamlfile>` I inadvertently used a rule name that was already in st2.

Instead of telling me this was a duplicate, st2 responded with:

    st2 rule create nightly_build.yaml 
    ERROR: 500 Server Error: Internal Server Error
    MESSAGE: Internal Server Error for url: http://127.0.0.1:9101/v1/rules

Exception trace in `st2api.log` is equally unhelpful:

    2017-04-14 09:28:01,056 80281840 ERROR hooks [-] API call failed: no such item for Cursor 
    instance
    Traceback (most recent call last):
      File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 631, in __call__
        self.invoke_controller(controller, args, kwargs, state)
      File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 531, in invoke_controller
        result = controller(*args, **kwargs)
      File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/api/base.py", line 284, in callfunction
        raise e
    IndexError: no such item for Cursor instance (_exception_data{},_exception_class='IndexError',_exception_message='no such item for Cursor instance')

It would be nice if st2 instead gave something straightforward in its error response, such as "rule name is already in use"

**Comment by lakshmi-kannan** [comment]
@stevemuskiewicz This seems like a regression for sure. What version of st2 were you using?

**Comment by stevemuskiewicz** [comment]
@lakshmi-kannan wups sorry forgot to mention version, I'm still on st2 2.1.1

**Comment by lakshmi-kannan** [comment]
@stevemuskiewicz https://gist.github.com/lakshmi-kannan/fe5ac9d083076d40aa5f7a23a62433d1 I cannot repro this in master (2.3dev). If it were a regression in 2.1.1, this seems fixed :).
