### ISSUE TITLE
st2client missing python dependencies

### ISSUE THREAD

**Issue by jwomack** [StackStorm/st2#3367]
I needed to go through stack traces to find the following dependencies:
pytz
editor
jsonschema
prompt_toolkit

Fixed by:
sudo pip install pytz
sudo pip install editor
sudo pip install jsonschema
sudo pip install prompt_toolkit

**Comment by LindsayHill** [comment]
How did you install st2client? Some of those dependencies - e.g. pytz - are covered in https://github.com/StackStorm/st2/blob/master/st2client/requirements.txt

**Comment by cyberious** [comment]
I too am unable to get st2client installed, have tried both Python 2.7 or Python 3.6 using pip install and falling down a rabbit whole of dependency. Installing a OS X.

```
Traceback (most recent call last):
  File "/usr/local/bin/st2", line 7, in <module>
    from st2client.shell import main
  File "/usr/local/lib/python2.7/site-packages/st2client/shell.py", line 39, in <module>
    from st2client.commands import pack
  File "/usr/local/lib/python2.7/site-packages/st2client/commands/pack.py", line 18, in <module>
    import editor
ImportError: No module named editor
```
Finally got working after manually running `sudo pip install python-editor`

**Comment by enykeev** [comment]
The dependency is [there](https://github.com/StackStorm/st2/blob/master/st2client/requirements.txt#L7) though. I would also like to know how you're installing st2client, it might that we missed something during, say, packaging....

**Comment by cyberious** [comment]
Just using `pip install st2client`

**Comment by cognifloyd** [comment]
The problem occurs when installing via pypi:
```pip install st2client --user```

The reason is that the requirements in [st2client/setup.py](https://github.com/StackStorm/st2/blob/v2.2.1/st2client/setup.py#L54-L61) do not match with [st2client/requirements.txt](https://github.com/StackStorm/st2/blob/v2.2.1/st2client/requirements.txt).

These are in requirements.txt, but not setup.py 

- `argcomplete`
- `pytz`
- `sseclient`
- `python-editor`
- `prompt-toolkit`

These version requirements don't match (requirements.txt vs setup.py):

- `requests[security]<2.12,>=2.11.1` vs `requests<3.0,>=2.7.0`

**Comment by cognifloyd** [comment]
To avoid setup.py and requirements.txt getting out of sync, requirements.txt could be replaced with something simpler, as described here: https://caremad.io/posts/2013/07/setup-vs-requirement/

Would that be acceptable? If not, what's st2's preferred method for keeping requirements.txt and setup.py in sync?

**Comment by j3p0uk** [comment]
This is still an issue, the package on pypi needs the following installed before it is usable:

`pip install argcomplete pytz jsonschema prompt_toolkit python-editor`

**Comment by Kami** [comment]
@j3p0uk Thanks for reporting.

I need to check, because we did update setup.py in the past, but it's possible it's still out of sync.

**Comment by jjm** [comment]
I can confirm this is still an issue, I setup a virtualenv on MacOS using pipenv and had to install the packages listed above.

```
st2 2.7.2, on Python 2.7
```

**Comment by Kami** [comment]
@jjm I believe #4209 should solve that (I will verify it now).

It's targeted for v2.8.1 / v2.9.0 release.

**Comment by Kami** [comment]
@jjm I confirmed that changes in #4209 indeed fix this issue by running the following command in a fresh virtual environment:

```bash
pip install -e "git+https://github.com/stackstorm/st2.git@setup_reqs#egg=st2client&subdirectory=st2client"
```
