### ISSUE TITLE
Add an option to hide certain action executions from st2web ui

### ISSUE THREAD

**Issue by brezus** [StackStorm/st2#3384]
We have a few heartbeat/status check actions that run frequently and don't give us any useful information unless they fail. They largely just make it hard to see the useful parts of our action history. Other systems we've used in the past have had "only show on failure" flags that can be used to denote a recurring low-importance action. Something like that would be very useful for us, since what we normally see now looks like this:
![screen shot 2017-04-25 at 3 50 24 pm](https://cloud.githubusercontent.com/assets/609595/25632882/23f1b264-2f2a-11e7-88b9-3df37a2d9f30.png)

**Comment by Kami** [comment]
Shouldn't existing "status" filter do the trick (you should be able to filter on status = failure)?

Or you mean a different kind of filter?

**Comment by LindsayHill** [comment]
Closing due to no response to request for info. Let us know if you need to re-open this
