### ISSUE TITLE
Config option system.validate_trigger_payload not being honored

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2#3385]
https://github.com/StackStorm/st2/pull/3142 introduced a new option to disable validation for trigger payloads, among other things. The advertised default behavior is that validation is disabled by default, but can be explicitly enabled with [this option](https://github.com/StackStorm/st2/blob/master/conf/st2.conf.sample#L265).

However, several users have reported that [validation is still being done](https://github.com/StackStorm-Exchange/stackstorm-kubernetes/issues/11) regardless of the presence or even the value of this configuration option.

My theory is that, because [the configuration definition for these options](https://github.com/StackStorm/st2/pull/3142/files#diff-f7f00f2d9fa85d6b39dc2def0f872561R77) set up these two options as `StrOpt`, [this conditional](https://github.com/StackStorm/st2/pull/3142/files#diff-fcc1652906182b402530d76b68e1733aR91) always evaluates to False, since `cfg.CONF.system.validate_trigger_parameters` is always populated with a value, and will always evaluate to True in this expression. Therefore, the following validation logic isn't skipped and always takes place.

So, a few things need done:

- [x] confirm my theory, and that this is indeed a bug
- [x] fix le bug
- [x] find out why this wasn't caught in testing and amend things as needed

**Comment by Kami** [comment]
Good catch - this should totally be `BoolOpt` :)

And yeah, would need to dig in why the existing tests didn't catch this (we probably have no tests which directly use default value from the config).
