### ISSUE TITLE
Update runner_types from "run-python" to "python-script" in Exchange packs

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3389]
In several packs in the Exchange there are actions using the legacy `runner_type` of `run-python`. According to the upgrade notes: https://docs.stackstorm.com/upgrade_notes.html#st2-v0-9 this has been renamed to `python-script`.

We should update the actions to use the new `runner_type`

**Comment by Mierdin** [comment]
:+1: and this should apply to all "deprecated" runners. There are a number of other runners that have been "deprecated" for a long time, and we should make efforts to remove these, and enforce that all actions use the currently valid ones

**Comment by LindsayHill** [comment]
Well, this is depressing. I have a directory containing a local clone of all Exchange repos:

```
Lindsays-MacBook:exchange lhill$ grep python-script */actions/*.yaml|cut -f 1 -d '/'|sort -u|wc -l
      38
Lindsays-MacBook:exchange lhill$ grep run-python */actions/*.yaml|cut -f 1 -d '/'|sort -u|wc -l
      71
Lindsays-MacBook:exchange lhill$ grep python-script */actions/*.yaml|wc -l
     492
Lindsays-MacBook:exchange lhill$ grep run-python */actions/*.yaml|wc -l
    2378
Lindsays-MacBook:exchange lhill$
```

So we currently have 71 packs, containing a total of 2378 actions, that use `run-python`, and need updating to use `python-script`. 

All easy enough to do, just a bit tedious work. Looks like there's a few of the packs with auto-generated actions that blow out the total numbers a bit. 

Here's the current list of packs needing updates:

- [ ] [stackstorm-activecampaign](https://github.com/StackStorm-Exchange/stackstorm-activecampaign)
- [ ] [stackstorm-astral](https://github.com/StackStorm-Exchange/stackstorm-astral)
- [ ] [stackstorm-aws](https://github.com/StackStorm-Exchange/stackstorm-aws)
- [ ] [stackstorm-azure](https://github.com/StackStorm-Exchange/stackstorm-azure)
- [ ] [stackstorm-bitbucket](https://github.com/StackStorm-Exchange/stackstorm-bitbucket)
- [ ] [stackstorm-circle_ci](https://github.com/StackStorm-Exchange/stackstorm-circle_ci)
- [ ] [stackstorm-cisco_spark](https://github.com/StackStorm-Exchange/stackstorm-cisco_spark)
- [ ] [stackstorm-consul](https://github.com/StackStorm-Exchange/stackstorm-consul)
- [ ] [stackstorm-csv](https://github.com/StackStorm-Exchange/stackstorm-csv)
- [ ] [stackstorm-cubesensors](https://github.com/StackStorm-Exchange/stackstorm-cubesensors)
- [ ] [stackstorm-datadog](https://github.com/StackStorm-Exchange/stackstorm-datadog)
- [ ] [stackstorm-device42](https://github.com/StackStorm-Exchange/stackstorm-device42)
- [ ] [stackstorm-digitalocean](https://github.com/StackStorm-Exchange/stackstorm-digitalocean)
- [ ] [stackstorm-docker](https://github.com/StackStorm-Exchange/stackstorm-docker)
- [ ] [stackstorm-elasticsearch](https://github.com/StackStorm-Exchange/stackstorm-elasticsearch)
- [ ] [stackstorm-email](https://github.com/StackStorm-Exchange/stackstorm-email)
- [ ] [stackstorm-excel](https://github.com/StackStorm-Exchange/stackstorm-excel)
- [ ] [stackstorm-fireeye](https://github.com/StackStorm-Exchange/stackstorm-fireeye)
- [ ] [stackstorm-github](https://github.com/StackStorm-Exchange/stackstorm-github)
- [ ] [stackstorm-google](https://github.com/StackStorm-Exchange/stackstorm-google)
- [ ] [stackstorm-gpg](https://github.com/StackStorm-Exchange/stackstorm-gpg)
- [ ] [stackstorm-hpe_icsp](https://github.com/StackStorm-Exchange/stackstorm-hpe_icsp)
- [ ] [stackstorm-hubot](https://github.com/StackStorm-Exchange/stackstorm-hubot)
- [ ] [stackstorm-hue](https://github.com/StackStorm-Exchange/stackstorm-hue)
- [ ] [stackstorm-ipcam](https://github.com/StackStorm-Exchange/stackstorm-ipcam)
- [ ] [stackstorm-jenkins](https://github.com/StackStorm-Exchange/stackstorm-jenkins)
- [ ] [stackstorm-jira](https://github.com/StackStorm-Exchange/stackstorm-jira)
- [ ] [stackstorm-jmx](https://github.com/StackStorm-Exchange/stackstorm-jmx)
- [ ] [stackstorm-kubernetes](https://github.com/StackStorm-Exchange/stackstorm-kubernetes)
- [ ] [stackstorm-libcloud](https://github.com/StackStorm-Exchange/stackstorm-libcloud)
- [ ] [stackstorm-librato](https://github.com/StackStorm-Exchange/stackstorm-librato)
- [ ] [stackstorm-mailgun](https://github.com/StackStorm-Exchange/stackstorm-mailgun)
- [ ] [stackstorm-mistral](https://github.com/StackStorm-Exchange/stackstorm-mistral)
- [ ] [stackstorm-mmonit](https://github.com/StackStorm-Exchange/stackstorm-mmonit)
- [ ] [stackstorm-mysql](https://github.com/StackStorm-Exchange/stackstorm-mysql)
- [ ] [stackstorm-nest](https://github.com/StackStorm-Exchange/stackstorm-nest)
- [ ] [stackstorm-network_essentials](https://github.com/StackStorm-Exchange/stackstorm-network_essentials)
- [ ] [stackstorm-newrelic](https://github.com/StackStorm-Exchange/stackstorm-newrelic)
- [ ] [stackstorm-openstack](https://github.com/StackStorm-Exchange/stackstorm-openstack)
- [ ] [stackstorm-packer](https://github.com/StackStorm-Exchange/stackstorm-packer)
- [ ] [stackstorm-pagerduty](https://github.com/StackStorm-Exchange/stackstorm-pagerduty)
- [ ] [stackstorm-powerpoint](https://github.com/StackStorm-Exchange/stackstorm-powerpoint)
- [ ] [stackstorm-puppet](https://github.com/StackStorm-Exchange/stackstorm-puppet)
- [ ] [stackstorm-pushbullet](https://github.com/StackStorm-Exchange/stackstorm-pushbullet)
- [ ] [stackstorm-rackspace](https://github.com/StackStorm-Exchange/stackstorm-rackspace)
- [ ] [stackstorm-salt](https://github.com/StackStorm-Exchange/stackstorm-salt)
- [ ] [stackstorm-save_kittens](https://github.com/StackStorm-Exchange/stackstorm-save_kittens)
- [ ] [stackstorm-sensu](https://github.com/StackStorm-Exchange/stackstorm-sensu)
- [ ] [stackstorm-slack](https://github.com/StackStorm-Exchange/stackstorm-slack)
- [ ] [stackstorm-smartthings](https://github.com/StackStorm-Exchange/stackstorm-smartthings)
- [ ] [stackstorm-softlayer](https://github.com/StackStorm-Exchange/stackstorm-softlayer)
- [ ] [stackstorm-splunk](https://github.com/StackStorm-Exchange/stackstorm-splunk)
- [ ] [stackstorm-st2](https://github.com/StackStorm-Exchange/stackstorm-st2)
- [ ] [stackstorm-telegram](https://github.com/StackStorm-Exchange/stackstorm-telegram)
- [ ] [stackstorm-test](https://github.com/StackStorm-Exchange/stackstorm-test)
- [ ] [stackstorm-test2](https://github.com/StackStorm-Exchange/stackstorm-test2)
- [ ] [stackstorm-time](https://github.com/StackStorm-Exchange/stackstorm-time)
- [ ] [stackstorm-travis_ci](https://github.com/StackStorm-Exchange/stackstorm-travis_ci)
- [ ] [stackstorm-trello](https://github.com/StackStorm-Exchange/stackstorm-trello)
- [ ] [stackstorm-twilio](https://github.com/StackStorm-Exchange/stackstorm-twilio)
- [ ] [stackstorm-twitter](https://github.com/StackStorm-Exchange/stackstorm-twitter)
- [ ] [stackstorm-typeform](https://github.com/StackStorm-Exchange/stackstorm-typeform)
- [ ] [stackstorm-ubersmith](https://github.com/StackStorm-Exchange/stackstorm-ubersmith)
- [ ] [stackstorm-urbandict](https://github.com/StackStorm-Exchange/stackstorm-urbandict)
- [ ] [stackstorm-vault](https://github.com/StackStorm-Exchange/stackstorm-vault)
- [ ] [stackstorm-victorops](https://github.com/StackStorm-Exchange/stackstorm-victorops)
- [ ] [stackstorm-vsphere](https://github.com/StackStorm-Exchange/stackstorm-vsphere)
- [ ] [stackstorm-webpagetest](https://github.com/StackStorm-Exchange/stackstorm-webpagetest)
- [ ] [stackstorm-windows](https://github.com/StackStorm-Exchange/stackstorm-windows)
- [ ] [stackstorm-xml](https://github.com/StackStorm-Exchange/stackstorm-xml)
- [ ] [stackstorm-zendesk](https://github.com/StackStorm-Exchange/stackstorm-zendesk)

**Comment by nmaludy** [comment]
I think i got them all:

stackstorm-activecampaign
https://github.com/StackStorm-Exchange/stackstorm-activecampaign/pull/2

stackstorm-astral
https://github.com/StackStorm-Exchange/stackstorm-astral/pull/1

stackstorm-aws
https://github.com/StackStorm-Exchange/stackstorm-aws/pull/33

stackstorm-azure
https://github.com/StackStorm-Exchange/stackstorm-azure/pull/4

stackstorm-bitbucket
https://github.com/StackStorm-Exchange/stackstorm-bitbucket/pull/4

stackstorm-circle_ci
https://github.com/StackStorm-Exchange/stackstorm-circle_ci/pull/3

stackstorm-cisco_spark
https://github.com/StackStorm-Exchange/stackstorm-cisco_spark/pull/2

stackstorm-consul
https://github.com/StackStorm-Exchange/stackstorm-consul/pull/6

stackstorm-csv
https://github.com/StackStorm-Exchange/stackstorm-csv/pull/1

stackstorm-cubesensors
https://github.com/StackStorm-Exchange/stackstorm-cubesensors/pull/1

stackstorm-datadog
https://github.com/StackStorm-Exchange/stackstorm-datadog/pull/1

stackstorm-device42
https://github.com/StackStorm-Exchange/stackstorm-device42/pull/1

stackstorm-digitalocean
https://github.com/StackStorm-Exchange/stackstorm-digitalocean/pull/1

stackstorm-docker
https://github.com/StackStorm-Exchange/stackstorm-docker/pull/2

stackstorm-elasticsearch
https://github.com/StackStorm-Exchange/stackstorm-elasticsearch/pull/4

stackstorm-email
https://github.com/StackStorm-Exchange/stackstorm-email/pull/4

stackstorm-excel
https://github.com/StackStorm-Exchange/stackstorm-excel/pull/1

stackstorm-fireeye
https://github.com/StackStorm-Exchange/stackstorm-fireeye/pull/1

stackstorm-github
https://github.com/StackStorm-Exchange/stackstorm-github/pull/9

stackstorm-google
https://github.com/StackStorm-Exchange/stackstorm-google/pull/1

stackstorm-gpg
https://github.com/StackStorm-Exchange/stackstorm-gpg/pull/1

stackstorm-hpe_icsp
https://github.com/StackStorm-Exchange/stackstorm-hpe_icsp/pull/1

stackstorm-hubot
https://github.com/StackStorm-Exchange/stackstorm-hubot/pull/1

stackstorm-hue
https://github.com/StackStorm-Exchange/stackstorm-hue/pull/1

stackstorm-ipcam
https://github.com/StackStorm-Exchange/stackstorm-ipcam/pull/1

stackstorm-jenkins
https://github.com/StackStorm-Exchange/stackstorm-jenkins/pull/2

stackstorm-jira
https://github.com/StackStorm-Exchange/stackstorm-jira/pull/7

stackstorm-jmx
https://github.com/StackStorm-Exchange/stackstorm-jmx/pull/1

stackstorm-kubernetes
https://github.com/StackStorm-Exchange/stackstorm-kubernetes/pull/16

stackstorm-libcloud
https://github.com/StackStorm-Exchange/stackstorm-libcloud/pull/3

stackstorm-librato
https://github.com/StackStorm-Exchange/stackstorm-librato/pull/1

stackstorm-mailgun
https://github.com/StackStorm-Exchange/stackstorm-mailgun/pull/1

stackstorm-mistral
https://github.com/StackStorm-Exchange/stackstorm-mistral/pull/1

stackstorm-mmonit
https://github.com/StackStorm-Exchange/stackstorm-mmonit/pull/1

stackstorm-mysql
https://github.com/StackStorm-Exchange/stackstorm-mysql/pull/6

stackstorm-nest
https://github.com/StackStorm-Exchange/stackstorm-nest/pull/1

stackstorm-network_essentials
https://github.com/StackStorm-Exchange/stackstorm-network_essentials/pull/5

stackstorm-newrelic
https://github.com/StackStorm-Exchange/stackstorm-newrelic/pull/1

stackstorm-openstack
https://github.com/StackStorm-Exchange/stackstorm-openstack/pull/9

stackstorm-packer
https://github.com/StackStorm-Exchange/stackstorm-packer/pull/3

stackstorm-pagerduty
https://github.com/StackStorm-Exchange/stackstorm-pagerduty/pull/9

stackstorm-powerpoint
https://github.com/StackStorm-Exchange/stackstorm-powerpoint/pull/1

stackstorm-puppet
https://github.com/StackStorm-Exchange/stackstorm-puppet/pull/2

stackstorm-pushbullet
https://github.com/StackStorm-Exchange/stackstorm-pushbullet/pull/2

stackstorm-rackspace
https://github.com/StackStorm-Exchange/stackstorm-rackspace/pull/1

stackstorm-salt
https://github.com/StackStorm-Exchange/stackstorm-salt/pull/4

stackstorm-save_kittens
https://github.com/StackStorm-Exchange/stackstorm-save_kittens/pull/1

stackstorm-sensu
https://github.com/StackStorm-Exchange/stackstorm-sensu/pull/4

stackstorm-slack
https://github.com/StackStorm-Exchange/stackstorm-slack/pull/5

stackstorm-smartthings
https://github.com/StackStorm-Exchange/stackstorm-smartthings/pull/1

stackstorm-softlayer
https://github.com/StackStorm-Exchange/stackstorm-softlayer/pull/1

stackstorm-splunk
https://github.com/StackStorm-Exchange/stackstorm-splunk/pull/1

stackstorm-st2
https://github.com/StackStorm-Exchange/stackstorm-st2/pull/3

stackstorm-telegram
https://github.com/StackStorm-Exchange/stackstorm-telegram/pull/2

stackstorm-test
https://github.com/StackStorm-Exchange/stackstorm-test/pull/5

stackstorm-test2
https://github.com/StackStorm-Exchange/stackstorm-test2/pull/1

stackstorm-time
https://github.com/StackStorm-Exchange/stackstorm-time/pull/1

stackstorm-travis_ci
https://github.com/StackStorm-Exchange/stackstorm-travis_ci/pull/2

stackstorm-trello
https://github.com/StackStorm-Exchange/stackstorm-trello/pull/2

stackstorm-twilio
https://github.com/StackStorm-Exchange/stackstorm-twilio/pull/1

stackstorm-twitter
https://github.com/StackStorm-Exchange/stackstorm-twitter/pull/2

stackstorm-typeform
https://github.com/StackStorm-Exchange/stackstorm-typeform/pull/2

stackstorm-ubersmith
https://github.com/StackStorm-Exchange/stackstorm-ubersmith/pull/2

stackstorm-urbandict
https://github.com/StackStorm-Exchange/stackstorm-urbandict/pull/1

stackstorm-vault
https://github.com/StackStorm-Exchange/stackstorm-vault/pull/4

stackstorm-victorops
https://github.com/StackStorm-Exchange/stackstorm-victorops/pull/3

stackstorm-vsphere
https://github.com/StackStorm-Exchange/stackstorm-vsphere/pull/20

stackstorm-webpagetest
https://github.com/StackStorm-Exchange/stackstorm-webpagetest/pull/1

stackstorm-windows
https://github.com/StackStorm-Exchange/stackstorm-windows/pull/1

stackstorm-xml
https://github.com/StackStorm-Exchange/stackstorm-xml/pull/1

stackstorm-zendesk
https://github.com/StackStorm-Exchange/stackstorm-zendesk/pull/1

**Comment by LindsayHill** [comment]
Well that was quick, and I'm pretty sure will rocket you to the top of the contributor standings for Exchange packs.

@warrenvw can you please review & merge those PRs? Most should be fine. But watch out for any that have automatic action generators. They may need updates to ensure that the action generators don't later over-write these changes

**Comment by LindsayHill** [comment]
Thanks for the super work @nmaludy - all merged now, and I think that should put you well in the lead for commits to the Exchange repo!
