### ISSUE TITLE
How to get action output while action is running?

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2#3401]
Is it possible to see action output while the action has the status "running"?

In the st2 web ui, I see:

```
ACTION OUTPUT
// Action produced no data
```

And only after the status is "succeeded" or "failed" all the output is displayed. Is it also possible to display information as soon as the python action does a print statement?

**Comment by LindsayHill** [comment]
Not currently, but it's something we've wanted for a while, and it's bubbled up towards the top of the backlog now. See https://github.com/StackStorm/st2/issues/2175

**Comment by LindsayHill** [comment]
Will close this in favor of #2175
