### ISSUE TITLE
error happened while generating RPM

### ISSUE THREAD

**Issue by scutojr** [StackStorm/st2#3415]
I want to make RPM and I run 'make rpms' under project root directory and then it will run 'make rpm' under each subproject. When it tries to copy a directory called packaging, it failed:
```
/home/hehe/dev/st2/st2/st2actions
tar --transform=s~^~st2actions-0.4.0/~ -czf ~/rpmbuild/SOURCES//st2actions.tar.gz bin conf st2actions
cp packaging/rpm/st2actions.spec ~/rpmbuild/SPECS//
cp: cannot stat `packaging/rpm/st2actions.spec': No such file or directory
make[1]: *** [rpm] Error 1
```
Finally, I only got one rpm ~/rpmbuild/RPMS/noarch/st2client-2.2.1-1.noarch.rpm. Is this error normal and what is right way to generate RPM?

**Comment by armab** [comment]
Yeah, we have a dedicated repository for packaging https://github.com/StackStorm/st2-packages/ (with Docker or Vagrant environment) to build + generate `deb` or `rpm` packages for StackStorm.

Please take a look and if you have any problems with the process, - open an issue in `st2-packages`. So I'm closing this.
