### ISSUE TITLE
Mistral backend concurrency question

### ISSUE THREAD

**Issue by tim-ireland** [StackStorm/st2#3429]
Mistral backend question.  I have some st2 workflows using mistral-v2 runner which all use `with-items` to process a collection in mistral by calling an action repeately.  The execution queue seems to have backed up to the point where mistral api calls to POST executions are returning 500 after a 60 sec timeout.  

```
mistral.log:2017-05-17 20:02:14,834 140683480255376 INFO wsgi [-] 127.0.0.1 "PUT /v2/action_executions/1ec52d3e-8b2c-45e5-9d10-5cacc96c4033 HTTP/1.1" status: 500  len: 307 time: 61.0299492
mistral.log:2017-05-17 20:02:27,041 140683481276240 INFO wsgi [-] 127.0.0.1 "PUT /v2/action_executions/94e2cb56-06fd-4e5e-9940-94545d139584 HTTP/1.1" status: 500  len: 307 time: 60.4287479
mistral.log:2017-05-17 20:02:34,928 140683479365584 INFO wsgi [-] 127.0.0.1 "POST /v2/executions HTTP/1.1" status: 500  len: 307 time: 61.0704420
mistral.log:2017-05-17 20:02:34,940 140683479364784 INFO wsgi [-] 127.0.0.1 "PUT /v2/action_executions/a974001a-04a5-406a-a1ef-33dd9066d851 HTTP/1.1" status: 500  len: 307 time: 60.8621340
mistral.log:2017-05-17 20:02:34,953 140683479365104 INFO wsgi [-] 127.0.0.1 "POST /v2/executions HTTP/1.1" status: 500  len: 307 time: 60.8260779
```

I am using:
	mistral 2.2.1
	st2 2.2.1

My actions which run as workflows under mistral are stuck in a running state, while my st2 actions and action chains finish quickly.

```
[root@6312592392b1 home]# st2 execution list -w 150 -n 1`
|   591cc36e9a195a0541308334 | connect.handle_network_event | stanley      | running (58413s elapsed) | Wed, 17 May 2017 21:41:02 UTC |                               |
```

I am wondering if anyone can comment on the concurrency of the mistral backend when running multiple workflows each using `with-items`?  I found the following log message in mistral.log:
```
2017-05-23 13:37:47,655 140348950580592 INFO event_engine [-] Find 0 event triggers.
2017-05-23 13:37:47,818 140348950580752 INFO wsgi [-] mistral_api listening on 0.0.0.0:8989
2017-05-23 13:37:47,818 140348950580752 INFO service [-] Starting 2 workers
2017-05-23 13:37:47,825 140348910207696 INFO wsgi [-] (11782) wsgi starting up on http://0.0.0.0:8989
2017-05-23 13:37:47,830 140348910207696 INFO wsgi [-] (11783) wsgi starting up on http://0.0.0.0:8989
2017-05-23 13:37:47,842 140348911133552 INFO server [-] blocking executor handles only one message at once. threading or eventlet executor is recommended.
2017-05-23 13:37:47,853 140348950581072 INFO server [-] blocking executor handles only one message at once. threading or eventlet executor is recommended.
```

I noticed that mistral appears to have 3 options for the backend: `threading`, `eventlet`, and `blocking` - and it appears that the default is `blocking`.  I don’t see any way to change that (at least supported via configuration), and further, I found this review (https://review.openstack.org/#/c/356343) which suggests that only `blocking` is currently supported due to deadlock concerns.

This would suggest that even with multiple st2 action runners, if the workflows are using mistral then they are single-threaded on the backend.  Is that a correct interpretation?

**Comment by rakhmerov** [comment]
@tim-ireland Hi, yes, your interpretation is partially true. "Partially" because Mistral engine processes RPC messages in single-threaded mode. Although other components, Api and executor are multi-threaded. So, for example, Mistral actions can be run in parallel.
One thing that is easy to do now is to run more engines, then they will be processing workflows in parallel and hence polling MQ more frequently. And in general, this issue has also been reported by other users a couple of times (through other channels related to OpenStack) so we'll be investigating it.

Thanks
Renat

**Comment by m4dcoder** [comment]
I'm going to close this issue. There's a workaround for now. The Mistral team has taken note and will look at this further on their side.
