### ISSUE TITLE
Dynamic general rules..

### ISSUE THREAD

**Issue by userindia77** [StackStorm/st2#3437]
Hey

We have a urgent requirement of having set of dynamic rules for all workflows which needs to be executed first. And the rules would be given input params and need to fetch some external data viz.., {ls,date} or postgresql data, apply rules and if matched intsead of triggering the action now schedule the whole rule to specified timing using cron job.

Plz, Let me know if it's already supported and how.

Ramesh

**Comment by lakshmi-kannan** [comment]
@userindia77 It seems like you still want a workflow. A workflow can have any number of tasks. So the initial few tasks could get postgresql data and do all the matching inside a python action and then let the data flow into rest of the workflow. 

Have you actually had a look at the docs? It seems all the basic pieces are documented. If you want us to tell you exactly how to build workflows for your use cases, please reach out to our sales. We do professional services. This is a open source repo and thereby we only address specific bugs, feature requests and improvements in st2 platform. I am closing this issue.
