### ISSUE TITLE
st2-apply-rbac-definitons requires --config-file option

### ISSUE THREAD

**Issue by bigmstone** [StackStorm/st2#3444]
When using RBAC from a fresh install you must provide the `--config-file` option and the location of the config file otherwise it will attempt to use default database credentials and fail to apply.

**Comment by LindsayHill** [comment]
Related to this broader issue? https://github.com/StackStorm/st2/issues/3203

**Comment by bigmstone** [comment]
Yep. Exact same problem. Closing.
