### ISSUE TITLE
st2common/st2-validate-pack-config takes a long time

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3450]
When running the CI pipeline against some of our packs i noticed that performing the example config validation takes a long time (example build: https://circleci.com/gh/EncoreTechnologies/stackstorm-activedirectory/7).

It takes much longer to perform this check than to run unit tests or even install dependencies.

Are we doing something wrong in our pack, or is there some way to speed this up?

**Comment by Kami** [comment]
I don't even see validate-pack-config step here - https://circleci.com/gh/EncoreTechnologies/stackstorm-activedirectory/7

Am I missing something (I do see other config checks, but not st2-validate-pack-config one).

As far as why it might be slow - all those various lint and config checks work on per-file basis which means some of them might take a bit longer if you have a lot of YAML files in your pack.

And on a related note, please gist and provide timing information for exactly the step which is taking long so we can have a look.

**Comment by nmaludy** [comment]
@Kami I've modified our makefile to print timestamps at the beginning and end of each target.

You can see this by clicking on the "make all" section of this build
https://circleci.com/gh/EncoreTechnologies/stackstorm-activedirectory/14

If you notice:
```
==================== example config check ====================

Start Time = 2017-06-12T23:36:09,831515901+0000
. /home/ubuntu/stackstorm-activedirectory/ci/virtualenv/bin/activate; \
	st2-check-validate-pack-example-config /tmp/packs/activedirectory || exit 1;
Running example config check on pack: activedirectory
Validating example config /tmp/packs/activedirectory/activedirectory.yaml.example for pack activedirectory...
Validating config "/tmp/packs/activedirectory/activedirectory.yaml.example" against schema in "/tmp/packs/activedirectory/config.schema.yaml"
Config "/tmp/packs/activedirectory/activedirectory.yaml.example" successfuly validated against schema in /tmp/packs/activedirectory/config.schema.yaml.
End Time = 2017-06-12T23:37:55,148592502+0000
```

Takes a total of almost 2 minutes to complete.

Looking at the `st2-check-validate-pack-example-config` i notice this line: 
```
pip install --cache-dir ${HOME}/.pip-cache -q -r ${ST2_REPO_PATH}/requirements.txt
```

Guessing that is probably taking a while if it's the first time being called?

**Comment by LindsayHill** [comment]
@nmaludy yep, the `pip install` line can take a while - there's quite a few requirements that get installed there. I know with st2docs checks that most of the total elapsed time taken for checks is with installing requirements.

**Comment by nmaludy** [comment]
@LindsayHill it looks like those requirements are installed in the dependency phase of the build into the virtualenv directory: https://github.com/StackStorm-Exchange/ci/blob/master/.circle/dependencies#L33 

However, it doesn't appear that the virtualenv directory is cached. Is the virtualenv directory supposed to be cached?

Probably only need to update/refresh cache when `requirements.txt` changes in whatever repo we're installing requirements for (in this case st2 repo).

**Comment by nmaludy** [comment]
Closing this, not an issue

**Comment by armab** [comment]
@nmaludy Caching virtualenv makes sense.

It brings ~`2mins` timing improvement, according to experiments
but has some corner cases (see https://github.com/StackStorm/st2/pull/3545/files#r125296840 comment)
