### ISSUE TITLE
st2 execution run should display result for Mistral workflows on completion

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#3476]
We should display workflow result (result from the last completed task / action) on workflow completion when using `st2 execution run` command.

We already do that for action chain workflows and, IIRC, we also already did it for Mistral workflows.

Not displaying a result means user needs to type another command (`st2 execution get <last task execution id>`) which is rather annoying.

See https://gist.github.com/Kami/5b2f9bb7dd3b98cf46e5fddcecba9387

**Comment by jaf-jaf** [comment]
I agree, it would be helpfull

**Comment by Kami** [comment]
It turns out we also didn't do it for action chain workflows - #3481.
