### ISSUE TITLE
How do we implement async way in workflow

### ISSUE THREAD

**Issue by leoxhj** [StackStorm/st2#3495]
Hi dear,

No sure if this is right place to ask support.
We're using st2 as our workflow engine, there should be a very common for the scenario to implement async way to external tools.
a specific user case for instance as described below:

1. action to create a ticket in remedy
2. workflow should hold up until remedy close/approved ticket
3. remedy inform workflow
4. workflow continue

I tried to find kind of way to implement, but seems nothing details mentioned in official docs.

must appreciated if any help can get from your side.

Leo

**Comment by LindsayHill** [comment]
Here's one design pattern:

1/ Action creates a ticket in remedy

2/ Some sort of approval/close ticket takes place in Remedy. If it is approved in Remedy, configure Remedy to send a webhook to StackStorm

3/ StackStorm then uses that webhook with a rule to kick off whatever workflow it is that you want.

So the initial action that creates a ticket does not have to be part of the same workflow that gets run later. You just have an action that creates a ticket, and another workflow/action that actually does something.

**Comment by leoxhj** [comment]
Dear LindsayHill,

Thank you very much for the prompt reply, would it possible for you to give an example code.

I attached my workflow for your reference. 
In my workflow,  there's a  task"approval" which invoke subtask(sub-workflow) "approval", and it does approval in remedy.
[pool-decommission.txt](https://github.com/StackStorm/st2/files/1087004/pool-decommission.txt)

Leo

**Comment by LindsayHill** [comment]
I can't give you example code, because it's not a specific, contained example. Your overall workflow could contain any number of steps, specific to your organization. 

But your overall workflow would look like what I described above:
1/ Your first workflow creates an ticket in remedy
2/ Approval happens in remedy, and it sends a webhook to StackStorm.
3/ StackStorm has a rule that matches that webhook, and runs your second workflow, that goes and does whatever it is that you need.

**Comment by leoxhj** [comment]
Thanks LindsayHill,

We will consider about this way, for now, we will use long time timeout in the workflow and let action take the waiting things.

Leo

**Comment by LindsayHill** [comment]
You can do that pattern if you like, although I would not want to have large numbers of long-running actions hanging around.
