### ISSUE TITLE
Install pack dependencies failed due to - Failed to install requirement "six>=1.9.0,<2.0": Collecting six<2.0,>=1.9.0

### ISSUE THREAD

**Issue by leoxhj** [StackStorm/st2#3509]
Dear support, 

I tried install a pack we built in our gitlab, and it fails at 3rd step, detail error shown as follows:
the pack dependency: six version seems already exist, not sure why it failed.

Please help!

root@a474eb9015f2:~/.pip# st2 pack install http://git.dev.sh.ctripcorp.com/st2/cms.git=dev

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[  failed   ] install pack dependencies

id: 594ca069225ea60105602466
action.ref: packs.install
parameters: 
  packs:
  - http://git.dev.sh.ctripcorp.com/st2/cms.git=dev
status: failed
error: st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Setting up virtualenv for pack "cms"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Removing virtualenv in "/opt/stackstorm/virtualenvs/cms"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv for pack "cms" in "/opt/stackstorm/virtualenvs/cms"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv in "/opt/stackstorm/virtualenvs/cms" using Python binary "/opt/stackstorm/st2/bin/python"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Running command "/opt/stackstorm/st2/bin/virtualenv -p /opt/stackstorm/st2/bin/python --always-copy /opt/stackstorm/virtualenvs/cms" to create virtualenv.
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing base requirements
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/setup_virtualenv.py", line 48, in run
    setup_pack_virtualenv(pack_name=pack_name, update=update, logger=self.logger)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py", line 86, in setup_pack_virtualenv
    install_requirement(virtualenv_path=virtualenv_path, requirement=requirement)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py", line 188, in install_requirement
    (requirement, stdout))
Exception: Failed to install requirement "six>=1.9.0,<2.0": Collecting six<2.0,>=1.9.0

traceback: None
failed_on: install pack dependencies
start_timestamp: 2017-06-23T05:00:25.783347Z
end_timestamp: 2017-06-23T05:00:43.416698Z
+--------------------------+------------------------+---------------------------+-------------------------+-------------------------------+
| id                       | status                 | task                      | action                  | start_timestamp               |
+--------------------------+------------------------+---------------------------+-------------------------+-------------------------------+
| 594ca06a225ea6008987cb97 | succeeded (1s elapsed) | download pack             | packs.download          | Fri, 23 Jun 2017 05:00:26 UTC |
| 594ca06c225ea6008987cb99 | succeeded (1s elapsed) | make a prerun             | packs.virtualenv_prerun | Fri, 23 Jun 2017 05:00:28 UTC |
| 594ca06d225ea6008987cb9b | failed (13s elapsed)   | install pack dependencies | packs.setup_virtualenv  | Fri, 23 Jun 2017 05:00:29 UTC |
+--------------------------+------------------------+---------------------------+-------------------------+-------------------------------+

root@a474eb9015f2:/opt/stackstorm/st2/bin# ./pip show six
Name: six
Version: 1.10.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /opt/stackstorm/st2/lib/python2.7/site-packages
Requires: 

BR,
Leo

**Comment by leoxhj** [comment]
I finally figured problem, since our production has no internet connection, and we use our pip source repos.

 after we add below line to pip.conf, the problem solved.:
trusted-host=repo.matrix.ctripcorp.com

root@a474eb9015f2:~/.pip# cat pip.conf
[global]
index-url = http://repo.matrix.ctripcorp.com/pypi/simple/
trusted-host=repo.matrix.ctripcorp.com

**Comment by armab** [comment]
Thanks for double-checking.
Since it's not an issue anymore, closing then.
