### ISSUE TITLE
'st2 action list' broken with unicode

### ISSUE THREAD

**Issue by leoxhj** [StackStorm/st2#3510]
Dear support,

After we installed a customized pack, it fails to run command "st2 action list":

```
root@a474eb9015f2:~/.pip# st2 action list
ERROR: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

attached packs for your reference.

**Comment by leoxhj** [comment]
[cms.zip](https://github.com/StackStorm/st2/files/1096815/cms.zip)

**Comment by leoxhj** [comment]
ok, I also figured out this issue, it's due to Chinese character in action metadata files.
so, seems version 2.2.1 is not support unicode like Chinese character?

**Comment by armab** [comment]
Confirming it's a bug on latest st2: 

```
$ st2 --version
st2 2.4dev

$ cat /etc/default/locale
# Created by cloud-init v. 0.7.9 on Mon, 19 Jun 2017 19:10:24 +0000
LANG="en_US.UTF-8"
```
