### ISSUE TITLE
is it possible to give out each entity some examples for REST API documents 

### ISSUE THREAD

**Issue by leoxhj** [StackStorm/st2#3535]
Is it possible to give out each entity some examples for REST API documents

**Comment by LindsayHill** [comment]
One of the easiest ways to find examples is to run the command in debug mode. Try running `st2 --debug <command>`, and it will display full `curl` commands. Does that help?

**Comment by leoxhj** [comment]
@LindsayHill Yes, it helps. It would be better for beginners if later we can add some typical examples.
maybe we can refer to below examples :) just my personal suggestion.
https://docs.camunda.org/manual/7.5/reference/rest/case-execution/variables/get-single-variable/

**Comment by armab** [comment]
As I understand the the proposal is to add more copy-paste examples for https://api.stackstorm.com/

**Comment by leoxhj** [comment]
Seems 
it has been talked before. https://github.com/StackStorm/st2/issues/3332

**Comment by armab** [comment]
Good find :+1: so I'm closing this.

@leoxhj Please add your notes https://github.com/StackStorm/st2/issues/3332
That example like https://docs.camunda.org/manual/7.5/reference/rest/case-execution/variables/get-single-variable/ is good to include in that issue.
