### ISSUE TITLE
StackStorm silently ignores incompatible python action results

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3540]
When working on this issue: https://github.com/StackStorm-Exchange/stackstorm-digitalocean/issues/2

I noticed that when this pack returns a custom `digitalocean.Droplet` object from its python action, that StackStorm silently ignores these results. See output example in the PR: https://github.com/StackStorm-Exchange/stackstorm-digitalocean/pull/3

Would it be a good idea to log a warning and/or error message rather than silently ignoring and discarding these results (or maybe something more)?

**Comment by Kami** [comment]
I believe this is the same as issue (partially) fixed in https://github.com/StackStorm/st2/pull/3489.

It was recently discovered by @tonybaloney.

A while ago, when we introduced support for ability for Python runner actions to return result tuple we introduced this regression.

**Comment by Kami** [comment]
So for now, as you can see in #3489 we simply return str() version of the result (same as we did in the past), but correct long term solution, imo, would be to throw in such scenarios.

**Comment by nmaludy** [comment]
Closed, duplicate of https://github.com/StackStorm/st2/pull/3489
