### ISSUE TITLE
How can we "suspend" or "wait" an action when it fails, workflow should on pause and can be resumed.

### ISSUE THREAD

**Issue by leoxhj** [StackStorm/st2#3543]
Dear support,

In our use case, we will have scenario when one of actions has failed, workflow should suspend and wait manual interaction or re-run (Is it possible to re-run current failed execution rather than to start a new one), after that, workflow can continue to execute the rest tasks/actions, is this supported by now?

I noticed below basic mentioned for mistral workflow, but there's no samples for how to use "task pause-before", "task retry...", also not sure if pause-before and others is the correct way to be used in this scenario.

...
task action input
task concurrency
task on-complete
task on-error
task on-success
task pause-before
task publish
task retry break-on
task retry continue-on
task retry count
task retry delay
task timeout
task wait-before
task wait-after
task with-items
...

another question here is does action has state like "suspend" or "wait" or "cancel", something like that, means whole workflow is waiting to be handled manually (either fix external service and then do a re-run, or maybe just cancel current action, means we just want skip it), and then resume workflow for the rest after that.

**Comment by leoxhj** [comment]
I googled related topic and find another once right suit to our scenarios:

We assume WF is in paused/errored state when 1) user manually pause the WF,
2) pause is specified on transition (on-condition(s) such as on-error), and
3) task errored.

The resume feature will support the following use cases.
1) User resumes WF from manual pause.
2) In the case of task failure, user fixed the problem manually outside of
Mistral, and user wants to re-run the failed task.
3) In the case of task failure, user fixed the problem manually outside of
Mistral, and user wants to resume from the next task.

details pls find below link:
https://openstack.nimeyo.com/39787/openstack-dev-mistral-proposal-for-the-resume-feature

**Comment by armab** [comment]
Regarding `pause`/`resume` mistral functionality, see: https://github.com/StackStorm/st2/pull/3507 which is in progress. @m4dcoder probably will add support for mistral pause/resume in stackstorm `2.4`.

**Comment by leoxhj** [comment]
@armab, it is real good news, appreciated for the efforts and look forward to getting the upgrade.

**Comment by LindsayHill** [comment]
Pause/Resume functionality was added in ST2 2.4
