### ISSUE TITLE
Feature Request: trigger event history

### ISSUE THREAD

**Issue by johnarnold** [StackStorm/st2#3548]
I'm a new user, so if there's a way to do this already, please let me know!

Would be really useful to have a dashboard, similar to the actions history, that displays all the trigger events that have been emitted by all the sensors, ideally with a way to filter by sensor, and drill down to see all the event fields.

**Comment by Mierdin** [comment]
Hey @johnarnold, welcome!

I believe what you're looking for is ``trigger-instance``. These are "instances" of triggers being fired. See the below CLI output, these are all tweets matched by my search sensor configuration. Note that I'm filtering based on the name of the trigger):

```
mierdin@stackstorm:~$ st2 trigger-instance list --trigger=twitter.stream_matched_tweet
+--------------------------+------------------------------+-------------------------------+-----------+
| id                       | trigger                      | occurrence_time               | status    |
+--------------------------+------------------------------+-------------------------------+-----------+
| 595d7a9102ebd510c6c1ce34 | twitter.stream_matched_tweet | Wed, 05 Jul 2017 23:47:29 UTC | processed |
| 595d7ab202ebd510c6c1ce44 | twitter.stream_matched_tweet | Wed, 05 Jul 2017 23:48:02 UTC | processed |
| 595d7b5e02ebd510c6c1ce8a | twitter.stream_matched_tweet | Wed, 05 Jul 2017 23:50:54 UTC | processed |
+--------------------------+------------------------------+-------------------------------+-----------+
```

In terms of "dashboard", you can't currently see any trigger instances via the WebUI.

**Comment by armab** [comment]
As @Mierdin noted, there is CLI & API for that.

If you want it as a WebUI feature, please submit a feature request in https://github.com/stackstorm/st2web dashboard instead for better tracking and higher chances to have it implemented.

Thanks!

**Comment by johnarnold** [comment]
For historical reference, yes I'm aware of the CLI, was looking for GUI dashboard.  I'll resubmit to st2web
