### ISSUE TITLE
Setting Trigger criteria for Nested payload  

### ISSUE THREAD

**Issue by divgwd** [StackStorm/st2#3555]
Hi,
I wanted to know if it's possible to apply Trigger Criteria on a nested payload such as the one shown below:
```
{"_score": 1.0, "_type": "logs", "_id": "AV0XLeccAZcNMHbbAG--", "_index": "alertsfromsocketio", "_source": {  "level": "CRITICAL", "IP_ADDRESS": "172.16.23.28", "METRIC": "Bytes_received",  "ALARM_NAME": "TPS_Usage", "VALUE": "15","time": "2017-07-06 14:46:06"}},
 {"_score": 1.0, "_type": "logs", "_id": "AV0XT8egAZcNMHbbAKg7", "_index": "alertsfromsocketio", "_source": { "level": "CRITICAL", "IP_ADDRESS": "172.16.23.28", "METRIC": "Bytes_Sent",  "ALARM_NAME": "TPS_Usage", "VALUE": "15", "time": "2017-07-06 15:21:06"}},
 {"_score": 1.0, "_type": "logs", "_id": "AV0XT8egAZcNMHbbAKg7", "_index": "alertsfromsocketio", "_source": {"level": "CRITICAL", "IP_ADDRESS": "172.16.23.28", "METRIC": "mysql_local.net.Bytes_received","ALARM_NAME": "TPS_Usage", "VALUE": "15",  "time": "2017-07-06 15:21:06"}}
```
what I mean is can I check If  1st "METRIC", 2nd "METRIC", 3rd "METRIC" has come in as a part of the same payload and then execute a rule?
And also is there a way to add additional conditions on top of the first mentioned conditions  ie alone with the METRIC condition I want to trigger an action if they all have the same ALARM_NAME?

**Comment by Kami** [comment]
Right now you can't do that as part of the rule criteria comparison, but there are some workarounds available to handle such scenarios.

If those triggers come into the system via sensor, you could do those checks inside a sensor and if all those things match, you would dispatch this aggregate trigger from the sensor.

If those triggers come into the system via webhook, you could handle that by writing a custom sensor which exposes an HTTP endpoint to which webhooks are sent and then you do those checks inside the sensor and dispatch an trigger when all this criteria is met (we also used this approach ourselves many times already).
