### ISSUE TITLE
regarding st2 API /api/v1/executions parameters

### ISSUE THREAD

**Issue by leoxhj** [StackStorm/st2#3563]
Dear support,

for below API:
GET /api/v1/executions 

how can we filter out all executions which are workflows?

There's a parameter "runner" mentioned in query parameters, but no idea how to use it since the response data structure for "runner" is like below, it's not like simple a string but a json.

    "runner": {
      "runner_module": "python_runner",
      "uid": "runner_type:python-script",
      "enabled": true,
      "name": "python-script",
      "runner_parameters": {
        "timeout": {
          "default": 600,
          "type": "integer",
          "description": "Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."
        },

I have tried like below, but all fails.
https://10.2.111.65/api/v1/executions?runner=mistral_v2
https://10.2.111.65/api/v1/executions?runner.runner_module=mistral_v2
https://10.2.111.65/api/v1/executions?runner_module=mistral_v2

also, I noticed for POST method, there's a parameter "action_is_workflow" which can identify whether  it's action or workflow, but pity this parameter doesn't present in GET method.

**Comment by leoxhj** [comment]
figured out, I misspelled runner "mistral_v2", the correct one should be "mistral-v2", but weird since most place it uses "mistral_v2" 
https://10.2.111.65/api/v1/executions?runner=mistral-v2

**Comment by LindsayHill** [comment]
Looks like that filtering is based on the runner name, which is set to `mistral-v2` here https://github.com/StackStorm/st2/blob/master/contrib/runners/mistral_v2/runner.yaml#L4

I suspect there might have been a change at some point to move from `-` to `_`, but the `mistral-v2` name was retained for backwards compatibility.
