### ISSUE TITLE
Bug: regression on icon.png loading

### ISSUE THREAD

**Issue by johnarnold** [StackStorm/st2#3567]
icon.png for a pack will not load if the name and ref are different in the pack.yaml

https://github.com/StackStorm/st2/issues/3128
https://github.com/StackStorm/st2/pull/3131

I just confirmed this in back-to-back testing.

**Comment by lakshmi-kannan** [comment]
@johnarnold Can you post the pack.yml you used in testing? I am trying to repro as well.

**Comment by lakshmi-kannan** [comment]
I can confirm that when pack name and ref are different in pack.yml, icon doesn't render. I chased it down to UI not even making calls to get the icon for the pack whose name is different from ref. I'll chase this down but it seems like a st2web problem.

**Comment by lakshmi-kannan** [comment]
https://github.com/StackStorm/st2web/blob/master/apps/st2-actions/actions.controller.js#L81
Looks like the URL we build is based on "name" and not "ref". I'll talk to @enykeev and @bigmstone who are our UI folks and figure out why we use "name" as opposed to "ref". Stay tuned.

**Comment by lakshmi-kannan** [comment]
Fix in https://github.com/StackStorm/st2web/pull/388
