### ISSUE TITLE
regarding st2 api response data

### ISSUE THREAD

**Issue by leoxhj** [StackStorm/st2#3569]
Dear support, 

current ST2 rest api response data has too much information, most of them is useless for user, also too much information affect system performance, propose use can specify return fields.

**Comment by armab** [comment]
Are you referring to any particular REST endpoints?
We need more real-life examples.

**Comment by leoxhj** [comment]
for example GET api/v1/executions, we might only need field status, response has bulk of information which we don't need them, the main reason is if lot of executions get retrieved, it is very slow.

**Comment by armab** [comment]
From what I see `/api/v1/executions` https://api.stackstorm.com/api/v1/executions/#/action_executions_controller.get_all has a lot of advanced filtering:
- `exclude_attributes` - List of attributes to exclude
- `status` - Execution status filter
- and so on

[![](https://i.imgur.com/yVW6CoE.png)](https://api.stackstorm.com/api/v1/executions/#/action_executions_controller.get_all)
Isn't `exclude_attributes` what you need?

If not enough, - In terms of proposal, please provide exact interface/additional filter(s), including naming, example `curl` request and described behavior you'd like to see in future.
That will give more chances to get a proposal codified as a feature.

**Comment by leoxhj** [comment]
@armab my apologies, I didn't go through all parameters carefully, yes, the exculde_attributes should help.
Thanks.

**Comment by bigmstone** [comment]
Going to close this issue for now. @leoxhj feel free to open back up if you have additional issues/questions on this topic.

**Comment by leoxhj** [comment]
Can we add an attribute: include_attributes, so if I only need status field , I can just add it instead of exclude_attributes which I need exclude all rest except status?
