### ISSUE TITLE
st2 pack install should show how many actions, rules and sensors are being installed

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3586]
This came from AWS pack discussion where AWS pack has 2000+ actions. st2 pack install aws is so slow and as a user I begin to think that there is something wrong. This happened to me personally multiple times. So if we just show the number of artifacts being registered, we mentally setup the user to expect a delay. 

Apparently, pack index already has this info. Let's show it in CLI then!

**Comment by armab** [comment]
https://github.com/StackStorm-Exchange/index/blob/87d6ac55709695cb62886760ceeba304c15671b1/v1/index.json#L138 :smiling_imp:

**Comment by warrenvw** [comment]
I guess it's just coincidence that this is issue 3586, and there are 3581 AWS actions. Just off by 5. :)
