### ISSUE TITLE
Upgrade requests and certifi to the latest version

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#3603]
Right now we can't upgrade `requests` and `certifi` to the latest version because one of the recent versions of `certifi` break requests to SSL endpoints on RHEL 6 and RHEL 7 - they fail with cert validation error.

```bash
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)
```

The reason for that is that a recent version of `certifi` removed 1024 bit root certificates (https://pypi.python.org/pypi/certifi) and those RHEL distros run older version of OpenSSL so validation fails (https://github.com/certifi/python-certifi/issues/32).

It works in existing versions of StackStorm because no certifi is installed by default as it's not yet a `requests` dependency and as such, old and obsolete system CA bundle is used.

The same issue would happen if user installed / upgraded `certifi` manually (which is a good practice anyway). This also means the whole thing is a ticking time bomb.

That's obviously problematic. It should be in the best user interest (for safety reasons of course) to always run latest version of `certifi` and OpenSSL.

There are a couple of possible solutions to that:

* Update installer scripts and docs to install latest version of OpenSSL (>= 1.0.2) on RHEL.
* Update our code to add `certifi.old_where()` to requests SSL CA cert search path. This location still contains old 1024 bit root certificates.

The second proposed solution is really a work-around and not something I would suggest for production - it should always be in the best interest of user to run latest version of OpenSSL and use latest up to date CA cert bundle.

It's also a bit problematic because requests is used in many different places and it's hard to ensure environment is set up correctly everywhere (also packs).

The "problem" with first approach is that users might encounter issues in case they try to manually install StackStorm on RHEL and they don't follow / see docs and don't update OpenSSL.

Comments? Other suggested approaches?

**Comment by armab** [comment]
Just for reference:
- Big RedHat thread about `OpenSSL 1.0.2`: https://bugzilla.redhat.com/show_bug.cgi?id=1276310
- Bigger thread in `python-certifi` about the issue: https://github.com/certifi/python-certifi/issues/26

I'm :+1: for https://github.com/StackStorm/st2/pull/3604 revert for now as last worked solution.

Talking about the instructions for installing newer `OpenSSL`, - it's probably not realistic for now before `RHEL` officially adds a corresponding package. We don't have `openssl-1.0.2` package in any RPM repo yet, building the package ourselves or asking users to install OpenSSL from sources is not an option too.

I'm afraid we're most probably stuck in limbo for a long time here, waiting for a proper solution from the upstreams.

**Comment by armab** [comment]
Not an issue anymore, this seems to be fixed in upstream.
