### ISSUE TITLE
connecting to mongo with ssl enabled doesn't seem to work

### ISSUE THREAD

**Issue by lolovarga** [StackStorm/st2#3613]
I have a mongodb PAAS instance that I want to use for stackstorm. I want to connect over ssl, but connection is not successful. I validated that the connection string is correct and that the db is available, I can connect using the mongo cli client.
This is the relevant st2.conf section:
```
[database]
host = stackstormmdb.xxx.com
port = 10255
username = stackstormmdb
password = this_is_not_the_real_password
ssl = True
```
Error:
```
2017-07-26 14:44:16,708 139698506724048 INFO __init__ [-] Connecting to database "st2" @ "stackstormmdb.xxx.com:10255" as user "stackstormmdb".
2017-07-26 14:44:37,667 140595344765648 INFO __init__ [-] Connecting to database "st2" @ "stackstormmdb.xxx.com:10255" as user "stackstormmdb".
2017-07-26 14:44:58,929 140527869940432 INFO __init__ [-] Connecting to database "st2" @ "stackstormmdb.xxx.com:10255" as user "stackstormmdb".
````

Connecting using the mongo cli client:
```
root@o2-gog-st2-0:/var/log/st2#  mongo  stackstormmdb.xxx.com:10255/st2 --ssl -u stackstormmdb -p
MongoDB shell version: 2.6.10
Enter password:
connecting to: stackstormmdb.xxx.com:10255/st2
globaldb:PRIMARY>
```

**Comment by LindsayHill** [comment]
@lolovarga Which MongoDB *aaS is this one? Is it a proper MongoDB, or is it Azure Cosmos?

If it's Azure Cosmos, I've heard of other issues related to using that with StackStorm. They don't yet implement a full MongoDB API, and so some StackStorm things will fail.

**Comment by lolovarga** [comment]
I am using azure indeed. I understand that some thing might not work, that's what I want to identify, so that we can ask those features to be added. 
Nevertheless, I don't expect the connection itself to be falling, add long add the mongo cli  client connects.

**Comment by LindsayHill** [comment]
It might have been helpful to mention the use of Cosmos earlier, since it does not have a full MongoDB implementation.

I'm not sure that the connection is failing due to initial connection problems. If it failed due to being unable to connect, you would normally see an ERROR message after the "Connecting to database..." entry. It does not log a "Connected to database" message.

Were you also seeing other error messages, e.g. 
```
OperationFailure: Document collection cannot be replaced while a previous document collection update operation is ongoing.
```

If you are using SSL, you may need to specify some additional ssl-related properties in the `[database]` section in `st2.conf`. Using `ssl=true` may not be enough. See https://docs.stackstorm.com/install/config/config.html#configure-mongodb

**Comment by lolovarga** [comment]
Sorry I didn't mention it from the start. You are correct, I do see that message about the operation failure. Do you happen to know what the error refers to? It would help if we could drill down to the operations that are missing.

**Comment by LindsayHill** [comment]
You could try putting services into [debug mode](https://docs.stackstorm.com/troubleshooting/debug_mode.html) to see more about the operations being attempted. You could also go through the [code](https://github.com/StackStorm/st2). 

Last time I looked, Cosmos didn't have any docs about what they did & didn't support. Makes it a long & painful exercise to go through ST2 code and audit every MongoDB operation, then test it against Cosmos to see what happens. Does Cosmos now have a reference list of unsupported MongoDB operations? If you could get that, it might be faster to match that against the operations in the ST2 code.

**Comment by johnarnold** [comment]
@LindsayHill for posterity, https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-feature-support#mongodb-protocol-support

I may be testing cosmosdb soon as well.

**Comment by LindsayHill** [comment]
Ah, that is good to see. ST2 should be fine with both 3.2 and 3.4, although 3.4 is the primary version we test against. We're in the process of adding 3.6 support (has some other implications related to mongoengine). At some point in future we'll drop 3.2 support, but by that stage Cosmos should have 3.4 GA support.

**Comment by kgrvamsi** [comment]
So Stackstorm supports Csomosdb as backend for Mongodb......do we have any tests that confirms its working?

**Comment by nzlosh** [comment]
No Cosmos is not supported.  MongoDB is the only database tested with StackStorm.  The fact it was compatible with MongoDB in 2018 was fortunate for those that used it.  If you want to use it today, you'll need to test it for yourself.
