### ISSUE TITLE
st2.notifiers.work queue is growing. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3622]
Reported by: @emptywee

From slack:
```
it was st2.notifiers.work queue


[5:18] 
with over 747k messages


[5:18] 
purged it


[5:21] 
I see no consumers for that queue


[5:21] 
can anyone here point me in the right direction with this? :slightly_smiling_face:
```

**Comment by lakshmi-kannan** [comment]
I think this is happening after we switched notifier to scan execution queue as opposed to liveactions queue. There is no consumer for liveactions queue.

**Comment by lakshmi-kannan** [comment]
Notifiers now consume "ActionExecution" RabbitMQ exchange with queue name "st2.notifiers.execution.work". Notifier used to scan "LiveAction" exchange with
"st2.notifiers.work" queue name. When you upgrade from older versions, make sure
"st2.notifiers.work" queue size is 0. If you upgrade when it's non-empty, you might
 miss notifications. Post upgrade, please delete queue "st2.notifiers.work" queue manually
 using ``rabbitmqadmin purge queue name=st2.notifiers.work``. If not, this queue will
 grow indefinitely and rabbitmq would eat up a lot of disk space.

**Comment by lakshmi-kannan** [comment]
Added info in Upgrade Notes https://github.com/StackStorm/st2/issues/3622

**Comment by armab** [comment]
"As seen on all production servers."

expecting to see that issue in our fleet as well
