### ISSUE TITLE
Sensor container creates way too many rabbitmq queues

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3628]
Reported by: @emptywee on slack

From slack:
```
I have so many queues like `st2.sensor.watch.sensor_container-0ddd32c70e`


[6:58] 
the last part is changing


[6:58] 
maybe over 600 of them


[6:58] 
is it normal?


[6:59] 
most of them are idling, but one


[6:59] 
they have no consumers as well, and they are bound to st2.sensor
```

**Comment by Kami** [comment]
If the queues contain random names they should be deleted after the sensor wrapper process exists.

We do need to investigate though, maybe it makes more sense to make those queues persistent across restarts so sensor wrapper can continue where it left off on restart. But at least now it seems, with the random name that the queue should not be permanent and should only be there for the duration of the sensor wrapper process life time (aka while connection is established to RabbitMQ).

**Comment by lakshmi-kannan** [comment]
Validate if there are unacknowledged messages for queues with name st2.sensor.watch.sensor_container-${UUID}. If there are unacknowledged messages, then wait until it goes down to zero. 

```
rabbitmqadmin list queues vhost name node messages messages_unacknowledged
```

Now stop st2 and delete the sensor_watch queues
 
```
st2ctl stop
```

Delete sensor_watch queues. 

```
for q in `rabbitmqadmin -f long -d 3 list queues | grep name | grep sensor | awk '{print $2}'`;do rabbitmqadmin delete queue name=$q;done
```

**Comment by emptywee** [comment]
Thank you @lakshmi-kannan  :) Deleting it, right now...
