### ISSUE TITLE
Bug: Retrying "register exchanges" causes TypeError exception, using Redis as message queue

### ISSUE THREAD

**Issue by johnarnold** [StackStorm/st2#3635]
OS: Ubuntu 16.04
st2 version:  2.3.2

Problem description:
Testing redis as alternative message queue. Registering exchanges in kombu connection throws a TypeError.  There's a code problem here that I don't think is related to transport protocol.

```
2017-08-01 02:07:26,696 139712428401040 DEBUG bootstrap_utils [-] Registering exchanges...
2017-08-01 02:07:26,705 139712428401040 ERROR st2notifier [-] (PID=17199) Results tracker quit due to exception.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/st2notifier.py", line 56, in main
    _setup()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/st2notifier.py", line 27, in _setup
    register_signal_handlers=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 117, in setup
    register_exchanges_with_retry()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/transport/bootstrap_utils.py", line 83, in register_exchanges_with_retry
    return retrying_obj.call(register_exchanges)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 205, in call
    if not self.should_reject(attempt):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 189, in should_reject
    reject |= self._retry_on_exception(attempt.value[1])
TypeError: unsupported operand type(s) for |=: 'bool' and 'error'
```

Ref:
https://github.com/StackStorm/st2/issues/3601

**Comment by lakshmi-kannan** [comment]
@johnarnold Thanks for the issue but if the service you use is not an officially supported one, we'll not prioritize it over other issues. Also, the bug you are pointing to is in a third party library. If you can help them out with a fix, that'd be great. Since this is not a direct st2 issue, I am going to go ahead and close the issue. Supporting redis for message queue is not supported and not something we'll support in the near future.

**Comment by johnarnold** [comment]
@lakshmi-kannan 

I'm pointing to an issue with register_exchanges in bootstrap_utils.py returning an 'error' instead of a bool -- I don't believe that's proper behavior for the callback.

I believe that could happen regardless of transport.  Also doesn't appear to be an issue with retrying.  Do you want to reactivate the issue?

Also, I'm a bit surprised that you would close an issue out of hand.  Does this project not want community contribution of enhancements?

**Comment by Kami** [comment]
@johnarnold We didn't want to come out this way - we definitely appreciate and value user contributions.

The problem lakshmi wanted to point out is that we don't officially support Redis as a message bus transport. Even if we managed to fix those couple of issues, who knows how many more issues are hiding underneath.

There are countless of software alternatives (detabases, web servers, etc.) we could officially support, but we simply don't have resources to do it and it's better to focus and officially support one small set which we can test, etc. and we know works well.

Having said that, if you manage to get it to work, we would happily merge the fixes as long as they don't interfere with other code.

**Comment by Kami** [comment]
@johnarnold #3638 should fix the actual retrying issue - thanks for reporting this and a good catch.

I also tried to see what's the deal with Redis transport and it already breaks very early one - for some reason even`exchange_declare` doesn't work (exchange / key is not created in Redis) which is a very basic functionality so the whole issue of supporting Redis is probably a very deep rabbit hole.

**Comment by Kami** [comment]
So the actual "exchange not exist issue" I mentioned above is related to queue not being declared yet aka not all workers being online yet.

This seems to expose different behavior between RabbitMQ and Redis transports - with RabbitMQ it works just fine if not all the workers are online yet and queues declared, but with Redis transport it seems like queues need to be declared up front for it to work.

**Comment by Kami** [comment]
I actually managed to get it to work by pre-declaring all the queue on service setup.

Will open a PR with that change shortly. The feature itself will be behind a feature flag and out official recommendation still is to use RabbitMQ because who knows how many issues are still hiding underneath when using Redis backend.

**Comment by Kami** [comment]
Please see #3639 for a fix and details.

Please also see a big note about redis not being officially supported backend :)

**Comment by lakshmi-kannan** [comment]
@johnarnold Sorry for closing the issue a little prematurely. I misunderstood the issue. There were two separate issues. One is the bug in register_exchanges in bootstrap_utils.py as you pointed out and other is supporting redis. The title of the issue kinda misled me to believe this is about supporting redis and I closes the issue for which I apologize. 

Though @Kami looked into a potential unblocker for Redis, we don't intend to support it officially. I think we've made that clear ample number of times in this issue. If this is something you want to look into and support, we'll welcome contributions as long as it doesn't make the code base hard for us to manage down the road. 

Do you still want me to reopen this issue?

**Comment by johnarnold** [comment]
@Kami @lakshmi-kannan  Thanks to both of you for not burying this.  

I don't want to be a weird corner case either.  I would point out:
- Redis is super popular, including support from practically every cloud provider.
- Redis is the most common broker for Kombu (via celery)

We already use redis extensively internally, so it would be great to make it work.  I've used RabbitMQ previously with elasticsearch and other things, but prefer using PaaS services wherever possible.  I hope that Kombu's abstraction will allow some flexibility here, since many potential Stackstorm customers will already have a broker in their infrastructure.

**Comment by Kami** [comment]
Let us know how it goes with the latest release (v2.4.0) which includes those changes.

I've been using Redis as a message bus for local development for almost a month now and I haven't encountered any issues yet.
