### ISSUE TITLE
Mistral subworkflow completion delay while under load

### ISSUE THREAD

**Issue by JohnWelborn** [StackStorm/st2#3655]
In production, and now in testing I'm able to reproduce a delay between when a subworkflow completes its last task and when the subworkflow is finished. In production I also see this between the last subworkflow and when the job is marked as succeeded.

Here is what I'm using to reproduce the delay along with an action to summarize the amount:

https://gist.github.com/JohnWelborn/0aa58bedffaa78c7e79ae707131d1dd2

st2 2.3.2

```
[resultstracker]
query_interval = 5
thread_pool_size = 10
```

**Comment by JohnWelborn** [comment]
@bigmstone ^ as discussed in chat

**Comment by emptywee** [comment]
I second that, but in my case results to the parent workflow come a little bit faster. Though my load could be lower.

**Comment by JohnWelborn** [comment]
this looks useful:
```
[mistral]
jitter_interval = 0
```

**Comment by JohnWelborn** [comment]
All my problems have gone away after running 8 each of st2api/mistral-server/mistral-api and the following config:

```
[mistral]
jitter_interval = 0

[resultstracker]
query_interval = 2
thread_pool_size = 20

```

**Comment by emptywee** [comment]
@JohnWelborn 8 what? Didn't really get it.

**Comment by LindsayHill** [comment]
Mistral callbacks should have resolved this.
