### ISSUE TITLE
st2ctl clean fails to delete mongo db when on a separate server

### ISSUE THREAD

**Issue by skjbulcher** [StackStorm/st2#3659]
Originial bug report [here ](https://github.com/StackStorm/st2-docker/issues/32)(example is taken from a docker network).

When running st2ctl clean, command fails with `mong: command not found`. After installing mongo (`apt-get install -y mongodb-clients`, the error changes to:

```
Dropping st2 Database...
MongoDB shell version: 2.4.9
connecting to: st2
Tue Aug  8 18:28:04.691 Error: couldn't connect to server 127.0.0.1:27017 at src/mongo/shell/mongo.js:145
exception: connect failed
```

`st2ctl clean` appears to require a mongo client, and fails to obtain the db connection information from st2.conf

**Comment by armab** [comment]
Fixed in https://github.com/StackStorm/st2/pull/3669.
Thanks to @nmaludy `st2cl clean` now relies on python script that's using mongo creds from `st2.conf`.
