### ISSUE TITLE
Sensors in "Examples" pack should do something meaningful

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3663]
The sensors in examples pack all have pass implementations. Create an active and a passive sensor that does some real work.

**Comment by lakshmi-kannan** [comment]
As part of PR https://github.com/StackStorm/st2/pull/3658, I added a sample working polling sensor https://github.com/StackStorm/st2/pull/3658/commits/7749edd8b8d419fd9f01abe22957e5ca5af623c9

**Comment by lakshmi-kannan** [comment]
A passive sensor still needs to be written. Write a simple flask app and just relay the incoming payload to the trigger could be an example.

echo_flask_sensor.py

**Comment by armab** [comment]
Passive sensor implemented in https://github.com/StackStorm/st2/pull/3667 by @warrenvw.

@lakshmi-kannan @warrenvw Can we close this now is resolved?

**Comment by lingfish** [comment]
Hi @warrenvw and @armab - in order to use this, is the recommendation to then adjust nginx appropriately to point to it?
