### ISSUE TITLE
Never finishing mistral tasks and multiple triggered chatops.post_result tasks if I cancel them

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#3680]
@m4dcoder asked me to file an issue after looking into all this with me on Slack.

Under some circumstances parent workflows are kept in the running state despite successful execution reported from mistral, thus preventing st2 result tracker from querying completion of the whole task.

The longer such tasks are kept in the running state without cancelling them, then the more chatops notify events are generated for some reason. In order to stop it I have to:

1. empty db.live_action_d_b and db.trigger_instance_d_b collections from mongodb
2. purge the st2.trigger_instances_dispatch.rules_engine queue in rabbit

**Comment by m4dcoder** [comment]
Proposed fix at https://github.com/StackStorm/st2/pull/3684. @emptywee, please feel free to cherry pick this and test on your end.

**Comment by emptywee** [comment]
@m4dcoder thanks much! I updated the files you have committed, but also had to update https://github.com/StackStorm/st2/blob/1b4105e9407ff191c9ea90506fbe1f8309edba71/st2common/st2common/constants/action.py with the missing constants.

After that it worked well and results got tracked properly. I will let it run this way for a couple of days or until I run into any issue and update this issue with the outcome.

Thanks again!
