### ISSUE TITLE
Feature Proposal: Webhooks (location-id)

### ISSUE THREAD

**Issue by diellenne** [StackStorm/st2#3690]
We heavily use web-hooks in our integration and would like to have an ID returned that allows us to trace from the point of the web-hook being received instead of a HTTP 2xx code like we currently get.
 
Currently the returned values look something like below. It would be great to have a header returned with a usable ID.
 
```
Access-Control-Allow-Headers →Content-Type,Authorization,X-Auth-Token,St2-Api-Key,X-Request-ID
Access-Control-Allow-Methods →GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Origin →null
Access-Control-Expose-Headers →Content-Type,X-Limit,X-Total-Count,X-Request-ID
Connection →keep-alive
Content-Length →73
Content-Type →application/json
Date →Fri, 30 Jun 2017 10:52:01 GMT
Server →nginx/1.12.0
X-Request-ID →af949d41-95f1-4383-aeeb-89576c451461
```
Look forward to the response. We believe this will be of value to the wider community.

**Comment by Kami** [comment]
I believe you should be able to achieve the same end result using Traces - https://docs.stackstorm.com/reference/traces.html

You can specify `St2-Trace-Tag` header when submitting a webhook and then you can trace this event through the system using the traces functionality.

**Comment by LindsayHill** [comment]
The other thing you can do today is directly call the executions API, if you know you always want to trigger one specific action in response to a web hook. So rather than use webhook ->rule -> action, you just call the action directly, and you'll get an execution ID that you can trace.

**Comment by LindsayHill** [comment]
Closing since `St2-Trace-Tag` and/or direct call to executions ID offers this capability.
