### ISSUE TITLE
examples.remote-fib

### ISSUE THREAD

**Issue by warrenvw** [StackStorm/st2#3694]
I executed the `examples.remote-fib` action using the UI, and noticed the following error:

`ImportError: No module named six.moves`

I don't think this is "user error" on my part.. so creating this issue to track.

![screen shot 2017-08-21 at 5 26 31 pm](https://user-images.githubusercontent.com/9972858/29543674-a32018cc-8697-11e7-856f-b3b2895277ad.png)

![screen shot 2017-08-21 at 5 26 20 pm](https://user-images.githubusercontent.com/9972858/29543672-a056f0f2-8697-11e7-9571-ce95c9b1cda1.png)

**Comment by LindsayHill** [comment]
Just tested with st2vagrant, version 2.8.1, seems to work with no problems.
