### ISSUE TITLE
Add '--last -1' to list all results from CLI

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#3735]
> Related to https://github.com/StackStorm/st2/issues/3736

Following the https://github.com/StackStorm/st2/issues/3708#issuecomment-328666287 consensus, there should be a way to to get all the results for any command in CLI via `--last -1`.

----

For reference, Mistral uses similar `--limit -1`
```
optional arguments:
  -h, --help            show this help message and exit
  --filter FILTERS      Filters. Can be repeated.
  --limit [LIMIT]       Maximum number of tasks to return in a single result.
                        limit is set to 100 by default. Use --limit -1 to
                        fetch the full result set.
```

Another example, `docker ps` CLI by default returns all possible results (via `--last -1`):

Name | default | Description
-- | -- | --
--last, -n | -1 | Show n last created containers (includes all states)

https://docs.docker.com/engine/reference/commandline/ps/#usage

**Comment by nmaludy** [comment]
+1
