### ISSUE TITLE
Restart chatops at pack install

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2#3739]
I always forget to remember restarting st2_chatops service after a pack (re-)install with new aliases.

It would be great if "st2 pack install" took care of doing it itself.

**Comment by Kami** [comment]
Restart shouldn't be needed.

StackStorm hubot adapter periodically reloads available commands from st2api (by default that is every 120 seconds - https://github.com/StackStorm/hubot-stackstorm#plugin-environment-variable-options), so new aliases which are available when you install the pack should eventually be available without the restart.

Having said that - I do think that needs to be documented (if not already) and we should eventually look into making this more real-time - we should be able to utilize stream API endpoint for that.

**Comment by vincent-legoll** [comment]
OK, I wasn't aware of that, and I jumped the gun after pack install so probably hadn't waited enough.

What about just triggering the refresh at the end of package install to get from worst case 120s refresh to almost instant ?

**Comment by Kami** [comment]
@vignesh-terafast Yeah, that would also be another option, but would still require us to utilize the event stream API endpoint.

In any case, thanks for bringing this up and let's continue the discussion in #3740.
