### ISSUE TITLE
Web UI 2.4 input validation error for non-required inputs

### ISSUE THREAD

**Issue by DavidJohnGee** [StackStorm/st2#3741]
There is an issue with the Web UI on 2.4.

In rules or actions, If I input a value in a non-required form field then remove the value, I receive a validation error.

![image](https://user-images.githubusercontent.com/4283339/30378926-bd4db234-988c-11e7-89b5-b78b09281fc0.png)

![image](https://user-images.githubusercontent.com/4283339/30378943-ccd63bf4-988c-11e7-87dd-7dd3661e7613.png)

**Comment by LindsayHill** [comment]
Track at https://github.com/StackStorm/st2web/issues/424
