### ISSUE TITLE
Web UI rule criteria input trigger parameter drop-down issue (2.4)

### ISSUE THREAD

**Issue by DavidJohnGee** [StackStorm/st2#3745]
When using the web-ui to create a rule, the list of triggers are displayed in a drop-down list, however the trigger parameters are not in drop down list in the criteria section. If you edit the rule after saving, the trigger parameters appear in drop down lists. It appears it works when editing a previously created rule, but not from scratch.

To replicate:
i) Create a rule
ii) Select a trigger like: core.st2.generic.notify which has plenty of parameters
iii) Try adding criteria. You'll note distinct lack of trigger parameters appearing in a drop-down list
iv) Save the rule after completing required parameters like action, pack and name
v) Click edit on the rule
vi) The rule's criteria and the trigger parameters now appear when selecting the input field and triggering the javascript

Thanks,
D

**Comment by LindsayHill** [comment]
Track at https://github.com/StackStorm/st2web/issues/423
