### ISSUE TITLE
st2 reload is not removing actions which are not exist in disk

### ISSUE THREAD

**Issue by sibirajal** [StackStorm/st2#3749]
Hello Team, 

It appears that when I remove the action yaml file from disk and performing "st2ctl reload" is not removing the deleted action reference from action list. 

They are still available in the DB reference. Can you please confirm whether this is an expected? It would be good if we can delete action reference when the yaml file doesn't exist in the disk as part of st2ctl reload.

**Comment by LindsayHill** [comment]
Yes, that is the expected behavior. 

See this request for a `--purge` flag https://github.com/StackStorm/st2/issues/3313

**Comment by LindsayHill** [comment]
Will close this, leaving #3313 open as request for purge flag.
