### ISSUE TITLE
'st2 execution tail --help' doesn't work

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#3751]
When running `st2 execution tail --help` it works as `st2 execution tail`, giving output for the latest execution (I guess).

It should print the help/usage instead.

**Comment by Kami** [comment]
Good catch :+1:

**Comment by Kami** [comment]
@armab It looks like we don't actually have `--help` flag for a lot of commands. For example - https://github.com/StackStorm/st2/pull/3750/commits/a27e26fad9c1e525fef0aaf98b8c220a48a1b9ae#r139398958

**Comment by Kami** [comment]
c56fde2a55fa0851c59427d3cbc5c3922bedcc52 fixes it.
