### ISSUE TITLE
RabbitMQ Cluster_Urls does not work

### ISSUE THREAD

**Issue by elliot-smith** [StackStorm/st2#3764]
Hi,

My environment configuration is below and all of the instances (rabbitmq and Stackstorm) where just built.
		
OS: 3.10.0-693.2.2.el7.x86_64 (RHEL7)
RabbitMQ version: 3.6.10
ST2 version:  2.4.0
Erlang version 19.1.0
Python Version: Python 2.7.5

If I use stackstorm (2.4.0) with an external rabbitmq cluster and connect the fresh ST2 build that was just built using cluster_urls the st2 stack fails.

My st2.conf configuration file for rabbitmq is the following:
```ini
[messaging]
cluster_urls = <amqp://username:password@RABBIT_MQ_ADDRESS_1:5672/>,
               <amqp://username:password@RABBIT_MQ_ADDRESS_2:5672/>
```
			   
The logs for when I try and load stackstorm are under [rabbitmq_cluster_start_error.txt](https://github.com/StackStorm/st2/files/1331517/rabbitmq_cluster_start_error.txt)

However, if I change the configuration on the same instance to the snippet it functions perfectly (please see [rabbitmq_single_node.txt](https://github.com/StackStorm/st2/files/1331516/rabbitmq_single_node.txt)).
```ini
[messaging]
url = amqp://username:password@RABBIT_MQ_ADDRESS_1:5672/
			   
```

All of the logs repeat the following error section and send the CPU usage up to 100% when using the cluster (due to error retries I believe) whereas it sits at under 25% when I use "url"
```
Registering content...[flags = --config-file /etc/st2/st2.conf --register-all]
2017-09-26 01:54:04,523 INFO [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
Traceback (most recent call last):
  File "/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 387, in main
    setup(argv)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 379, in setup
    register_internal_trigger_types=True)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/script_setup.py", line 95, in setup
    register_exchanges_with_retry()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/transport/bootstrap_utils.py", line 151, in register_exchanges_with_retry
    return retrying_obj.call(register_exchanges)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/transport/bootstrap_utils.py", line 124, in register_exchanges
    with Connection(connection_urls) as conn:
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/kombu/connection.py", line 179, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/kombu/transport/__init__.py", line 81, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/kombu/transport/__init__.py", line 62, in resolve_transport
    raise KeyError('No such transport: {0}'.format(transport))
KeyError: u'No such transport: '
```
Do you have any ideas as to how we can fix this error?

**Comment by LindsayHill** [comment]
Just to confirm, does your `[messaging]` section look like this:
```ini
[messaging]
cluster_urls = <amqp://username:password@RABBIT_MQ_ADDRESS_1:5672/>,
               <amqp://username:password@RABBIT_MQ_ADDRESS_2:5672/>
```
Or like this:
```ini
[messaging]
cluster_urls = amqp://username:password@RABBIT_MQ_ADDRESS_1:5672/, amqp://username:password@RABBIT_MQ_ADDRESS_2:5672/
```

Can you provide an example of your config that is less obfuscated? e.g. change server1.mydomain.com to server1.example.com.

**Comment by elliot-smith** [comment]
Hi @LindsayHill,

My configuration is

`
[messaging]
cluster_urls = <amqp://username:password@RABBIT_MQ_ADDRESS_1:5672/>,
               <amqp://username:password@RABBIT_MQ_ADDRESS_2:5672/>
`

or in the less obfuscated manner
`
cluster_urls = <amqp://username:password@server1.example.com:5672/>,
               <amqp://username:password@server2.example.com:5672/>
`
as per the documentation here: https://docs.stackstorm.com/install/config/config.html?highlight=cluster_urls#configure-rabbitmq

**Comment by LindsayHill** [comment]
Try configuring your `[messaging]` section like this:

```ini
[messaging]
cluster_urls = amqp://username:password@server1.example.com:5672/,
               amqp://username:password@server2.example.com:5672/
```

i.e. don't use `<` or `>`. I think the intention of those is to show that it is a variable section that needs editing.

I have tested this with my local setup, which does not have a RabbitMQ cluster, but you can use `cluster_urls` to point to a single instance. That works. I also tried adding an additional config pointing to a dummy instance, and that worked OK (obviously it couldn't connect to the dummy instance, but could connect to the real node). 

You can see in the docs the single node example:
```ini
[messaging]
url = <amqp://#RMQ_USER:#RMQ_PASSWD@#RMQ_HOST:#RMQ_PORT/#RMQ_VHOST>
```

That includes the `<>` marks, but those are not used in the default configuration. So they are just meant to be highlighting a variable section, not meant to be included in the actual configuration.

**Comment by elliot-smith** [comment]
Thanks @LindsayHill, apologies for the misinterpreting documentation.

I just did a quick test on the cluster and it seems like it requires the "home node" to always be running. Whenever I shut down the first node in the list (i.e. server1.example.com) stackstorm fails to launch despite the second node (i.e. server2.example.com) running.

```ini
[messaging]
cluster_urls = amqp://username:password@server1.example.com:5672/,
                      amqp://username:password@server2.example.com:5672/
```

The stackstorm cmd line output is attached here 
[shutdown-server1.txt](https://github.com/StackStorm/st2/files/1335945/shutdown-server1.txt)
The st2actionrunner.log is attached here (these logs repeat indefinitely changing the CPU usage to 100%)
[st2actionrunner.log](https://github.com/StackStorm/st2/files/1335956/st2actionrunner.log)

Should I raise a separate issue and close this one for the above error?

**Comment by LindsayHill** [comment]
Good to hear. I might make a small change to the docs to make this more
clear.

Yes, I suggest opening a separate issue for that one. There may be some
control options around failover behavior, but I don’t know them off the top
of my head
