### ISSUE TITLE
Mistral queues are left around after st2ctl restart

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3811]
## List queues before stopping mistral

```
ubuntu@st2test:~$ sudo rabbitmqctl list_queues
Listing queues ...
amq.gen--9oCuZglimKnpAzrRbW07g	0
amq.gen-DneH6VOkD50zHD_eImJ4Ug	0
amq.gen-RJ9aCDsbPjoOzKV994XU5Q	0
amq.gen-vAd-muvVKgy6Hx8bSE-mTA	0
mistral_engine	0
mistral_engine.0.0.0.0	0
mistral_engine_fanout_d9a1d67a148846a682f815e9e2d75018	0
mistral_executor	0
mistral_executor.0.0.0.0	0
mistral_executor_fanout_2dd3f5ed31ec40369dd741ec35e9008e	0
st2.actionrunner.cancel	0
st2.actionrunner.pause	0
st2.actionrunner.req	0
st2.actionrunner.resume	0
st2.actionrunner.work	0
st2.notifiers.execution.work	0
st2.preinit	0
st2.resultstracker.work	0
st2.sensor.watch.sensor_container-90ceb1732f	0
st2.trigger.watch.St2Timer-688e522ccb	0
st2.trigger.watch.TimersController-b294f21185	0
st2.trigger.watch.WebhooksController-467ff02387	0
st2.trigger.watch.sensorwrapper_linux_FileWatchSensor-caa3182e02	0
st2.trigger_instances_dispatch.rules_engine	0
```

## Stop services
```
ubuntu@st2test:~$ sudo st2ctl stop
```

## Start services
```
ubuntu@st2test:~$ sudo st2ctl start
##### st2 components status #####
st2actionrunner PID: 20676
st2actionrunner PID: 20681
st2actionrunner PID: 20686
st2actionrunner PID: 20689
st2actionrunner PID: 20692
st2actionrunner PID: 20696
st2actionrunner PID: 20700
st2actionrunner PID: 20703
st2actionrunner PID: 20706
st2actionrunner PID: 20709
st2api PID: 20714
st2stream PID: 20718
st2auth PID: 20722
st2garbagecollector PID: 20726
st2notifier PID: 20730
st2resultstracker PID: 20736
st2rulesengine PID: 20740
st2sensorcontainer PID: 20744
st2chatops is not running.
mistral-server PID: 20821
mistral-api PID: 20783
```

## List queues again 
```
ubuntu@st2test:~$ sudo rabbitmqctl list_queues
Listing queues ...
mistral_engine	0
mistral_engine.0.0.0.0	0
mistral_engine_fanout_1e5b0a5b47fc48dc9c65f4e10461dc52	0
mistral_engine_fanout_d9a1d67a148846a682f815e9e2d75018	0
mistral_executor	0
mistral_executor.0.0.0.0	0
mistral_executor_fanout_2dd3f5ed31ec40369dd741ec35e9008e	0
mistral_executor_fanout_4c9032c69fea45e78199480600aca65d	0
st2.actionrunner.cancel	0
st2.actionrunner.pause	0
st2.actionrunner.req	0
st2.actionrunner.resume	0
st2.actionrunner.work	0
st2.notifiers.execution.work	0
st2.preinit	0
st2.resultstracker.work	0
st2.sensor.watch.sensor_container-3a32d86233	0
st2.trigger.watch.St2Timer-406e2302de	0
st2.trigger.watch.TimersController-1fe899a5be	0
st2.trigger.watch.WebhooksController-36e3b24690	0
st2.trigger.watch.sensorwrapper_linux_FileWatchSensor-81b449ce02	0
st2.trigger_instances_dispatch.rules_engine	0
ubuntu@st2test:~$
```

Pay attention to mistral_engine_fanout and mistral_executor_fanout queues.

**Comment by machao19902** [comment]
@lakshmi-kannan Hi, lakshmi-kannan. I also find the zombie queue which has the name likes st2.sensor.watch.sensor_container-<random_string> 
I execute the command below and get some information that:
root@rabbitmq-0:/# rabbitmqctl list_queues name auto_delete arguments |grep st2|  grep -v "x-expires"| sort -n
st2.sensor.watch.sensor_container-4a0699b704	false	[]

As we know if the name of queue is randomed, the auto_delete property is set as false and we do not set expire time for the queue,
the queue will be a zombie queue after some service restared.
I track the code and find a solution can resolve this question:
 
In the code of st2/st2common/st2common/services/sensor_watcher.py
We can change this method as below
from
    @staticmethod
    def _get_queue(queue_suffix):
        queue_name = queue_utils.get_queue_name(queue_name_base='st2.sensor.watch',
                                                queue_name_suffix=queue_suffix,
                                                add_random_uuid_to_suffix=True
                                                )
        return reactor.get_sensor_cud_queue(queue_name, routing_key='#')
to
    @staticmethod
    def _get_queue(queue_suffix):
        queue_name = queue_utils.get_queue_name(queue_name_base='st2.sensor.watch',
                                                queue_name_suffix=queue_suffix,
                                                add_random_uuid_to_suffix=True
                                                )
        # return reactor.get_sensor_cud_queue(queue_name, routing_key='#')
        return reactor.get_sensor_cud_queue_with_auto_delete(queue_name, routing_key='#', auto_delete=True)
, and add a method in the code of st2/st2common/st2common/transport/reactor.py
as below:
def get_sensor_cud_queue_with_auto_delete(name, routing_key, auto_delete=True):
    return Queue(name, SENSOR_CUD_XCHG, routing_key=routing_key, auto_delete=auto_delete)

This modification above is setting  auto_delete as True for the Queue of kombu to solve the problem of zombie queue
about queue st2.sensor.watch.sensor_container-<random_string>, 
but I don't know why the previous code doesn't set auto_delete as True.
Could you confirm that this modification is correct to solve the problem?
Thanks.

**Comment by armab** [comment]
Closing due to Mistral Deprecation.
