### ISSUE TITLE
many  zombie processes forked by st2actionrunner

### ISSUE THREAD

**Issue by damonchen** [StackStorm/st2#3813]
/opt/stackstorm/st2/bin/python /opt/stackstorm/st2/bin/st2actionrunner --config-file /etc/st2/st2.conf
root     16338  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     16343  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     16362  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     16366  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     16367  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     16561  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     16688  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     16801  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     16918  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     17033  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     17150  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     17262  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     17379  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     17609  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     17724  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     17841  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     17956  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     18115  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     18239  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     18374  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     18513  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     18655  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     18791  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     18931  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     19065  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     19204  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     19339  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     19483  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     19613  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     19752  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     19882  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     20016  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     20156  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     20306  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     20447  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     20582  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     20710  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>
root     20832  0.0  0.0      0     0 ?        Zs   Oct24   0:00  \_ [sudo] <defunct>

**Comment by armab** [comment]
Thanks for the report, however more detailed info with some code examples would be very helpful for us to understand the issue and be able to reproduce it.
For example, what's your OS, what version of st2 do you have, what is the environment (AWS/Vagrant/Docker/etc)? What actions are you running, are you able to reproduce it every time after executing specific set of workflows/actions/tasks?

**Comment by armab** [comment]
Closing.

Please reopen if you see this again and provide more detailed info.
