### ISSUE TITLE
st2 key load doesn't support secret values

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3815]
### Problem

Currently `st2 key load xxx.json` doesn't support loading `secret`/encrypted values. 

https://github.com/StackStorm/st2/blob/master/st2client/st2client/commands/keyvalue.py#L288-L300

Looks like the model in `st2client` needs to be updated: https://github.com/StackStorm/st2/blob/master/st2client/st2client/models/keyvalue.py

**Comment by emptywee** [comment]
I second that.

**Comment by Mierdin** [comment]
@nmaludy Is this ready to be closed?
