### ISSUE TITLE
re-run a workflow from error step got failed

### ISSUE THREAD

**Issue by suttonsun** [StackStorm/st2#3829]
Hi,

I am using stackstorm 2.4.0, and we created lots of workflow with mistral V2 format. I always need re-run workflow from failed action/sub-flow. I observed st2 re-run function works properly only for first level action/subflow of main flow, if re-run sub flow from second levels of  main flow, it always get complaints.
for example, here is my case main flow->sub-flow 1 in main flow-> sub-flow 2 in sub-flow 1 -> sub-flow 3 in sub-flow 2, it is no problem to re-run sub-flow 1 if it is error, but it can't re-run from sub-flow2 and sub flow3, it always get error like below.  could you help on this?

[root@pln-n1-eso4sap1 st2]# st2 execution re-run 59fffaa075ac3561368a64ae --tasks create_and_config_vm_for_single_sid.create_vlun_and_mount_rdm_for_sid_creation
.............
id: 5a0032e575ac353681c5cab0
action.ref: sap.create_single_sid
parameters: 
  workload_type_id: 3ebad09b-bba2-41dc-87f7-0b9cd83af90b
status: failed
error: Only tasks in error state can be rerun. Unable to identify rerunable tasks: create_and_config_vm_for_single_sid.create_vlun_and_mount_rdm_for_sid_creation. Please make sure that the task name is correct and the task is in rerunable state.
traceback:   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py", line 119, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py", line 231, in run
    result = self.resume_workflow(ex_ref=self.rerun_ex_ref, task_specs=task_specs)
  File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py", line 345, in resume_workflow
    'and the task is in rerunable state.' % ', '.join(missing_tasks))

start_timestamp: 2017-11-06T10:01:08.422040Z
end_timestamp: 2017-11-06T10:01:41.758153Z
result: See error and traceback.

**Comment by Kami** [comment]
Thanks for reporting this.

First, I would recommend to upgrade to the latest stable version (v2.5.0) which has been released just recently (if possible). There were some Mistral related bug fixes in v2.5.0. I can't recall anything specific about the re-run, but it's still worth trying.

If the same issue exists, please come back and report it here and we will have a look.

/cc @m4dcoder

**Comment by suttonsun** [comment]
Hi Kami,

Today  I installed 2.5.0 in lab, and tested re-run from sub-sub-flow, it got the same error message with 2.4.0. could you take a look?

below is my test case and output

[root@ceph-node1 actions]# st2 --version
st2 2.5.0
[root@ceph-node1 actions]# st2 execution get 5a01bca57d09102ff538aed5
id: 5a01bca57d09102ff538aed5
action.ref: core.main_test
parameters: 
  str: xb
status: failed (32s elapsed)
result_task: sub_flow
result: 
  extra:
    state: ERROR
    state_info: null
  result: null
  tasks:
  - created_at: '2017-11-07 14:01:14'
    id: 8ef1b573-0325-4464-befd-d8c037f68cf2
    input: null
    name: startup_step
    published: {}
    result:
      failed: false
      return_code: 0
      stderr: ''
      stdout: this is sub flow 1
      succeeded: true
    state: SUCCESS
    state_info: null
    updated_at: '2017-11-07 14:01:16'
    workflow_execution_id: c4343e7b-342e-4554-9f06-3c6a8db2d66b
    workflow_name: core.sub_flow_1
  - created_at: '2017-11-07 14:01:16'
    id: 96b20821-795e-4654-b974-3123460ab250
    input: null
    name: sub_flow
    published: {}
    result:
      extra:
        state: ERROR
        state_info: null
      result: null
      tasks:
      - created_at: '2017-11-07 14:01:18'
        id: 8674e91a-6f49-4540-ac51-541bb186a9aa
        input: null
        name: startup_step
        published: {}
        result:
          failed: false
          return_code: 0
          stderr: ''
          stdout: this is sub flow 2
          succeeded: true
        state: SUCCESS
        state_info: null
        updated_at: '2017-11-07 14:01:21'
        workflow_execution_id: 7d8c54b4-4917-4bf1-ac53-56894f066a78
        workflow_name: core.sub_flow_2
      - created_at: '2017-11-07 14:01:21'
        id: 7a34187c-e25c-4a8f-bf56-c6c58ea31bb5
        input: null
        name: call_remote
        published: {}
        result:
          192.168.30.136:
            failed: true
            return_code: 1
            stderr: 'cat: /root/abc.txt: No such file or directory'
            stdout: ''
            succeeded: false
        state: ERROR
        state_info: '{192.168.30.136: {u''succeeded'': False, u''failed'': True, u''return_code'': 1, u''stderr'': u''cat: /root/abc.txt: No such file or directory'', u''stdout'': u''''}}'
        updated_at: '2017-11-07 14:01:23'
        workflow_execution_id: 7d8c54b4-4917-4bf1-ac53-56894f066a78
        workflow_name: core.sub_flow_2
    state: ERROR
    state_info: '{tasks: [{u''state_info'': None, u''name'': u''startup_step'', u''created_at'': u''2017-11-07 14:01:18'', u''updated_at'': u''2017-11-07 14:01:21'', u''id'': u''8674e91a-6f49-4540-ac51-541bb186a9aa'', u''workflow_execution_id'': u''7d8c54b4-4917-4bf1-ac53-56894f066a78'', u''state'': u''SUCCESS'', u''result'': {u''failed'': False, u''stderr'': u'''', u''return_code'': 0, u''succeeded'': True, u''stdout'': u''this is sub flow 2''}, u''published'': {}, u''input'': None, u''workflow_name'': u''core.sub_flow_2''}, {u''state_info'': u"{192.168.30.136: {u''succeeded'': False, u''failed'': True, u''return_code'': 1, u''stderr'': u''cat: /root/abc.txt: No such file or directory'', u''stdout'': u''''}}", u''name'': u''call_remote'', u''created_at'': u''2017-11-07 14:01:21'', u''updated_at'': u''2017-11-07 14:01:23'', u''id'': u''7a34187c-e25c-4a8f-bf56-c6c58ea31bb5'', u''workflow_execution_id'': u''7d8c54b4-4917-4bf1-ac53-56894f066a78'', u''state'': u''ERROR'', u''result'': {u''192.168.30.136'': {u''succeeded'': False, u''failed'': True, u''return_code'': 1, u''stderr'': u''cat: /root/abc.txt: No such file or directory'', u''stdout'': u''''}}, u''published'': {}, u''input'': None, u''workflow_name'': u''core.sub_flow_2''}], result: None, extra: {u''state_info'': None, u''state'': u''ERROR''}}'
    updated_at: '2017-11-07 14:01:27'
    workflow_execution_id: c4343e7b-342e-4554-9f06-3c6a8db2d66b
    workflow_name: core.sub_flow_1
start_timestamp: 2017-11-07T14:01:09.410463Z
end_timestamp: 2017-11-07T14:01:41.559726Z
+------------------------------+------------------------+--------------+-----------------+-------------------------------+
| id                           | status                 | task         | action          | start_timestamp               |
+------------------------------+------------------------+--------------+-----------------+-------------------------------+
|   5a01bca77d09102ff538aed7   | succeeded (2s elapsed) | startup_step | core.local      | Tue, 07 Nov 2017 14:01:10 UTC |
| + 5a01bca87d09102ff538aed9   | failed (24s elapsed)   | sub_flow     | core.sub_flow_1 | Tue, 07 Nov 2017 14:01:12 UTC |
|    5a01bcaa7d09102ff538aedb  | succeeded (2s elapsed) | startup_step | core.local      | Tue, 07 Nov 2017 14:01:14 UTC |
|  + 5a01bcad7d09102ff538aedd  | failed (10s elapsed)   | sub_flow     | core.sub_flow_2 | Tue, 07 Nov 2017 14:01:16 UTC |
|     5a01bcae7d09102ff538aedf | succeeded (2s elapsed) | startup_step | core.local      | Tue, 07 Nov 2017 14:01:18 UTC |
|     5a01bcb17d09102ff538aee1 | failed (2s elapsed)    | call_remote  | core.remote     | Tue, 07 Nov 2017 14:01:21 UTC |
+------------------------------+------------------------+--------------+-----------------+-------------------------------+
[root@ceph-node1 actions]# st2 execution re-run 5a01bca57d09102ff538aed5 --tasks sub_flow.sub_flow.call_remote
.
id: 5a01c01f7d09102ff538af16
action.ref: core.main_test
parameters: 
  str: xb
status: failed
error: Only tasks in error state can be rerun. Unable to identify rerunable tasks: sub_flow.sub_flow.call_remote. Please make sure that the task name is correct and the task is in rerunable state.
traceback:   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py", line 119, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py", line 233, in run
    result = self.resume_workflow(ex_ref=self.rerun_ex_ref, task_specs=task_specs)
  File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py", line 347, in resume_workflow
    'and the task is in rerunable state.' % ', '.join(missing_tasks))

start_timestamp: 2017-11-07T14:15:59.113449Z
end_timestamp: 2017-11-07T14:15:59.803780Z
result: See error and traceback.

**Comment by suttonsun** [comment]
Any update on this? is this a bug or something wrong with what I did?

**Comment by suttonsun** [comment]
troubleshooting with the code, I found the issue is that the attribute "task_execution_id" of object "execution" is always 'None', so that there is no re-run 'task' found and raise exception. The code is located at/opt/stackstorm/runners/mistral_v2/mistral_v2.py in method is "_get_tasks". Could you help on workaround to make it work?

            workflow_ex_ids = [wf_ex.id for wf_ex in executions
                               if (getattr(wf_ex, 'task_execution_id', None) and
                                   wf_ex.task_execution_id in parent_task_ids)]

**Comment by suttonsun** [comment]
@armab @Kami    I am waiting for your response for 2 weeks, could you please verify my issue and post workaround to figure it out?

**Comment by wyjuly** [comment]
We saw the same bug in stackstorm 2.5.
It should be a very useful feature to rerun workflow from the failed point.
