### ISSUE TITLE
Action 'linux.service' fails on Centos7

### ISSUE THREAD

**Issue by shkadov** [StackStorm/st2#3842]
When I tried to execute restart some service on the Centos7 server got the following error:
```
Traceback (most recent call last):
  File "/tmp/5a0459bc07ac686fb813a920/service.py", line 24, in <module>
    subprocess.call(cmd, shell=True)
NameError: name 'cmd' is not defined
```
After investigation the resolution has been found:
in file /opt/stackstorm/packs/linux/actions/service.py the entry

`elif re.search(distro, 'Redhat') or re.search(distro, 'Fedora'):`

fixed to 

`elif re.search(distro, 'Redhat') or re.search(distro, 'Fedora') or re.search(distro, 'CentOS Linux'):`

The issue has gone

**Comment by armab** [comment]
Thanks for reporting it and looking on solution.

Since you have the working code change, Pull Request would be very welcome!

https://github.com/StackStorm/st2/blob/master/contrib/linux/actions/service.py
