### ISSUE TITLE
latency issue with st2 execution list output

### ISSUE THREAD

**Issue by sibirajal** [StackStorm/st2#3856]
Hello Team, 

I have tried to retrieve the execution stats from our ST2 instance and it took 27 seconds for retriving the 3593 records. In our case the mongodb,rabbitmq and postgresql are in seperate host. Also tried to get the execution stats with 50000 records and it failed with connection aborted error. 

The max page size limit is set to 100000 in our ST2 instance. Can you please take a look and investigate the reason for latency in retriving the results and connection error? 

time st2 execution list -n 30000 |wc -l
3593

real	0m27.943s
user	0m4.081s
sys	0m0.197s

st2 execution list -n 50000
ERROR: ('Connection aborted.', BadStatusLine("''",))

cat /etc/st2/st2.conf |grep max
max_page_size = 100000

st2 --version
st2 2.5.0

**Comment by Kami** [comment]
Thanks for reporting this.

I believe it might be related to #3854.

CLI wasn't really designed to display 1000's of records at once (there is a lot of overhead in retrieving, parsing and formatting that many records inside the CLI).

If you really need to retrieve that many records at once, imo, the best way would be to directly hit the API (this way you avoid all the overhead in CLI).

And the connection error might be related to the actual result (HTTP response payload) size. Actual execution objects can be huge. The best way to avoid that is to implement pagination (e.g. retrieve 100 records at once).

**Comment by Kami** [comment]
@sibirajal Can you please also clarify what you are trying to achieve / what's the expected end result / outcome?

It looks like you are trying to retrieve some statistics and there might be better ways to do that then listing all the executions :)

**Comment by sibirajal** [comment]
@Kami Thanks for the response. 

I have been using the 'st2 execution list -n 10000' command to retrieve the execution results from our ST2 system for auditing purpose. Mostly we use that high numbers to pull the execution stats for last 30 days. 

Would it be possible to retrieve the same execution results using the API?

**Comment by Kami** [comment]
@sibirajal Thanks.

Yes, it should be possible to retrieve that using the API - curl "http://URL/api/v1/executions". And depending on the fields you need, you can also exclude a bunch of other fields which contain a lot of data (result, trigger_instance, etc.) using `?exclude_attributes` query param filter (there are also other files which allow you to filter on status, rule, action, etc.)

**Comment by Kami** [comment]
Discussed this offline - the user only needs IDs of executions from the last 30 days so the most efficient and simple solution for now is to simply directly query the database using MongoD REPL:

```bash
use st2();
# authenticate
db.action_execution_d_b.find({"start_timestamp": {$gte: 1508751349395128}}, {"id": 1})
```

Where the timestamp is number of microseconds since the unix epoch (seconds * 1000000). For the last 30 days scenario this would be `*(<timestamp now in seconds> - (30 * 86400)) * 1000000)`.

In the future, #3858 should also allow users to retrieve such information more efficiently via the API and #3854 via the CLI.

**Comment by Kami** [comment]
@sibirajal #3953 should help - it will be included in the next release (no ETA for that yet).

**Comment by LindsayHill** [comment]
Closing since #3953 has shipped.
