### ISSUE TITLE
Regarding publishing value of variables on some condition

### ISSUE THREAD

**Issue by sumeetisp** [StackStorm/st2#3875]
In creat_vm example provided at following link [here](https://docs.stackstorm.com/mistral.html#stitching-together-a-more-complex-workflow)

How can we change the value of status_message based on the on-success and on-error condition?

Like on-success the value of status_message should be "x" and on-error value should be "y"

**Comment by nmaludy** [comment]
@sumeetisp The `publish` block runs when the task's status is `success`, there is also another block called `publish-on-error` that runs when the task's status is `error`. This, i believe, should allow you to accomplish what you're after. Please see the Mistral DSL for some more info: https://docs.openstack.org/mistral/latest/user/dsl_v2.html#common-task-attributes
