### ISSUE TITLE
Parsing json output

### ISSUE THREAD

**Issue by sumeetisp** [StackStorm/st2#3878]
How to publish a variable depending on if a particular key exists in json output?

For e.g
Consider following json output
x={"a":1,"b":2}

Then,
if b exists in x then c=3 otherwise c=4

**Comment by LindsayHill** [comment]
I think that the way to do it would be to have branching `on-success:` options, similar to here https://github.com/StackStorm/st2/blob/master/contrib/examples/actions/workflows/mistral-branching.yaml#L17

Depending on the contents of X, you would execute different tasks. Those tasks would be `core.noop` actions that publish the variable you want.

**Comment by sumeetisp** [comment]
I not looking for executing different tasks. I am looking to publish a variable with a particular value depending on certain key is present in the output of the task.

**Comment by LindsayHill** [comment]
I know you don't want to execute a different task. But what I'm trying to say is that I don't think you can do a conditional publish. Instead you need to conditionally execute different tasks, each of which can have a different `publish:` line. There's no actual action executed - it calls `core.noop`. It is a common pattern to use `core.noop` when you're trying to publish something without calling a real action.

There may also be other patterns to solve your bigger problem. You're focusing on a very narrow aspect, and without wider context about the real problem you're trying to solve it's hard to offer more general help.

**Comment by sumeetisp** [comment]
How to parse following,

"published": {
        "status": "Entity successfully created",
        "ci_id": "{\"success\":true,\"id\":\"svr-1511520146139\",\"message\":\"Entity created successfuly\"}"
      }


I want to access <% $.ci_id.id%>
