### ISSUE TITLE
Parsing json output - Continued from #3878

### ISSUE THREAD

**Issue by sumeetisp** [StackStorm/st2#3883]
How to parse following,

     "published": {
            "status": "Entity successfully created",
            "ci_id": "{\"success\":true,\"id\":\"some text\",\"message\":\"Entity created successfuly\"}"
          }

I want to access <% $.ci_id.id%>

**Comment by LindsayHill** [comment]
Have you tried this syntax? https://docs.stackstorm.com/mistral_yaql.html#dictionaries

Also, rather than opening issues for usage questions, you may like to join the Slack community (https://stackstorm.com/community-signup)
