### ISSUE TITLE
salt.client end with TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Skyneo** [StackStorm/st2#3906]
Hi,

I am testing salt module, but even after I installed all packages mention in requirements my run are failing

I am trying ` dev01slack01:~# st2 run salt.client matches='dev*' module=test.ping` and i keep getting error:

>  id: 5a2eab055b3a0f2e864326be
status: failed
parameters:
  matches: dev*
  module: test.ping
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 259, in <module>\n    obj.run()\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 155, in run\n    output = action.run(**self._parameters)\n  File \"/opt/stackstorm/packs/salt/actions/client.py\", line 16, in run\n    ret = cli.cmd(matches, module, arg=args, kwarg=kwargs)\n  File \"/opt/stackstorm/virtualenvs/salt/lib/python2.7/site-packages/salt/client/__init__.py\", line 711, in cmd\n    arg = salt.utils.args.condition_input(arg, kwarg)\n  File \"/opt/stackstorm/virtualenvs/salt/lib/python2.7/site-packages/salt/utils/args.py\", line 29, in condition_input\n    for arg in args:\nTypeError: 'NoneType' object is not iterable\n"
  stdout: ''

My local salt master:

> root@dev01slack01:~# salt-run --versions
Salt Version:
           Salt: 2017.7.2
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-103-generic
         system: Linux
        version: Ubuntu 16.04 xenial

with `st2 2.5.0`

**Comment by LindsayHill** [comment]
Looking at https://github.com/StackStorm-Exchange/stackstorm-salt/blob/master/actions/client.py, the code is pretty simple:

```python
import salt.client

from st2common.runners.base_action import Action


class SaltClientAction(Action):
    def run(self, matches, module, args=[], kwargs={}):
        '''
        CLI Examples:
            st2 run salt.client matches='web*' module=test.ping
            st2 run salt.client module=pkg.install \
                    kwargs='{"pkgs":["git","httpd"]}'
        '''
        cli = salt.client.LocalClient()
        ret = cli.cmd(matches, module, arg=args, kwarg=kwargs)
        return ret
```

Can you do something like this:
```sh
ubuntu@st2vagrant:~$ source /opt/stackstorm/virtualenvs/salt/bin/activate
(salt) ubuntu@st2vagrant:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> cli = salt.client.LocalClient()
>>> matches='dev*'
>>> module='test.ping'
>>> args=[]
>>> kwargs={}
>>> ret = cli.cmd(matches, module, arg=args, kwarg=kwargs)
```

And see what that returns? (what we're doing here is just interactively running that code, bypassing ST2).

The docs indicate that it should be fine to pass args as an empty array like that, and it did work in the past, but maybe something has changed here.

Also: in future for pack-specific issues, you can log them directly against that integration pack, rather than the core repo. So that would be github.com/StackStorm-Exchange/stackstorm-salt/issues

**Comment by Skyneo** [comment]
Yes, my bad, I ment to open it there :(

I did what u suggested but it didnt returned anything:

```
root@dev01slack01:~# source /opt/stackstorm/virtualenvs/salt/bin/activate
(salt) root@dev01slack01:~# python
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> cli = salt.client.LocalClient()
>>> matches='dev*'
>>> module='test.ping'
>>> args=[]
>>> kwargs={}
>>> ret = cli.cmd(matches, module, arg=args, kwarg=kwargs)
>>>
```

**Comment by Skyneo** [comment]
I did some more testing.

`st2 run salt.client module=service.status args=httpd` this end succesfull

```
id: 5a2faa4d5b3a0f2e864326e5
status: succeeded
parameters:
  args:
  - httpd
  module: service.status
result:
  exit_code: 0
  result:
    dev01master01: false
    dev01salt01: false
  stderr: ''
  stdout: ''
```

but another modules without arguments also failed.

I changed `/opt/stackstorm/packs/salt/actions/client.py` to look like this:

```
import salt.client

from st2common.runners.base_action import Action


class SaltClientAction(Action):
    def run(self, matches, module, args=[], kwargs={}):
        '''
        CLI Examples:

            st2 run salt.client matches='web*' module=test.ping
            st2 run salt.client module=pkg.install \
                    kwargs='{"pkgs":["git","httpd"]}'
        '''
        cli = salt.client.LocalClient()
        if args is None:
          ret = cli.cmd(matches, module)
        else:
          ret = cli.cmd(matches, module, arg=args, kwarg=kwargs)
        return ret
```
and that did a trick:

```
# st2 run salt.client module=test.ping matches=dev*
....
id: 5a2fab235b3a0f2e864326e8
status: succeeded
parameters:
  matches: dev*
  module: test.ping
result:
  exit_code: 0
  result:
    dev01master01: true
    dev01salt01: true
  stderr: ''
  stdout: ''
```

**Comment by LindsayHill** [comment]
I think that is a valid fix. An alternative is to change the action metadata (client.yaml), to set `default = []` for `args:`

I think there may have been some change in the past around the way st2client handles unspecified parameters, and it is now sending `None`, whereas in the past it didn't set it at all. I'm still investigating that angle.

**Comment by LindsayHill** [comment]
Funny thing is that local.py has a related problem, but it's the other way around. The pack has a default `args = []`, and that breaks local actions, as they expect `args = None`.

**Comment by LindsayHill** [comment]
See https://github.com/StackStorm-Exchange/stackstorm-salt/pull/5

**Comment by LindsayHill** [comment]
@Skyneo in your workaround, you've done this:
```python
        if args is None:
          ret = cli.cmd(matches, module)
        else:
          ret = cli.cmd(matches, module, arg=args, kwarg=kwargs)
        return ret
```
Could you do a test for, and try this instead?
```python
        if args is None:
          ret = cli.cmd(matches, module, kwarg=kwargs)
        else:
          ret = cli.cmd(matches, module, arg=args, kwarg=kwargs)
        return ret
```

I want to check if we need to do any special handling for kwarg=None.
