### ISSUE TITLE
Pack installation fails while registering the pack on stackstorm 2.5.X

### ISSUE THREAD

**Issue by rashisha** [StackStorm/st2#3921]
Pack installation is failing on stackstorm with the following error:
requests.exceptions.HTTPError: 502 Server Error: Connection refused
Unable to retrieve detailed message from the HTTP response. Expecting value: line 1 column 1 (char 0)
 for url: http://127.0.0.1:9101/v1/packs/register.
Though the required pack gets downloaded under /opt/stackstorm/packs but fails while trying to register it with stackstorm

**Comment by nmaludy** [comment]
@rashisha wlWhat pack are you trying to install?

Are there any errors in /var/log/st2/st2api.log or /var/log/st2/st2actionrunner.*.log

**Comment by Kami** [comment]
This looks like an st2api, st2stream or nginx issue.

As @nmaludy asked, please gist all the logs, notably the st2api, st2stream and nginx ones so we can have a look.

**Comment by LindsayHill** [comment]
No response, closing
