### ISSUE TITLE
ChatOps not posting notify messages

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3935]
### System Info

```
[root@stackstorm ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)
[root@stackstorm ~]# st2 --version
st2 2.5.1
```

### Problem

When executing a command via ChatOps (example: `!st2 execution get xxx`) i see the "ack" message immediately, however the result message is never posted. This is new in `2.5.1`.

![image](https://user-images.githubusercontent.com/3693851/34723973-531afc6a-f51a-11e7-8408-6d92ca7e6b39.png)

Checking the execution list, i can see that the action to post the result succeeded:

``` shell
[root@stackstorm ~]# st2 execution list -n 2
+----------------------------+-----------------+--------------+------------------------+-----------------+---------------+
| id                         | action.ref      | context.user | status                 | start_timestamp | end_timestamp |
+----------------------------+-----------------+--------------+------------------------+-----------------+---------------+
|   5a54c7be032fb60d0d1e7389 | st2.executions. | st2admin     | succeeded (2s elapsed) | Tue, 09 Jan     | Tue, 09 Jan   |
|                            | get             |              |                        | 2018 13:46:38   | 2018 13:46:40 |
|                            |                 |              |                        | UTC             | UTC           |
| + 5a54c7c1032fb60ccf832b45 | chatops.post_re | stanley      | succeeded (4s elapsed) | Tue, 09 Jan     | Tue, 09 Jan   |
|                            | sult            |              |                        | 2018 13:46:41   | 2018 13:46:45 |
|                            |                 |              |                        | UTC             | UTC           |
+----------------------------+-----------------+--------------+------------------------+-----------------+---------------+
+------------------------------------------------------------------------------------------------------------------------+
| Note: Only first 2 action executions are displayed. Use -n/--last flag for more results.                               |
+------------------------------------------------------------------------------------------------------------------------+
```

**Comment by LindsayHill** [comment]
@nmaludy is st2chatops correctly connecting to `/api/v1/stream`? Can you see those connections in the nginx logs and st2stream.log?

**Comment by armab** [comment]
@nmaludy Is replacing st2 `v2.5.1` rpm package with older `v2.5.1` guaranteed fixes the issue/regression?
Also are you configuring chatops via puppet-st2? Curious if there is any st2chatops.env config diff we missed in recent Puppet PRs.

**Comment by nmaludy** [comment]
@armab @LindsayHill yeah looks like a puppet-st2 thing, i'm making a PR for it now

**Comment by sergiik** [comment]
@nmaludy What was the issue in your case? I have the same problem after installing using the latest puppet-st2 module

**Comment by nmaludy** [comment]
@sergiik It was a bug in the `puppet-st2` module. It's fixed in the latest version `1.0.0-rc2` https://github.com/StackStorm/puppet-st2/releases/tag/v1.0.0-rc2  . If you upgrade to the latest version, then it should fix your problem :)

**Comment by sergiik** [comment]
@nmaludy thank you for your answer. 
I found the error. It was my configuration fault while trying to change default ports.

**Comment by nmaludy** [comment]
@sergiik I'm the maintainer of the puppet-st2 module. Feel free, any time, time open an issue on the GitHub page: https://github.com/StackStorm/puppet-st2

Also PLEASE stop by #puppet on the StackStorm Slack https://stackstorm.com/community-signup

I'd love to chat about how you guys use Puppet and StackStorm!
