### ISSUE TITLE
Optimize deleting old action execution data

### ISSUE THREAD

**Issue by kevin-vh** [StackStorm/st2#3936]
Using `st2-purge-executions` or the `st2garbagecollector` process, all `ActionExecution` objects are fully loaded into memory, resulting in extremely high memory usage when cleaning up execution data in cases where actions have a lot of data as input and running the actions very frequently.

In our case we're fetching network measurements from a number of devices on a 5 minute interval, which generates a lot of data by a large amount of actions.

The troublesome line is the following: [https://github.com/StackStorm/st2/blob/6df54d7f3703dad890b83b7feed4b43584b2861a/st2common/st2common/garbage_collection/executions.py#L82](url).
Here, all `ActionExecution` objects matching the filters are unnecessarily loaded in to memory; only the ids are needed at [https://github.com/StackStorm/st2/blob/6df54d7f3703dad890b83b7feed4b43584b2861a/st2common/st2common/garbage_collection/executions.py#L108](url). This causes the deletion process to be slow and memory intensive in our case.

Loading more `ActionExecution` data into memory than the available system memory leads to the garbage collection never deleting everything, because all data is fetched before starting to delete data.

The process would run smoother and safer if only (necessary) data i.e. the ids of the `ActionExecution`s were fetched, rather than all of the data.

**Comment by Kami** [comment]
Thanks for reporting this.

That's indeed a valid point and good catch - we should only load the fields we need.

The fix should be pretty easy and straight forward and I will look into it.

**Comment by kevin-vh** [comment]
Great, thanks!
