### ISSUE TITLE
st2 pack install hangs during installing dependencies

### ISSUE THREAD

**Issue by m4dcoder** [StackStorm/st2#3959]
The command `st2 pack install` hangs during installing dependencies (or could be any other step) in the CLI even though the workflow completed server side. User is running `st2 v2.3.2`. There's no errors in the st2api and st2stream logs. All st2 services are running. This errors persist after restart of the services. The issue is currently not reproducible on another system.

**Comment by m4dcoder** [comment]
@Kami can you take a look tomorrow?

**Comment by m4dcoder** [comment]
After users cancelled some long running workflows, the problem went away.

**Comment by Kami** [comment]
Could be a stream or intermediate networking issue connecting to the stream service, but dunno.
