### ISSUE TITLE
Add filters to get a specific user's execution list

### ISSUE THREAD

**Issue by apolloliu** [StackStorm/st2#3966]
I add this issue so as to discuss a demand that allows user to observe execution list or a specific execution entry of their own to isolate execution list through execution api. This needs to add filter extension of execution api.
For further design, it may be available to take advantage of role assignment of RBAC and add a new permission type to allow admin to scan all members or a specific user'
execution list. 
I'm sure st2 in community version doesn't support all of above. There need more discussion and I'd like to implement this if st2 team think it worthy.

**Comment by LindsayHill** [comment]
It looks like the executions API already supports filtering via user with the `user` param, e.g. `GET 'http://127.0.0.1:9101/v1/executions/?status=succeeded&limit=1&exclude_attributes=result%2Ctrigger_instance&sort_desc=True&parent=null&user=st2admin`

This is not currently available with the `st2 execution list` API, but it should be easy enough to add to there. It is supported in the Web UI today.

You can also query the available list of users to filter on with something like `GET http://127.0.0.1:9101/v1/executions/views/filters?types=user`

Or are you thinking of something else here?

**Comment by apolloliu** [comment]
@LindsayHill  Thanks for your explaination. I haven't see it can filter the execution history belonging to a user on logining in the website.  I'm not sure what means of supporting in the Web UI. Forgive me for I know nothing about front end.

**Comment by LindsayHill** [comment]
This is what I mean by user filtering in the Web UI:
<img width="877" alt="user_filter" src="https://user-images.githubusercontent.com/3607046/35590429-b699fea6-05bb-11e8-9ff2-5212c9e8028b.png">

This is working today. 

Do you want to add something to the CLI? For example, the ability to run `st2 execution list --user=lindsay`?

**Comment by apolloliu** [comment]
@LindsayHill I very appreciate for your response. Let me tell what I really want to do.
First, My final goal is that a user can just observe all execution histories belong to him once logining in. That means one user can not look at the histories of another user. I guess this isolation should be implemented through dynamic permission grant. 
Second, I want to apply this isolation function to `rules` resources. I'm not sure if this should be proposed as a new issue. You can imagine that every rule has a user to be bundled. one can not see the rule which another user adds.
Third, thanks your screenshot. From my simplest enterprise edition software,
![qq 20180131105018](https://user-images.githubusercontent.com/5372499/35602729-e2cc3124-0674-11e8-9e42-79b719af0409.png)
This doesn't show the `user` filter.  Even though it isn't the main point I care about. I also want to know how to add user filter like this.

**Comment by LindsayHill** [comment]
> I also want to know how to add user filter like this.
Upgrade to StackStorm 2.6 and you should see it.

**Comment by LindsayHill** [comment]
Thank for you the additional clarification on what you are trying to achieve. Looking at the current [RBAC documentation](https://docs.stackstorm.com/rbac.html) I don't think that is currently supported. There are controls for viewing executions, but it looks like that [inherits permissions](https://docs.stackstorm.com/rbac.html#permission-inheritance) from the actions that a user has permissions to execute. 

So a user will only see a limited set of executions, but that could include actions executed by someone else who also has access to view & execute those actions. 

I think it could be useful to design an enhancement to the RBAC controls to allow users to only see results for actions they executed. You are welcome to start work on that if you wish. This would require the general RBAC controls, which are only in the Enterprise version.

**Comment by apolloliu** [comment]
Yeah, it isn't supported currently. The inherits permissions for `Executions` and `Rule enforcements` only grant the permissions(including permissions of view and operation) belong to a pack. What I want to implement is granting permission by a specific user label of every rule and every execution.

I think if a user can't see a specific rule or action, he or she can't execute it or change it.  Everyone can just view and operate his or her own. Maybe system admin have all permission to view and operate all rules or actions.

I'd like to contribute this general RBAC controls. Before that, do you any suggestion 
on how to start it?

**Comment by apolloliu** [comment]
@LindsayHill Hi, I have two commits to implement this feature. Could them be pushed to community?
[commit 1](https://github.com/apolloliu/st2/commit/82e8af80c267efd03ce0bec7a58c373006651e9d)
[commit 2](https://github.com/apolloliu/st2/commit/d7aa5f790b47568f1bf9e12b34dd5f9c199b689c)

**Comment by LindsayHill** [comment]
Can you create a new pull request containing those commits? Reference this
issue number.

**Comment by apolloliu** [comment]
Sure, I just need your confirmation my works to avoid futile actions.

**Comment by LindsayHill** [comment]
The best thing to do is to create a pull request. Then we can see all the changes in context, we can check the automated test results, and we can discuss the changes further

**Comment by apolloliu** [comment]
What the modifications are based on v2.6. If I create a pull request, I need to move and adjust all changes into master branch. But no matter how trouble it is, I'll finish it.

**Comment by apolloliu** [comment]
@LindsayHill This is my PR #4013 but need some tests.

**Comment by LindsayHill** [comment]
Addressed with https://github.com/StackStorm/st2/pull/4054 (superseded #4013)
