### ISSUE TITLE
Scheduling Workflow

### ISSUE THREAD

**Issue by guptasakshi01** [StackStorm/st2#3969]
Hi,
I want to schedule a workflow that executes every 15 minutes,
Please help on this requirement.
Thanks,
Sakshi

**Comment by Kami** [comment]
You can achieve that by using `IntervalTime` trigger - https://docs.stackstorm.com/rules.html?highlight=interval#core-st2-intervaltimer.

**Comment by guptasakshi01** [comment]
It worked as required, Thanks.
