### ISSUE TITLE
Setup Action in Stackstorm

### ISSUE THREAD

**Issue by chella2830** [StackStorm/st2#3983]
Hello,

I want to setup an action to see if i am getting the trigger from an event. The action is that i want to display a message in a log file on Stackstorm server itself or maybe a CLI output. How can i do this action?

Thanks

**Comment by LindsayHill** [comment]
You probably want to look at some of the StackStorm documentation - e.g. look at the [Quick Start](https://docs.stackstorm.com/start.html). In the "Define a Rule" section, the example writes the trigger body to a file on the ST2 server.
