### ISSUE TITLE
Stackstorm and Proxy setting

### ISSUE THREAD

**Issue by chella2830** [StackStorm/st2#3984]
Hello,
Here is my proxy setting -

```shell
root@ubuntu:/etc/default# cat st2actionrunner
http_proxy=http://proxyx..xxx.com:8080
https_proxy=http://proxyx.x.com:8080
no_proxy=localhost,127.0.0.1

root@ubuntu:/etc/default# cat st2api
http_proxy=http://proxyx.xxx.com:8080
https_proxy=http://proxyx.xxx.com:8080
no_proxy=localhost,127.0.0.1
```

Restarted both services

```shell
root@ubuntu:/home/tsgadmin# st2 pack install ghost2logger
ERROR: 400 Client Error: Bad Request
MESSAGE: No results from the index: tried https://index.stackstorm.org/v1/index.json.
Status: [
    {
        "url": "https://index.stackstorm.org/v1/index.json",
        "message": "ProxyError(MaxRetryError(\"HTTPSConnectionPool(host='index.stackstorm.org', port=443): Max retries exceeded with url: /v1/index.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6c0dd78410>: Failed to establish a new connection: [Errno -2] Name or service not known',)))\",),)",
        "error": "unresponsive",
        "packs": 0
    }
] for url: http://127.0.0.1:9101/v1/packs/index/search
```

removed the above settings -
and then did the same above command -

```shell
root@ubuntu:/etc/default# st2 pack install ghost2logger

For the "ghost2logger" pack, the following content will be registered:

rules     |  0
sensors   |  2
triggers  |  0
actions   |  0
aliases   |  0

Installation may take a while for packs with many items.

        [  running  ] download pack
```
I am getting timeout error. need help here.

Thanks

**Comment by LindsayHill** [comment]
Do you need to use a proxy to access the Internet from your ST2 server?

**Comment by LindsayHill** [comment]
The errors indicate that you misconfigured your proxy settings - eg invalid hostname

**Comment by chella2830** [comment]
Whether if i use proxy i am getting the above error message. However if i am not using proxy i am getting this error message -
root@ubuntu:/etc/default# st2 pack install ghost2logger

For the "ghost2logger" pack, the following content will be registered:

rules     |  0
sensors   |  2
triggers  |  0
actions   |  0
aliases   |  0

Installation may take a while for packs with many items.

        [  timeout  ] download pack

ERROR: list index out of range

I am not having any problems with other packs. No proxy issue and i am not using proxy for downloading other packs. It is only this pack that is giving me grief.

**Comment by LindsayHill** [comment]
So to be clear: you do not need to use a proxy to connect to the Internet? So why are you configuring a proxy?

**Comment by chella2830** [comment]
because i am not able to install ghost2logger either way - i tired to test using proxy - it didn't work, i tried to test installing directly without using proxy, still the install didn't work

**Comment by LindsayHill** [comment]
Do you need to use a proxy to connect to the Internet? I am trying to help track down where the problem might be, but it's really confusing to me. Are you able to connect to the Internet from your ST2 server directly, or do you need to use a proxy?

**Comment by LindsayHill** [comment]
Let's get the answer to that bit, and then we can work out what to look at next
