### ISSUE TITLE
Reverse workflow failed in Stackstorm

### ISSUE THREAD

**Issue by wyjuly** [StackStorm/st2#3994]
Hi there,

I've created a reverse workflow in stackstorm and get error as below:

  "error": "Invalid task name [wf_spec=ReverseWorkflowSpec {'input': ['test1', 'test2'], 'tasks': {'testa': {'action': 'st2.action', 'input': {'ref': 'core.noop'}, 'version': '2.0', 'type': 'reverse', 'name': 'testa'}}, 'type': 'reverse', 'name': 'dev.test_reverse', 'version': '2.0'}, task_name=None]"

So stackstorm doesn't support reverse flow, right?

**Comment by LindsayHill** [comment]
The [documentation](https://docs.stackstorm.com/mistral.html) indicates that reverse workflows are supported. What is your action metadata and your workflow definition?

**Comment by wyjuly** [comment]
@LindsayHill Thanks for your response.
The metadata:

```
---
name: "test_reverse"
runner_type: "mistral-v2"
pack: "dev"
enabled: true
entry_point: "workflows/test_reverse.yaml"

parameters:
  test1:
    required: false
    type: string
    position: 0
  test2:
    required: false
    type: string
    position: 1
```


The definition:

```
version: '2.0'

dev.test_reverse:
  type: reverse
  input:
    - test1
    - test2

  tasks:
    step1:
      action: core.noop
    step2:
      action: core.noop
    step3:
      action: core.noop
      requires: [step2]
    step4:
      action: nova.servers_add_floating_ip server=<% $.vm_id %> address=<% $.vm_ip %>
      requires: [step1,step2]
```

And the error:

```
{
  "traceback": "  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py\", line 120, in _do_run\n    (status, result, context) = runner.run(action_params)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 49, in wrapped_f\n    return Retrying(*dargs, **dkw).call(f, *args, **kw)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 206, in call\n    return attempt.get(self._wrap_exception)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 247, in get\n    six.reraise(self.value[0], self.value[1], self.value[2])\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 200, in call\n    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)\n  File \"/opt/stackstorm/runners/mistral_v2/mistral_v2/mistral_v2.py\", line 239, in run\n    result = self.start_workflow(action_parameters=action_parameters)\n  File \"/opt/stackstorm/runners/mistral_v2/mistral_v2/mistral_v2.py\", line 281, in start_workflow\n    **options)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/mistralclient/api/v2/executions.py\", line 59, in create\n    return self._create('/executions', data)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/mistralclient/api/base.py\", line 100, in _create\n    self._raise_api_exception(resp)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/mistralclient/api/base.py\", line 160, in _raise_api_exception\n    error_message=error_data)\n",
  "error": "Invalid task name [wf_spec=ReverseWorkflowSpec {u'input': [u'test1', u'test2'], u'tasks': {u'step4': {u'name': u'step4', u'requires': [u'step1', u'step2'], u'version': '2.0', u'action': u'nova.servers_add_floating_ip', u'input': {u'server': u'<% $.vm_id %>', u'address': u'<% $.vm_ip %>'}, u'type': u'reverse'}, u'step3': {u'name': u'step3', u'requires': [u'step2'], u'version': '2.0', u'action': u'st2.action', u'input': {u'ref': u'core.noop'}, u'type': u'reverse'}, u'step2': {u'action': u'st2.action', u'input': {u'ref': u'core.noop'}, u'version': '2.0', u'type': u'reverse', u'name': u'step2'}, u'step1': {u'action': u'st2.action', u'input': {u'ref': u'core.noop'}, u'version': '2.0', u'type': u'reverse', u'name': u'step1'}}, u'type': u'reverse', u'name': u'dev.test_reverse', u'version': u'2.0'}, task_name=None]"
}
```

**Comment by LindsayHill** [comment]
I think that you need to define a target task in the metadata. Something like this:
```
  task:
    required: true
    type: string
```

**Comment by wyjuly** [comment]
@LindsayHill I've simplified the flow as your suggestion:

meta:

```
---
name: "test_reverse"
runner_type: "mistral-v2"
pack: "dev"
enabled: true
entry_point: "workflows/test_reverse.yaml"

parameters:
  test1:
    required: false
    type: string
    position: 0
  test2:
    required: false
    type: string
    position: 1
  task:
    default: step4
    immutable: true
    type: string
```

definition
```
version: '2.0'

dev.test_reverse:
  type: reverse
  input:
    - test1
    - test2

  tasks:
    step1:
      action: core.noop
    step4:
      action: core.noop
      requires: [step1]:
```

And still get errors:

```
{
  "traceback": "  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py\", line 120, in _do_run\n    (status, result, context) = runner.run(action_params)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 49, in wrapped_f\n    return Retrying(*dargs, **dkw).call(f, *args, **kw)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 206, in call\n    return attempt.get(self._wrap_exception)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 247, in get\n    six.reraise(self.value[0], self.value[1], self.value[2])\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 200, in call\n    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)\n  File \"/opt/stackstorm/runners/mistral_v2/mistral_v2/mistral_v2.py\", line 239, in run\n    result = self.start_workflow(action_parameters=action_parameters)\n  File \"/opt/stackstorm/runners/mistral_v2/mistral_v2/mistral_v2.py\", line 281, in start_workflow\n    **options)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/mistralclient/api/v2/executions.py\", line 59, in create\n    return self._create('/executions', data)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/mistralclient/api/base.py\", line 100, in _create\n    self._raise_api_exception(resp)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/mistralclient/api/base.py\", line 160, in _raise_api_exception\n    error_message=error_data)\n",
  "error": "Invalid task name [wf_spec=ReverseWorkflowSpec {u'input': [u'test1', u'test2'], u'tasks': {u'step4': {u'name': u'step4', u'requires': [u'step1'], u'version': '2.0', u'action': u'st2.action', u'input': {u'ref': u'core.noop'}, u'type': u'reverse'}, u'step1': {u'action': u'st2.action', u'input': {u'ref': u'core.noop'}, u'version': '2.0', u'type': u'reverse', u'name': u'step1'}}, u'type': u'reverse', u'name': u'dev.test_reverse', u'version': u'2.0'}, task_name=None]"
}
```

**Comment by cognifloyd** [comment]
@m4dcoder asked in slack for my use-case (why I would rather use a `reverse` over a `direct` workflow). I'll copy what I said in slack, expounding on a couple of the points to make my use case clearer.

I have a workflow with a set of tasks that process or retrieve various bits of data. I want them to run as fast as possible in parallel, and I don't really care about the order, except that some tasks require the data from other tasks to look up or figure out their bit of data. In the end, there are three tasks that use that data to configure a server (with an ansible playbook that gets input data via extra_args) and a couple of other servers that need to know about that server (using core.remote in one case, and I haven't decided whether to use a playbook or something else for manipulating the sqlite database on the third server).

Right now, I have an action-chain workflow with a bunch of on-successes. But, as I convert that to a mistral workflow I'd rather not have to manually define all of `on-success` things, and figure out where I need to add some `core.noop` tasks to serve as synchronization points, collecting data before continuing with dependent tasks. I don't want to figure out these points of synchronization and where things can go in parallel. Just saying which data is required to run that task is enough. With a direct workflow, I only need to add one `core.noop` task that requires on my three target tasks, and then let the workflow engine figure out the ordering of everything else.

With the action-chain, I kept bouncing the order of the on-successes around as I added or removed tasks. It's annoying to have to change on-success requirements on unrelated tasks (the only relation being they come earlier). The required data for each task is much easier to define (in this case) than defining the order of the tasks. As I add additional setup tasks going forward (telling more parts of our infrastructure about this new server), I want to avoid constantly mangling the chain of on-successes that has little to do with what I'm trying to accomplish. Thus, a `reverse` workflow looks like a much simpler for a complex data manipulation workflow that will only expand going forward.

**Comment by cognifloyd** [comment]
Oh, and one more thing to note:
There are no `reverse` workflows in the ST2 tests/examples:
https://github.com/StackStorm/st2/tree/master/contrib/examples/actions/workflows/tests
https://github.com/StackStorm/st2/tree/master/contrib/examples/actions/workflows
https://github.com/StackStorm/st2/tree/master/contrib/examples/actions

**Comment by m4dcoder** [comment]
Looks like there is a bug in our mistral runner. Mistral expects a target `task_name` to be given for reverse workflow (the final task in the WF waiting on the requires). Our mistral runner is passing `task` instead.

**Comment by wyjuly** [comment]
Thanks @m4dcoder @cognifloyd
