### ISSUE TITLE
How to stop tracking result for cancelled flow

### ISSUE THREAD

**Issue by wyjuly** [StackStorm/st2#3996]
Hi all,

I found there are many tracking logs in st2resulttracking.log for those cancelled flows like:
```
2018-02-12 12:04:50,568 79399664 INFO mistral_v2 [-] [5a3a0dcf09b5a24e33d1028b] Query returned status "CANCELLED" for mistral execution 6afee7e9-6795-4957-8a91-4fc33f7092f2.
...
2018-02-12 12:04:52,366 79397584 INFO mistral_v2 [-] There are active mistral tasks for 59c4b06a09b5a2787543647c.
2018-02-12 12:04:52,367 79397584 INFO mistral_v2 [-] There are active st2 tasks for 59c4b06a09b5a2787543647c.
2018-02-12 12:04:52,368 79397584 INFO mistral_v2 [-] [59c4b06a09b5a2787543647c] Determined execution status: canceling
```

The stackstorm services have been stuck before because of disk is full. I doubt these are records with error status updated since these flows have already been cancelled from UI or cli.

I checked in table live_action_d_b and workflow_executions_v2, the flow and liveaction's status are cancelled.

So what can I do to stop stackstorm's result tracking for these flow/liveactions? Do I need to delete the liveaction record in DB? Thanks.

**Comment by Kami** [comment]
@wyjuly Which version of StackStorm are you using?

/cc @m4dcoder

**Comment by m4dcoder** [comment]
If you look at the log entries, the WF hasn’t been cancelled yet. There are still actions under the WF that are in some active state. You should find out why they are still active.

**Comment by wyjuly** [comment]
@Kami we are using version 2.4.
@m4dcoder One day the disk is full and all stackstorm service is stuck including rabbitmq service.
I free the space and restart all of those services. Maybe that's the reason that some actions under the WF is active, but in fact they will not be executed any more.

Just want to know if I got such dead WF/actions but still polling in the logs, how to cancel them via mongo cli or postgres cli.

**Comment by m4dcoder** [comment]
@wyjuly First, I suggest that you migrate to 2.6. There's number of bug fixes and enhancements we've made to the st2resultstracker that tracks Mistral WF completion. Second, to clear existing actions from polling, if you have a lot of executions to clean up, you can login to the mongoDB instance, go to the st2 database, and truncate the action_execution_state_d_b collection.  After you do that, restart st2.
