### ISSUE TITLE
Token TTL in st2.conf doesn't work

### ISSUE THREAD

**Issue by wyjuly** [StackStorm/st2#4012]
Hi there,

We found that the token_ttl in /etc/st2/st2.conf doesn't work.
Below is our configuration:

[auth]
token_ttl = 5184000
host = 0.0.0.0
port = 9100
use_ssl = False

It's version 2.2 and we upgrade it to 2.4.

There is two actions in one flow, it took 3 days for step one and while stackstorm starts step 2 the error occurred:

      "state_info": "{status: 401, cookies: {}, encoding: None, url: http://127.0.0.1:9101/v1/actionexecutions, elapsed: 0.011803, content: {u'faultstring': u'Unauthorized - Token has expired.'}, headers: {u'Content-Length': u'58', u'Access-Control-Allow-Headers': u'Content-Type,Authorization,X-Auth-Token,St2-Api-Key,X-Request-ID', u'Access-Control-Expose-Headers': u'Content-Type,X-Limit,X-Total-Count,X-Request-ID', u'X-Request-ID': u'3c6a8887-918b-4666-8dac-3fb23e0878dc', u'Server': u'gunicorn/19.7.1', u'Connection': u'keep-alive', u'Access-Control-Allow-Credentials': u'true', u'Date': u'Fri, 16 Feb 2018 09:37:50 GMT', u'Access-Control-Allow-Origin': u'http://127.0.0.1:3000', u'Access-Control-Allow-Methods': u'GET,POST,PUT,DELETE,OPTIONS', u'Content-Type': u'application/json'}, reason: Unauthorized, history: []}",

So the token_ttl doesn't work in version 2.4? And do we have another option in st2.conf for stackstorm to generate a new token each time it trigger the next action in a flow?

Thanks.
Jason

**Comment by Kami** [comment]
Hello,

There are two types of TTLs which can be configured:

1) for regular user accounts - `token_ttl` config option, defaults to 24 hours
2) for StackStorm services (actions, workflows, etc.) - `service_token_ttl` config option, defaults to 24 hours

Changing the `service_token_ttl` and restarting the services should do the trick.

Please let us know if that works for you.

**Comment by wyjuly** [comment]
@Kami Thank Kami. Let me try this and update here.

**Comment by Kami** [comment]
@wyjuly Any update on this - did that setting work for you? :)

**Comment by wyjuly** [comment]
@Kami Thanks Kami, on the way. Will upgrade to 2.6 and test with both service_token_ttl and token_ttl set in st2.conf and update the result here.

**Comment by wyjuly** [comment]
@Kami  I've completed testing.
After upgraded from 2.4 to 2.6 and add service_token_ttl in /etc/st2/st2.conf, stop and start service, the flow   continue running after one of the action completes after 26 hours.

So it looks the token ttl configuration works. But I'm not sure which change is the key factor: upgrade to 2.6 or add service_token_ttl.

If it succeeded again because of the new parameter maybe we should put it into the DOC to let more users know that. Thanks.

**Comment by bigmstone** [comment]
Jeez - my memory isn't what it used to be. I didn't know I had a hand in this fix...but it looks like you were seeing the results of #3523 which was resolved in #3524. Not certain which release this got put in but I would have assumed 2.4 would have worked for you. Either way glad it is working now. Feel free to re-open if you see anything else going on that's related to this.
