### ISSUE TITLE
Rerun action in version 2.6 doesn't work

### ISSUE THREAD

**Issue by wyjuly** [StackStorm/st2#4018]
Hi there,

We've upgraded our stackstorm from 2.4 to 2.6.

After that I found that re-run an action doesn't work if I change the parameter.

After you change one of the parameter and rerun the action, it still runs with the old parameter.

**Comment by bigmstone** [comment]
@wyjuly Thanks for the report. Is this from CLI, Web Interface or both?

**Comment by wyjuly** [comment]
@bigmstone I just tried click RERUN button in web interface.
Sorry I should create this issue in st2web.

**Comment by lakshmi-kannan** [comment]
Moved to st2web https://github.com/StackStorm/st2web/issues/515
