### ISSUE TITLE
Auto scroll in 2.6

### ISSUE THREAD

**Issue by wyjuly** [StackStorm/st2#4019]
Hi all,

I found that in version 2.6 the webUI will try to scroll down/up to the selected flow.

Suppose there are 40 flows in the page and I click the first one, then I want to choose the 35th. the auto-scroll will stop me to do that. I have to scroll down and click one of the flow/action to prevent the page scroll up to the first flow.  then scroll down a bit and click another flow/action, finally go to the 35th one.

Is that a new feature?

**Comment by enykeev** [comment]
We have a similar problem reported in https://github.com/StackStorm/st2web/issues/500. If it sounds alike, we already have a fix that is going live in a few days time.

**Comment by bigmstone** [comment]
Thanks for the report, feel free to create a new issue on StackStorm/st2web if you think the resolution doesn't fit your issue.

**Comment by wyjuly** [comment]
Thanks @enykeev & @bigmstone . Yes https://github.com/StackStorm/st2web/issues/500 is just what I saw. So it's ok to close this one and I'll track st2web#500.
