### ISSUE TITLE
Flow is always 'pausing' after creating inquiry with core.ask

### ISSUE THREAD

**Issue by wyjuly** [StackStorm/st2#4028]
Hi all,

I have a flow with core.ask in it. After that step the flow status will be changed to pausing, then paused. At that time I can respond to the inquiry and the flow status will be changed to running.

But I often found that the flow status is always pausing after the inquiry is created. So I cannot respond to the inquiry since that will delete it and the flow cannot be resumed.

is there any way that I can manually change the flow status to paused? From cli or update mistral/stackstorm database? Thanks a lot.

**Comment by bigmstone** [comment]
@wyjuly is the workflow stuck in pausing or just taking a bit of time to make it into the paused state? As far as I can remember we don't have a tool for manipulating state directly. The only way to do that is through modifying its status via mongo.

This isn't exactly a pleasant UX though and warrants some thought and enhancement.

**Comment by wyjuly** [comment]
Also sometimes after I respond to an inquiry, the flow status was changed to 'Failed' and the output of the sub-flow shows: 

```
{
  "traceback": "  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py\", line 210, in _do_resume
    (status, result, context) = runner.resume()
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 206, in call
    return attempt.get(self._wrap_exception)
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py\", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File \"/opt/stackstorm/runners/mistral_v2/mistral_v2/mistral_v2.py\", line 444, in resume
    self.context.get('user', None)
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/services/action.py\", line 308, in request_resume
    % liveaction.id
",
  "error": "Unable to resume liveaction \"5a9fe1f2a9dc5b169b3f706f\" because it is not in a paused state."
}
```

But I'm sure that before I respond the inquiry I checked the main flow's status with:
`st2 execution list --status paused`

And the main flow's ID is in the list.

**Comment by wyjuly** [comment]
@bigmstone I tested many flows with inquiry. Yes the status changed from pausing to paused will take a bit time. But some of them will not be changed after more than 30 minutes And there are other flows running at that time so that shouldn't caused by heavy load.

I'm ok to change its status from mongo since I want to resume the flow, not re-run it.
And obviously change it to paused from cli is not permitted since it told me that:

```
st2 execution pause 5a9fd73da9dc5b169b3f6e7d
ERROR: 404 Client Error: Not Found
MESSAGE: Unable to identify resource with id "['5a9fd73da9dc5b169b3f6e7d']". for url: http://127.0.0.1:9101/v1/executions/['5a9fd73da9dc5b169b3f6e7d']

```

But the flow exists. Maybe the CLI wants to find a flow with status is running to pause, right?

**Comment by bigmstone** [comment]
@wyjuly Can you provide the workflow execution output `st2 exectuion get <execution_id>` with the execution that is still in the `pausing` state. It's also helpful if you can share the workflow itself so we can see what exactly you're using and how. I'd suggest sharing via [gist](gist.github.com) and posting the links here. That will make it easier for us to read through them.

**Comment by bigmstone** [comment]
@wyjuly I'm going to close this issue for now. Please re-open if the issue persists and provide the above requested information.
