### ISSUE TITLE
api.stackstorm.com is unsync with openapi.yaml (CD)

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4051]
In the [openapi spec](https://github.com/StackStorm/st2/blob/master/st2common/st2common/openapi.yaml) there are several instances of a block called `x-parameters`. These are "vendor extensions" according the OpenAPI spec https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#patterned-objects . 

The API documentation generator is leaving these out, so there's no way to know they exist without looking directly at the spec.

Example:
- API docs for `POST /auth/v1/tokens` https://api.stackstorm.com/auth/v1/tokens/#/token_controller.post
- Spec for `POST /auth/v1/tokens` https://github.com/StackStorm/st2/blob/master/st2common/st2common/openapi.yaml#L3991-L4020
- You can see that the parameters `remote_addr` and `remote_user` are missing from the docus, even though they're in the spec.

**Comment by armab** [comment]
Confirming there is unsync between https://api.stackstorm.com/ and [`openapi.yaml`](https://github.com/StackStorm/st2/blob/master/st2common/st2common/openapi.yaml).

After looking further, last update for https://api.stackstorm.com is `Nov 3, 2017`, according to https://github.com/StackStorm/st2/pull/4046#issuecomment-374579734.

----

We'll need to add re-generation task for api.stackstorm.com in CircleCI if openapi.yaml content was changed (on `master` build, similar to [`deploy` job](https://github.com/StackStorm/st2/blob/master/circle.yml#L257-L265)).

**Comment by lakshmi-kannan** [comment]
@enykeev and I had a chat and we decided on the following:

1. We'll ship updated documentation on every release. Having API documentation from master is a stretch goal. We can use api-staging.stackstorm.com for this if needed. 

In terms of how we are going to automate this:

1. We are going to add a task in st2cd release automation to invoke a circle build on https://github.com/StackStorm/st2apidocs 

There are some minor improvements we decided to do. I'll link PRs here when I make those changes.

**Comment by lakshmi-kannan** [comment]
Also, I created api-unstable.stackstorm.com to show master API documentation. When DNS propagates, this should work.

**Comment by armab** [comment]
@lakshmi-kannan For `api-unstable` can you please include the Terraform change in: https://github.com/StackStorm/ops-infra/blob/master/terraform/api.stackstorm.com.tf ?

Considering there is already infra-as-code for `api.stackstorm.com`, there would be no good excuse to skip the `api-unstable` ;)

**Comment by lakshmi-kannan** [comment]
@armab Didn't realize we had a tf for this :). Would have made my life easier instead of figuring out AWS UI manually. Let me add it.

**Comment by armab** [comment]
https://github.com/StackStorm/st2apidocs is responsible for the https://api.stackstorm.com/ generation.

Looks like the build in https://github.com/StackStorm/st2apidocs is still broken that results in CD failure to generate and upload the documentation. See https://github.com/StackStorm/st2apidocs/issues/9 for more info.

**Comment by armab** [comment]
Thanks to @Sheshagiri work https://github.com/StackStorm/st2apidocs/issues/9 https://github.com/StackStorm/st2apidocs/pull/11 https://github.com/StackStorm/st2apidocgen/pull/9, API docs generation and deployments are now working.

- stable API doc, based on current `v3.2.0` branch: https://api.stackstorm.com/
- latest evelopment API doc, based on `master` branch: https://api-unstable.stackstorm.com/
