### ISSUE TITLE
Cannot get decrypted value via sensor_service

### ISSUE THREAD

**Issue by mxmader** [StackStorm/st2#4057]
According to:
https://docs.stackstorm.com/sensors.html

I am supposed to be able to get the decrypted value of a key in the st2kv as follows:
`kvp = self.sensor_service.get_value('cmdb.api_password', decrypt=True)`

Yet, the `decrypt` argument is not implemented in `st2reactor.st2reactor.container.sensor_wrapper.SensorService.get_value` in the `master`, `v2.6`, and `v2.2` branches (I'm using a v2.2.1 fork for reference).

Thus, I've resorted to accessing the datastore service directly, like:
`kvp = self.sensor_service._datastore_service.get_value('cmdb.api_password', decrypt=True)`

**Comment by LindsayHill** [comment]
Resolved by #4058
