### ISSUE TITLE
Multiple criteria matches in a rule

### ISSUE THREAD

**Issue by suganyamuthusamy** [StackStorm/st2#4086]
Hi,
As per the documentation, i can understand single trigger can have single rule configured to execute a workflow/action.
We wanted to configure multiple criteria matches to run multiple workflows. 
For example,
Trigger A has a trigger.subject as "abc". Rule contains the criteria match for trigger.subject='abc' to execute action A.
If the same trigger A has trigger.subject = "xyz", execute action B. 
Can you please explain how can we achieve this in stackstorm.

**Comment by LindsayHill** [comment]
Create two different rules. First rule matches on trigger.subject == abc, and runs actions A.
Second rule matches on trigger.subject == xyz, and runs action B.
