### ISSUE TITLE
Responding to inquiry doesn't resume the flow

### ISSUE THREAD

**Issue by wyjuly** [StackStorm/st2#4092]
Hi there,

Have you ever seen this before: 
I have a flow like
```
main_flow:
  subflow_1:
    subflow_1_2:
      subflow_1_2_3:
        inquiry
```
The inquiry is created, and the status of main_flow, subflow_1, subflow_1_2 and subflow_1_2_3 have been changed to paused, it's great.
But after responding to the inquiry successfully, only main_flow's status is changed to 'running', subflow_1, subflow_1_2 and subflow_1_2_3 are still in 'paused' status.

I cannot do anything but updating the mongodb, changed the status to  resuming and succeeded for subflow_1, subflow_1_2 and subflow_1_2_3, but the main_flow still cannot be resumed, it always show running and won't move forward.

Any suggestion for such scenario? Thanks a lot.
Jason

**Comment by deepa2603** [comment]
I am also facing the same issue in mistral workflow. 

In mistral:

Action 1:
  on-failure: inquiry
Inquiry:
   on-success: A
A:
  echo a

After getting the response, inquiry is not resuming the workflow.

**Comment by LindsayHill** [comment]
See #4309
