### ISSUE TITLE
Stackstorm 2.7-1 remote shell script issue

### ISSUE THREAD

**Issue by sibirajal** [StackStorm/st2#4095]
I’ve upgraded our Stackstorm automation servers to latest St2-2.7-1 version. After the upgrade noticed below error while executing the remote shell script action.

```
result:
error: 'Failed to import runner module remote_script_runner.remote_script_runner

[Errno 2] No such file or directory'
traceback: " File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/worker.py”, line 160, in _run_action
result = self.container.dispatch(liveaction_db)
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py”, line 63, in dispatch
runner = self._get_runner(runnertype_db, action_db, liveaction_db)
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py”, line 343, in _get_runner
config=config)
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/base.py”, line 81, in get_runner
raise ActionRunnerCreateError(’%s%s’ % (msg, str(e)))
```

**Comment by sibirajal** [comment]
Here is the remote_runner which we have in our ST2 server. 

$ ls -lht /opt/stackstorm/runners/remote_runner/remote_runner/
total 24K
-rwxr-xr-x 1 st2 root  803 Apr 18 21:22 __init__.py
-rwxr-xr-x 1 st2 root 3.6K Apr 18 21:22 remote_command_runner.py
-rwxr-xr-x 1 st2 root 7.8K Apr 18 21:22 remote_script_runner.py
-rwxr-xr-x 1 st2 root 5.4K Apr 18 21:22 runner.yaml

$ls -lht /opt/stackstorm/runners/remote_script_runner/remote_script_runner
total 8.0K
-rw-r--r-- 1 root st2packs 6.4K Feb  2 07:13 remote_script_runner.pyc

**Comment by sibirajal** [comment]
Failure log

2018-04-26 09:13:39,481 54935056 INFO loader [-] Loading runner module from "/opt/stackstorm/runners/remote_script_runner/remote_script_runner.py".
2018-04-26 09:13:39,481 54935056 ERROR base [-] Failed to import runner module remote_script_runner.remote_script_runner
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/base.py", line 76, in get_runner
    module = register_runner(package_name=package_name, module_name=module_name)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/loader.py", line 218, in register_runner
    RUNNER_MODULES_CACHE[package_name][module_name] = imp.load_source(load_name, module_path)
IOError: [Errno 2] No such file or directory

**Comment by armab** [comment]
According to Slack, `st2ctl reload --register-all` helped.
Thanks @nmaludy for debugging it :+1:
