### ISSUE TITLE
st2auth takes 2x longer to start in 2.7.x

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4100]
**Note** This is only a real problem on CentOS 6 and only manifests in Travis

## Background

I've been seeing CI failures in puppet-st2 only for the CentOS 6 tests. Every failure reported the `st2auth` service failing to start. 

Example: 
- Full build: https://travis-ci.org/StackStorm/puppet-st2/builds/372527703
- CentOS 6 job: https://travis-ci.org/StackStorm/puppet-st2/jobs/372527704#L2070-L2071

In the job logs you can see:

```
       Error: Could not start Service[st2auth]: Execution of '/sbin/service st2auth start' returned 1: Starting st2auth: [FAILED]
       Error: /Stage[main]/St2::Profile::Server/Service[st2auth]/ensure: change from stopped to running failed: Could not start Service[st2auth]: Execution of '/sbin/service st2auth start' returned 1: Starting st2auth: [FAILED]
```

## Investigation

I went through many layers of debugging trying to capture stderr/stdout of the st2auth process to see what the error was. Every attempt resulted in no error messages being printed that pointed me in the right direction (thinking that Puppet wasn't configuring something properly).

In my digging i ended up editing `/etc/init.d/st2auth` https://github.com/StackStorm/st2-packages/blob/master/packages/st2/rpm/st2auth.init 

I added tons of debugging statements into this file and found out that the `daemon` call was starting up fine (https://github.com/StackStorm/st2-packages/blob/master/packages/st2/rpm/st2auth.init#L47-L48). However the `waitforpid` call was returning `1` https://github.com/StackStorm/st2-packages/blob/master/packages/st2/rpm/st2auth.init#L49 .

Digging in further i realized that this `waitforpid` function is defined in `/opt/stackstorm/st2/share/sysvinit/functions` here: https://github.com/StackStorm/st2-packages/blob/master/packages/st2/conf/rhel-functions-sysvinit#L195-L241

I added some more debugging statements into the `waitforpid` function and saw that the service was never coming up and the loop was terminating (job here: https://travis-ci.org/StackStorm/puppet-st2/jobs/373574533#L5792-L5822)

I then noticed this statement `local pid= pid_file= base= timeout="3.0"` https://github.com/StackStorm/st2-packages/blob/master/packages/st2/conf/rhel-functions-sysvinit#L196

My next step was to change the timeout to `10.0` and rebuild. This build succeeded. Looking at the logs you can see it took about 4 seconds for the `st2auth` service to start (each line is 0.1 seconds).  https://travis-ci.org/StackStorm/puppet-st2/jobs/373578635#L5818-L5859

I then tried to reproduce on `2.6.0` and could not, the service started in ~2 seconds (https://travis-ci.org/StackStorm/puppet-st2/jobs/373914093#L5830-L5837)

## Problem

It boils down to `st2auth` having a much longer startup time in `2.7.x` (~4 seconds) as opposed to `2.6.0` (~2 seconds). This extra startup time caused the `waitforpid` timeout to be triggered, resulting in a failure to start the service.

Because this `waitforpid` function is only used in CentOS 6, that is the only OS that is affected.

### Option 1 - Increase timeout

Increase the timeout in the `waitforpid` function to a larger number. This would solve the immediate problem, however if the startup time grows in the future this may need to be continually adjusted.

### Option 2 - Debug st2auth startup time

We could try and figure out why the `st2auth` service has a longer startup time in `2.7.x` and try to fix it. We would need to add some performance tests against this so that there are not regressions in the future. Ideally the testing limit should be the same as whatever is configured in the `waitforpid` function

### Option 3 - Other ideas

I'm open to other options/ideas on how to fix this.

**Comment by armab** [comment]
The №1 candidate here is updated `pip` dependencies (happened in `v2.7.0`) which may cause `st2auth` startup slowdown: https://github.com/StackStorm/st2/pull/4049

Something like that happened many times before and we're guilty here by not having any Performance Testing in our CI so we can't track such regressions.

Another option is a regression in StackStorm code itself, happened during the `v2.7` development.

**Comment by Kami** [comment]
Thanks for reporting this.

This could be related to eventlet upgrade or also to some other system change. The version we now use (http://eventlet.net/doc/changelog.html), always comes bundled with `dnspython` which is used for green / async DNS resolution.

It's likely that some DNS resolution is failing / taking a very long time (could have something to do with IPv6 and / or localhost and /etc/hosts).

One thing which is weird though is that it only affects st2auth, but not other services.

**Comment by Kami** [comment]
I'm not totally 100% sure about the root cause so I can't recommend the work-around yet.

I would check st2.conf config settings to see if some setting uses a hostname (e.g. localhost) and then play around with using an IPv4 address directly to see if that changes things.

**Comment by armab** [comment]
There are indeed `localhost` occurrences at: https://github.com/StackStorm/puppet-st2/blob/master/files/etc/st2/st2.conf.erb
good to have ideas to check :+1:

**Comment by nmaludy** [comment]
@armab that file isn't currently used and is slated for cleanup

**Comment by nmaludy** [comment]
There was one reference to `localhost` here: https://github.com/StackStorm/puppet-st2/blob/master/manifests/init.pp#L154

I tried changing this to `127.0.0.1` and the startup time still took longer than 3 seconds.

**Comment by Kami** [comment]
Digging in some more - turns out more libraries we use rely on `pkg_resources` (flex, kombu, etc.) and sadly I don't think there is any good way (which wouldn't require us to maintain fork or awful hacks / workarounds) to avoid that issue :/

Others also came to similar conclusions in https://github.com/pypa/setuptools/issues/510#issuecomment-368125053.

**Comment by nmaludy** [comment]
@armab thoughts on increasing the timeout for RHEL 6 startup to work around this for now?

**Comment by armab** [comment]
Thanks @Kami , that looks like a good research and reasoning.

If you say we can't fix it in st2, - the only option to deal with the consequences is to lift the st2 services startup timeouts in `st2-packages` as @nmaludy suggests.
But yeah, it's all horrible :disappointed:

**Comment by armab** [comment]
There are `st2 v2.7.2` in plans.
We'll need `st2-packages` fix with changed EL6 service startup timeout to be included in that patch version.

**Comment by nmaludy** [comment]
@armab I just submitted a PR in `st2-packages`: https://github.com/StackStorm/st2-packages/pull/555
