### ISSUE TITLE
Incorporate Metrics Collection Across ST2

### ISSUE THREAD

**Issue by bigmstone** [StackStorm/st2#4102]
Now that the metrics framework has been established it needs to be implemented across ST2.

Initial scope:
* Action execution total time by `st2.{pack}.{action}` name
* Number of action executions by `st2.{pack}.{action}` name
* Action execution total time in a specific state by `st2.{pack}.{action}.{state}` name
* Number of action executions in a specific state by `st2.{pack}.{action}.{state}` name
* Rule dispatch count by `st2.{pack}.{rule}` name
* Trigger count by `st2.{pack}.{trigger}` name
* Aggregate counts for the above I.E.: Total number of executions across all actions

**Comment by nmaludy** [comment]
+1
