### ISSUE TITLE
Workflow issue - "Failed to find action [action_name=%s]\"

### ISSUE THREAD

**Issue by sumeetisp** [StackStorm/st2#4107]
Following is my scenario,
I have a master (lets call it x) workflow which will invoke another workflow y
At the very beginning, when master workflow x is executed it fails to find the y workflow.
But when i execute the y workflow first and then the master workflow, it executes successfully.

Changes that is see in postgres table mistral,
1) At the very beginning, the table has no record of workflow y but when it is executed separately we see an record for the workflow y being created.

How can we get this resolved?

**Comment by LindsayHill** [comment]
What is a minimal example to reproduce this, and the full error output?

**Comment by sumeetisp** [comment]
`{
      "state_info": "Failed to run task [error=Failed to find workflow [name=hivecenter_linux.run_cmd_ssh] [namespace=], wf=hivecenter_framework.invoke_item, task=hivecenter_execute_workflow]:\nTraceback (most recent call last):\n  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/task_handler.py\", line 63, in run_task\n    task.run()\n  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py\", line 158, in wrapper\n    result = f(*args, **kwargs)\n  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py\", line 374, in run\n    self._run_new()\n  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py\", line 158, in wrapper\n    result = f(*args, **kwargs)\n  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py\", line 403, in _run_new\n    self._schedule_actions()\n  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py\", line 481, in _schedule_actions\n    timeout=self._get_timeout()\n  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py\", line 158, in wrapper\n    result = f(*args, **kwargs)\n  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/actions.py\", line 538, in schedule\n    wf_spec_name=self.wf_name\n  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/utils.py\", line 91, in resolve_workflow_definition\n    (wf_spec_name, namespace)\nWorkflowException: Failed to find workflow [name=hivecenter_linux.run_cmd_ssh] [namespace=]\n",}
`

**Comment by sumeetisp** [comment]
I am not sure if this can be replicated because this issue we are seeing in containerized environment.

**Comment by sumeetisp** [comment]
#4108 Even this is same issue. Has more details.

**Comment by LindsayHill** [comment]
> I am not sure if this can be replicated because this issue we are seeing in containerized environment.
So this does not happen if this is in a non-containerized environment?

**Comment by LindsayHill** [comment]
> #4108 Even this is same issue. Has more details.

OK, if #4108 has details, we will track it there. Without details to replicate this, it's very hard to figure out what's going on.
