### ISSUE TITLE
st2 auth returns BadStatusLine("''",) for 401 error

### ISSUE THREAD

**Issue by mbayha** [StackStorm/st2#4131]
##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION

```
st2 2.7.1, on Python 2.7
```

##### OS / ENVIRONMENT / INSTALL METHOD

running on CentOS 7.4 VMWare VM

Leveraged the installation instructions located at https://ewc-docs.extremenetworks.com/install/rhel7.html#minimal-installation and used the defaults

##### SUMMARY

Using the EWC plugin for ldap, if "chase_referrals": true is set in the backend_kwargs, a 401 results in the message BadStatusLine("''",) on the cli:

$ st2 auth mbayha1123
Password:
ERROR: ('Connection aborted.', BadStatusLine("''",))

Running st2 auth for the same user but specifying --debug shows that the actually message returned is a 401:

$ st2 --debug auth mbayha1123
Password:
# -------- begin 63897296 request ----------
curl -X POST -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.14.2' -H  'content-type: application/json' -H  'Content-Length: 2' -H  'Authorization: Basic bWJheWhhMTEyMzphc2RmYWRzZg==' --data-binary '{}' http://127.0.0.1:9100/tokens
# -------- begin 63897296 response ----------
{
    "faultstring": "Invalid or missing credentials"
}
# -------- end 63897296 response ------------

ERROR: 401 Client Error: Unauthorized
MESSAGE: Invalid or missing credentials for url: http://127.0.0.1:9100/tokens

CLI settings:
----------------
Config file path: /home/mbayha/.st2/config
Client settings:
----------------
ST2_BASE_URL: http://127.0.0.1
ST2_AUTH_URL: http://127.0.0.1:9100
ST2_API_URL: http://127.0.0.1:9101/v1
ST2_STREAM_URL: http://127.0.0.1:9102/v1
ST2_AUTH_TOKEN: None

Proxy settings:
---------------
HTTP_PROXY:
HTTPS_PROXY:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/shell.py", line 343, in run
    func(args)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/commands/auth.py", line 72, in run_and_print
    instance = self.run(args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/commands/auth.py", line 69, in run
    return self.manager.create(instance, auth=(args.username, args.password), **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 40, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 306, in create
    self.handle_error(response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 166, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: Unauthorized
MESSAGE: Invalid or missing credentials for url: http://127.0.0.1:9100/tokens

##### STEPS TO REPRODUCE

Use the following auth sections, but with valid CNs and password
     [auth]
     host = 127.0.0.1
     port = 9100
     use_ssl = False
     debug = True
     enable = True
     logging = /etc/st2/logging.auth.conf

     mode = standalone

     # Note: Settings below are only used in "standalone" mode
     backend = ldap
     backend_kwargs = {"bind_dn": "CN=[[REDACTED]],OU=User Policy 0,OU=All Users,DC=[[REDACTED]],DC=com", "bind_password": "[[REDACTED]]", "base_ou": "DC=[[REDACTED]],DC=com", "group_dns": ["CN=[[REDACTED]],OU=Security Groups,DC=[[REDACTED]],DC=com"], "host": "[[REDACTED]]", "port": "636", "use_ssl": true, "chase_referrals": true}

     # Base URL to the API endpoint excluding the version (e.g. http://myhost.net:9101/)
     api_url =

run st2 auth <username> using a combination that should return a 401 error

```yaml

```

##### EXPECTED RESULTS

should receive the following message at the CLI:

ERROR: 401 Client Error: Unauthorized
MESSAGE: Invalid or missing credentials for url: http://127.0.0.1:9100/tokens

##### ACTUAL RESULTS

received the following message at the CLI:

ERROR: ('Connection aborted.', BadStatusLine("''",))

```

```

**Comment by mbayha** [comment]
Yeah, looks like this may have been the result of a config issue. It no longer provides the results for an invalid user that it was. It now reports a 401 as expected.

**Comment by Topher33** [comment]
@mbayha Seeing the same message... what was the solve in the config? 
received the following message at the CLI:

ERROR: ('Connection aborted.', BadStatusLine("''",))
