### ISSUE TITLE
pip version mismatch in packs virtual environment 

### ISSUE THREAD

**Issue by guptasakshi01** [StackStorm/st2#4136]
##### ISSUE TYPE
 - Other

##### STACKSTORM VERSION
2.7.2

##### OS / ENVIRONMENT / INSTALL METHOD
ubuntu

##### SUMMARY
We have upgraded stacktstorm to 2.7.2, we are able to see different versions of pip in the virtual env of packs.
Examples
1. in pack test1 pip version is pip 9.0.1
requirements.txt for test1 pack contains following
azure-graphrbac==0.40.0

2. in pack test2 pip version is pip 10.0.1
requirements.txt for test2 pack contains following
requests==2.18.4
reportlab==3.4.0
urllib3==1.22

Please clarify this.
Is the version of pip within virtual environment dependent on the python modules mentioned in requirements.txt of pack ?

**Comment by Kami** [comment]
@guptasakshi01 Please confirm that the above^ works for you.

**Comment by guptasakshi01** [comment]
@Kami  
I have deleted the virtual env for pack test2 and registered again, but still i am getting pip version as 10.0.1

**Comment by LindsayHill** [comment]
@guptasakshi01 what were the exact commands that you ran?

**Comment by guptasakshi01** [comment]
After Removing test2 pack and installing it again i am getting error:-

+--------------------------+---------------------+---------------+----------------+-------------------------------+
| id                       | status              | task          | action         | start_timestamp               |
+--------------------------+---------------------+---------------+----------------+-------------------------------+
| 5b0bb63c7052cf05b2ca4166 | failed (1s elapsed) | download pack | packs.download | Mon, 28 May 2018 07:56:44 UTC |
+--------------------------+---------------------+---------------+----------------+-------------------------------+

**Comment by LindsayHill** [comment]
Is there anything useful in the logs? For example, the st2api.log, or the st2actionrunner logs?

What if you look at the full output for that execution above - what does it tell you?

**Comment by LindsayHill** [comment]
What does `st2 execution get 5b0bb63c7052cf05b2ca4166` tell you? There should have been some more output when you ran the command. If it failed at the download step, it could be something else going on - e.g. your proxy setup, GitHub outage, etc. Look at the details and logs and it should tell you.

**Comment by guptasakshi01** [comment]
@LindsayHill  Result of st2 execution get 5b0bb63c7052cf05b2ca4166

id: 5b0bb63c7052cf05b2ca4166
status: failed (1s elapsed)
parameters:
  force: false
  packs:
  - test2
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 320, in <module>
    obj.run()
  File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 179, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 88, in run
    pack_url, pack_version = self._get_repo_url(pack, proxy_config=self.proxy_config)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 312, in _get_repo_url
    raise Exception('No record of the "%s" pack in the index.' % name_or_url)
Exception: No record of the "test2" pack in the index.
"
  stdout: ''

**Comment by LindsayHill** [comment]
test2 is not a valid pack on exchange.stackstorm.org. If your pack is hosted on an internal index, you should check that. 

If your pack is not listed on exchange.stackstorm.org or your internal index, you need to install it by giving a path to the git repo, eg `st2 pack install https://my.gitlab/org/test2`

Where is the pack `test2` located?

**Comment by LindsayHill** [comment]
Closing due to no response
