### ISSUE TITLE
How to change the limitation of flow's output? 1024KB may be not enough.

### ISSUE THREAD

**Issue by wyjuly** [StackStorm/st2#4163]
##### ISSUE TYPE

 - Bug Report

##### STACKSTORM VERSION

```
st2 2.7.2, on Python 2.7
```

##### OS / ENVIRONMENT / INSTALL METHOD

RHEL 7.2

##### SUMMARY

I have a big flow with many subflows. Each subflow has its own published items in output.
Finally I got below error, it shows size of 'output' but I think it should be the total json response of the subflow since its output is one UUID, no more than 50 characters.

Failed to complete action [error=Size of \\'output\\' is 1736KB which exceeds the limit of 1024KB, action=st2.action, task=test_sub_flow_2]

The question is: Do we have any configuration item to be changed and enlarge the max flow output size? 1024KB is the default max flow's result size right? How can we change it? 
Thanks.
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by LindsayHill** [comment]
See https://forum.stackstorm.com/t/allowing-large-results-in-mistral-workflows/139
