### ISSUE TITLE
How to find the missed mongo password after upgrading from 2.4.0 to 2.7.2

### ISSUE THREAD

**Issue by wyjuly** [StackStorm/st2#4175]
##### SUMMARY

After upgrading from 2.4.0 to 2.7.2, the mongo db cannot be accessed from cli.
In 2.4.0 the /etc/st2/st2.conf looks like 

> [database]
> username = stackstorm

And we can access mongo with cli:
`mongo --port 27017 -u "stackstorm" `

After upgrading the stackstorm works well including its cli, api and web UI.
But the db cannot be accessed from db cli:

```
[root@test]# mongo --port 27017 -u "stackstorm"
MongoDB shell version v3.4.7
connecting to: mongodb://127.0.0.1:27017/
MongoDB server version: 3.4.7
2018-06-12T08:07:26.574+0000 E QUERY    [thread1] Error: Missing expected field "pwd" :
DB.prototype._authOrThrow@src/mongo/shell/db.js:1461:20
@(auth):5:1
@(auth):1:2
exception: login failed
```

I'm curious how stackstorm connect to mongodb then? I don't find the db password from st2.conf.

##### ISSUE TYPE
 - Other

##### STACKSTORM VERSION
Paste the output of `st2 --version`:
From st2 2.4.0, on Python 2.7
to 
st2 2.7.2, on Python 2.7

##### STEPS TO REPRODUCE

```yaml

```

**Comment by wyjuly** [comment]
Yes I found that before the upgrade process the mongod service is stopped so tried twice.
Sorry that I found it could be connected with 
`mongo`

Thanks @Kami  for your kindly support. Please close this issue.

**Comment by Kami** [comment]
Great to hear that you got it resolved :+1:
