### ISSUE TITLE
Proposal: Deprecate CloudSlang

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2#4199]
### SUMMARY

Begin deprecating CloudSlang runner

### ISSUE TYPE
 - Other

The CloudSlang runner has always been marked "Experimental". It has seen no recent updates, and very little traction from users. Now that Orchestra has been released, we need to begin consolidating workflow engine choices.

We should begin the CloudSlang deprecation in 2.9, with formal removal in 3.1.

Tasks:

- [x] Mark CloudSlang as DEPRECATED in [Changelog](https://github.com/StackStorm/st2/pull/4261)
- [x] Update documentation to show CloudSlang as [deprecated](https://github.com/StackStorm/st2docs/pull/767)
- [ ] Create WARNING logs on pack registration if any packs are using CloudSlang

In 3.1, change WARNING logs to FATAL errors if packs use CloudSlang runner, and remove remaining documentation references.

**Comment by armab** [comment]
+ :100:
I don't remember a single question during the last 12 months about it and TBH I even forgot that we have such runner at all.

**Comment by LindsayHill** [comment]
Thinking a little more about it, I think what we'll do is stop shipping this runner as part of core, but leave the code available somewhere for people who wish to use it. Makes it clear that there's no ongoing testing/development of this by the ST2 team.

**Comment by m4dcoder** [comment]
@LindsayHill +1, when we make runner pluggable w/ stevedore. This means when we are ready to deprecate Mistral, we do the same for related codes.

**Comment by LindsayHill** [comment]
Has been removed
