### ISSUE TITLE
Error when creating rule using the trigger type core.st2.CronTimer 

### ISSUE THREAD

**Issue by m4dcoder** [StackStorm/st2#4214]
##### SUMMARY
Error when creating rule using the trigger type core.st2.CronTimer 

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
st2 2.8dev, on Python 2.7.12

##### OS / ENVIRONMENT / INSTALL METHOD
Development environment on Xenial, running from git clone, using ./tools/launchdev.sh to run st2

##### STEPS TO REPRODUCE
For the following timer rule...
```yaml
---
name: cron_daily
pack: sandbox
description: Test timer rule
enabled: false

trigger:
  type: core.st2.CronTimer
  parameters:
    timezone: US/Pacific
    hour: 18
    minute: 0
    second: 0

action:
  ref: core.local
  parameters:
    cmd: date
```

On running ./tools/launchdev.sh --startclean, I get the following error on registering rules...
```
2018-06-28 20:06:19,778 ERROR [-] Failed to create rule cron_daily.
Traceback (most recent call last):
  File "/home/ubuntu/projects/stackstorm/st2/st2common/st2common/bootstrap/rulesregistrar.py", line 155, in _register_rules_from_pack
    increment_trigger_ref_count(rule_api=rule_api)
  File "/home/ubuntu/projects/stackstorm/st2/st2common/st2common/services/triggers.py", line 283, in increment_trigger_ref_count
    Trigger.update(trigger_db, inc__ref_count=1)
  File "/home/ubuntu/projects/stackstorm/st2/st2common/st2common/persistence/base.py", line 219, in update
    cls._get_impl().update(model_object, **kwargs)
  File "/home/ubuntu/projects/stackstorm/st2/st2common/st2common/models/db/__init__.py", line 423, in update
    return instance.update(**kwargs)
AttributeError: 'NoneType' object has no attribute 'update'
```

However, on rule list, the rule is registered.
```
$ st2 rule list
+--------------------------+---------+-------------------------+---------+
| ref                      | pack    | description             | enabled |
+--------------------------+---------+-------------------------+---------+
| sandbox.cron_daily       | sandbox | Test timer rule         | False   |
| sandbox.cron_on_interval | sandbox | Test timer rule         | False   |
+--------------------------+---------+-------------------------+---------+
```

##### EXPECTED RESULTS
There should be no error on registering rules. Users should not have to include and fill in all optional parameters.

##### ACTUAL RESULTS
I had to fill in all the parameters for the core.st2.CronTimer in order to not get the error. It looks like get_trigger_db_given_type_and_params is trying to find the trigger DB object by the list of parameters. In this case, some parameters are optional and shouldn't have to be included.

**Comment by m4dcoder** [comment]
If the rule includes all the other optional parameters but leave the value to `null`, then the rule registers without error. User should be able to skip optional parameters.

```yaml
---
name: cron_daily
pack: sandbox
description: Test timer rule
enabled: false

trigger:
  type: core.st2.CronTimer
  parameters:
    timezone: US/Pacific
    hour: 18
    minute: 0
    second: 0
    week: null
    day_of_week: null
    year: null
    month: null
    day: null

action:
  ref: core.local
  parameters:
    cmd: date
```

**Comment by heldersilverio** [comment]
It seems to me that I have the same problem. Is there any solution?

**Comment by winem** [comment]
This issue is no longer reproducable. Tested with 3.5 on U18 and U20. Defaults and optional parameters work as expected now.
