### ISSUE TITLE
Feature Idea: core.inject_trigger

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2#4231]
##### SUMMARY
I would like to inject/dispatch triggers in the middle of workflows so that rules can trigger additional workflows when those trigger points are reached. Then, custom triggers registered in a pack can serve as well known synchronization points.

##### ISSUE TYPE
 - Feature Idea

##### EXPECTED RESULTS
trigger `my_42_trigger` registered in `example` pack with the following action in a workflow to dispatch it.

```
dispatch_action_in_workflow:
  action: core.inject_trigger
  input:
    trigger: example.my_42_trigger
    parameters:
      answer_to: "{{ task('life').result.stdout }}"
      the_universe: "{{ _.and_everything }}"
```

#### EXAMPLE USE CASE
I have a data-processing workflow that gets triggered by a sensor when a new server comes online. The workflow gathers data about the server, processes it (using custom actions), and then dispatches/injects the additional triggers once each piece of data is available. This way, the sub-workflows can start as soon as the data they require is available, and the data-processing workflow can be much simpler without having to keep a centralized list of everything that should start once the data is ready.

#### IMPLEMENTATION THOUGHTS
This could be, as @nmaludy suggested in slack, an action that uses webhooks to kick off the various triggers/workflows.

If the action were in core, however, it could skip the webhook processing, and just inject the trigger. This might work something like the sensor service's dispatch method.

I looked at putting this in the `st2` pack, but the st2 client lib doesn't have the ability to kick off triggers, so it makes more sense to make this part of the `core` pack. Possible names include `core.inject_trigger` or `core.dispatch_trigger`. "dispatch" is nice because it mirrors the terminology used in sensors.

Looking at what might be useful in implementing this:
- [st2common.transport.reactor.TriggerDispatcher](https://github.com/StackStorm/st2/blob/a376219/st2common/st2common/transport/reactor.py#L75) Used by [actions API](https://github.com/StackStorm/st2/blob/6261a2a39c23b7c9e43e3dd43050b445bfd8e458/st2api/st2api/controllers/v1/actions.py) and [webhooks API](https://github.com/StackStorm/st2/blob/7c1e386f957a33cabd0142dc67440498b655503d/st2api/st2api/controllers/v1/webhooks.py)
- [st2reactor.container.utils.create_trigger_instance](https://github.com/StackStorm/st2/blob/f71f9b1/st2reactor/st2reactor/container/utils.py#L29)

**Comment by Kami** [comment]
#4259 should resolve this.

Here is also some more context and details - https://forum.stackstorm.com/t/is-there-a-way-to-trigger-event-in-workflow-like-inquiry-and-consume-it-in-rules/199 (in short, multiple people have already asked about such feature in the past).
