### ISSUE TITLE
pack yaml configuration file for secret key is not decrypted  

### ISSUE THREAD

**Issue by jinpingh** [StackStorm/st2#4240]
##### SUMMARY
st2 2.7.1, on Python 2.7

Installed a pack san and created san.ymal file under /opt/stackstorm/configs/san.yaml. Create secret key for password:

```yaml
---
firewall_ip: "10.52.204.36"
username: "admin"
password: "{{st2kv.system.fortinetkey}}"
```

When running action,  password key is not converted:
Have put debug message and run action from console. See print out:

```shell
 stdout: '############################################
    user: admin
    password: 00875FF285AAA643358FED9F78D17C0BB8E36FDE85D30DADC07B202F4B4E0BE1D5A0F42B88ADC60F405EC5E4D8EFFCA14DB1F1F178F80F3FC0
    firewall_ip: 10.52.204.36
    ############################################
```

The same setting is working on st2 version 2.6.

Key info:

```shell
root@st2-111:/var/log/st2# st2 key list
+-------------+-----------------------------+--------+-----------+--------------+------+------------------+
| name        | value                       | secret | encrypted | scope        | user | expire_timestamp |
+-------------+-----------------------------+--------+-----------+--------------+------+------------------+
| fortinetkey | 00875FF285AAA643358FED9F78D | True   | True      | st2kv.system |      |                  |
|             | 17C0BB8E36FDE85D30DADC07B20 |        |           |              |      |                  |
|             | 2F4B4E0BE1D5A0F42B88ADC60F4 |        |           |              |      |                  |
|             | 05EC5E4D8EFFCA14DB1F1F178F8 |        |           |              |      |                  |
|             | 0F3FC0                      |        |           |              |      |                  |
| xmckey      | 00875FF285C23D789CE49DE4C93 | True   | True      | st2kv.system |      |                  |
|             | 379448455455CEE812E34025EF1 |        |           |              |      |                  |
|             | 2868855326B1FA78ABFED79FB5D |        |           |              |      |                  |
|             | 71AB0AFBF4FD7F735CC30600A7A |        |           |              |      |                  |
|             | DA8C87                      |        |           |              |      |                  |
+-------------+-----------------------------+--------+-----------+--------------+------+------------------+
```

##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report

##### STACKSTORM VERSION
`st2 2.7.1, on Python 2.7`

##### OS / ENVIRONMENT / INSTALL METHOD
XMC/master OVA

##### STEPS TO REPRODUCE
Run a action to involve parse pack configuration file under /opt/stackstorm/configs with secret key.

##### EXPECTED RESULTS

```shell
 stdout: '############################################
    user: admin
    password: admin123
    firewall_ip: 10.52.204.36
    ############################################
```

**Comment by nmaludy** [comment]
can you please post your pack's config.schem.yamk?

**Comment by jinpingh** [comment]
Going to create config.schema.yaml in case user want to configure firewall later.
it is tested on st2 2.6 and is working, but not 2.7.

**Comment by LindsayHill** [comment]
@jinpingh Looking at your example code above, that's just for writing out the `san.yaml` - you should still have an unchanging ` config.schema.yaml`.

You really need to have a `config.schema.yaml` - this defines the valid schema for the `san.yaml` file, and should include `secret:true` for the parameters that may be encrypted.

Also, can you paste a snippet of how you are retrieving & using the config values in your code?

**Comment by jinpingh** [comment]
Yes, i am going to create config.schema.yaml file.
this is code for retrieving and using config values:

from st2common.runners.base_action import Action
from fortinet_policy import FortinetApi


```
class FortinetBaseAction(Action): 
    def __init__(self, config=None):
        super(FortinetBaseAction, self).__init__(config)
        self.firewall_ip = self.config['firewall_ip']
        self.username = self.config['username']
        self.password = self.config['password']
        self.fortinet = self.fortinet_init()

```

**Comment by Kami** [comment]
@jinpingh Did you figure this one out?

It also looks like an issue with missing / invalid config schema to me (missing `secret: true` attribute for password parameter in the schema).
