### ISSUE TITLE
How to use python client to execute an action, can you give a code example?

### ISSUE THREAD

**Issue by xiongxiaogang** [StackStorm/st2#4241]
How to use python client to execute an action, can you give a code example?
Executing 'st2 run ansible.playbook playbook=/home/vagrant/test/getfacts.yaml ' with cli is successful. If it is replaced with python client , how to execute it?

**Comment by armab** [comment]
The ideal place to ask such questions is https://forum.stackstorm.com/

https://forum.stackstorm.com/t/invoke-an-action-from-a-python-action-script/24/4 has a complete solution example by @nmaludy.

**Comment by xiongxiaogang** [comment]
Thanks a million, you are a lifesaver.
