### ISSUE TITLE
Password field within HTTP runner not set as secret

### ISSUE THREAD

**Issue by daniel-mckenna** [StackStorm/st2#4244]
https://github.com/StackStorm/st2/blob/543edb7777093c85179e5dddd08671c31e788560/contrib/runners/http_runner/http_runner/runner.yaml#L24-L26

Password field within HTTP runner not set as secret field leaving password recorded in plain text.

**Comment by Kami** [comment]
Thanks for reporting this, will open a fix.

**Comment by Kami** [comment]
Resolved by #4245.

Thanks again for reporting this.
