### ISSUE TITLE
"st2 pack config" should support nested config schemas which use references

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#4251]
Right now we don't support configs schemas like this one which uses references - https://github.com/StackStorm-Exchange/stackstorm-libcloud/blob/master/config.schema.yaml (this one is actually especially complex since it also uses `anyOf` in the referenced object, but that part can be ignored for now).

This will require a bit more work, since we will need to inspect all the schema properties for `$ref` and handle references accordingly.

Same story for the WebUI.

**Comment by nmaludy** [comment]
Related to this: https://github.com/StackStorm/st2/issues/3455

**Comment by Kami** [comment]
@nmaludy Thanks. Will close it as a duplicate of #3455.
