### ISSUE TITLE
EWC always defaults to mistral-v2 runner type, how to create orchestra workflow using EWC

### ISSUE THREAD

**Issue by jonathangull** [StackStorm/st2#4253]
##### SUMMARY

Going to Suite or clicking on + from Actions app to create a new workflow, the runner type always defaults to mistral-v2 and is not editable, how to create orchestra workflow using EWC?

##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report

##### STACKSTORM VERSION
root@stackstorm:/opt/stackstorm/packs/mistral# st2 --version
st2 2.8.0, on Python 2.7.12 

##### OS / ENVIRONMENT / INSTALL METHOD
step by step install on ubuntu Virtualbox running on mac 

##### STEPS TO REPRODUCE
1. go to Actions tab.
2. click on + to create a new action under defaults pack.
3. click on settings button near - Current: New workflow
4. You have option to specify name,description add parameters but you cant edit the json attribute runner_type mistral-v2 from right side. 

##### EXPECTED RESULTS
Hoping to create orchestra workflow using composer, Tried creating a test orchestra workflow by following example here - 
https://docs.stackstorm.com/orchestra/languages/orchestra.html
but EDIT is not shown clicking which takes to EWC as it happens for mistral-v2 kind of workflows.

**Comment by Kami** [comment]
Right now the WebUI (Workflow Designer) only supports Mistral workflows since Orchestra is still in preview / beta mode.

Support for Orchestra in Workflow Designer is on our roadmap for v3.0.
