### ISSUE TITLE
st2 pack install --json outputs non-json text to stdout

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4260]
##### SUMMARY

When running `st2 pack install --json xxx` there is information printed to `stdout` that is not in JSON format, causing integration with external tools that expect JSON to fail.

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
```shell
$ st2 --version
st2 2.8.1, on Python 2.7.5
```

##### OS / ENVIRONMENT / INSTALL METHOD
```
os = CentOS 7
install method = one-liner
```

##### STEPS TO REPRODUCE
```shell
$ st2 pack install --json git
```

##### EXPECTED RESULTS

Output should **only** contain JSON on `stdout` (and ideally `stderr`)

```shell
$ st2 pack install --json git
{
    "author": "StackStorm, Inc.", 
    "description": "st2 content pack containing git integrations", 
    "name": "git", 
    "version": "0.4.0"
    "content":
    {
        "rules": 1,
        "sensors": 1,
        "triggers": 0,
        "actions": 3,
        "aliases": 1
    }
}
```

##### ACTUAL RESULTS

Note the non-JSON text above the JSON output.

```shell
$ st2 pack install --json git
For the "git" pack, the following content will be registered:

rules     |  1
sensors   |  1
triggers  |  0
actions   |  3
aliases   |  0

Installation may take a while for packs with many items.
{
    "author": "StackStorm, Inc.", 
    "description": "st2 content pack containing git integrations", 
    "name": "git", 
    "version": "0.4.0"
}
```

**Comment by lakshmi-kannan** [comment]
@nmaludy Is this an actual issue meaning are you trying to tool around st2 pack install -j? Or is this just a cosmetic issue? 

I can try it make all json but I am not sure how "useful" this is?

**Comment by nmaludy** [comment]
@lakshmi-kannan I ran into this when working on Tasks for the StackStorm puppet module. Those tasks call st2 pack install -j. It's expecting JSON output so there it can returning meaningful, structured data to the caller.

Does that make sense?

**Comment by nmaludy** [comment]
Yeah , I think skipping if asking for JSON it YAML is acceptable.
