### ISSUE TITLE
execution of an action does not time out

### ISSUE THREAD

**Issue by NikosVlagoidis** [StackStorm/st2#4262]
##### SUMMARY

I have an action that is running for 5 days even if I set a timeout for 600s.

##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report

##### STACKSTORM VERSION
Paste the output of `st2 --version`:

st2 2.7.2, on Python 2.7

##### OS / ENVIRONMENT / INSTALL METHOD

Docker

##### STEPS TO REPRODUCE

I have an action that runs every 5 minutes triggered by a rule with st2.IntervalTimer.
This action needs to run with concurency policy set to 1. It was stuck in running for 5 days so every other action was canceled . 

```yaml

```

##### EXPECTED RESULTS

I expected my action to time out after 600s but it stacked running for 5 days

**Comment by LindsayHill** [comment]
What is the metadata for the action that you are running? How/where are you setting the timeout?

**Comment by NikosVlagoidis** [comment]
I think st2 has a default timeout for actions at 600s? How can I check the metadata?

**Comment by LindsayHill** [comment]
Default timeout depends on the runner. 

> How can I check the metadata?

What is the name of the action or workflow you are running? What parameters are you calling it with?

Go and look for that metadata in `/opt/stackstorm/packs/<pack>/actions/<name>.yaml`. Provide that file, along with the parameters you use when calling it.

**Comment by NikosVlagoidis** [comment]
```
---
name: my_action
pack: my_pack
runner_type: "python-script"
entry_point: "my_action.py"
description: My description
enabled: true

```

This is the metadata for my action. It is called with an rule with Interval every 5 minutes.

I can see on the web ui that the default timeout is 600s. Isn't this true? Should I explicitly state it in the metadata?
