### ISSUE TITLE
Add a check to Travis which fails the build if unit tests task takes more than X minutes

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#4268]
To avoid regressions such as the one fixed in https://github.com/StackStorm/st2/pull/4264, we should add a check to Travis build which reports a big warning or fails a build of "ci-unit" tasks takes more than some reasonable amount of minutes (perhaps 10 or so).

**Comment by LindsayHill** [comment]
Addressed by https://github.com/StackStorm/st2/pull/4277
