### ISSUE TITLE
Pack config doesn't save after 2.8 update

### ISSUE THREAD

**Issue by kgliana** [StackStorm/st2#4287]
##### SUMMARY

After updating to version 2.8, you may notice an error message when trying to save pack config.

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
st2 2.8.1, on Python 2.7.5

##### OS / ENVIRONMENT / INSTALL METHOD
CentOS Linux release 7.5.1804 (Core)

##### STEPS TO REPRODUCE
1. Browse to https://myst2server.com/#/packs
2. Select any pack
3. make a change to pack config
4. Click save button

##### EXPECTED RESULTS
Expect the changes to get saved to file /opt/stackstorm/configs/mypack.yaml
 
##### ACTUAL RESULTS
An error message and pack config doesn't get saved.

##### Root Cause
The API endpoint for config management seems to have been relocated,
from: /api/v1/pack/configs
to: /api/v1/configs

##### Workaround
1. edit /opt/stackstorm/static/webui/js/main.js
2. find and modify moduleApi2.default.request({path:"/pack/configs",query....
   to: moduleApi2.default.request({path:"/configs",query....
3. save file and refresh browser.

**Comment by enykeev** [comment]
Thanks for reporting! Seems like I botched this one during a process of deprecating st2client.js library. Expect a fix to land in next patch release.
