### ISSUE TITLE
Creating your first pack docs issue

### ISSUE THREAD

**Issue by shreyas-shinde** [StackStorm/st2#4296]
##### SUMMARY

Documentation issue.  
Here https://docs.stackstorm.com/reference/packs.html#creating-your-first-pack it says using runner_type: "local-shell-cmd" . It should be runner_type: "local-shell-script" else it gives error  
raise ValueError('entry_point is only valid for local-shell-script runner')

##### ISSUE TYPE
Pick one below and delete the rest:
 - Other: Documentation

**Comment by armab** [comment]
Our docs are Open Source too: https://github.com/StackStorm/st2docs/blob/master/docs/source/reference/packs.rst
Contributions are very welcome!
