### ISSUE TITLE
Action status PENDING on COMPLETED STATES

### ISSUE THREAD

**Issue by NikosVlagoidis** [StackStorm/st2#4303]
##### SUMMARY

I was looking at the source code of st2 and found that LIVEACTION_STATUS_PENDING is on LIVEACTION_COMPLETED_STATES. Don't know if that is intended but it looks kind of wrong to me.

[code](https://github.com/StackStorm/st2/blob/master/st2common/st2common/constants/action.py#L117)

**Comment by shusugmt** [comment]
I guess this is sane. `PENDING` status is a special status only for `core.ask` and this is used when `core.ask` itself has done its job, which is to trigger the pause for the entire workflow.

**Comment by LindsayHill** [comment]
https://github.com/StackStorm/st2/pull/4309
