### ISSUE TITLE
Command didn't finish in 60 seconds in satck storm

### ISSUE THREAD

**Issue by jyothinaby** [StackStorm/st2#4306]
##### SUMMARY

shell script in stack storm is failing saying command   didnt fifnsh in 60 seconds
seems the timeout is set in paramiko_ssh.py.
how to make it work like command should run and exit only when it is complete?
cant make my workflow sleep as we cant predict the time taken by the command.

##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report
 - Feature Idea
 - Other

other

##### STACKSTORM VERSION
Paste the output of `st2 --version`:
st2 2.6.0

##### OS / ENVIRONMENT / INSTALL METHOD

installed using docker
##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

command should execute successfully without the timeout. it should comeout only when it is sucess

##### ACTUAL RESULTS

command is running only for 60 seconds

**Comment by LindsayHill** [comment]
The action has a timeout parameter. The default is 60s, but you can pass a longer timeout with `timeout=<s>`

You must have **some** time-out. You can’t let an action run indefinitely. Weeks? Months? Years?

**Comment by jyothinaby** [comment]
i have added timeout in yaml in actions like below:
parameters:
  timeout:
    required: false
    type: integer
    default: 600
 but getting error as below:
packages/mistralclient/api/base.py\", line 100, in _create\n    self._raise_api_exception(resp)\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/mistralclient/api/base.py\", line 160, in _raise_api_exception\n    error_message=error_data)\n",
  "error": "Invalid input [name=main, class=DirectWorkflowSpec, unexpected=[u'timeout']]"

**Comment by Kami** [comment]
@jyothinaby It looks like you are trying to set a timeout for the workflow action.

You need to set this `timeout` parameter for your remote runner action which you are calling inside a workflow (the change needs to be made in a workflow).

And in the future, to allow us provide better support, please include as much details as possible - at the very least, the workflow metadata and workflow definition YAML file content.

**Comment by jyothinaby** [comment]
it worked .. thanks a lot
