### ISSUE TITLE
 \\nHost key verification failed.\\r\\nlost connection', u'stdout': u''}}"

### ISSUE THREAD

**Issue by jyothinaby** [StackStorm/st2#4308]
##### SUMMARY

not able to SSH to some boxes in stackstorm using the pack linux.scp..getting error like below:  \\nHost key verification failed.\\r\\nlost connection', u'stdout': u''}}"
##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report
 - Feature Idea
 - Other

##### STACKSTORM VERSION
Paste the output of `st2 --version`:

st2 2.6.0
##### OS / ENVIRONMENT / INSTALL METHOD

docker
##### STEPS TO REPRODUCE

ssh to linux boxes

```yaml

``` Initiate_Validation:
                action: linux.scp
                input:
                    destination: <% $.destination %>
                    source: <% $.source %>
                    hosts: <% $.hosts %>
                    username: <% $.username %>
                    password: <% $.password %>
                    force: <% $.force %>
                    args: <% $.args %>
                    keyfile: <% $.keyfile %>
                    verbose: <% $.verbose %>
                    recursive: <% $.recursive %>
                publish:
                    status_message: " copying python files ."
                on-success:
                    - connectAdmin
                on-error:
                    - scpFail


##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->
files should be copied  from one linux box to other
##### ACTUAL RESULTS
<!--- What happened? What output did you get? -->
getteing error \\\\nHost key verification failed.\\\\r\\\\nlost connection', u'stdout': u''}}"

**Comment by blag** [comment]
Can you SSH or SCP manually to the destination using that same key? The `Host key verification failed` error means that the destination's key changed and the SSH client is warning you that it might be an SSH MITM attack. So double check that the destination's key in the `known_hosts` file on the StackStorm server matches the destination's actual key.

**Comment by LindsayHill** [comment]
As above, this is because you've got changed keys. 

Note - as per the Github issue template, this is for bugs & feature requests. If you need help with using StackStorm, a better place is forum.stackstorm.com, or the Slack community (stackstorm.com/community-signup)

You should also upgrade to a newer version of StackStorm. 2.8.1 is the current GA version.
