### ISSUE TITLE
action to call splunk query from stackstorm

### ISSUE THREAD

**Issue by jyothinaby** [StackStorm/st2#4329]
##### SUMMARY

Provide a quick summary of your bug or feature request.

i am trying to call splunk query from stackstorm with action splunk.search, can you let me know how to call it from yaml file undwe workflows?

##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report
 - Feature Idea
 - Other

##### STACKSTORM VERSION
Paste the output of `st2 --version`:

st2 2.6.0
##### OS / ENVIRONMENT / INSTALL METHOD

docker

##### STEPS TO REPRODUCE

```yaml

```

**Comment by LindsayHill** [comment]
As the issue template said, please use forum.stackstorm.com if you are looking for help using StackStorm. You can also use docs.stackstorm.com to see examples of workflows. 

Issues are for bugs and feature requests
