### ISSUE TITLE
nginx on RHEL returns 200 instead of 308 for http://localhost

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4358]
##### SUMMARY

When doing the `one-liner` install or `puppet-st2` (haven't tested ansible), `nginx` returns a 200 when doing a  `curl http://localhost`. Instead this should return `308 - Moved Permanently`.

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
`2.9.0`

##### OS / ENVIRONMENT / INSTALL METHOD
Happens in multiple install methods:
* `one-liner`
* `puppet-st2`

Happens on both RHEL 6 and RHEL 7

##### STEPS TO REPRODUCE
* Install StackStorm
* `curl http://localhost`

##### EXPECTED RESULTS
```shell
$ curl http://localhost
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.0</center>
</body>
</html>
```

##### ACTUAL RESULTS
```
$ curl http://localhost
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by nmaludy** [comment]
### Debugging

I found that RHEL/CentOS hosts have a `/etc/nginx/conf.d/default.conf`.

Simply removing the `default_server` property doesn't disable this server. 

To fix the problem i simply removed this default config and restarted nginx.

```
$ sudo rm /etc/nginx/conf.d/default.conf
$ sudo systemctl restart nginx
$ curl http://localhost
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.0</center>
</body>
</html>
```

### Thoughts

Thinking that on all OSes we should be removing the default nginx config, especially since the StackStorm config binds to `80`

**Comment by armab** [comment]
A respective fix for one-line-installer can be done in `st2-packages`: https://github.com/StackStorm/st2-packages/tree/master/scripts
