### ISSUE TITLE
st2 pack install fails - Action "packs.install" cannot be found

### ISSUE THREAD

**Issue by johnarnold** [StackStorm/st2#4364]
##### SUMMARY

Bug - pack install fails with error:

root@3073574a8dbf:/# st2 pack install msexchange

For the "msexchange" pack, the following content will be registered:

rules     |  0
sensors   |  1
triggers  |  0
actions   |  5
aliases   |  0

Installation may take a while for packs with many items.
ERROR: 400 Client Error: Bad Request
MESSAGE: Action "packs.install" cannot be found. for url: http://st2api:9101/packs/install

Is this URI incorrect?

##### ISSUE TYPE
Pick one below and delete the rest:
Bug Report

##### STACKSTORM VERSION
st2 2.8.1, on Python 2.7.6

##### OS / ENVIRONMENT / INSTALL METHOD

Docker - 1PPC

##### STEPS TO REPRODUCE
1. docker-compose up -d
2. docker-compose exec st2actionrunner \
  st2-register-content --config-file /etc/st2/st2.conf \
    --register-all --register-setup-virtualenvs
3. docker exec -it stackstorm_st2actionrunner_1 bash
4. st2 pack install msexchange

##### EXPECTED RESULTS
msexchange pack should install

##### ACTUAL RESULTS
ERROR: 400 Client Error: Bad Request
MESSAGE: Action "packs.install" cannot be found. for url: http://st2api:9101/packs/install

**Comment by LindsayHill** [comment]
Does your system have the `packs` pack installed? Or is this is a new system with no packs installed?

**Comment by johnarnold** [comment]
@LindsayHill 

Brand new (dev box).  Nothing installed yet, fresh volumes/containers etc.

**Comment by LindsayHill** [comment]
If you're using 1ppc, you should be using the new k8s packs. Read 
https://docs.stackstorm.com/install/ewc_ha.html#custom-st2-packs

**Comment by johnarnold** [comment]
Hmm... we're not using kubernetes yet.  We're using ansible to deploy containers and integrate with our SaaS services (postgres, mongodb, redis, etc).   All the 1PPC containers on a given node share a volume mount, e.g.

    volumes:
      - ./runtime/entrypoint.d:/st2-docker/entrypoint.d
      - ./runtime/st2.d:/st2-docker/st2.d
      - ./conf/stackstorm.env:/st2-docker/env
      - /home/johnar/stackstorm/packs:/opt/stackstorm/packs
      - /home/johnar/stackstorm/virtualenvs:/opt/stackstorm/virtualenvs
      - /home/johnar/stackstorm/configs:/opt/stackstorm/configs

I tried the new command:
root@a58b5e4cf79a:/# st2-pack-install msexchange
bash: st2-pack-install: command not found


Is it 2.9 only?

**Comment by armab** [comment]
`MESSAGE: Action "packs.install" cannot be found. for url: http://st2api:9101/packs/install` in that particular environment means that there is no mechanism to share pack content between many `st2actionrunner`, `st2sensorcontainer`, `st2api` Docker containers in a distributed way.

One way is to bundle needed packs into a immutable Docker container which you'll need to share between many st2 microservices.
Another way is to add a NFS file system which will keep pack content synced between st2 microservices. In that case `st2 pack install` will work. See: https://docs.stackstorm.com/reference/ha.html#read-write-nfs-mounts
