### ISSUE TITLE
Feature Request: Specify Python version in Pack Metadata

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2#4386]
##### SUMMARY

Let packs specify their required Python version (python2 or python3) in `pack.yaml`.

Then when ST2 installs those packs, it should use the specified Python version.

This will let packs be installed from Web UI, and ensure that appropriate Python version is used, avoiding confusion when actions do not work as expected.

##### ISSUE TYPE
 - Feature Idea

##### DETAILS

The default Python version used for virtualenv setup is python2. Users can install packs using `--python3` to change this. 

There is no way for a pack to signal that it needs python3. We should have something like `python_version=3` in `pack.yaml`. This value can also be made available via the StackStorm Exchange index.json. 

If set to 3, ST2 should automatically use Python3 when installing the pack. Otherwise it should default to 2.

In future, we could make the default version 3, unless otherwise specified (Obviously this requires updates to Exchange packs, and GA Py3 support across ST2).

**Comment by nmaludy** [comment]
+1 i like this idea! I also like the forward thinking approach is switching to Python 3 as the default in the future.

**Comment by jeking3** [comment]
Recommend requiring SemVer for the version description, and it would be nice to support the ~= style of "I can use any 3.x" or "I can use any 3.6.x".

**Comment by Kami** [comment]
I agree with @jeking3 - we should use semver which we already use for ``stackstorm_version`` attribute.

In fact, I think we should follow the same format as we use for ``stackstorm_version``.

For backward and forward compatibility reasons, we should assume it works with any Python release if that attribute is not specified (we handle ``stackstorm_version`` in the same way).

It's also worth noting that ``python3`` parameter is only there as a short term solution and "mixed Python version" deployments have multiple issues / edge cases and going forward (once Python 3 is officially supported) we won't advertise mixed versions support anymore.

**Comment by LindsayHill** [comment]
Resolved by https://github.com/StackStorm/st2/pull/4474
