### ISSUE TITLE
Orquesta - Make auth token available to tasks in workflow

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2#4414]
##### SUMMARY

Let me use `st2.actions.list` or `core.inject_trigger` (or anything that needs access to the API token) from within an orquesta workflow

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
st2 2.9.1, on Python 2.7.5

##### OS / ENVIRONMENT / INSTALL METHOD
CentOS 7
Installed via ansible-st2

##### STEPS TO REPRODUCE
```yaml
version: '1.0'
description: get actions list
tasks:
  actions_list:
    action: st2.actions.list
```

##### EXPECTED RESULTS
Return actions list.

##### ACTUAL RESULTS
traceback due to missing auth token
```
{
  "result": "None",
  "exit_code": 1,
  "stderr": "st2.actions.python.St2ActionsListAction: DEBUG    Calling client method \"get_all\" with kwargs \"{'limit': 10}\"
Traceback (most recent call last):
  File \"/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py\", line 320, in <module>
    obj.run()
  File \"/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py\", line 179, in run
    output = action.run(**self._parameters)
  File \"/opt/stackstorm/packs/st2/actions/actions_list.py\", line 27, in run
    'exclude_attributes': exclude
  File \"/opt/stackstorm/packs/st2/actions/lib/action.py\", line 102, in _run_client_method
    result = method(**method_kwargs)
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py\", line 40, in decorate
    return func(*args, **kwargs)
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py\", line 193, in get_all
    self.handle_error(response)
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py\", line 166, in handle_error
    response.raise_for_status()
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/requests/models.py\", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized
MESSAGE: Unauthorized - One of Token or API key required. for url: http://127.0.0.1:9101/v1/actions?limit=10
",
  "stdout": ""
}
```

**Comment by cognifloyd** [comment]
Spelunking through the code, it looks like this is where the runner gets the auth token:

https://github.com/StackStorm/st2/blob/caadb0b1d166f64684c976a006dcfc39a7f4f99f/st2actions/st2actions/container/base.py#L91-L96

This is the beginning of `_create_auth_token` showing when it does not return a token:

https://github.com/StackStorm/st2/blob/caadb0b1d166f64684c976a006dcfc39a7f4f99f/st2actions/st2actions/container/base.py#L369-L375

I inserted a LOG line to see what context was getting passed in.

For the orquesta workflow itself, it *does* get the auth token, but tasks in that workflow do not. Ultimately the reason the orquesta tasks are not getting an auth_token appears to be because there is no `user` in the context.

**Comment by cognifloyd** [comment]
`user` is missing in the parent context of the action executions in an orquesta workflow. The action service automatically applies the parent's user to the child task, but only if `user` is in the parent context.
Relevant snippets of code are embedded below.

The parent context (`st2_ctx`) is created (see code snippets below) in two places in 2.9.1 but only one place in master (following the with-items PR). To hack in a fix, I added the `user` parameter in both places in my 2.9.1 install:
```
st2_ctx = {
    'execution_id': wf_ex_db.action_execution,
    'user': wf_ex_db.context['st2']['user'],
}
```
This allows me to run `st2.actions.list` and similar actions that need a token.

I don't know if getting the `user` here is the right approach. I wonder if `st2_ctx` shouldn't be a copy of `wf_ex_db.context['parent']` instead of grabbing just the `user` from `wf_ex_db.context['st2']`. I didn't submit a PR because I'm not sure what the logically correct way to fix this is. And, I'm not sure what the implications of this change are in the grand scheme of orquesta and ST2, so I'd rather someone else write the actual fix and the tests.

===========================

in `handle_workflow_execution` (2.9.1 only)
https://github.com/StackStorm/st2/blob/a2bf25e085dfc9d2d407e8160a2febd48e5a4920/st2actions/st2actions/workflows/workflows.py#L144-L145

in `request_next_tasks` (2.9.1 and master - this `st2_ctx` is `parent` in the `ae_ex_ctx` context below)
https://github.com/StackStorm/st2/blob/7c27c9e1ec224c7a7103423453225dc999a6f747/st2common/st2common/services/workflows.py#L816-L817

in `request_task_execution`
https://github.com/StackStorm/st2/blob/7c27c9e1ec224c7a7103423453225dc999a6f747/st2common/st2common/services/workflows.py#L462

in `request_action_execution`
https://github.com/StackStorm/st2/blob/7c27c9e1ec224c7a7103423453225dc999a6f747/st2common/st2common/services/workflows.py#L497-L508

liveaction actually gets the user from parent context if available
https://github.com/StackStorm/st2/blob/7c27c9e1ec224c7a7103423453225dc999a6f747/st2common/st2common/services/action.py#L76-L83

**Comment by m4dcoder** [comment]
Fix at https://github.com/StackStorm/st2/pull/4421
