### ISSUE TITLE
Orquesta interoperability with mistral

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2#4416]
##### SUMMARY

I need to be able to run mistral workflows from within an orquesta workflow. This will help in transitioning workflows from mistral to orquesta, so that not everything has to be converted all at once. In working to create some minimal test cases, I figured I'd go ahead and test the four configurations (see steps to reproduce for more info):

- actionchain in orquesta
- orquesta in actionchain
- mistral in orquesta
- orquesta in mistral

Ultimately, actionchain is compatible with orquesta, but mistral is not.

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
st2 2.9.1, on Python 2.7.5

##### OS / ENVIRONMENT / INSTALL METHOD
Centos 7
Installed via ansible-st2

##### STEPS TO REPRODUCE
Install this pack and run all the actions (I used the pack name `z_st2_issues`)
https://github.com/cognifloyd/orquesta_interoperability_tests

There are 7 actions:

- (3) simple baseline workflows (with a single echo task in actionchain, mistral, and orquesta), and
- (4) the interoperability workflows mentioned above.

In each of the interoperability workflows, I tested two things:

1. Can the workflow type A start workflow type B
2. If workflow type B is started and completes, can workflow type A continue on to a subsequent task.

##### EXPECTED RESULTS
All workflows should complete successfully, including all sub workflows.

##### ACTUAL RESULTS

First the baseline tests to show that the underlying simple workflows work as expected.
[See the logs here.](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/test_results/simple.log)

| Simple Workflow | workflow                                                                                                                             |
|-----------------|--------------------------------------------------------------------------------------------------------------------------------------|
| actionchain     | [simple.actionchain.yaml](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/actions/simple.actionchain.yaml) |
| orquesta        | [simple.orquesta.yaml](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/actions/simple.orquesta.yaml)       |
| mistral         | [simple.mistral.yaml](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/actions/simple.mistral.yaml)         |

Then the interoperability tests:

| Workflows: A in B       | Test 1: Starts B | Test 2: Continues after B | workflow                                                                                                                                 | log                                                                                                                                         |
|-------------------------|------------------|---------------------------|------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------|
| actionchain in orquesta | :heavy_check_mark: PASS              | :heavy_check_mark: PASS                       | [actionchain.orquesta.yaml](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/actions/actionchain.orquesta.yaml) | [actionchain.orquesta.log](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/test_results/actionchain.orquesta.log) |
| orquesta in actionchain | :heavy_check_mark: PASS              | :heavy_check_mark: PASS                       | [orquesta.actionchain.yaml](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/actions/orquesta.actionchain.yaml) | [orquesta.actionchain.log](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/test_results/orquesta.actionchain.log) |
| mistral in orquesta     | :x: FAIL            | n/a                       | [mistral.orquesta.yaml](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/actions/mistral.orquesta.yaml)         | [mistral.orquesta.log](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/test_results/mistral.orquesta.log)         |
| orquesta in mistral     | :heavy_check_mark: PASS              | :x: FAIL                      | [orquesta.mistral.yaml](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/actions/orquesta.mistral.yaml)         | [orquesta.mistral.log](https://github.com/cognifloyd/orquesta_interoperability_tests/blob/master/test_results/orquesta.mistral.log)         |

_It's also interesting to see how much less `st2 execution get` shows for orquesta workflows, but that should be a separate issue._

**Comment by m4dcoder** [comment]
@cognifloyd Thanks for the thorough investigation here. We appreciate your time and effort. Since Mistral is being deprecated and we have limited resources currently focused on Orquesta, at this moment, we can review the information you provided and identify the cause. As for the data returned from `st2 execution get`, the design is intentional.  We felt that the output for Mistral was too noisy. We provide better error information in orquesta and we intend to improve st2 tail to stream more relevant information.  But feel free to open a separate issue and tell us what exact data you need in the output.

**Comment by cognifloyd** [comment]
In case anyone is wondering:

**Comment by cognifloyd** [comment]
In case anyone else is looking for workarounds, this one doesn't work either:
I just tried wrapping a mistral workflow in an action chain workflow to run it from orquesta. But the mistral workflow freezes just as it would if directly run within orquesta.

I suspect (in an uneducated gut/guessing kind of way) this has something to do with #4414.

**Comment by cognifloyd** [comment]
My hunch seems right. This from the mistral logs:
```
2018-10-29 15:06:16.025 11633 INFO st2mistral.notifiers.stackstorm_notifier [req-92fa5070-7c04-4c08-a12e-b220026ee45d - - - - -] [11de7a4e-6e27-424f-b69d-c9f9446e74db] The workflow event WORKFLOW_FAILED for 11de7a4e-6e27-424f-b69d-c9f9446e74db will be published to st2.
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier [req-92fa5070-7c04-4c08-a12e-b220026ee45d - - - - -] Unable to process event for publisher "st2".: Exception: [11de7a4e-6e27-424f-b69d-c9f9446e74db] Unable to publish event because st2 returned status code 401. {
    "faultstring": "Unauthorized - One of Token or API key required."
}
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier Traceback (most recent call last):
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/notifiers/default_notifier.py", line 39, in notify
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier     publisher.publish(ex_id, data, event, timestamp, **params)
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/st2mistral/notifiers/stackstorm_notifier.py", line 297, in publish
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier     func(ex_id, data, event, timestamp, **kwargs)
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/st2mistral/notifiers/stackstorm_notifier.py", line 145, in on_workflow_status_update
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier     'status code %s. %s' % (root_id, resp.status_code, resp.text)
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier Exception: [11de7a4e-6e27-424f-b69d-c9f9446e74db] Unable to publish event because st2 returned status code 401. {
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier     "faultstring": "Unauthorized - One of Token or API key required."
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier }
2018-10-29 15:06:16.162 11633 ERROR mistral.notifiers.default_notifier
```

**Comment by cognifloyd** [comment]
Duplicate of #4414. Validated by hacking in `user` so it shows up in the parent context, so that liveaction automatically pulls it into the current action's context. Then, mistral workflows can run in orquesta.

I didn't validate that that fixes running orquesta from a mistral workflow, but I suspect it will, and I only need orquesta to run mistral at this point, so I'm satisfied.

**Comment by m4dcoder** [comment]
Partial fix at https://github.com/StackStorm/st2/pull/4421. I confirm that orquesta workflow will be able to run mistral workflow but not vice versa. Please feel free to open a separate issue for mistral workflow running orquesta workflow.
