### ISSUE TITLE
Feature Request - Add get_children method to st2client for liveactions

### ISSUE THREAD

**Issue by trstruth** [StackStorm/st2#4442]
##### SUMMARY
While writing a custom web application that displays data from my stackstorm executions, I came across the use case of retrieving the children of a given execution id.  It's currently possible to retrieve similar data by invoking `client.liveactions.get_all({'parent': <execution-id>})` but this doesn't allow for controlling the depth to which children are retrieved (which the `GET/api/v1/executions/{id}/children` does).  By adding a method `get_children(self, execution_id, **kwargs)` to `LiveActionResourceManager`, we can make a request to the api endpoint mentioned above to expose the desired functionality in the python client.

I'm opening this issue in hopes of confirming that this is the correct way of going about doing this in the eyes of the maintainers, in which case I will open a PR to implement it.

##### ISSUE TYPE
 - Feature Idea

**Comment by Kami** [comment]
Thanks for this feature request.

It sounds reasonable and useful to me, so PR is more than welcome :)

**Comment by lakshmi-kannan** [comment]
Fixed in https://github.com/StackStorm/st2/pull/4444. Closing.
