### ISSUE TITLE
Gunicorn workers

### ISSUE THREAD

**Issue by lyandut** [StackStorm/st2#4454]
Why is the workers and threads of gunicorn set to 1? How can i change this config to increase the concurrency performance of st2？
![image](https://user-images.githubusercontent.com/33196654/49013572-34634e80-f1b8-11e8-836b-204a2ac1cc0b.png)

**Comment by Kami** [comment]
For StackStorm (non-Mistral) services, that value can be changed inside the service manager files (upstart / systemd) on your system - https://github.com/StackStorm/st2-packages/blob/master/packages/st2/debian/st2.st2api.upstart#L20, https://github.com/StackStorm/st2-packages/blob/master/packages/st2/rpm/st2api.service#L10.

Another way to increase st2api throughput is to simply start another instance of st2api service.

**Comment by lyandut** [comment]
It works. After i modified `/etc/init.d/st2api` and restarted the service, more than one workers were generated.
![image](https://user-images.githubusercontent.com/33196654/49015047-eac93280-f1bc-11e8-95be-7be37763ec25.png)

**Comment by Kami** [comment]
Another thing worth noting is that we use eventlet for concurrency.

In theory it should be thread safe, but if you experience issues like hanging connections when bumping thread count, you should look at spinning more worker processes or even better (as recommended for distributed deployment), run more instances of st2api service.

**Comment by lyandut** [comment]
I've deployed stackstorm service on two machines, but I find that its performance is always stable at handling 7 to 8 tasks per second, so I want to improve its performance by increasing the number of gunicorn workers.
