### ISSUE TITLE
Custom action mistral not working getting exception -InvalidActionException: Failed to find action

### ISSUE THREAD

**Issue by vaibhavpatil123** [StackStorm/st2#4483]
##### SUMMARY

InvalidActionException: Failed to find action [action_name=actionadd] 

##### ISSUE TYPE
from mistral_lib.actions import base

mistral_add_actions.py
---------------------
class AddAction(base.Action):

    def __init__(self):
        pass

    def run(self):
        return {"stderr": "", "stdout": "Hi this is output"}

---------------------
setup.py

from setuptools import setup

setup(
    setup_requires=['pbr'],
    package_dir={'': ''},
    py_modules=['mistral_add_actions'],
    pbr=True,
)

---------------------
setup.cfg 

[metadata]
name = unm_actions
summary = A Mistral action to execute Ansible playbooks
home-page = https://github.com/d0ugal/mistral-ansible-actions
license = Apache-2
classifier =
    Intended Audience :: Developers
    Natural Language :: English
    License :: OSI Approved :: Apache Software License
    Programming Language :: Python
    Programming Language :: Python :: 2.7
    Programming Language :: Python :: 3.3
    Programming Language :: Python :: 3.4
    Programming Language :: Python :: 3.5
    Topic :: Internet
    Topic :: Utilities

[files]
packages =
    unm_actions

[entry_points]

mistral.actions =
    actionadd = unm_actions.mistral_add_actions:AddAction

------------------------------------------------------------------
refer https://docs.openstack.org/mistral/latest/terminology/workflows.html
not working

**Comment by LindsayHill** [comment]
This Github repo is for the StackStorm project. If you're using just Mistral, you'll need to log an issue against their repo
