### ISSUE TITLE
Advanced Comparison does not work

### ISSUE THREAD

**Issue by sinnershiki** [StackStorm/st2#4496]
##### SUMMARY

Advanced Comparison in Rules does not work

https://docs.stackstorm.com/rules.html

##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report

##### STACKSTORM VERSION

I executed `st2-submit-debug-info`

`st2-debug-output-34858c1cc2c4-2019-01-11-082031.tar.gz.asc`

##### OS / ENVIRONMENT / INSTALL METHOD

st2-docker

##### STEPS TO REPRODUCE

I tried the search operator in criteria. But It didn't work. Sensor is working correctly. And it works if I do not specify criteria.

```rule.yml
name: "test-jira-rule"
pack: "test"
description: "test search criteria"
enabled: true

trigger:
  type: "jira.issues_tracker_for_apiv2"

criteria:
  trigger.fields.components:
    type: "search"
    condition: any
    pattern:
      item.name:
        type: "equals"
        pattern: "test"

action:
  ref: "core.echo"
  parameters:
    message: "{{trigger.fields.components}"
```

```trigger.fields.components.json
{
  "failed": false,
  "stderr": "",
  "return_code": 0,
  "succeeded": true,
  "stdout": "[{u'self': u'https://xxx.xxx.com/rest/api/2/component/17110', u'id': u'17110', u'name': u'test'}]"
}
```

**Comment by blag** [comment]
I wrote the `search` operator specifically for rules triggered from Jira, so I'm sorry to hear that it's not working for you.

What does your trigger data look like?

**Comment by sinnershiki** [comment]
I'm sorry. It occurred because "}" was missing in the action part of rule. 

I could notice by your verification. Thank you very much.
