### ISSUE TITLE
PIP version restrictions on packs test virtualenv

### ISSUE THREAD

**Issue by pkaramol** [StackStorm/st2#4515]
This is more of a question on an issue preventing our packs development rather than a bug.

We are using the `st2-run-pack-tests.sh` script to run some tests on our packs.

Given that we are using a private pip repo (nexus) and we recently upgraded it, the later seems to have issues with older versions of `pip`.

What are the implications of loosening [this](https://github.com/StackStorm/st2/blob/master/st2common/bin/st2-run-pack-tests#L201) restriction and allowing for `pip==19.0.1` which is the latest?

**Comment by Kami** [comment]
Thanks for opening this issue.

The plan is to get those dependencies updated in #4500 in the near future.

In the past we had a lot of issues with newer pip versions and older distributions (RHEL 6) so we needed to pin it to an older version to ensure it works correctly across all the various distributions we support.

**Comment by pkaramol** [comment]
So more or less it is an issue of the OS/distro?

In your opinion if we explicitly update pip to latest (19.0.1) would it create st2-pack related issues for the tests run on the virtualenv of the script?

**Comment by pkaramol** [comment]
Ok thx for the feedback, closing this.
