### ISSUE TITLE
 core.st2.DateTimer not trigging

### ISSUE THREAD

**Issue by vovaled** [StackStorm/st2#4556]
Summary:
Rule not triggering using core.st2.DateTimer.

Issue:
Bug Report

STACKSTORM VERSION:
st2 2.9.1, on Python 2.7.12

OS / ENVIRONMENT / INSTALL METHOD
Ubuntu 16.04.3 LTS

##### STEPS TO REPRODUCE
The rule created using REST API (/api/v1/rules):

---
name: "rule_name"
pack: "custom_pack"
description: "description"
enabled: true
trigger: 
  type: "core.st2.DateTimer"
  parameters: 
    date: "2019-02-17 09:37:00"
    timezone: "UTC"
    
action: 
 ref: "core.http"
 description: "description"
 parameters: 
   url: "https://example/url"
   body: { 
    "key": vcalue"
      }
   allow_redirects: true
   method: "POST"
   headers: 
     Content-Type: "application/json"
     Authorization: "token"
     cache-control: "no-cache"

##### EXPECTED RESULTS
The rule should run when time met 2019-02-17 09:37:00

##### ACTUAL RESULTS
Rule not triggering

st2 rule-enforcement list --rule=custom_pack.rule_name
No matching items found

No errors in logs regarding this task execution.

**Comment by Kami** [comment]
Can you please gist the log of st2timersengie service (``/var/log/st2/st2timersengine.log``)?

**Comment by vovaled** [comment]
I dont have such file (st2timersengine.log) under this path /var/log/st2/

**Comment by LindsayHill** [comment]
@vovaled are all your services running correctly? (`st2ctl status`)

I wonder if you've upgraded an older system, but missed this https://docs.stackstorm.com/upgrade_notes.html#ref-upgrade-notes-v2-9

**Comment by Kami** [comment]
Is this a fresh installation or did you recently upgrade from pre StackStorm v2.9.0 to StackStorm v2.9.1?

We moved timer related functionality from ``st2rulesengine`` to new ``st2timersengine`` service in v2.9.0. 

If you did a manual upgrade you need to make sure your config contains ``timersengine`` section otherwise the timersengine service won't start.

See https://docs.stackstorm.com/upgrade_notes.html#st2-v2-9 for details.

**Comment by vovaled** [comment]
Running this command st2ctl status:
##### st2 components status #####
st2actionrunner PID: 26748
st2actionrunner PID: 26751
st2actionrunner PID: 26754
st2actionrunner PID: 26761
st2actionrunner PID: 26764
st2actionrunner PID: 26767
st2actionrunner PID: 26770
st2actionrunner PID: 26774
st2actionrunner PID: 26778
st2actionrunner PID: 26781
st2api PID: 26794
st2api PID: 27295
st2stream PID: 19058
st2stream PID: 26801
st2auth PID: 18290
st2auth PID: 26807
st2garbagecollector PID: 26818
st2notifier PID: 26824
st2resultstracker PID: 26829
st2rulesengine PID: 26834
st2sensorcontainer PID: 26838
st2chatops is not running.
st2timersengine is not running.
st2workflowengine PID: 26866
mistral-server PID: 26953
mistral.api PID: 26909
mistral.api PID: 27080
mistral.api PID: 27084

Yes, we upgraded recently but never used this module before. 
now I added to /etc/st2/st2.conf :
[timersengine]
logging = /etc/st2/logging.workflowengine.conf

and restarted the service, however:
##### st2 components status #####
st2actionrunner PID: 13471
st2actionrunner PID: 13474
st2actionrunner PID: 13477
st2actionrunner PID: 13480
st2actionrunner PID: 13483
st2actionrunner PID: 13486
st2actionrunner PID: 13489
st2actionrunner PID: 13492
st2actionrunner PID: 13495
st2actionrunner PID: 13501
st2api PID: 13514
st2api PID: 13695
st2stream PID: 13518
st2stream PID: 13795
st2auth PID: 13526
st2auth PID: 13717
st2garbagecollector PID: 13531
st2notifier PID: 13536
st2resultstracker PID: 13541
st2rulesengine PID: 13547
st2sensorcontainer PID: 13555
st2chatops is not running.
st2timersengine is not running.
st2workflowengine PID: 13582
mistral-server PID: 13661
mistral.api PID: 13626
mistral.api PID: 13825
mistral.api PID: 13828

**Comment by vovaled** [comment]
service st2timersengine status
● st2timersengine.service - StackStorm service st2timersengine
   Loaded: loaded (/lib/systemd/system/st2timersengine.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-02-18 18:11:48 UTC; 4s ago
  Process: 19462 ExecStart=/opt/stackstorm/st2/bin/st2timersengine $DAEMON_ARGS (code=exited, status=1/FAILURE)
 Main PID: 19462 (code=exited, status=1/FAILURE)

Feb 18 18:11:48 ip-10-192-252-177 systemd[1]: st2timersengine.service: Unit entered failed state.
Feb 18 18:11:48 ip-10-192-252-177 systemd[1]: st2timersengine.service: Failed with result 'exit-code'

**Comment by armab** [comment]
You included workflowengine logging config for timersengine, despite docs mentioning correct timersengine one https://docs.stackstorm.com/upgrade_notes.html#st2-v2-9

```diff
[timersengine]
-logging = /etc/st2/logging.workflowengine.conf
+logging = /etc/st2/logging.timersengine.conf
```

Please update the st2.conf with correct settings, restart the services and take a look at beforementioned `/var/log/st2/st2timersengine.log` if you still having any issues with service startup.

**Comment by vovaled** [comment]
Sorry for the typo, I just copied it wrong here. Its already set correctly 
[timersengine]
logging = /etc/st2/logging.timersengine.conf

**Comment by vovaled** [comment]
service st2timersengine status
● st2timersengine.service - StackStorm service st2timersengine
   Loaded: loaded (/lib/systemd/system/st2timersengine.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-02-18 19:39:51 UTC; 566ms ago
 Main PID: 6818 (st2timersengine)
    Tasks: 1
   Memory: 36.1M
      CPU: 563ms
   CGroup: /system.slice/st2timersengine.service
           └─6818 /opt/stackstorm/st2/bin/python /opt/stackstorm/st2/bin/st2timersengine --config-file /etc/st2/st2.conf

Feb 18 19:39:52 ip-10-192-252-177 st2timersengine[6818]:     self.register_opt(opt, group, clear_cache=False)
Feb 18 19:39:52 ip-10-192-252-177 st2timersengine[6818]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 1824, in __inner
Feb 18 19:39:52 ip-10-192-252-177 st2timersengine[6818]:     return f(self, *args, **kwargs)
Feb 18 19:39:52 ip-10-192-252-177 st2timersengine[6818]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 1961, in register_opt
Feb 18 19:39:52 ip-10-192-252-177 st2timersengine[6818]:     return group._register_opt(opt, cli)
Feb 18 19:39:52 ip-10-192-252-177 st2timersengine[6818]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 1344, in _register_opt
Feb 18 19:39:52 ip-10-192-252-177 st2timersengine[6818]:     if _is_opt_registered(self._opts, opt):
Feb 18 19:39:52 ip-10-192-252-177 st2timersengine[6818]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 574, in _is_opt_registered
Feb 18 19:39:52 ip-10-192-252-177 st2timersengine[6818]:     raise DuplicateOptError(opt.name)
Feb 18 19:39:52 ip-10-192-252-177 st2timersengine[6818]: oslo_config.cfg.DuplicateOptError: duplicate option: logging
root@ip-10-192-252-177:/opt/stackstorm# vi /opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py

**Comment by armab** [comment]
The error message shows `DuplicateOptError: duplicate option: logging` for `st2timersengine` in `st2.conf`.

You need to review your Stackstorm config once again.

**Comment by vovaled** [comment]
There is nothing unusal in the config file:


cat /etc/st2/st2.conf
=============================================
# System-wide configuration

[api]
# Host and port to bind the API server.
host = 127.0.0.1
port = 9101
logging = /etc/st2/logging.api.conf
mask_secrets = True
# allow_origin is required for handling CORS in st2 web UI.
# allow_origin = http://myhost1.example.com:3000,http://myhost2.example.com:3000

[timersengine]
logging = /etc/st2/logging.timersengine.conf

[workflow_engine]
logging = /etc/st2/logging.workflowengine.conf

[stream]
logging = /etc/st2/logging.stream.conf

[sensorcontainer]
logging = /etc/st2/logging.sensorcontainer.conf

[rulesengine]
logging = /etc/st2/logging.rulesengine.conf

[actionrunner]
logging = /etc/st2/logging.actionrunner.conf
virtualenv_opts = --always-copy

[resultstracker]
logging = /etc/st2/logging.resultstracker.conf

[notifier]
logging = /etc/st2/logging.notifier.conf

[exporter]
logging = /etc/st2/logging.exporter.conf

[garbagecollector]
logging = /etc/st2/logging.garbagecollector.conf

[auth]
host = 127.0.0.1
port = 9100
use_ssl = False
debug = False
enable = True
logging = /etc/st2/logging.auth.conf

mode = standalone

# Note: Settings below are only used in "standalone" mode
backend = flat_file
backend_kwargs = {"file_path": "/etc/st2/htpasswd"}

# Base URL to the API endpoint excluding the version (e.g. http://myhost.net:9101/)
api_url =

[system]
base_path = /opt/stackstorm

[webui]
webui_base_url = https://ss.itaws.wixpress.com

[syslog]
host = 127.0.0.1
port = 514
facility = local7
protocol = udp

[log]
excludes = requests,paramiko
redirect_stderr = False
mask_secrets = True

[system_user]
user = stanley
ssh_key_file = /home/stanley/.ssh/stanley_rsa

[messaging]
url = amqp://guest:guest@127.0.0.1:5672/

[ssh_runner]
remote_dir = /tmp
[keyvalue]
encryption_key_path = /etc/st2/keys/datastore_key.json

**Comment by vovaled** [comment]
Had to update the file /opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/timer/config.py

to this version:  https://github.com/StackStorm/st2/blob/09fc032f30753f6ab6619470de9ea9e3ced23b03/st2reactor/st2reactor/timer/config.py

Thank you all for the assistance and quick responses, not its working!

**Comment by vovaled** [comment]
Can be closed
