### ISSUE TITLE
Stackstorm error in orquestra workflow

### ISSUE THREAD

**Issue by riyu94** [StackStorm/st2#4624]
In orquestra workflow, stackstorm threw the following error:

 - Bug Report

st2 2.10.0, on Python 2.7.5

Output:

{
  "traceback": "  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py\", line 127, in _do_run
    (status, result, context) = runner.run(action_params)
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/local_runner/local_shell_command_runner.py\", line 49, in run
    return self._run(action=action)
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/local_runner/base.py\", line 175, in _run
    read_stderr_buffer=stderr)
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/green/shell.py\", line 109, in run_command
    env=env, cwd=cwd, shell=shell, preexec_fn=preexec_func)
  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/eventlet/green/subprocess.py\", line 58, in __init__
    subprocess_orig.Popen.__init__(self, args, 0, *argss, **kwds)
  File \"/usr/lib64/python2.7/subprocess.py\", line 711, in __init__
    errread, errwrite)
  File \"/usr/lib64/python2.7/subprocess.py\", line 1327, in _execute_child
    raise child_exception
",
  "error": "execve() arg 2 must contain only strings"
}

The same task succeeded many times, but failed thrice giving the above error.

**Comment by m4dcoder** [comment]
@riyu94 This looks like an error running the action defined in the task.  Can you provide the workflow definition here?

**Comment by riyu94** [comment]
Actually that is an API to our ticketing system. 
The main issue is : It worked for almost all cases, but gave this error only for a few. And the API works well when ran locally on machine.

**Comment by m4dcoder** [comment]
Well, the error `arg 2 must contain only strings` is data type specific.  So my suggestion is to look at the cases where it fail and make sure the input being passed into the core.local action is string type.

**Comment by riyu94** [comment]
ok will check.
Thanks

**Comment by riyu94** [comment]
Resolved it, thanks

**Comment by m4dcoder** [comment]
Glad you resolved it.
