### ISSUE TITLE
Bad rewrite directive in controller nginx HA config

### ISSUE THREAD

**Issue by GuiTeK** [StackStorm/st2#4665]
##### SUMMARY

I tried to use [the controller nginx HA config](https://github.com/StackStorm/st2/blob/v3.0.0/conf/HA/st2.conf.sample) for setting up our controller nginx server.

However, I noticed that when logging in to the WebUI, there was an error message in the JS console:
> EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.

This is because:
1. The WebUI requests `https://controller-ip/stream/stream`
2. Because of the rewrite directive quoted below, it redirects to `https://controller-ip/stream/`
3. The path which gets passed to the proxy is `/` instead of `/stream/` somehow (I don't know exactly why about this, but I can tell that this is what is happening for sure, I checked the nginx logs of the worker)
4. The [worker nginx HA config](https://github.com/StackStorm/st2/blob/master/conf/HA/nginx/st2.conf.blueprint.sample) expects an URI with `/stream/` but instead receives `/`
5. The worker nginx server will then respond with the default nginx page
6. Causing the JS error because it is indeed not the expected response

https://github.com/StackStorm/st2/blob/2c8fec90a8029fdce4e7adf19af683edb84bd006/conf/HA/nginx/st2.conf.controller.sample#L82

When removing/commenting out this directive, the request `https://controller-ip/stream/stream` made by the WebUI is passed to the worker nginx as `/stream`, which correctly responds with the intended response of type `text/event-stream`.

##### ISSUE TYPE
Bug Report

##### STACKSTORM VERSION
st2 3.0.0, on Python 2.7.12

(seems to affect previous versions as well)

##### OS / ENVIRONMENT / INSTALL METHOD
Custom HA install

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

**Comment by armab** [comment]
Thanks for reporting this issue.

It looks like https://github.com/StackStorm/st2/blob/master/conf/HA/nginx/st2.conf.blueprint.sample you mentioned is a bit unsync with https://github.com/StackStorm/st2/blob/master/conf/HA/st2.conf.sample

Can you please try replacing all `stream`-related locations with this directive:
https://github.com/StackStorm/st2/blob/2c8fec90a8029fdce4e7adf19af683edb84bd006/conf/nginx/st2.conf#L72-L102 and verify if the issue still present?

**Comment by GuiTeK** [comment]
Should I replace it in the controller nginx configuration or in the worker nginx configuration?

Also, did you mean `proxy_pass  https://st2/;` instead of `proxy_pass  http://127.0.0.1:9102/;` (the snippet of code you provided isn't the HA version I think)? C.F. https://github.com/StackStorm/st2/blob/2c8fec90a8029fdce4e7adf19af683edb84bd006/conf/nginx/st2.conf#L86

I replaced it in the controller nginx configuration with `proxy_pass  https://st2/;` and the issue is still present.

**Comment by armab** [comment]
Thanks for the report @GuiTeK, I could reproduce it.

Will update the configs soon.
