### ISSUE TITLE
PIP Upgrade

### ISSUE THREAD

**Issue by bigmstone** [StackStorm/st2#4681]
When PIP upgraded to 10 it caused a lot of issues. We pinned to 9.x. Needs to be reassessed now.

**Comment by armab** [comment]
For the history: https://github.com/StackStorm/st2-packages/pull/549

**Comment by armab** [comment]
Because `st2` repo during these months already incorporated env fixes related to py3, pip and dist_utils,
the remaining work just took 1 fix in `st2-packages` and another 10 PRs to update pip in different repos.

We're now on latest pip `v19` instead of old `v9`.
