### ISSUE TITLE
Actions stuck in delayed state. 

### ISSUE THREAD

**Issue by bhanukumar22** [StackStorm/st2#4694]
##### SUMMARY

Actions stuck in delayed state for more than 5 hours. 

##### ISSUE TYPE
 - Other

##### STACKSTORM VERSION
st2 2.10.3, on Python 2.7.5

##### OS / ENVIRONMENT / INSTALL METHOD
Installed on Linux OS.
Installed with one line. 

Executions were working fine. We had around 50 actions triggered at a same time using script for stress test.
We have set concurrency limit set to 10.

We were expecting the actions to complete after few mins, but it got stuck.

**Comment by Kami** [comment]
I believe this issue was addressed in v3.0.0, but there is another issue with executions bouncing between ``delayed`` and ``policy-delayed`` status which will be addressed in v3.0.1 which will be out in the next week or two.

**Comment by bhanukumar22** [comment]
Initially actions went to policy-delayed, then it got stuck in delayed state.

**Comment by Kami** [comment]
As per my comment above - I would try upgrading to v3.0.0 (it works correctly there, it just causes some unnecessary bouncing between statues) and if that doesn't work, wait for the v3.0.1 release.

**Comment by m4dcoder** [comment]
Please upgrade to v3.0.1.  There's a fix relating to delayed status.  We can reopen this issue if you encounter it again.
