### ISSUE TITLE
Action Aliases: Support static parameters

### ISSUE THREAD

**Issue by nicholasamorim** [StackStorm/st2#4703]
##### SUMMARY

When using chatops, I started defining certain action aliases. One alias I set up was basically `deploy app`, that in turn would trigger an `ansible-playbook` action with certain parameters. 

Those parameters are static (playbook X, folder Y) and shouldn't be changed with user input.

I was then surprised to find that action aliases do not support default/static parameters. You can define in the format such as `deploy web {{playbook="someplay"}}` but there are valid use-cases for simply having static parameters being passed to the action. Having a default in the format looks like a workaround for the time being but that's all that it is.

I think Action Aliases could benefit from something like `action_parameters` where we define certain parameters to be passed to the action that _do not depend_ on user input and _should not be changed_.

##### ISSUE TYPE
 - Feature Idea

##### STACKSTORM VERSION
Paste the output of `st2 --version`: 3.0.0

**Comment by armab** [comment]
Duplicate of https://github.com/StackStorm/st2/issues/1704

**Comment by armab** [comment]
Thanks for the report.
Will close it in favor of existing #1704 issue. To bring more examples in one place, I'd also suggest to post your use case there as well.

Thanks!
