### ISSUE TITLE
Issues setting up development environment on macOS

### ISSUE THREAD

**Issue by RaviTezu** [StackStorm/st2#4708]
##### SUMMARY
I am trying to set up a development environment on macOS to write packs. I am using PyCharm for the same. I tried to install the dependencies (like st2common, st2reactor) from source(https://docs.stackstorm.com/development/sources.html) which are needed for writing packs, but no luck. It is failing at installing `inotify`: `inotify is not available on macosx-10.13-x86_64`.

##### ISSUE TYPE
 - Other

I found a way though, by cloning the st2 repo and then adding the `st2common`, `st2reactor`.. etc to project path and the `imports` will just work in PyCharm. Creating this issue to see if there's any better of doing this.

**Comment by LindsayHill** [comment]
As you found, one of the dependencies we use is not supported on macOS. There is no current supported development method that works entirely on macOS.

You could investigate using VSCode Remote Development.

**Comment by LindsayHill** [comment]
Take a look at these PRs https://github.com/StackStorm/st2/pull/4145 and https://github.com/StackStorm/st2/pull/4191 (note they weren't merged). 

Have a read through the comments, see if things have changed since then, they may have.

**Comment by LindsayHill** [comment]
It's possible that we'll get to a point where you'll be able to get the install working. That might be OK for development, although it should not be relied on upon for full testing.

**Comment by RaviTezu** [comment]
Thank you @LindsayHill 
Closing this issue.
