### ISSUE TITLE
Cannot install st2 pack (or any pack) after upgrade to 3.0.1

### ISSUE THREAD

**Issue by Rudd-O** [StackStorm/st2#4718]
##### SUMMARY

    root@salt:~# st2 pack install st2
    2019-06-21 03:25:22,167 140133084539632 INFO __init__ [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "userAdmin".
    2019-06-21 03:25:22,300 140133084539632 INFO __init__ [-] Successfully connected to database "st2" @ "127.0.0.1:27017" as user "userAdmin".
    2019-06-21 03:25:24,213 140133084539632 INFO partitioner_lookup [-] Using partitioner default with sensornode sensornode1.
    2019-06-21 03:25:24,216 140133084539632 INFO partitioners [-] Found 2 registered sensors in db scan.
    2019-06-21 03:25:24,234 140133084539632 INFO manager [-] Setting up container to run 2 sensors.
    2019-06-21 03:25:24,237 140133084539632 INFO manager [-] (PID:29509) SensorContainer started.
    2019-06-21 03:25:24,242 140133008468400 INFO process_container [-] Running sensor linux.FileWatchSensor
    2019-06-21 03:25:24,274 140133008468400 WARNING api [-] "auth.api_url" configuration option is not configured
    2019-06-21 03:25:24,478 140133008468560 INFO mixins [-] Connected to amqp://guest:**@127.0.0.1:5672//
    2019-06-21 03:25:24,521 140133008468400 INFO process_container [-] Sensor linux.FileWatchSensor started
    2019-06-21 03:25:24,546 140133008468400 WARNING api [-] "auth.api_url" configuration option is not configured
    2019-06-21 03:25:34,215 140144428991504 INFO sensor_wrapper [-] No config found for sensor "FileWatchSensor"
    2019-06-21 03:25:34,219 140144428991504 INFO sensor_wrapper [-] Watcher started
    2019-06-21 03:25:34,220 140144428991504 INFO sensor_wrapper [-] Running sensor initialization code
    2019-06-21 03:25:34,282 140144378283184 INFO mixins [-] Connected to amqp://guest:**@127.0.0.1:5672//
    2019-06-21 03:25:34,316 140304482571280 INFO sensor_wrapper [-] Found config for sensor "ClusterParticipationSensor"
    2019-06-21 03:25:34,323 140304482571280 INFO sensor_wrapper [-] Watcher started
    2019-06-21 03:25:34,324 140304482571280 INFO sensor_wrapper [-] Running sensor initialization code
    2019-06-21 03:25:34,324 140304482571280 INFO sensor_wrapper [-] Running sensor in passive mode
    2019-06-21 03:25:34,325 140304482571280 INFO cluster_participation [-] Retrieving list of machines and exclusion reasons.
    2019-06-21 03:25:34,328 140304482571280 INFO cluster_participation [-] Retrieving list of machines and exclusion reasons from cluster beta.
    2019-06-21 03:25:34,320 140144428991504 INFO sensor_wrapper [-] Running sensor in passive mode
    2019-06-21 03:25:34,436 140304435125296 INFO mixins [-] Connected to amqp://guest:**@127.0.0.1:5672//
    2019-06-21 03:25:37,563 140304482571280 INFO cluster_participation [-] 40 included nodes, 23 excluded (or including) nodes in cluster beta.
    2019-06-21 03:25:37,568 140304482571280 WARNING api [-] "auth.api_url" configuration option is not configured
    2019-06-21 03:25:37,577 140304482571280 AUDIT access [-] Access granted to "sensor_service" with the token set to expire at "2019-06-22T03:25:37.573622Z". (username='sensor_service',token_expiration='2019-06-22T03:25:37.573622Z')
    2019-06-21 03:25:37,685 140304482571280 INFO cluster_participation [-] 0 changes from last poll.
    id: 5d0c4e2e57118e73fea28bee
    action.ref: packs.install
    parameters: 
    packs:
    - st2
    python3: false
    status: failed
    result_task: download pack
    result: 
    error: "Failed running task "download pack".. Additional properties are not allowed ('python3' was unexpected)

    Failed validating 'additionalProperties' in schema:
        {'additionalProperties': False,
        'description': u'Downloads packs and places it in the local content repository.',
        'properties': {u'abs_repo_base': {u'default': u'/opt/stackstorm/packs/',
                                        u'immutable': True,
                                        u'type': u'string'},
                        u'content_version': {u'description': u'Git revision of the pack content to use for this action execution (git commit sha / tag / branch). Only applies to packs which are git repositories.',
                                            u'required': False,
                                            u'type': [u'string', 'null']},
                        u'debug': {u'default': False,
                                u'description': u'Enable runner debug mode.',
                                u'required': False,
                                u'type': u'boolean'},
                        u'env': {u'description': u'Environment variables which will be available to the script.',
                                u'type': [u'object', 'null']},
                        u'force': {u'default': False,
                                u'description': u'Set to True to force install the pack and skip StackStorm version compatibility check',
                                u'required': False,
                                u'type': u'boolean'},
                        u'log_level': {u'default': u'DEBUG',
                                    u'description': u'Default log level for Python runner actions.',
                                    u'enum': [u'AUDIT',
                                                u'CRITICAL',
                                                u'ERROR',
                                                u'WARNING',
                                                u'INFO',
                                                u'DEBUG'],
                                    u'type': u'string'},
                        u'packs': {u'items': {u'type': u'string'},
                                u'required': True,
                                u'type': u'array'},
                        u'timeout': {u'default': 600,
                                    u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds.",
                                    u'type': u'integer'},
                        u'verifyssl': {u'default': True, u'type': u'boolean'}},
        'title': u'download',
        'type': 'object'}

    On instance:
        {u'abs_repo_base': u'/opt/stackstorm/packs/',
        u'debug': False,
        'force': False,
        u'log_level': u'DEBUG',
        'packs': [u'st2'],
        'python3': u'False',
        u'timeout': 600,
        u'verifyssl': True}"
    traceback: "Traceback (most recent call last):
    File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/action_chain_runner/action_chain_runner.py", line 527, in _run_chain
        liveaction = self._run_action(liveaction)
    File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/action_chain_runner/action_chain_runner.py", line 751, in _run_action
        raise e
    ValidationError: Additional properties are not allowed ('python3' was unexpected)

    Failed validating 'additionalProperties' in schema:
        {'additionalProperties': False,
        'description': u'Downloads packs and places it in the local content repository.',
        'properties': {u'abs_repo_base': {u'default': u'/opt/stackstorm/packs/',
                                        u'immutable': True,
                                        u'type': u'string'},
                        u'content_version': {u'description': u'Git revision of the pack content to use for this action execution (git commit sha / tag / branch). Only applies to packs which are git repositories.',
                                            u'required': False,
                                            u'type': [u'string', 'null']},
                        u'debug': {u'default': False,
                                u'description': u'Enable runner debug mode.',
                                u'required': False,
                                u'type': u'boolean'},
                        u'env': {u'description': u'Environment variables which will be available to the script.',
                                u'type': [u'object', 'null']},
                        u'force': {u'default': False,
                                u'description': u'Set to True to force install the pack and skip StackStorm version compatibility check',
                                u'required': False,
                                u'type': u'boolean'},
                        u'log_level': {u'default': u'DEBUG',
                                    u'description': u'Default log level for Python runner actions.',
                                    u'enum': [u'AUDIT',
                                                u'CRITICAL',
                                                u'ERROR',
                                                u'WARNING',
                                                u'INFO',
                                                u'DEBUG'],
                                    u'type': u'string'},
                        u'packs': {u'items': {u'type': u'string'},
                                u'required': True,
                                u'type': u'array'},
                        u'timeout': {u'default': 600,
                                    u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds.",
                                    u'type': u'integer'},
                        u'verifyssl': {u'default': True, u'type': u'boolean'}},
        'title': u'download',
        'type': 'object'}

    On instance:
        {u'abs_repo_base': u'/opt/stackstorm/packs/',
        u'debug': False,
        'force': False,
        u'log_level': u'DEBUG',
        'packs': [u'st2'],
        'python3': u'False',
        u'timeout': 600,
        u'verifyssl': True}
    "
    error: Failed running task "download pack".. Additional properties are not allowed ('python3' was unexpected)

    Failed validating 'additionalProperties' in schema:
        {'additionalProperties': False,
        'description': u'Downloads packs and places it in the local content repository.',
        'properties': {u'abs_repo_base': {u'default': u'/opt/stackstorm/packs/',
                                        u'immutable': True,
                                        u'type': u'string'},
                        u'content_version': {u'description': u'Git revision of the pack content to use for this action execution (git commit sha / tag / branch). Only applies to packs which are git repositories.',
                                            u'required': False,
                                            u'type': [u'string', 'null']},
                        u'debug': {u'default': False,
                                u'description': u'Enable runner debug mode.',
                                u'required': False,
                                u'type': u'boolean'},
                        u'env': {u'description': u'Environment variables which will be available to the script.',
                                u'type': [u'object', 'null']},
                        u'force': {u'default': False,
                                u'description': u'Set to True to force install the pack and skip StackStorm version compatibility check',
                                u'required': False,
                                u'type': u'boolean'},
                        u'log_level': {u'default': u'DEBUG',
                                    u'description': u'Default log level for Python runner actions.',
                                    u'enum': [u'AUDIT',
                                                u'CRITICAL',
                                                u'ERROR',
                                                u'WARNING',
                                                u'INFO',
                                                u'DEBUG'],
                                    u'type': u'string'},
                        u'packs': {u'items': {u'type': u'string'},
                                u'required': True,
                                u'type': u'array'},
                        u'timeout': {u'default': 600,
                                    u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds.",
                                    u'type': u'integer'},
                        u'verifyssl': {u'default': True, u'type': u'boolean'}},
        'title': u'download',
        'type': 'object'}

    On instance:
        {u'abs_repo_base': u'/opt/stackstorm/packs/',
        u'debug': False,
        'force': False,
        u'log_level': u'DEBUG',
        'packs': [u'st2'],
        'python3': u'False',
        u'timeout': 600,
        u'verifyssl': True}
    traceback: Traceback (most recent call last):
    File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/action_chain_runner/action_chain_runner.py", line 527, in _run_chain
        liveaction = self._run_action(liveaction)
    File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/action_chain_runner/action_chain_runner.py", line 751, in _run_action
        raise e
    ValidationError: Additional properties are not allowed ('python3' was unexpected)

    Failed validating 'additionalProperties' in schema:
        {'additionalProperties': False,
        'description': u'Downloads packs and places it in the local content repository.',
        'properties': {u'abs_repo_base': {u'default': u'/opt/stackstorm/packs/',
                                        u'immutable': True,
                                        u'type': u'string'},
                        u'content_version': {u'description': u'Git revision of the pack content to use for this action execution (git commit sha / tag / branch). Only applies to packs which are git repositories.',
                                            u'required': False,
                                            u'type': [u'string', 'null']},
                        u'debug': {u'default': False,
                                u'description': u'Enable runner debug mode.',
                                u'required': False,
                                u'type': u'boolean'},
                        u'env': {u'description': u'Environment variables which will be available to the script.',
                                u'type': [u'object', 'null']},
                        u'force': {u'default': False,
                                u'description': u'Set to True to force install the pack and skip StackStorm version compatibility check',
                                u'required': False,
                                u'type': u'boolean'},
                        u'log_level': {u'default': u'DEBUG',
                                    u'description': u'Default log level for Python runner actions.',
                                    u'enum': [u'AUDIT',
                                                u'CRITICAL',
                                                u'ERROR',
                                                u'WARNING',
                                                u'INFO',
                                                u'DEBUG'],
                                    u'type': u'string'},
                        u'packs': {u'items': {u'type': u'string'},
                                u'required': True,
                                u'type': u'array'},
                        u'timeout': {u'default': 600,
                                    u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds.",
                                    u'type': u'integer'},
                        u'verifyssl': {u'default': True, u'type': u'boolean'}},
        'title': u'download',
        'type': 'object'}

    On instance:
        {u'abs_repo_base': u'/opt/stackstorm/packs/',
        u'debug': False,
        'force': False,
        u'log_level': u'DEBUG',
        'packs': [u'st2'],
        'python3': u'False',
        u'timeout': 600,
        u'verifyssl': True}

    failed_on: download pack
    start_timestamp: Fri, 21 Jun 2019 03:25:34 UTC
    end_timestamp: Fri, 21 Jun 2019 03:25:46 UTC
    result: 
    error: "Failed running task "download pack".. Additional properties are not allowed ('python3' was unexpected)

    Failed validating 'additionalProperties' in schema:
        {'additionalProperties': False,
        'description': u'Downloads packs and places it in the local content repository.',
        'properties': {u'abs_repo_base': {u'default': u'/opt/stackstorm/packs/',
                                        u'immutable': True,
                                        u'type': u'string'},
                        u'content_version': {u'description': u'Git revision of the pack content to use for this action execution (git commit sha / tag / branch). Only applies to packs which are git repositories.',
                                            u'required': False,
                                            u'type': [u'string', 'null']},
                        u'debug': {u'default': False,
                                u'description': u'Enable runner debug mode.',
                                u'required': False,
                                u'type': u'boolean'},
                        u'env': {u'description': u'Environment variables which will be available to the script.',
                                u'type': [u'object', 'null']},
                        u'force': {u'default': False,
                                u'description': u'Set to True to force install the pack and skip StackStorm version compatibility check',
                                u'required': False,
                                u'type': u'boolean'},
                        u'log_level': {u'default': u'DEBUG',
                                    u'description': u'Default log level for Python runner actions.',
                                    u'enum': [u'AUDIT',
                                                u'CRITICAL',
                                                u'ERROR',
                                                u'WARNING',
                                                u'INFO',
                                                u'DEBUG'],
                                    u'type': u'string'},
                        u'packs': {u'items': {u'type': u'string'},
                                u'required': True,
                                u'type': u'array'},
                        u'timeout': {u'default': 600,
                                    u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds.",
                                    u'type': u'integer'},
                        u'verifyssl': {u'default': True, u'type': u'boolean'}},
        'title': u'download',
        'type': 'object'}

    On instance:
        {u'abs_repo_base': u'/opt/stackstorm/packs/',
        u'debug': False,
        'force': False,
        u'log_level': u'DEBUG',
        'packs': [u'st2'],
        'python3': u'False',
        u'timeout': 600,
        u'verifyssl': True}"
    traceback: "Traceback (most recent call last):
    File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/action_chain_runner/action_chain_runner.py", line 527, in _run_chain
        liveaction = self._run_action(liveaction)
    File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/action_chain_runner/action_chain_runner.py", line 751, in _run_action
        raise e
    ValidationError: Additional properties are not allowed ('python3' was unexpected)

    Failed validating 'additionalProperties' in schema:
        {'additionalProperties': False,
        'description': u'Downloads packs and places it in the local content repository.',
        'properties': {u'abs_repo_base': {u'default': u'/opt/stackstorm/packs/',
                                        u'immutable': True,
                                        u'type': u'string'},
                        u'content_version': {u'description': u'Git revision of the pack content to use for this action execution (git commit sha / tag / branch). Only applies to packs which are git repositories.',
                                            u'required': False,
                                            u'type': [u'string', 'null']},
                        u'debug': {u'default': False,
                                u'description': u'Enable runner debug mode.',
                                u'required': False,
                                u'type': u'boolean'},
                        u'env': {u'description': u'Environment variables which will be available to the script.',
                                u'type': [u'object', 'null']},
                        u'force': {u'default': False,
                                u'description': u'Set to True to force install the pack and skip StackStorm version compatibility check',
                                u'required': False,
                                u'type': u'boolean'},
                        u'log_level': {u'default': u'DEBUG',
                                    u'description': u'Default log level for Python runner actions.',
                                    u'enum': [u'AUDIT',
                                                u'CRITICAL',
                                                u'ERROR',
                                                u'WARNING',
                                                u'INFO',
                                                u'DEBUG'],
                                    u'type': u'string'},
                        u'packs': {u'items': {u'type': u'string'},
                                u'required': True,
                                u'type': u'array'},
                        u'timeout': {u'default': 600,
                                    u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds.",
                                    u'type': u'integer'},
                        u'verifyssl': {u'default': True, u'type': u'boolean'}},
        'title': u'download',
        'type': 'object'}

    On instance:
        {u'abs_repo_base': u'/opt/stackstorm/packs/',
        u'debug': False,
        'force': False,
        u'log_level': u'DEBUG',
        'packs': [u'st2'],
        'python3': u'False',
        u'timeout': 600,
        u'verifyssl': True}
        ...
        ...

##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report

##### STACKSTORM VERSION
3.0.1 Ubuntu packages Xenial distro.

**Comment by Rudd-O** [comment]
The upgrade should run `st2ctl  reload --register-all` to solve the problem.

**Comment by Rudd-O** [comment]
Now `st2 run st2.executions.get` blows up with much the same error.

**Comment by LindsayHill** [comment]
Yes - running `st2ctl reload --register-all` is required when running upgrades. See https://docs.stackstorm.com/install/upgrades.html#general-upgrade-procedure

Obviously it would be better to be able to do this as part of post-install scripts or elsewhere, but I think there may be some issues related to doing this in a distributed environment. If you can figure out a way to do it automatically, PRs to https://www.github.com/StackStorm/st2-packages would be interesting.

**Comment by armab** [comment]
Closing as it's something that documented as expected StackStorm upgrade procedure.
