### ISSUE TITLE
Are there any ways to configure to conceal specific action parameters from execution history?

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm/st2#4719]
##### Summary
This is an asking about a feature to hide specific input parameters of run action from execution history.

##### ISSUE TYPE
Question / Feature request

##### Background
I want to make an action to be able to authenticate to a service with individual accounts, not only system wide one which is configured by pack.

An easy way to implement it is to add parameters to an action, that receive user account informations for a service.

##### Problem
I think anybody can see all actions' parameters and result that were executed in the past.
In this case, an automation pack designer virtually can't implement an action that deals (receive or output) with any kind of confidential data.

##### Question
Are there ways to configure any of below?

- Disable to show specific parameters of action from execution result.
- Disable to keep track of specific action parameters in execution result.

##### Related Issues
* https://github.com/StackStorm/st2/issues/2915
* https://github.com/StackStorm/st2/issues/3384

**Comment by armab** [comment]
I'm not sure if hiding action param is the way to go as this specific feature might be not that popular in a broader context.

As a workaround, do you think you can mark those specific action params as secrets (https://docs.stackstorm.com/reference/pack_configs.html#configuration-schema) so their values at least would be masked in history?

**Comment by armab** [comment]
The valid feature request that fits into StackStorm RBAC (https://docs.stackstorm.com/rbac.html#restricting-users-to-only-view-resources-they-own-or-created) functionality could be enhancing RBAC capabilities to allow users viewing history only from actions they executed.
Does that sound reasonable?

A step further from RBAC, something that solves broader problem is multi-tenancy, where multiple users can be logically isolated but share the same st2 instance. It's not something that's implemented in StackStorm yet.

**Comment by userlocalhost** [comment]
Thank you for your prompt reply. And I appreciate that you let me know the very important feature (`secret`). I completely forgot this parameter, and this is what I want!

I confirmed this parameter is valid not only for pack, but also action metadata. When `secret` parameter of action is true, user can only concealed this value from history as below.
<img width="787" alt="スクリーンショット 2019-06-24 11 07 46" src="https://user-images.githubusercontent.com/469934/59986548-4899fc00-9672-11e9-9717-91df651b16d5.png">

> In this case, an automation pack designer virtually can't implement an action that deals (receive or output) with any kind of confidential data.

I understood that my idea, that I initially posted, was completely wrong by your favor. We could make actions like this by making use of it.

Thank you!

**Comment by userlocalhost** [comment]
I realize this feature has already mentioned in the document now. It's my fault not to read it, sorry.
https://docs.stackstorm.com/actions.html?highlight=secret#action-metadata

And I appreciate your advice again, @armab.

**Comment by armab** [comment]
Glad to know that secrets solved it for you :+1:
