### ISSUE TITLE
Please run this command with root privileges | CentOS Docker | st2ctl

### ISSUE THREAD

**Issue by RaviTezu** [StackStorm/st2#4721]
##### SUMMARY
Hi, I am trying to run st2 on CentOS docker image and followed the installation steps provided in the docs. After the installation, I am trying to start the services using `st2ctl start` and it errors out saying "Please run this command with root privileges". 

``` bash
bash-4.2$ id
uid=7447 gid=0(root) groups=0(root),7447
bash-4.2$ st2ctl start
Please run this command with root privileges
```

I am doing this as part of writing the Dockerfile for installing st2 on CentOS. Unfortunately, I cannot use Ubuntu. 

##### ISSUE TYPE
 - Bug Report

I see that we are checking for uid=0 [here](https://github.com/StackStorm/st2/blob/037ca9b485eeb6e3d18846ac53073e079b1090a6/st2common/bin/st2ctl#L72) and can we skip this check if we are running st2ctl on a container?

**Comment by RaviTezu** [comment]
Found the issue. Looks the login didn't happen as root. Closing this.

**Comment by RaviTezu** [comment]
Hi, 
I would like to know why we would need root privileges to start the st2 services. Any way that we can allow non-root user to start the services in a container?

**Comment by armab** [comment]
`st2ctl restart` is just a wrapper around `service ...` commands.
You can check and run `service st2api restart` in your container from user with no privileges to verify this.

**Comment by RaviTezu** [comment]
Thanks @armab 
For security reasons we run the processes as non-root on the container and this check `uid==0` is not allowing us to use `st2ctl`. I have looked at the `Dockerfile` in `st2-devbox` and looks like `supervisord` can help us here.

**Comment by armab** [comment]
Take a look also at https://github.com/StackStorm/st2-docker/pull/162 @shusugmt work in progress with supervisord for Xenial images.
Hope that helps.

**Comment by armab** [comment]
Thanks for the report.
root privileges are indeed required for restarting a linux service. This comes from OS level and not StackStorm.
Will close this as non issue.

If you need more guidance regarding custom Docker setup, please feel free to ask in community slack or forum.
