### ISSUE TITLE
Proposal: update install documentation for ST2 on Ubuntu 18.04

### ISSUE THREAD

**Issue by barrymattingly** [StackStorm/st2#4725]
##### SUMMARY

Install Documentation for ST2 on Ubuntu 18.04 (Docs3.1dev) still includes gnupg-curl which is unavailable on 18.04 and may not be needed.

##### ISSUE TYPE
Pick one below and delete the rest:
 - Other

##### STACKSTORM VERSION
Trying to install

##### OS / ENVIRONMENT / INSTALL METHOD
Ubuntu 18.04, tried one-line install and manual install

##### STEPS TO REPRODUCE
**on 18.04
sudo apt-get install -y gnupg-curl

~ [890]$ curl -ksSL https://stackstorm.com/packages/install.sh | bash -s -- --user=st2admin --password='Ch@ngeMe'

~ [891]$ sudo apt-get install gnupg-curl

##### EXPECTED RESULTS
I expect ST2 to install via one-line install ST2.  
It appears gnupg-curl is not available on 18.04, causing an issue when it is recommended as required 

##### ACTUAL RESULTS
~ [890]$ curl -ksSL https://stackstorm.com/packages/install.sh | bash -s -- --user=st2admin --password='Ch@ngeMe'
*** Detected Distro is Ubuntu ***
*** Detected flavor bionic ***
Could not find file https://raw.githubusercontent.com/StackStorm/st2-packages/v3.0/scripts/st2bootstrap-deb.sh

~ [891]$ sudo apt-get install gnupg-curl
[sudo] password for bcm9576:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package gnupg-curl

**Comment by LindsayHill** [comment]
Looks good - and it matches what's in the installer script if you use the `--unstable` branch (those script versions have support for Bionic). 

Could you submit a docs PR? https://github.com/StackStorm/st2docs/blob/master/docs/source/install/u18.rst

Once Ubuntu Bionic support goes GA with 3.1, the installer script should Just Work, without needing the `--unstable` flag.

**Comment by LindsayHill** [comment]
Resolved by https://github.com/StackStorm/st2docs/pull/917
