### ISSUE TITLE
st2 request stucks at " Requested"

### ISSUE THREAD

**Issue by sadanand25** [StackStorm/st2#4727]
##### SUMMARY

When executing any st2 action for the first time on a fresh & clean RabbitMQ immediately after st2 startup, - it runs forewer and stuck in requested state:

root@*****:~# st2 run core.local echo 123
....................................................................................................................................................

##### ISSUE TYPE
root@ubuntu16:~# st2 execution list
+--------------------------+------------+--------------+------------------------+------------------------+----------------------+
| id                       | action.ref | context.user | status                 | start_timestamp        | end_timestamp        |
+--------------------------+------------+--------------+------------------------+------------------------+----------------------+
| 58c96cadc8980518d7cf8ada | core.local | st2admin     | requested              | Wed, 15 Mar 2017       |                      |
|                          |            |              |                        | 16:32:45 UTC           |                      |
+--------------------------+------------+--------------+------------------------+------------------------+----------------------+

##### STACKSTORM VERSION

[root@****** ~]# st2 --version
st2 2.10.1, on Python 2.7.5

##### OS / ENVIRONMENT / INSTALL METHOD

Red Hat Enterprise Linux Server release 7.6 (Maipo)

##### STEPS TO REPRODUCE
st2ctl stop 
rabbitmqctl stop_app
rabbitmqctl force_reset
st2ctl start_app

```
##### EXPECTED RESULTS
#st2 run core.local echo 123

should run..

##### ACTUAL RESULTS
[root@******* ~]# st2 run core.local echo 123
.
id: 5d1347e5c935b29fb4cdcb9f
status: succeeded
parameters:
  cmd: echo 123
result:
  failed: false
  return_code: 0
  stderr: ''
  stdout: 123
  succeeded: true

**Comment by sadanand25** [comment]
Requested to help in rectifying issue.

**Comment by armab** [comment]
I couldn't reproduce it on freshly installed `st2 3.0.1, on Python 2.7.5` in a Vagrant VM running `CentOS Linux release 7.6.1810 (Core)`.

Here is the script I tried:
```sh
#!/bin/bash

# output executed commands
set -o xtrace

sudo st2ctl stop
# emulate fresh & clean RabbitMQ
sudo rabbitmqctl stop_app
sudo rabbitmqctl reset
sudo rabbitmqctl start_app

# isolate & make sure the problem is not with RabbitMQ startup
sleep 30
# but with StackStorm startup itself
sudo st2ctl start

st2 run core.local echo 123
```

which executed successfully:
```
[vagrant@centos7 ~]$ ./test.sh 
+ sudo st2ctl stop
+ sudo abbitmqctl stop_app
sudo: abbitmqctl: command not found
+ sudo rabbitmqctl reset
Resetting node rabbit@centos7 ...
Error: mnesia_unexpectedly_running
+ sudo rabbitmqctl start_app
Starting node rabbit@centos7 ...
...done.
+ sleep 30
+ sudo st2ctl start
##### st2 components status #####
st2actionrunner PID: 11684
st2actionrunner PID: 11686
st2actionrunner PID: 11688
st2actionrunner PID: 11690
st2actionrunner PID: 11692
st2actionrunner PID: 11694
st2actionrunner PID: 11696
st2actionrunner PID: 11698
st2actionrunner PID: 11700
st2actionrunner PID: 11705
st2api PID: 11724
st2api PID: 11886
st2stream PID: 11751
st2stream PID: 11887
st2auth PID: 11802
st2auth PID: 11918
st2garbagecollector PID: 11831
st2notifier PID: 11838
st2resultstracker PID: 11845
st2rulesengine PID: 11852
st2sensorcontainer PID: 11863
st2chatops is not running.
st2timersengine PID: 11919
st2workflowengine PID: 11934
st2scheduler PID: 11951
mistral-server PID: 11981
mistral.api PID: 11980
mistral.api PID: 12168
+ st2 run core.local echo 123
.
id: 5d13631a46ab4c2ff5dc55e7
status: succeeded
parameters: 
  cmd: echo 123
result: 
  failed: false
  return_code: 0
  stderr: ''
  stdout: 123
  succeeded: true
```
We had similar issue reported before https://github.com/StackStorm/st2/issues/3290, however it was fixed a long time ago. 

Someone also will need to try reproducing it on a real RHEL 7 VM.

In a meantime, I'd suggest to debug it on a fresh new VM and latest st2 to ensure you can re-produce it consistently. Additionally, any other information we should know might help here.

**Comment by sadanand25** [comment]
Hello Eugen,

Appreciate your reply,

I will  try  as you suggested.

Thanks,

Sadanand

**Comment by trstruth** [comment]
I've seen tasks get stuck in a `requested` state when the st2scheduler process is not running.  Does `st2ctl status` show that st2scheduler is running?
