### ISSUE TITLE
Rbac roles not properly set after upgrade to enterprise.

### ISSUE THREAD

**Issue by EdwinZuidema** [StackStorm/st2#4745]
## SUMMARY

When installing the community stackstorm with this command:

`curl -sSL https://stackstorm.com/packages/install.sh | bash -s -- --user=st2admin --password='Ch@ngeMe'`

and then doing the upgrade to the enterprise version, with this command:

```
curl -s https://${EWC_LICENSE_KEY}:@packagecloud.io/install/repositories/StackStorm/enterprise/script.deb.sh | sudo bash
sudo apt-get install -y bwc-enterprise
```

RBAC is enabled by default, but no admin roles are granted for the Stanley and st2admin users, leading to the UI giving cryptic error messages:

```
Unable to retrieve action spec. main.js:1:599802
Error: "Request failed with status code 403"
```

### STACKSTORM VERSION

`st2 3.1.0, on Python 3.6.8`

##### OS, environment, install method

Ubuntu Server 18.04, one line install

## Steps to reproduce the problem

See summary.

## Expected Results

Stanley and st2admin users already having admin RBAC roles after upgrade to enterprise, or at least an error message stating what the actual problem is (the user not having access due to RBAC restristions), instead of the cryptic 403 error in the console.

## Actual Results

See summary.

**Comment by armab** [comment]
Thanks for the report!
The documentation instructions seems to be wrong.

The upgrade instructions from community -> enterprise should be the same as running enterprise install via `https://stackstorm.com/bwc/install.sh` script.
