### ISSUE TITLE
Drop Ubuntu14 support

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#4747]
As we shipped Ubuntu18 with Python 3 in `v3.1`, we'll need to deprecate Ubuntu Trusty 14.04 LTS support which reached end of its life.

We still ship U14 packages, the are several items to close the loop and deprecate Ubuntu Trusty:
- [x] remove from [st2docs](https://github.com/StackStorm/st2docs)
- [x] [st2cd automation](https://github.com/StackStorm/st2cd)
- [x] [st2ci automation](https://github.com/StackStorm/st2ci)
- [x] [st2vagrant](https://github.com/StackStorm/st2vagrant)
- [x] stop building U14 packages (across all the repos)
  - [x] remove U14 from CircleCI config [st2](https://github.com/StackStorm/st2)
  - [x] remove U14 from [packaging dockerfiles](https://github.com/StackStorm/st2packaging-dockerfiles)
  - [x] remove U14 from [st2-packages](https://github.com/StackStorm/st2-packages)
  - [x] [st2web](https://github.com/StackStorm/st2web)
  - [x] [st2chatops](https://github.com/StackStorm/st2chatops)
    + [x] [hubot-stackstorm](](https://github.com/StackStorm/hubot-stackstorm) (if neccessary - possibly node.js version bump)
      * [x] [st2client.js](https://github.com/StackStorm/st2client.js) (if necessary - possibly node.js version bump)
  - [ ] something else?
- [x] Configuration Management
  - [x] Ansible https://github.com/StackStorm/ansible-st2/issues/246
  - [x] Puppet https://github.com/StackStorm/puppet-st2/issues/274
  - [x] ~Chef https://github.com/StackStorm/chef-stackstorm/issues/73~ repo to be deprecated
- [x] st2-docker? - Decide what to do

**Comment by amanda11** [comment]
I think ansible and puppet items on this list are done...

**Comment by armab** [comment]
@amanda11 Thanks for the follow-up!
Looks like the only missing item is https://github.com/StackStorm/st2packaging-dockerfiles/pull/85. @blag there looks like a very minor change requested before we can merge it.

**Comment by armab** [comment]
Looks like all the items are finally completed.
Closing.
