### ISSUE TITLE
CentOS/RHEL 8 support

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#4761]
Similar to recently added Ubuntu Bionic packages for StackStorm, add support for CentOS/RHEL 8 with python 3 and MongoDB 4.

**Comment by punkrokk** [comment]
We have the docker packages merged and building:  https://github.com/StackStorm/st2packaging-dockerfiles/pull/74

**Comment by armab** [comment]
Initial EL8 support in StackStorm is finished :checkered_flag: by @punkrokk  and will be released with the st2 `v3.2`

**Comment by armab** [comment]
From the https://github.com/orgs/StackStorm/projects/9 project only post-tasks related to deployment methods (Ansible, Puppet, Chef, etc) are missing which will be added after `v3.2` release.
