### ISSUE TITLE
Currently breaking CIs: AMQP/Kombu dependency conflict

### ISSUE THREAD

**Issue by GuiTeK** [StackStorm/st2#4770]
## SUMMARY

The ST2 requirements.txt currently on master (from commit https://github.com/StackStorm/st2/commit/a9f72ae54f41ead4dd7c20a0bf53be5bed0c6127) requires `amqp==2.5.0` and `kombu==4.6.4`. The problem is, `kombu==4.6.4` requires `amqp==2.5.1`, so there is a **dependency conflict**.

Pip fails with the following error:
```
ERROR: kombu 4.6.4 has requirement amqp<3.0,>=2.5.1, but you'll have amqp 2.5.0 which is incompatible.
```

When using a **recent version of `pip`** (e.g. 19.2.2), this will cause pip to **fail to install the requirements**. However, if you try with an old version (e.g. 8.1.1), it will work. I don't know at which specific version of Pip it stops working.

I think ST2 requirements.txt should require `amqp==2.5.1` instead of `amqp==2.5.0`. I made the PR: https://github.com/StackStorm/st2/pull/4771

**Note**: this might be considered urgent because as https://github.com/StackStorm-Exchange/ci uses the master branch of ST2 and not a specific version, **it is currently breaking CIs** (depending on what version of Pip is used by the CI).

### STACKSTORM VERSION

Current master branch, 26ffc2f4fe16b7a5b6fe46b98e32daf88e473dde

##### OS, environment, install method

N/A

## Steps to reproduce the problem

It's easier to reproduce with Docker.

1. Start a container with the following command: `docker run -it ubuntu:16.04 /bin/bash`
2. Run the following commands inside the Docker container:
```
apt-get update
apt-get install python3 python3-pip python3-dev git build-essential libffi-dev libssl-dev nano
pip3 install virtualenv # To have a newer version of pip easily
virtualenv st2-amqp-test
cd st2-amqp-test
source ./bin/activate
# Create the st2/requirements.txt file
pip install -r requirements.txt # This will fail
```

## Expected Results

Should correctly install all the dependencies when doing `pip install -r requirements.txt`.

## Actual Results

Pip fails with the following error:
```
ERROR: kombu 4.6.4 has requirement amqp<3.0,>=2.5.1, but you'll have amqp 2.5.0 which is incompatible.
```

**Comment by blag** [comment]
Yep, I've got a PR incoming that fixes this. Thanks!
