### ISSUE TITLE
Rhel patching through Ansible

### ISSUE THREAD

**Issue by sadanand25** [StackStorm/st2#4815]
SUMMARY

Hello Team, we have created role for RHEL 6,7 patching through Ansible, 
before automation we following below step. 
 1. pre artifacts.
  2. Before patching plain reboot.
  3. Patching excluding kernel and reboot
  4. Kernel patching and reboot.
 
main role execution :
#cat  runsetup.yml
---
- name: Performing multiple commands
  hosts: patch
  become: yes
  gather_facts: no
  any_errors_fatal: false
  roles:
        - patch_server2

# cd patch_servers

#tree

.
|-- defaults
|   `-- main.yml
|-- files
|-- handlers
|   `-- main.yml
|-- meta
|   `-- main.yml
|-- README.md
|-- tasks
|   |-- after_patch_reboot.yml
|   |-- check_uptime.yml
|   |-- display_details.yml
|   |-- fetch_data.yml
|   |-- kernel_com.yml
|   |-- kernel_mail.yml
|   |-- kernel_pat.yml
|   |-- main.yml
|   |-- patching.yml
|   |-- post_mail.yml
|   |-- pre_commands.yml
|   `-- pre_mail.yml
|-- templates
|-- tests
|   |-- inventory
|   `-- test.yml
`-- vars
    `-- main.yml

ISSUE TYPE:

We facing below issues.
 1. Sometimes playbook stucks eventhough task get completed in the background.
 2. For one host patching, error mail came successfully, if we tired to patch more than one server mail will came for last server.
we need error mail should came for each hosts while performing patching.

Ansible VERSION
ansible 2.6.1

OS / ENVIRONMENT / INSTALL METHOD

Red Hat Enterprise Linux Server release 7.6 (Maipo)

STEPS TO REPRODUCE

ansible runsetup.yml

##### EXPECTED RESULTS
we need error mail should came for each hosts while performing patching.
and palybook should not stuck .

**PLEASE READ**: If you are a paid Extreme Workflow (EWC) customer, please contant [Extreme
Network GTAC](https://gtacknowledge.extremenetworks.com/articles/How_To/How-to-contact-Extreme-Networks-Global-Technical-Assistance-Center-GTAC)
or send an email to support@stackstorm.com

For free community support, please use out forum at [https://forum.stackstorm.com](https://forum.stackstorm.com)

**Comment by armab** [comment]
Thank you very much for your interest in StackStorm!

This appears to be a general use question related to Ansible and not a bug report or feature request to StackStorm core.

We'll suggest to ask questions about general use in Slack Community https://stackstorm.com/#community or forum at https://forum.stackstorm.com

If you still feel it's a StackStorm bug, - please investigate further and feel free to re-open the issue and provide more information including logs and examples for us to reproduce this in isolated and simple way.
