### ISSUE TITLE
Canceling a task makes UI unusable

### ISSUE THREAD

**Issue by nicholasamorim** [StackStorm/st2#4836]
## SUMMARY

I've had a `core.http` task running and I cancelled it on the UI. Once I did that the UI became unusable. See screenshots below. The UI never loads.

![Screenshot 2019-12-18 at 22 49 34](https://user-images.githubusercontent.com/2200260/71122286-e406c680-21e8-11ea-8f69-07ba21a843d5.png)

![Screenshot 2019-12-18 at 22 49 25](https://user-images.githubusercontent.com/2200260/71122289-e79a4d80-21e8-11ea-9ef0-6b9dfa20a45f.png)

### STACKSTORM VERSION

Paste the output of ``st2 --version``:

st2 3.1.0, on Python 2.7.12

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

Debian - package install via ansible

## Steps to reproduce the problem

Not sure because it seems this only happens if you cancel at some specific point. I've cancelled tasks before and this now happened. I had 2 core.http tasks running, cancelled one and then this happened.

## Expected Results

For the UI to keep working.

## Actual Results

The screenshots posted in the description.

**Comment by nicholasamorim** [comment]
Funky, after a couple minutes some kind of cleanup or timeout happened and the UI is back in usable state, no complaints anymore.

**Comment by armab** [comment]
I assume this could be closed?

If still in issue, please report a bug in https://github.com/stackstorm/st2web instead
