### ISSUE TITLE
An exception is raised when calling MockDatastoreService.set_value() with a ttl

### ISSUE THREAD

**Issue by ya3xp** [StackStorm/st2#4880]
## SUMMARY

When using `MockDatastoreService.set_value()` for unit testing (e.g. via `BaseActionTestCase`), a `ValueError` exception will be raised if `ttl` argument is specified.

### STACKSTORM VERSION

`st2 3.1.0, on Python 3.6.8`

### OS, environment, install method

Custom install, but not relevant to this case, see below.

## Steps to reproduce the problem

See [code](https://github.com/StackStorm/st2/blob/6d1809a4bb577e117baa00f249757284db9c6e76/st2tests/st2tests/mocks/datastore.py#L108) for `MockDatastoreService.set_value()`. If `ttl` argument is specified, `ValueError` will explicitly be raised.

```python
class MockDatastoreService(BaseDatastoreService):
    # ...
    def set_value(self, name, value, ttl=None, local=True, scope=SYSTEM_SCOPE, encrypt=False):
        """
        Store a value in a dictionary which is local to this class.
        """
        if ttl:
            raise ValueError('MockDatastoreService.set_value doesn\'t support "ttl" argument')
        # ...
```

## Expected Results

Both `action_service.set_value()` and  `sensor_service.set_value()` support `ttl` argument. Although I understand that this argument cannot be honored in a mock situation, `MockDatastoreService`  should be consistent with the behavior of the class it is mocking - perhaps fire a warning instead of an Exception?

## Actual Results

An exception is returned while running tests:
```python
ValueError: MockDatastoreService.set_value doesn't support "ttl" argument
```
It is not possible to test actions or sensors that use `xxx.set_value()` with a `ttl` argument.

**Comment by ytjohn** [comment]
I too would like to change this behavior. I understand the ttl will not decrement, but if my code is already setting a ttl, raising this makes it impossible to truly test.  It should work just like encryption. You can pass in encrypt or decrypt arguments and even though there's no encryption, it doesn't raise that as an issue.

I've modified my local installed copy as such:

```python
    def set_value(
        self, name, value, ttl=None, local=True, scope=SYSTEM_SCOPE, encrypt=False
    ):
        """
        Store a value in a dictionary which is local to this class.
        """


        name = self._get_full_key_name(name=name, local=local)

        instance = KeyValuePair()
        instance.id = name
        instance.name = name
        instance.value = value

        if ttl:
            self._logger.warning(
                'MockDatastoreService.set_value doesn\'t fully support "ttl" argument'
            )
            instance.ttl = ttl

        self._datastore_items[name] = instance
        return True
```

And this is the result

```python
>>> import logging
>>> logger = logging.getLogger(__name__)
>>> m = MockDatastoreService(logger, "example", "MyClass")
>>> m.set_value("foo", "bar", 900)
MockDatastoreService.set_value doesn't fully support "ttl" argument
True
>>> m.get_value("foo")
'bar'
>>> m.list_values()
[<KeyValuePair name=example.MyClass:foo,value=bar>]
>>> m.list_values()[0].ttl
900
```
