### ISSUE TITLE
newer sshkeys are not working in paramiko

### ISSUE THREAD

**Issue by eedgar** [StackStorm/st2#4890]
## SUMMARY

Using ecdsa-sha2-nistp521 ssh keys do not work in stackstorm with paramiko

### STACKSTORM VERSION

st2 3.1.0, on Python 2.7.6

##### OS, environment, install method

st2-docker

Post what OS you are running this on, along with any other relevant information/

- e.g. Docker, Vagrant, Kubernetes, etc. Describe how you installed ST2
- e.g. one-line install, custom install, etc -->

## Steps to reproduce the problem

generate a newer ssh key.  
run a remote command such as ls -R   it fails. 
Switch to an older id_rsa based ssh key and it succeeds.

## Expected Results
Modern ssh keys are supported for better security.

What did you expect to happen when running the steps above?
get the results of ls /   when using a newer ssh key type.

## Actual Results
A connection failed error.

**Comment by armab** [comment]
Thanks for the report!

Can you please check if upstream paramiko is supporting that SSH key format? Or maybe they started to support it in some paramiko version?

**Comment by eedgar** [comment]
It may be fixed.  this looks like the closest bug report. https://github.com/paramiko/paramiko/issues/1565

**Comment by armab** [comment]
Thanks for finding this :+1: New question is: to which paramiko version should we upgrade to be able to fix it?
