### ISSUE TITLE
Feature Proposal: Business-key concept on workflow instances.

### ISSUE THREAD

**Issue by kedare** [StackStorm/st2#4905]
It would be interesting to implement the concept of business key when running a workflow.

The business key should be injectable via any means of running new workflow instances (sensors, webhooks), etc...

You can see an example of how business key work on Camunda for example: https://blog.camunda.com/post/2018/10/business-key/

A business key is basically an indexed unique reference that is attached to the workflow instance, to be able to locate the workflow instance (to know the status/result) without having to store somewhere else the mapping between the instance ID and the "external" ID.

A typical example would be with a rule reacting to an OpsGenie alert, to use the OpsGenie alert ID as business key to be able to easily find the workflow that has been triggered by this specific opsgenie alert (if not, it would be required to store the mapping in another database)

Maybe this could be extended to be able to attach multiple indexed metadata/keys to workflows instances and not just a single key.

**Comment by mickmcgrath13** [comment]
Thank you for the proposal!

Will Traces not do this?
https://docs.stackstorm.com/reference/traces.html

An example of how it can be used is outlined in this blog post:
https://stackstorm.com/2016/02/04/watching-watcher-test-debug-rules-trace-stackstorm-triggers/

Specifically:

---
Each sensu event has a unique id field which is used by the StackStorm Sensu event handler as the Trace Tag for the StackStorm TriggerInstance.

In this case that value is 03cce13d-3dd9-41a8-a357-b1df62ab0705. Use this value to obtain a StackStorm Trace.
```
# st2 trace list --trace-tag 03cce13d-3dd9-41a8-a357-b1df62ab0705
id: 5698439eaef3392a8c2a832a
trace_tag: 03cce13d-3dd9-41a8-a357-b1df62ab0705
start_timestamp: 2016-01-15T00:55:58.625104Z
+---------------------------+------------------+----------------------------------+
| id                        | type             | ref                              |
+---------------------------+------------------+----------------------------------+
|  5698439eaef3392a8c2a8329 | trigger-instance | sensu.event_handler              |
|  56983951aef3392ac6e7ba9c | rule             | app_remidiation.on_app_response_ |
|                           |                  | check                            |
| +5698439eaef3392a8c2a832c | execution        | app_remediation.remediate        |
|  5698439faef3392a8c2a832e | trigger-instance | core.st2.generic.actiontrigger   |
+---------------------------+------------------+----------------------------------+
```
---

**Comment by kedare** [comment]
Indeed it's exactly that :)

Thank you
