### ISSUE TITLE
Typo in #4874 breaks pack filtering by tags via the API

### ISSUE THREAD

**Issue by mweinberg-cm** [StackStorm/st2#4918]
## SUMMARY

Filtering packs by tags via the API fails due to a typo in #4874. 

### STACKSTORM VERSION

Paste the output of ``st2 --version``: 
```
st2 3.2dev (c8534cae7), on Python 3.6.9
```

##### OS, environment, install method

One-line install on Ubuntu 18.04.3 LTS. 

## Steps to reproduce the problem

curl -H "X-Auth-Token: 9c1f9268b5fb4f8aaadfea1fa4bb992e" -k https://localhost/api/v1/actions?tags=anytag

## Expected Results

Either an empty list or an action should be returned.

## Actual Results

```
root@st2-dev-01:~/.st2# curl -H "X-Auth-Token: xxx" -k https://localhost/api/v1/actions?tags=marvel-project
{
    "faultstring": "Internal Server Error"
}
```

Will provide a PR to fix this.

**Comment by armab** [comment]
Fixed via https://github.com/StackStorm/st2/pull/4919

Thanks @winem for reporting and fixing!

BTW you can use https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword github magic words to automatically close an Issue once the linked PR was merged.
