### ISSUE TITLE
Ubuntu 20.04 LTS Support

### ISSUE THREAD

**Issue by Dahfizz9897** [StackStorm/st2#4920]
Running the installation script on a new 20.04 system fails with: 
`Unsupported ubuntu flavor focal. Please use 14.04 (trusty), 16.04 (xenial) or 18.04 (bionic) as base system!`

Is there documentation about what has to happen to add support for a new OS? I am happy to take some tasks to move this along.

(I'm also pretty sure support for 14.04 was dropped: https://docs.stackstorm.com/install/system_requirements.html )

**Comment by armab** [comment]
> Please use 14.04 (trusty), 16.04 (xenial) or 18.04 (bionic) as base system!

Ubuntu Trusty is about to be fully removed in `v3.2` release which we're preparing right now.
https://docs.stackstorm.com/latest/roadmap.html#release-history
Until that we still allowed to install that platform packages for someone who wasn't fast to migrate.

**Comment by armab** [comment]
I'll just copy here for the history what was already discussed in Slack:

- Starting adding Ubuntu 20.04 LTS support would be great. However StackStorm supports python 3.6 at the moment, while Ubuntu Focal Fossa includes python 3.8. The first step is to get st2 core support that python version.
- As @blag noted, there is a project for adding `CentOS8`/`RHEL8` which can be used as an example to understand which repositories are involved: https://github.com/orgs/StackStorm/projects/9

**Comment by blag** [comment]
We don't really have good documentation for this yet.

I have created [project #12](https://github.com/orgs/StackStorm/projects/12) to track progress of adding support for Ubuntu 20.04 for testing in 3.3dev and the 3.3.0 production release.

We have a [previous project #9](https://github.com/orgs/StackStorm/projects/9) to track progress of adding support for RHEL/CentOS 8 for testing in 3.2dev and the 3.2.0 production release. That's not a 100% complete list of all of the issues/PRs, but it's close enough to get you started.

To try to make this easier for you, here's a list of many (all?) repos you will need, in the rough order you will need to change them:

* [ ] [**st2-packages**](https://github.com/StackStorm/st2-packages) (create a branch with the installer script for the OS you want to support)
* [ ] [**st2vagrant**](https://github.com/StackStorm/st2vagrant) (add support and use environment variables to use your st2-packages branch)
* [ ] [**st2**](https://github.com/StackStorm/st2) - update `.circleci/config.yml` to add Ubuntu 20.04 to `DISTROS` for packaging
  - [ ] [st2web](https://github.com/StackStorm/st2web) (if necessary - possibly node.js version requirement bump) 
  - [ ] [st2chatops](https://github.com/StackStorm/st2chatops) (if necessary - possibly node.js version requirement bump)
    + [ ] [hubot-stackstorm](https://github.com/StackStorm/hubot-stackstorm) (if necessary - possibly node.js version requirement bump)
      - [ ] [st2client.js](https://github.com/StackStorm/st2client.js) (if necessary - possibly node.js version requirement bump)
* [ ] [**st2docs**](https://github.com/StackStorm/st2docs)
* [ ] [st2ci](https://github.com/StackStorm/st2ci)
* [ ] [st2cd](https://github.com/StackStorm/st2cd)
* [ ] Docker and imaging - seek help from ST2 maintainers
  - [ ] [st2-dockerfiles](https://github.com/StackStorm/st2-dockerfiles)
  - [ ] [st2-docker](https://github.com/StackStorm/st2-docker)
  - [ ] [packer-st2](https://github.com/StackStorm/packer-st2)
* [ ] Configuration management - seek help from ST2 maintainers
  - [ ] [ansible-st2](https://github.com/StackStorm/ansible-st2)
  - [ ] [chef-stackstorm](https://github.com/StackStorm/chef-stackstorm)
  - [ ] [puppet-st2](https://github.com/StackStorm/puppet-st2)

Don't feel intimidated by that list, just take it one step at a time. You don't need to do all or any of that yourself. I have bolded the four repositories you could probably do by yourself.

The ST2 maintainers who are interested in/use the docker, packer, and configuration management repositories will likely pitch in once support is added to the ST2 code and packaging repos. And one of us will probably also extend the st2ci and st2cd repos for you.

**Comment by GuiTeK** [comment]
Is there a planned release date for Ubuntu 20.04 ST2 package? Also, are the guidelines/checklist posted by @blag still up-to-date/valid?

**Comment by blag** [comment]
As far as I am aware, yes, that checklist is up-to-date. Our current plan is to support Ubuntu 20.04 in StackStorm v3.5, and work has not yet begun to support Ubuntu 20.04.

StackStorm v3.4 will be released in a week or two, and work on v3.5 will commence after that. Currently, v3.5 is planned for release in April/May 2021, although that may be pushed back a bit since the v3.4 release is running late.

**Comment by amanda11** [comment]
Ubuntu 20.04  3.5dev packages are now available in the "unstable" package. 3.5 release date will be discussed at the June TSC.

**Comment by winem** [comment]
@GuiTeK 3.5.0 is released and U20 support was added with this release. Happy testing!
