### ISSUE TITLE
Push Stackstorm 3.2 to Docker Hub

### ISSUE THREAD

**Issue by TunaYagci** [StackStorm/st2#4948]
## SUMMARY

We need the `stackstorm/stackstorm:3.2` image. The latest image is [stackstorm/stackstorm:3.1](https://hub.docker.com/layers/stackstorm/stackstorm/3.1/images/sha256-b5d0f92901dad1e24b98cb335b8124cffe729ca264216478fa9d32a00b6b8822?context=explore)

You may ask why don't you use [stackstorm/stackstorm:latest ](https://hub.docker.com/layers/stackstorm/stackstorm/latest/images/sha256-1358d05502aa39e67a54432d96ebd449810e6224d01630901f11f329d2666f7b?context=explore)image which is 3.2. Reason why is that it's not tagged and not suitable for a CI (latest means it can change at any point).

### STACKSTORM VERSION

3.2

##### OS, environment, install method

Docker

**Comment by armab** [comment]
Thanks for your message.

There is no `stackstorm:3.2` image for the current all-in-one [`st2-docker`](https://github.com/stackstorm/st2-docker) and we don't plan to push one as that project relies on `Ubuntu Trusty` we just dropped support for.

An alternative to this is a replacement in st2-dockerfiles which is based on `Ubuntu:Bionic` and `python 3`. If you're motivated, try docker-compose with those StackStorm images, test and provide your feedback at https://github.com/StackStorm/st2-dockerfiles/pull/28

**Comment by armab** [comment]
https://github.com/stackstorm/st2-docker project has been revamped and relies on https://github.com/StackStorm/st2-dockerfiles which have 3.2 images in Docker hub.
