### ISSUE TITLE
Need help on bastion host configuration in stack storm.

### ISSUE THREAD

**Issue by saisandeepachanta** [StackStorm/st2#4967]
**PLEASE READ**: If you are a paid Extreme Workflow (EWC) customer, please contact [Extreme
Network GTAC](https://gtacknowledge.extremenetworks.com/articles/How_To/How-to-contact-Extreme-Networks-Global-Technical-Assistance-Center-GTAC).

For free community support, please use our forum at [https://forum.stackstorm.com](https://forum.stackstorm.com)

Team,

I would be really greatfull to you in someone helps me with this current situation. I have one single jump server to get on to all the hosts in my environment. i had to know how to use my jump box as bastion host and trigger my automations on target hosts. 

Command line arguments are working, but i am not able to figure out how to do in stackstorm.

ssh -q -i /root/ntp/id_rsa  -o StrictHostKeyChecking=no -o "proxycommand ssh -q -W %h:%p -o StrictHostKeyChecking=no root@jumpbox" root@$vmname < /root/ntp/actions/checkfix_ntp

**Comment by saisandeepachanta** [comment]
@lakshmi-kannan @lattwood i saw your expertise on this issue. request you please help me.

**Comment by armab** [comment]
Github repository is for bugs, issues and code.

Please use StackStorm Forums https://forum.stackstorm.com/ or Slack Community https://stackstorm.com/#community for asking questions.

Thanks!
