### ISSUE TITLE
 Importing ABC directly from collections has been deprecated and will be removed in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [StackStorm/st2#5006]
## SUMMARY

 Importing ABC directly from collections has been deprecated and will be removed in Python 3.10 . Use collections for Python 2 and collections.abc for Python 3. six also has a fix with six.moves.collections_abc .

### STACKSTORM VERSION

master branch and Python 3.8

```
st2client/st2client/utils/types.py
27:class OrderedSet(collections.MutableSet):

st2common/st2common/util/db.py
32:    elif isinstance(value, collections.Mapping):

st2common/st2common/util/pack.py
126:        if isinstance(attribute, (tuple, list, collections.Iterable)):

st2common/st2common/util/types.py
27:class OrderedSet(collections.MutableSet):

st2common/st2common/util/misc.py
140:        if isinstance(v, collections.Mapping):

```

**Comment by armab** [comment]
Thanks for the heads up!

We don't support python `3.8` yet and there were problems reported from someone who even tried st2 with `3.7` version before https://github.com/StackStorm/st2/pull/4855. Currently `py27` and `py36` are part of the st2 build matrix (ex: https://travis-ci.org/github/StackStorm/st2/builds/711187690) and having `py38` in that list would be great, especially considering https://github.com/StackStorm/st2/issues/4920.

We would absolutely welcome any code contributions to improve the python versioning/support!
