### ISSUE TITLE
workflow retry 'parent_task.child_task'

### ISSUE THREAD

**Issue by guzzijones** [StackStorm/st2#5009]
https://github.com/StackStorm/st2/blob/d61b563c418f0f82f339a67053df421c8bbbc6c1/st2common/st2common/services/workflows.py#L505

1.tasks =  split task on dot
2. find tasks[0] task in workflow
3. if tasks[1] exists then set this task as running and recurse back into this function using tasks[1] and workflow from tasks[0] if it is a workflow

**Comment by armab** [comment]
@guzzijones Is it possible to adjust the issue to be less cryptic in front of StackStorm Community?
Please provide clear title, describe what's the problem is and more details in the Issue description.

**Comment by armab** [comment]
Closing due to no response or details provided.
