### ISSUE TITLE
Remove mistral from the launch_dev.sh script

### ISSUE THREAD

**Issue by punkrokk** [StackStorm/st2#5012]
The[ launch_dev.sh](https://github.com/StackStorm/st2/blob/master/tools/launchdev.sh#L96) script has funtionality that needs to get removed so it doesn't try to spin up mistral things

**Comment by amanda11** [comment]
Is this not part of all of the mistral bits of st2 that get removed, or does this need to be done separately, earlier etc?

I can split it out of the PR I'm working on to remove mistral from st2 repo, if we want it earlier and if it can be done separately.

**Comment by armab** [comment]
There is no need of separation so far. Launchdev script is just one of the places to touch.

**Comment by punkrokk** [comment]
I did not see it in the list so I documented with an issue

JP Bourget / @punkrokk

**Comment by amanda11** [comment]
I will update my pr so it references this issue as well
