### ISSUE TITLE
Remove keys by pattern from store

### ISSUE THREAD

**Issue by alirezastack** [StackStorm/st2#5015]
Sometimes it is necessary to delete bunch of keys based on a specific pattern. Is it possible to have this feature so users can delete keys by a pattern:

`st2 delete key MyData*`

**Comment by nzlosh** [comment]
Have you looked at the option to delete by prefix?

`st2 key delete_by_prefix --help`

**Comment by armab** [comment]
Closing as the question was answered by @nzlosh
