### ISSUE TITLE
Support running sensors using Python 3 virtual environments

### ISSUE THREAD

**Issue by dove-young** [StackStorm/st2#5020]
Running sensors using Python 3 virtual environments is not supported so far. 

https://github.com/StackStorm/st2/blob/master/st2reactor/st2reactor/container/process_container.py

```
        # NOTE: Running sensors using Python 3 virtual environments is not supported
        uses_python3, _ = is_pack_virtualenv_using_python3(pack=sensor['pack'])

        if uses_python3 and not six.PY3:
            format_values = {'pack': sensor['pack'], 'virtualenv_path': virtualenv_path}
            msg = PACK_VIRTUALENV_USES_PYTHON3 % format_values
            raise Exception(msg)
```

We are using stackstorm-ha in K8S and build StackStorm images with Python 3.  Since docker images have only python 3 installed,  we need to running sensors using Python 3.

**Comment by punkrokk** [comment]
@armab Is this a known `ST2 on K8s` limitation? Python3 sensors are the default on U18 and EL8.

**Comment by armab** [comment]
[`stackstorm-ha`](https://github.com/stackstorm/stackstorm-ha) is based on Docker images with `Ubuntu Bionic` and `python 3`.


@dove-young Is that original deployment method you're using or are there any modifications made? You noticed you build your own images, can you provide more details?

How do you install packs in K8s?
How do you run them and what error did you get?

**Comment by armab** [comment]
FYI this code `if uses_python3 and not six.PY3:` indicates that base environment is python 2, but the virtualenv pack was built with python 3.

**Comment by armab** [comment]
Issue here with the code logic is about running StackStorm in Python 2, while trying to use Sensors with python 3 virtualenv.

Closing, as from the upcoming StackStorm `v3.4.0` release we're switching the core platform to Python 3 only.
