### ISSUE TITLE
Show & Log a py2 deprecation warning on st2 services startup

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#5041]
An addition to [Add python warning if install a pack that only supports python 2 #5037 PR](https://github.com/StackStorm/st2/pull/5037) and [Python 2 Deprecation Game Plan](https://github.com/StackStorm/discussions/issues/40), apart of warning for `pack install`, we might need to also warn users that's running StackStorm in py2 environment.

I'd suggest to show and log that warning for each st2 service during its initial startup, but open to other ideas.
Maybe also show for every `st2ctl` execution?

**Comment by amanda11** [comment]
@armab  I think we can close this now?

**Comment by armab** [comment]
@amanda11 Sure, thanks for the follow-up :+1: 
Feel free to manage/triage issues if you'll see anything like that in the future.
