### ISSUE TITLE
Failed with assert len(split) == 3\n in python_runner.py

### ISSUE THREAD

**Issue by armudgal** [StackStorm/st2#5063]
## SUMMARY

I am trying to run an action but it fails with the follwing error
```
{
  "traceback": "  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/container/base.py\", line 127, in _do_run\n    (status, result, context) = runner.run(action_params)\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_runner.py\", line 267, in run\n    return self._get_output_values(exit_code, stdout, stderr, timed_out)\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_runner.py\", line 317, in _get_output_values\n    assert len(split) == 3\n",
  "error": ""
}
```
### STACKSTORM VERSION

`st2 3.1.0, on Python 2.7.6`

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

Running st2 on docker

## Steps to reproduce the problem

I am sorry I won't be able to share the sensitive details. I am still not able to figure out how to reproduce this problem with a minimal setup. I would like to understand the various reasons why this might be causing an issue.

## Expected Results

Action to run successfully

## Actual Results

```
{
  "traceback": "  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/container/base.py\", line 127, in _do_run\n    (status, result, context) = runner.run(action_params)\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_runner.py\", line 267, in run\n    return self._get_output_values(exit_code, stdout, stderr, timed_out)\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_runner.py\", line 317, in _get_output_values\n    assert len(split) == 3\n",
  "error": ""
}
```

Thanks!

**Comment by blag** [comment]
StackStorm 3.1 is really old, and isn't officially supported anymore. Please upgrade to a newer version of StackStorm and verify that the problem still exists.

Alternatively, you can see if there are any [professional StackStorm partners](https://stackstorm.com/partners/) who might be able to help you with this.

**Comment by blag** [comment]
I'm closing this issue since there isn't much that we can do here. But if you verify that the issue still exists in a more up-to-date version of StackStorm, please post back here instead of creating a new issue and we can reopen this issue for you. Thanks!

**Comment by armudgal** [comment]
Really appreciate it. We are in the process of moving to a newer version. Thanks a lot for the help
