### ISSUE TITLE
Remove the st2resulstracker service from st2ctl and development env

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#5070]
Mistral was deprecated and removed from the st2 in `v3.3.0` release. However there is a `st2resultstracker` service which is used for polling result from async runner. Mistral was the only async runner which means resultsracker is obsolete and could be disabled.

Team agreed that we should keep the service implementation in st2 codebase if we'll need it in future, but remove service from the associated packaging/startup logic, st2ctl , development env.

This should be easy & fun task, if anyone from @StackStorm/contributors wants to help removing that.

**Comment by winem** [comment]
Hi, 

I can tackle this one as well as it's also needed to let the tests in https://github.com/StackStorm/st2-packages/pull/683 pass again. 

What about the logrotate.conf, st2actions/conf/(logging|syslog).resultstracker.conf and the screen config? It shouldn't harm to keep them in the code base although there'll be no corresponding service but these configs can easily be re-created. So I tend to remove them as well. 

Will provide a PR as soon as we agreed on something regarding the 4 files mentioned above.

**Comment by armab** [comment]
Yes, I think you're right about the need of removing resultstracker from the files you mentioned.

**Comment by winem** [comment]
Done. Hope this fits your expectations. :)
