### ISSUE TITLE
St2Stream service broken when using SSL with mongodb

### ISSUE THREAD

**Issue by christopher-russell** [StackStorm/st2#5078]
## SUMMARY

This issue is an extension to #4832 however this time it is the st2stream service, I have looked that the code and can see the same monkey patch code hasn't been applied to the st2stream app

### STACKSTORM VERSION

Paste the output of ``st2 --version``: 3.3.0

##### OS, environment, install method

Docker compose with the split services and mongo db references commented out so that an external db can be used  https://github.com/StackStorm/st2-docker/blob/master/docker-compose.yml

All other services correctly connected to mongodb.net test instance with the exception of st2stream.

## Steps to reproduce the problem

use docker yaml at https://github.com/StackStorm/st2-docker/blob/master/docker-compose.yml, comment out mongo container and references, adjust files/st2-docker.conf to point to external DB with SSL = True enabled.
docker-compose up

## Expected Results

What did you expect to happen when running the steps above?

st2stream to operate correctly

## Actual Results

What happened? What output did you get?

2020-11-16 05:48:55,053 WARNING [-] Retry on ConnectionError - Cannot connect to database default :
maximum recursion depth exceeded

Adding monkey patch code to st2stream app resolves the issue (manually injected into container to test).

file:   st2stream/cmd/api.py
Code: 
from st2common.util.monkey_patch import monkey_patch
monkey_patch()

**Comment by armab** [comment]
Thanks for the report!

Considering there is an example PR to fix it for other services, we'd love to accept external contributions to fix this for str2stream as well. Help wanted.

**Comment by punkrokk** [comment]
What line did you put the monkey patch in?

**Comment by christopher-russell** [comment]
Hey, I added the line just below the copyright 

https://github.com/StackStorm/st2/blob/ce31176556be506606b83f6854630f8e6c0fd5ea/st2stream/st2stream/cmd/api.py#L15

from st2common.util.monkey_patch import monkey_patch
monkey_patch()

**Comment by armab** [comment]
@christopher-russell should be easy to submit a PR then. Can you do it?

**Comment by christopher-russell** [comment]
No worries, I'll submit a PR

**Comment by christopher-russell** [comment]
I've submitted in https://github.com/StackStorm/st2/pull/5091
