### ISSUE TITLE
TODO: Remove the --python3 flag and warning in packs.install

### ISSUE THREAD

**Issue by blag** [StackStorm/st2#5110]
Follow up from #5100 and [the Slack thread](https://stackstorm-community.slack.com/archives/CSBELJ78A/p1608901763314300?thread_ts=1608157605.269500&cid=CSBELJ78A) - remove the `--python3` flag to st2client entirely, including the deprecation warning.

**Comment by amanda11** [comment]
I'm happy to take this on, as I think I removed it once, and then put it back as we hadn't warned about its deprecation...
