### ISSUE TITLE
 YaqlEvaluationException: Unable to evaluate expression '<%= obj.flashvars %>'. YaqlGrammarException: Parse error: unexpected '=' at position 0 of expression '= obj.flashvars

### ISSUE THREAD

**Issue by DaemonShao** [StackStorm/st2#5133]
## SUMMARY

There are some problems with Orquesta workflow execution
```python
{
  "output": null,
  "errors": [
    {
      "type": "error",
      "message": "YaqlEvaluationException: Unable to evaluate expression '<%= obj.flashvars %>'. YaqlGrammarException: Parse error: unexpected '=' at position 0 of expression '= obj.flashvars"
    }
  ]
}
```
Enter the log field may have some html tags

### STACKSTORM VERSION

st2 3.3.0, on Python 3.6.9

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

ubuntu 18.04 apt install

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

## Expected Results

Action to run successfully

## Actual Results

```python
{
  "output": null,
  "errors": [
    {
      "type": "error",
      "message": "YaqlEvaluationException: Unable to evaluate expression '<%= obj.flashvars %>'. YaqlGrammarException: Parse error: unexpected '=' at position 0 of expression '= obj.flashvars"
    }
  ]
}
```

**Comment by blag** [comment]
What happens when you remove the `=` from the `<%=`?

**Comment by DaemonShao** [comment]
<%= obj.flashvars %> is not defined in my Workflow, I don't know where it comes from

**Comment by blag** [comment]
Are you using any workflows in your workflow that define that somewhere?

That error snippet does not look like anything that would be in Orquesta, so I'm fairly certain this is not a valid Orquesta bug.

**Comment by nzlosh** [comment]
Closing this issue.  Unable to reproduce and unable to diagnose further due to lack of response from the OP.
