### ISSUE TITLE
should check both 'http_proxy' and 'HTTP_PROXY' when get proxy info from environment variables

### ISSUE THREAD

**Issue by wfgydbu** [StackStorm/st2#5137]
## SUMMARY

I just faced an embarrassed problem that command `st2 action list` keeps return 503. 

I tried `st2 --debug action list` and the result in line  `HTTP_PROXY`(**uppercase**) was empty. This mislead me that the proxy info was set(which is not).

I finally found that the root cause is a **lowercase** `http_proxy` env variable was set in the system.

So I think it maybe more friendly to check both 'http_proxy' and 'HTTP_PROXY' to get proxy info when using st2 command with `--debug` option.

related code:
https://github.com/StackStorm/st2/blob/5c4e5f8e93c7ed83c4aa4d196085c2912ae7b285/st2client/st2client/base.py#L404

### STACKSTORM VERSION

3.3

##### OS, environment, install method
centos 7.6, custom install

## Steps to reproduce the problem

1) set **lowercase** proxy environment variable, eg. `export http_proxy='127.0.0.1:8888'`
2) run `st2 --debug action list`

## Expected Results

proxy info should be printed

## Actual Results

proxy info did not show, value of HTTP_PROXY is empty.

Thanks!

**Comment by armab** [comment]
Thanks @wfgydbu, that's a valid bug report and a good find.

> So I think it maybe more friendly to check both 'http_proxy' and 'HTTP_PROXY' to get proxy info when using st2 command with --debug option.

Agree :+1:  We'd welcome code contributions to improve this.

**Comment by wfgydbu** [comment]
Thanks, @armab.

I will be very happy to make this contribution as my first PR for st2. 

Feel free to assign it to me.  :)

**Comment by S-T-A-R-L-O-R-D** [comment]
I am working on it.

**Comment by S-T-A-R-L-O-R-D** [comment]
is this issue still open, or @wfgydbu resolved it?

**Comment by wfgydbu** [comment]
@S-T-A-R-L-O-R-D  Hello, being stuck in other things, feel free to submit a pr, thanks.
