### ISSUE TITLE
Passwords in UI and CLI displayed in plain text

### ISSUE THREAD

**Issue by minsis** [StackStorm/st2#5145]
## SUMMARY

UI and CLI clients both show clear text passwords when viewing the config

### STACKSTORM VERSION

Paste the output of ``st2 --version``:

st2 3.3.0, on Python 3.6.9

##### OS, environment, install method

Oracle 7 using st2-docker

## Steps to reproduce the problem

Here I'm just using the core.remote action on an interval timer

## Expected Results

Password shouldn't be displayed in clear text in the config. When going to edit or run the action the password is hidden.

## Actual Results

What happened? What output did you get?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!
![image](https://user-images.githubusercontent.com/11248197/107436973-e8302a80-6af3-11eb-9276-133459063da7.png)

![image](https://user-images.githubusercontent.com/11248197/107437237-4c52ee80-6af4-11eb-94f7-fd933c703365.png)

**Comment by blag** [comment]
To be clear, the issue here is that, in the rule widget, action parameters and action runner parameters that are marked `secret: true` are not properly obfuscated by the server.

This probably also happens for the `passphrase`, `private_key`, and `sudo_password` parameters to the remote runner.

**Comment by blag** [comment]
A better place to report this might be https://github.com/StackStorm/st2web.

**Comment by minsis** [comment]
Moved to https://github.com/StackStorm/st2web/issues/896
