### ISSUE TITLE
Special characters in st2admin account causing st2 key failure

### ISSUE THREAD

**Issue by maxfactor1** [StackStorm/st2#5180]
Just upgraded to version 3.4 and my keyvault is having problems. I believe it's due to my st2admin password containing special characters.

```
[root@stackstorm workflows]# st2 key list --scope=all
Traceback (most recent call last):
  File "/bin/st2", line 10, in <module>
    sys.exit(main())
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/shell.py", line 470, in main
    return Shell().run(argv)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/shell.py", line 385, in run
    config = self._parse_config_file(args=args, validate_config_permissions=False)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/base.py", line 183, in _parse_config_file
    result = parser.parse()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/config_parser.py", line 197, in parse
    value = get_func(section, key)
  File "/usr/lib64/python3.6/configparser.py", line 800, in get
    d)
  File "/usr/lib64/python3.6/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib64/python3.6/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%3C#V~Bvg%3E3t+'
```

This password above is what I used to install stackstorm. Or at least part of it. I've since changed the password via the documented htpasswd method, but the issue persists. Any tips? Left the password in for research purposes.

curl -sSL https://stackstorm.com/packages/install.sh | bash -s -- --user=st2admin --password='q7j/t%3C#V~Bvg%3E3t+'

**Comment by blag** [comment]
I'd like to verify if this is a regression or not. Can you try installing StackStorm v3.3.0 with the same password and see if you run into the same issue?

```bash
curl -sSL https://stackstorm.com/packages/install.sh | bash -s -- --version=3.3.0 --user=st2admin --password='q7j/t%3C#V~Bvg%3E3t+'
```

**Comment by maxfactor1** [comment]
I was running 3.3.0 before upgrading to 3.4.0. I had no issues then. I've gone ahead and reinstalled st2 at this time with a different password.

**Comment by blag** [comment]
Right, but does the install script for 3.3.0 have the same issue as the install script for 3.4.0? Please install 3.3.0 again on a non-production system with the problematic password `q7j/t%3C#V~Bvg%3E3t+` using the command I previously specified and see if the same error happens.

That will tell me if we broke something in the 3.4.0 release or if this bug exists in both 3.3.0 and 3.4.0. Thanks.

**Comment by winem** [comment]
I gave it a try and this is not something that was introduced with 3.4. The issue is reproducible with 3.3 and 3.2 as well.
