### ISSUE TITLE
Fix projection queries for compatibility with Mongo DB 4.4

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#5247]
``st2 execution list`` CLI command is failing out of the box when using MongoDB.

See two comments here for more info - https://github.com/StackStorm/st2/pull/5177#issuecomment-825200761, https://github.com/StackStorm/st2/pull/5177#issuecomment-825214833.

**Comment by amanda11** [comment]
@Kami Is this issue now resolved, given the #5251 merge?

**Comment by Kami** [comment]
Yep, sorry, forgot that the issue didn't auto close (forgot to reference it in the PR description).
