### ISSUE TITLE
NodeJS upgrade

### ISSUE THREAD

**Issue by amanda11** [StackStorm/st2#5254]
Node.js 10 has been deprecated. 

Identify if Node.js can be updated, and changes required.

- [x] st2chatops - https://github.com/StackStorm/st2chatops/pull/161
- [X] st2client.js
- [X] hubot-stackstorm
- [x] st2docs
- [x] ansible-st2
- [x] puppet-st2
- [x] st2-packages
- [x] st2ci - upgrade_deps scripts

**Comment by rush-skills** [comment]
puppet-st2 as of v2.3 installs node v14 for stackstorm v3.5+, so we can consider this closed too

**Comment by armab** [comment]
Thanks @rush-skills !
