### ISSUE TITLE
E: Unable to locate package st2 St2 installation Ubuntu 16.04- 

### ISSUE THREAD

**Issue by Sudhigalagali** [StackStorm/st2#5266]
## SUMMARY

E: Unable to locate package st2 St2 installation Ubuntu 16.04-  . I get this error when I follow the instructions from 

https://docs.stackstorm.com/install/u16.html#  . All the dependencies are successful until the step to start installing ST2. Thats where its fails. I see that ST2 packages are not available at https://packagecloud.io/StackStorm/stable/ubuntu/  . 

The default script as the below path to set as repository  https://packagecloud.io/StackStorm/stable/ubuntu/   but in this location I could not find anything that is why we are getting error however the packages are found at  https://packagecloud.io/StackStorm/stable   a level down.  

Below is the output I get when I run app-get install st2

Reading package lists... Done
Building dependency tree
Reading state information... Done
N: Ignoring file 'script.deb.sh' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: Unable to locate package st2

### STACKSTORM VERSION

Paste the output of ``st2 --version``:

##### OS, environment, install method
Ubuntu 16.04. , Manual install method. 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial
## Steps to reproduce the problem
Pick this os version and start intsalling St2 through one-install or manual install

**Comment by blag** [comment]
What version of ST2 are you trying to install? The latest (3.4.1 as of this writing)?

**Comment by blag** [comment]
> N: Ignoring file 'script.deb.sh' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

Why do you have a `.sh` file in the `/etc/apt/sources.list.d/` directory? I don't think our one line installer creates that file, or at least it doesn't create that file in that location.

**Comment by Sudhigalagali** [comment]
I had downloaded that file to check   what’s inside the file after the first attempt failed. Even without that file its still the same error.  I am not using one line installer.

**Comment by Sudhigalagali** [comment]
Yes 3.4 . Followed instructions from below url.

https://docs.stackstorm.com/install/u16.html

Thanks
Sudhi

**Comment by armab** [comment]
Closing as we don't support U16 anymore.
