### ISSUE TITLE
with item is taking more time in stackstorm and workflow is getting failed if the size is more than 500

### ISSUE THREAD

**Issue by itsmano** [StackStorm/st2#5273]
## SUMMARY

When we use with items in stackstorm its taking more time. And the workflow is getting failed if the list contains more than 500 elements.

### STACKSTORM VERSION

Paste the output of ``st2 3.4dev``:

##### OS, environment, install method

Deployed st2 in HA in amazon Kubernetes 

## Steps to reproduce the problem

1. Create a workflow with two actions. 
   a. one read data from database b. iterate the values and print 
2. for list size 100 it took 3 mins, for 200 it took 15 mins. For 500 the workflow got failed
This is the error message coming
    {
      ""type"": ""error"",
      ""message"": ""Execution failed. See result for details."",
      ""task_id"": ""task2""
    },
    {
      ""type"": ""error"",
      ""message"": ""ToozConnectionError: Timeout reading from socket"",
      ""task_id"": ""task2"",
      ""route"": 0
    }
  ]
     
Thanks!
Mano Prakadeesh

**Comment by arms11** [comment]
Not sure if you came across this, but thought it would help. I really loved the details provided in the link below:
https://www.cypherint.com/post/stackstorm-faster-with-items

**Comment by itsmano** [comment]
Hi @arms11  yeah, I saw this doc.

Getting errors in this piece of code. it says st2baseurl is not available. might bcoz of config coming as None.
Do we need to replace this with IP hardcoded?

   self.client = Client(base_url=config["st2baseurl"],
                auth_url=config["st2authurl"],
                api_key=self.api_key,
                api_url=config["st2apiurl"]
                )
                
Thanks
Mano

**Comment by guzzijones** [comment]
You need to run the pack configuration.

**Comment by guzzijones** [comment]
The user needs to run the `st2 pack config`
