### ISSUE TITLE
Remove st2exporter

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2#5295]
I think we should delete all of st2exporter. According to StackStorm/st2-packages#367 it was abandoned years ago.
See also: StackStorm/st2-packages#84 StackStorm/st2packaging-dockerfiles#30

Is there any reason to keep anything in the st2exporter directory?

**Comment by armab** [comment]
+100 good find. Unused codebase just makes things more confusing, not to forget that it pollutes the tests.

@Kami @m4dcoder Do you think the https://github.com/StackStorm/st2/tree/master/st2exporter is still used somehow somewhere?
