### ISSUE TITLE
Support version pinning for pack installs

### ISSUE THREAD

**Issue by minsis** [StackStorm/st2#5296]
The workflow packs.install doesn't support version pinning even when all the actions in the work flow do support it.

This should also extend to st2client `st2 pack install <packname>:<version>` or something similar.

As a real use case our security policies are pretty strict about upgrading software. We're using Ansible to sync packs across all nodes in each HA cluster we have. If someone adds a new approved pack install, the process will then upgrade any packs which would be unintended.

**Comment by armab** [comment]
Did you try the following syntax ?
```
# Install a version tag
st2 pack install cloudflare=0.1.0

# Or a specific git commit
st2 pack install cloudflare=776b9a4
```

More examples at https://docs.stackstorm.com/packs.html#installing-a-pack

**Comment by minsis** [comment]
Apologies, somehow I missed this.

**Comment by armab** [comment]
No worries!
