### ISSUE TITLE
Usage of udatetime causing CI failures for Exchange packs

### ISSUE THREAD

**Issue by blag** [StackStorm/st2#5346]
## SUMMARY

The weekend CI tests for all 100+ StackStorm Exchange packs failed again this weekend:

```python
#!/bin/bash
~/ci/.circle/test ; ~/ci/.circle/exit_on_py3_checks $?

Traceback (most recent call last):
  File "/home/circleci/ci/.circle/validate.py", line 21, in <module>
    from st2common.models.api.pack import PackAPI
  File "/tmp/st2/st2common/st2common/models/api/pack.py", line 24, in <module>
    from st2common import log as logging
  File "/tmp/st2/st2common/st2common/log.py", line 32, in <module>
    from st2common.logging.handlers import FormatNamedFileHandler
  File "/tmp/st2/st2common/st2common/logging/handlers.py", line 24, in <module>
    from st2common.util import date as date_utils
  File "/tmp/st2/st2common/st2common/util/date.py", line 24, in <module>
    import udatetime
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/udatetime/__init__.py", line 20, in <module>
    from udatetime.rfc3339 import (
ImportError: /home/circleci/virtualenv/lib/python3.6/site-packages/udatetime/rfc3339.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __exp_finite
Unable to retrieve pack name.
Original script exit code: 1

Exited with code exit status 1

CircleCI received exit code 1
```

I believe that this time it is related to [this Debian issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954305) where the udatetime library calls out to a C library, which does not properly link to the `libm` library, as detailed in freach/udatetime#30 and fixed in freach/udatetime#31, which is a miniscule, easy fix yet has been unmerged for over a year.

The udatetime package, introduced to StackStorm [back in March](https://github.com/StackStorm/st2/pull/4846) in an attempt to optimize storage performance, has not been touched [since 2018](https://github.com/freach/udatetime/commit/75a07891426364f8bf0b44305b00bb1dd90534ae) and I believe that it's been abandoned. The author's [blog](https://aboutsimon.com/blog/) has also not seen an update since 2018, and he hasn't posted anything to [Twitter](https://twitter.com/aboutsimon) since 2018 either. His [Xing profile](https://www.xing.com/profile/Simon_Pirschel2) does indicate that he has changed jobs multiple times since 2018 though.

I believe that the udatetime pack has been abandoned. We should consider offering to help maintain it, or we should move to a different library like [ciso8601](https://github.com/closeio/ciso8601), which is actively maintained (as of this writing, the [last release](https://pypi.org/project/ciso8601/2.2.0/) was on August 6th, 2021), and is also [faster than udatetime](https://pypi.org/project/ciso8601/#benchmark), since performance was obviously a reason to select udatetime to begin with. @Kami Can we get your guidance here please?

### STACKSTORM VERSION

StackStorm installed in CircleCI build container, cloned from the `master` branch:

```bash
git clone --depth 1 --single-branch --branch master https://github.com/StackStorm/st2.git /tmp/st2
```

##### OS, environment, install method

Ubuntu 18.04
Installed via git `master` branch, see [log 1](https://app.circleci.com/pipelines/github/StackStorm-Exchange/stackstorm-test/41/workflows/115d263d-af67-4ecf-85a6-296ad85eeabc/jobs/198?invite=true#step-103-1055), and [log 2](https://app.circleci.com/pipelines/github/StackStorm-Exchange/stackstorm-fpm/81/workflows/24fb58bf-fafd-4b3d-9a16-4d73fc079137/jobs/304?invite=true#step-103-1055).

## Steps to reproduce the problem

Run pack tests in CircleCI.

## Expected Results

I expected that udatetime would be importable and not cause issues, especially when the fix is literally a one-line fix that has been [deployed in Debian for over a year](https://salsa.debian.org/python-team/packages/python-udatetime/-/commit/f803c181cb1b37b5a37debc242569dd8f3e985c4).

## Actual Results

All StackStorm Exchange weekend builds failed in CircleCI.

**Comment by Kami** [comment]
I'm fine with switching to ``ciso8601`` or a similar alternative which is (actively) maintained and support.

In fact, as you said cisto8601, may even be better choice for multiple reasons.

1. Based on their benchmarks, it's faster
2. It supports  ISO 8601 or RFC 3339 date strings. IIRC, ``udatetime`` only supports RFC 3339 so we have a catch-all fallback in case we try to parse date string udatetime doesn't directly support. Although that may not be 100% the case and we may still need a fallback, which is fine
 > Note: ciso8601 doesn't support the entirety of the ISO 8601 spec, only a popular subset

**Comment by amanda11** [comment]
We also need to switch as udatetime won't build for python 3.9 - https://github.com/freach/udatetime/issues/32.

**Comment by nzlosh** [comment]
The swtiched to `ciso8601` has been made https://github.com/StackStorm/st2/pull/5692
