### ISSUE TITLE
Github actions broken after yesterdays commit

### ISSUE THREAD

**Issue by wingiti** [StackStorm/st2#5455]
## SUMMARY
Github actions for st2 are broken because the wrong quotation marks are used in a commit which was done yesterday:
https://github.com/StackStorm/st2/commit/722f5079e42ed0228e4f50aa3c542a7abdc7bd71

Black fails because of single quotes. Maybe some automation to update the st2 version needs to be fixed to use double quotes.

Last time it was also done "manually" (I guess it was after black was introduced):
https://github.com/StackStorm/st2/commit/541f4afd12c88343b9c333e4e8e69c06d125a75e

**Comment by armab** [comment]
Good find! :+1:  @wingiti Could you please submit a quick PR to fix this?

Extra bonus points for fixing it here as well to prevent from happening in the future: https://github.com/StackStorm/st2cd/search?q=__version__

**Comment by wingiti** [comment]
PR provided.

I think the issue in st2cd was already detected and fixed in: https://github.com/StackStorm/st2cd/tree/Fix-st2_prep_dev-action-to-use-double-quotes

But looks like it was not merged to master and is therefore not used.
Nevertheless there are more files in st2cd which are related to this version strings.

**Comment by armab** [comment]
Indeed, we overlooked the https://github.com/StackStorm/st2cd/pull/464. Merged it now.

Thanks for the pointers @wingiti and PR!
