### ISSUE TITLE
Include PySocks package in st2client module.

### ISSUE THREAD

**Issue by kingsleyadam** [StackStorm/st2#5460]
## SUMMARY

By default, the st2client cli doesn't support SOCKS proxy connection using `HTTP_PROXY`, `HTTPS_PROXY` because it lacks the `pysocks` pypi package.

### STACKSTORM VERSION

```
❯ st2 --version
st2 3.5.0, on Python 3.8.12
```

### OS, environment, install method

Client: MacOS Big Sur, Python 3.8
Stackstorm: Ubuntu 18.04, Python 3.6

## Steps to reproduce the problem

Attempt to use the st2 cli with `HTTP_PROXY`, `HTTPS_PROXY` set.

## Expected Results

No errors, and able to query the stackstorm server.

## Actual Results

Currently get the following error.

```
ERROR: Missing dependencies for SOCKS support.
```

To work around this for now, I install pysocks on my virtual environment where st2client is installed `pip install pysocks==1.7.1`.

**Comment by armab** [comment]
Makes sense!

How about composing a PR to support this?

**Comment by kingsleyadam** [comment]
> Makes sense!
> 
> 
> 
> How about composing a PR to support this?
> 
> 

Yep, I can do that.

**Comment by kingsleyadam** [comment]
PR opened: https://github.com/StackStorm/st2/pull/5469

**Comment by armab** [comment]
Closed via https://github.com/StackStorm/st2/pull/5469
