### ISSUE TITLE
Can't see 3-rd party modules logs in sensor pod

### ISSUE THREAD

**Issue by DavidMeu** [StackStorm/st2#5592]
I've configured urllib3 retries,
But can't see those in sensor container pod logs.

Also tried configure urllib3 log level in sensor, but no good.

```
 logger = logging.getLogger("urllib3")
 logger.setLevel(logging.WARNING)
```

**Comment by guzzijones** [comment]
actions and sensors will ignore loggers setup like this.  You need to use the sensor's built in logger.  Also ensure that your log levels are set to enable warning logs to actually write out.
