### ISSUE TITLE
How to migrate existing Rules/Actions/Worklfows from StackStorm running in a Azure VM to Kubernetes HA Cluster?

### ISSUE THREAD

**Issue by Bindu-yadav8** [StackStorm/st2#5647]
### Discussed in https://github.com/StackStorm/st2/discussions/5618

<div type='discussions-op-text'>

<sup>Originally posted by **Bindu-yadav8** April 12, 2022</sup>
Hello,

We are using StackStorm version st2 3.4.1, deployed on a VM and are managing and running Actions & workflows on the VM. 

Now we have deployed Highly Available StackStorm cluster based on Kubernetes and wanted to migrate all the existing actions/workflows and rules into the K8 cluster.

Can anybody provide a series of steps and suggestions on how to proceed on this migration?

@armab Could you please provide some insights on this?</div>

**Comment by armab** [comment]
Github Issues are best suitable for bug reports, while Discussions for questions.
Please don't open new duplicated issues if there's already a Discussion opened.

Thanks.
