### ISSUE TITLE
how to get the "incident_key" in pagerduty integration

### ISSUE THREAD

**Issue by Anz14** [StackStorm/st2#5657]
Hi Team, I have the stackstorm setup on Ubuntu VM for alert automation. I have integrated stackstorm with pagerduty.

Action chain workflow below:

chain:

name: "jenkins_disk_action"
ref: "jenkins.jenkins_disk_action"
parameters:
triggers: "{{ triggers }}"
on-success: "post_success_to_slack"
on-failure: "pagerduty_escalation"

name: "post_success_to_slack"
ref: "slack.post_message"
parameters:
channel: "#stackstorm-alerts"
message: "{{jenkins_disk_action.result}}"

name: "pagerduty_escalation"
ref: "pagerduty.incident.create.events_v1"
parameters:
service_key: "F97CLBXTLIYOOOBN2X9M7W07LS3HV"
description: "{{jenkins_disk_action.result}}"

How can I get the incident-key to avoid de-duplication of alert. How can I call the incident-key in the action -chain yaml

**Comment by nzlosh** [comment]
Duplicate https://github.com/StackStorm/st2/discussions/5656
