### ISSUE TITLE
authentication trouble to remote host

### ISSUE THREAD

**Issue by dreyna01** [StackStorm/st2#5698]
### Discussed in https://github.com/StackStorm/st2/discussions/5694

<div type='discussions-op-text'>

<sup>Originally posted by **dreyna01** August  1, 2022</sup>
Hello all,

I'm new to Stackstorm, I'm getting this error when trying to run linux.check_loadavg from the Stackstorm server to a remote host or to itself. Any advice would be greatly appreciated. Thanks in advance

st2 --version
st2 3.7.0, on Python 3.8.12

failed connecting to host q must be exactly 160, 224, or 256 bits long

and
failed: true
    return_code: 127
    stderr: 'bash: /tmp/62e80e250e6a518eabd95ff4/check_loadavg.py: No such file or directory'
    stdout: ''
    succeeded: false
</div>

**Comment by armab** [comment]
Perhaps try to also ask in the Slack community, maybe someone would be able to help you.
But this is an Open Source community and people are helping you as they can.


There is no need to create a duplicate issue. Closing this one.
