### ISSUE TITLE
Can we have conditions in a rule to match for multiple values for a trigger type?

### ISSUE THREAD

**Issue by zsmanjot** [StackStorm/st2#5700]
I am using below trigger in my rule. In my environment we have different types of servers serving different role. It can be SME, SMBA , SMCA , SMCDS. So whenver the alert comes for any of these roles the pattern should get matched and the rule should be invoked. 

`  trigger.role:
    pattern: ".*_SME$"
    type: matchregex

`
Currently i have it defined for one of the role and it is working fine, but how we can add rest of the patterns? If for example at a time 2 alerts for different role comes , the rule should be invoked for both of them. I tried using this but it did not work.

`  trigger.role:
    #pattern: ".*_SME$"
    pattern: (.*_SME$)(.*_SMBA$)
    type: matchregex
`

Seeking an update on this.

**Comment by nzlosh** [comment]
Regex provides `or` logic operator or class character and quantifiers that should meet your needs.  Use https://regex101.com/ to test your syntax and read up about how to use regex.

**Comment by zsmanjot** [comment]
i am using regex only but it does not pick up.  But i am using it like below all together in one line. If i mention only one role, it works fine. I think this is not the correct way of using it.

`trigger.role:
pattern: (.*_SME$)(.*_SMBA$)
type: matchregex`

**Comment by nzlosh** [comment]
The site provided above has documentation to help write regular expressions as well as evaluate if the regex functions as expected.  If writing regular expressions is not your thing, another approach would be to write 1 rule file per pattern.

**Comment by nzlosh** [comment]
Great to hear you've got a working solution :+1:
