### ISSUE TITLE
Where are "Rules" saved?

### ISSUE THREAD

**Issue by rickogg** [StackStorm/st2#5767]
## SUMMARY

When editing a new "Rule" within the StackStorm GUI we define the "Name" of the Rule and the "Pack" that the rule is defined under along with associated "Triggers"; however, when checking the /pack/<pack name>/rules/ directory we would expect to see an associated yaml file defined but the rules directory is entirely empty??

### STACKSTORM VERSION

st2 3.7.0, on Python 3.8.13

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

CentOS 8, one-line install

## Steps to reproduce the problem

Create a new rule within the StackStorm GUI and define the associated "pack"

## Expected Results

We would expect to see a yaml file within the pack/<packname>/rule/ directory

## Actual Results

The rule seems to be defined elseware as the rule does survive a server reboot; however, we cannot seem to locate the yaml file
Also, when issuing the st2 rule get <pack.rule-name> the metadata_file is blank

**Comment by arms11** [comment]
I do not believe this is a correct expectation with respect to Infrastructure as Code that Stackstorm promotes. The rule you see survive is stored in the MongoDB (persistence). The yaml file change/creation on the disk is never expected. That as far as I know must come from the rule definition yaml and registration of the pack.

**Comment by amanda11** [comment]
@arms11 is correct. When creating rules in the UI then they are stored into MongoDB directly and do not create yaml files on disk. The only case where the UI would create the yaml files is in the workflow composer which creates the associated workflow yaml files.

**Comment by rickogg** [comment]
Thanks, I suspected as much but thank you for confirming.
