### ISSUE TITLE
ISSUE: Try to compile source code in windows

### ISSUE THREAD

**Issue by ShimingLee** [StackStorm/st2#5788]
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting st2-auth-ldap
  Cloning https://gitee.com/mirrors_StackStorm/st2-auth-ldap.git (to revision v3.7) to c:\users\lism12\appdata\local\temp\pip-install-7afp9ewd\st2-auth-ldap_2a958b35cc6643e9acf4e601f09f88f2
  Resolved https://gitee.com/mirrors_StackStorm/st2-auth-ldap.git to commit a4dc11b040e4a833a5499d579fb83e99c695ac09
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting python-ldap==3.4.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/41/e2/6b12190c171b78d1cd8c9d0d3380d18b85959aecb2b1267f7bdd5b66cd8f/python-ldap-3.4.0.tar.gz (376 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting cachetools<2.1.0,>=2.0.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ac/e8/5492fd5ada0b05a1bc485bcb634b559acdec59383eef5c4203b5e22be296/cachetools-2.0.1-py2.py3-none-any.whl (11 kB)
Collecting pyasn1>=0.3.7
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pyasn1-modules>=0.1.5
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/95/de/214830a981892a3e286c3794f41ae67a4495df1108c3da8a9f62159b9a9d/pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Building wheels for collected packages: st2-auth-ldap, python-ldap
  Building wheel for st2-auth-ldap (setup.py): started
  Building wheel for st2-auth-ldap (setup.py): finished with status 'done'
  Created wheel for st2-auth-ldap: filename=st2_auth_ldap-3.7.0-py3-none-any.whl size=19299 sha256=196380d7794ab72f9413302f0a27e72cd7bc2a35be7959c665efc2f2498ad8c8
  Stored in directory: C:\Users\lism12\AppData\Local\Temp\pip-ephem-wheel-cache-t8cf3ke1\wheels\3a\e5\59\bdbf9a2647f759ff4f39f0648b92b5f0168ae4b933038a7e74
  Building wheel for python-ldap (pyproject.toml): started
  Building wheel for python-ldap (pyproject.toml): finished with status 'error'
Successfully built st2-auth-ldap
Failed to build python-ldap

  Running command git clone --filter=blob:none --quiet https://gitee.com/mirrors_StackStorm/st2-auth-ldap.git 'C:\Users\lism12\AppData\Local\Temp\pip-install-7afp9ewd\st2-auth-ldap_2a958b35cc6643e9acf4e601f09f88f2'
  Running command git checkout -b v3.7 --track origin/v3.7
  branch 'v3.7' set up to track 'origin/v3.7'.
  Switched to a new branch 'v3.7'
  error: subprocess-exited-with-error
  
  Building wheel for python-ldap (pyproject.toml) did not run successfully.
  exit code: 1
  
  [110 lines of output]
  C:\Users\lism12\AppData\Local\Temp\pip-build-env-ostbco0v\overlay\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
    warnings.warn(msg, warning_class)
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-38
  copying Lib\ldapurl.py -> build\lib.win-amd64-cpython-38
  copying Lib\ldif.py -> build\lib.win-amd64-cpython-38
  creating build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\async.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\asyncsearch.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\cidict.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\compat.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\constants.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\dn.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\filter.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\functions.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\ldapobject.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\logger.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\modlist.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\pkginfo.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\resiter.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\sasl.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\syncrepl.py -> build\lib.win-amd64-cpython-38\ldap
  copying Lib\ldap\__init__.py -> build\lib.win-amd64-cpython-38\ldap
  creating build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\deref.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\libldap.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\openldap.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\pagedresults.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\ppolicy.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\psearch.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\pwdpolicy.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\readentry.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\sessiontrack.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\simple.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\sss.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\vlv.py -> build\lib.win-amd64-cpython-38\ldap\controls
  copying Lib\ldap\controls\__init__.py -> build\lib.win-amd64-cpython-38\ldap\controls
  creating build\lib.win-amd64-cpython-38\ldap\extop
  copying Lib\ldap\extop\dds.py -> build\lib.win-amd64-cpython-38\ldap\extop
  copying Lib\ldap\extop\passwd.py -> build\lib.win-amd64-cpython-38\ldap\extop
  copying Lib\ldap\extop\__init__.py -> build\lib.win-amd64-cpython-38\ldap\extop
  creating build\lib.win-amd64-cpython-38\ldap\schema
  copying Lib\ldap\schema\models.py -> build\lib.win-amd64-cpython-38\ldap\schema
  copying Lib\ldap\schema\subentry.py -> build\lib.win-amd64-cpython-38\ldap\schema
  copying Lib\ldap\schema\tokenizer.py -> build\lib.win-amd64-cpython-38\ldap\schema
  copying Lib\ldap\schema\__init__.py -> build\lib.win-amd64-cpython-38\ldap\schema
  creating build\lib.win-amd64-cpython-38\slapdtest
  copying Lib\slapdtest\_slapdtest.py -> build\lib.win-amd64-cpython-38\slapdtest
  copying Lib\slapdtest\__init__.py -> build\lib.win-amd64-cpython-38\slapdtest
  running egg_info
  writing Lib\python_ldap.egg-info\PKG-INFO
  writing dependency_links to Lib\python_ldap.egg-info\dependency_links.txt
  writing requirements to Lib\python_ldap.egg-info\requires.txt
  writing top-level names to Lib\python_ldap.egg-info\top_level.txt
  reading manifest file 'Lib\python_ldap.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'Doc\.build'
  adding license file 'LICENCE'
  writing manifest file 'Lib\python_ldap.egg-info\SOURCES.txt'
  C:\Users\lism12\AppData\Local\Temp\pip-build-env-ostbco0v\overlay\Lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'slapdtest.certs' as data is deprecated, please list it in `packages`.
      !!
  
  
      ############################
      # Package would be ignored #
      ############################
      Python recognizes 'slapdtest.certs' as an importable package,
      but it is not listed in the `packages` configuration of setuptools.
  
      'slapdtest.certs' has been automatically added to the distribution only
      because it may contain data files, but this behavior is likely to change
      in future versions of setuptools (and therefore is considered deprecated).
  
      Please make sure that 'slapdtest.certs' is included as a package by using
      the `packages` configuration field or the proper discovery methods
      (for example by using `find_namespace_packages(...)`/`find_namespace:`
      instead of `find_packages(...)`/`find:`).
  
      You can read more about "package discovery" and "data files" on setuptools
      documentation page.
  
  
  !!
  
    check.warn(importable)
  creating build\lib.win-amd64-cpython-38\slapdtest\certs
  copying Lib\slapdtest\certs\README -> build\lib.win-amd64-cpython-38\slapdtest\certs
  copying Lib\slapdtest\certs\ca.conf -> build\lib.win-amd64-cpython-38\slapdtest\certs
  copying Lib\slapdtest\certs\ca.pem -> build\lib.win-amd64-cpython-38\slapdtest\certs
  copying Lib\slapdtest\certs\client.conf -> build\lib.win-amd64-cpython-38\slapdtest\certs
  copying Lib\slapdtest\certs\client.key -> build\lib.win-amd64-cpython-38\slapdtest\certs
  copying Lib\slapdtest\certs\client.pem -> build\lib.win-amd64-cpython-38\slapdtest\certs
  copying Lib\slapdtest\certs\gencerts.sh -> build\lib.win-amd64-cpython-38\slapdtest\certs
  copying Lib\slapdtest\certs\gennssdb.sh -> build\lib.win-amd64-cpython-38\slapdtest\certs
  copying Lib\slapdtest\certs\server.conf -> build\lib.win-amd64-cpython-38\slapdtest\certs
  copying Lib\slapdtest\certs\server.key -> build\lib.win-amd64-cpython-38\slapdtest\certs
  copying Lib\slapdtest\certs\server.pem -> build\lib.win-amd64-cpython-38\slapdtest\certs
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  building '_ldap' extension
  creating build\temp.win-amd64-cpython-38
  creating build\temp.win-amd64-cpython-38\Release
  creating build\temp.win-amd64-cpython-38\Release\Modules
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 "-DLDAPMODULE_AUTHOR=python-ldap project" "-DLDAPMODULE_LICENSE=Python style" -IModules -ID:\app\Anaconda3\envs\st2\include -ID:\app\Anaconda3\envs\st2\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" /TcModules/LDAPObject.c /Fobuild\temp.win-amd64-cpython-38\Release\Modules/LDAPObject.obj
  LDAPObject.c
  C:\Users\lism12\AppData\Local\Temp\pip-install-7afp9ewd\python-ldap_cda61375a8e44412aeeb1125b331b71e\Modules\common.h(15): fatal error C1083: 无法打开包括文件: “lber.h”: No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-ldap
ERROR: Could not build wheels for python-ldap, which is required to install pyproject.toml-based projects

how to fixed this problem?

**Comment by nzlosh** [comment]
StackStorm is developed and tested against the x86_64 architecture on the Linux platform, specifically Ubuntu and CentOS.  The error you're getting is related to your complier environment, for which we can't provide support.

My personal opinion would be to not attempt to get StackStorm running natively on Windows as there is no guarantee that StackStorm will function correctly even if you get past compiler errors and each subsequent upgrade risks breaking which is less than ideal for a production environment.  I'd recommend running StackStorm on a native Linux OS inside a virtual machine or docker container for  Windows hosts.

**Comment by ShimingLee** [comment]
@nzlosh @armab But I still think there will be a lot of people using windows for learning and development work, so I recommend supporting compilation on windows

**Comment by nzlosh** [comment]
StackStorm is open source and supported by volunteers with limited time and resource.  Unless there is an overwhelming demand to run StackStorm natively on Windows, I doubt anyone will be willing to invest in it.

The main demand is to run StackStorm in Kubernetes at cloud providers like Azure/Google/Amazon.  They all run Linux containers.  Windows has WSL and supports both virtual machines and containers.  Mac OS X supports virtual machines and containers.  This means, providing Linux containers (which are publicly available on Docker hub), Linux/Windows and Mac users can run StackStorm on their machines.

That said, if you feel compelled to run StackStorm natively on Windows, you're completely free to do that, but StackStorm maintainers will not be able to provide official support for such an endeavour.
