### ISSUE TITLE
Mongodb slow query

### ISSUE THREAD

**Issue by chain312** [StackStorm/st2#5805]
## SUMMARY

Mongodb slow query

### STACKSTORM VERSION

st2 3.7.8, on python 3.8.10

##### OS, environment, install method

docker deployment 

## Steps to reproduce the problem

When I input 20,000 pieces of data at a time in a short time, the problem of slow query by mongodb occurs. It takes more than ten seconds to read a piece of data. The cpu of the host where the mongodb container is located is 32G, the memory is 128G, and the utilization rate is not high.
The remaining 80% cpu.
![image](https://user-images.githubusercontent.com/30886624/201830685-41e875e5-4e8b-4e0b-8c48-31882f504587.png)
Memory remaining 90%
![image](https://user-images.githubusercontent.com/30886624/201830755-862f22ee-8063-4227-ae73-d3edcaabfc50.png)
Query time
![image](https://user-images.githubusercontent.com/30886624/201830904-21af9fb8-b38b-4926-85c9-84dd652bab83.png)
Size and number of action _ execution _ scheduling _ queue _ item _ d _ b tables
<img width="474" alt="3f0eb2c465156d3ef40d50ea3e55a01" src="https://user-images.githubusercontent.com/30886624/201831024-40f2584f-5168-419a-b5f5-9c40138002b3.png">

## Expected Results

Mongo read time is reduced so that I can run more action.

## Actual Results

I entered 20,000 pieces of data into the playbook.

Thanks!

**Comment by chain312** [comment]
I changed mongodb to fix this problem

**Comment by nzlosh** [comment]
Would you mind sharing what you changed to resolve this issue so that other people who encounter the same problem have an hint on how to resolve it?

**Comment by chain312** [comment]
> Would you mind sharing what you changed to resolve this issue so that other people who encounter the same problem have an hint on how to resolve it?

I have optimized the mongo sql index by creating an index in the [sort] field

**Comment by armab** [comment]
@chain312 Good to hear! Is it something you could contribute to StackStorm as a PR?

It would save you from doing the same operation for every new st2 installation and also make the community benefit from the enhancement.

**Comment by chain312** [comment]
> @chain312 Good to hear! Is it something you could contribute to StackStorm as a PR?
> 
> It would save you from doing the same operation for every new st2 installation and also make the community benefit from the enhancement.

Hello, mongodb tuning is not written code. Can I write it in https://github.com/StackStorm/st2docs project?

**Comment by armab** [comment]
The index creation in MongoDB is part of StackStorm initialization.
See examples of the past PRs adding DB schema/index changes:
- https://github.com/StackStorm/st2/pull/5568
- https://github.com/StackStorm/st2/pull/4690

What was the index you've added?

**Comment by chain312** [comment]
> The index creation in MongoDB is part of StackStorm initialization. See examples of the past PRs adding DB schema/index changes:
> 
> * [Change compound index to improve query performance #5568](https://github.com/StackStorm/st2/pull/5568)
> * [Limit database index field names to 65 characters #4690](https://github.com/StackStorm/st2/pull/4690)
> 
> What was the index you've added?

Thank you. I will submit the merge request later

**Comment by chain312** [comment]
> The index creation in MongoDB is part of StackStorm initialization. See examples of the past PRs adding DB schema/index changes:
> 
> * [Change compound index to improve query performance #5568](https://github.com/StackStorm/st2/pull/5568)
> * [Limit database index field names to 65 characters #4690](https://github.com/StackStorm/st2/pull/4690)
> 
> What was the index you've added?
I have submitted the code for your review
[Add a federated index to resolve mongo slow queries](https://github.com/StackStorm/st2/pull/5818)
