### ISSUE TITLE
Cannot upgrade ST2

### ISSUE THREAD

**Issue by rstorch01** [StackStorm/st2#5872]
Hello,

Updates are failing on our stackstorm server.  We use SpaceWalk for updates.  Do you know how to override this?
Error:
Error while executing packages action: Package st2-3.7.0-2.x86_64.rpm is not signed [[6]]" (code -1)

Operating system: `uname -a`, `./etc/lsb_release` or `cat /etc/redhat-release`
CentOS Linux release 7.9.2009 (Core)
    
StackStorm version: `st2 --version`     st2 3.6.0, on Python 3.6.8
       
  Actual package versions of all packages (st2, st2web, st2chatops, nginx, mongo, rabbitmq-server)
  st2web-3.6.0-1.x86_64        st2-3.6.0-3.x86_64
  
Contents of /etc/st2/st2.conf are attached
          
Output of st2ctl status
st2ctl status
##### st2 components status #####
st2actionrunner PID: 1146
st2actionrunner PID: 1165
st2actionrunner PID: 1171
st2actionrunner PID: 1182
st2actionrunner PID: 1189
st2actionrunner PID: 1199
st2actionrunner PID: 1208
st2actionrunner PID: 1215
st2actionrunner PID: 1228
st2actionrunner PID: 1234
st2api PID: 1035
st2api PID: 86277
st2stream PID: 1046
st2stream PID: 75848
st2auth PID: 1057
st2auth PID: 97956
st2garbagecollector PID: 1038
st2notifier PID: 1047
st2rulesengine PID: 1037
st2sensorcontainer PID: 1040
st2chatops is not running.
st2timersengine PID: 1039
st2workflowengine PID: 1053
st2scheduler PID: 1050
[st2conf.txt](https://github.com/StackStorm/st2/files/10501689/st2conf.txt)

#Issue details

**Comment by mamercad** [comment]
Have you imported [the GPG keys](https://docs.stackstorm.com/install/rhel7.html#setup-repositories)?

**Comment by rstorch01** [comment]
Thank you.  I see that page mentions a script that sets up the gpg key in addition to doing many other things.  I looked through the script to find the command that imports the GPG keys but am not sure exactly which it is and I don't want to break my system by guessing.  I see that there is a StackStorch_stable.repo on my server but it is empty.  

Do you know where I can find the import command I need?  Thank you.

**Comment by mamercad** [comment]
```shell
[root@6e3bf2dcadfb /]# curl -s https://packagecloud.io/install/repositories/StackStorm/stable/script.rpm.sh | bash
Detected operating system as centos/7.
Checking for curl...
Detected curl...
Downloading repository file: https://packagecloud.io/install/repositories/StackStorm/stable/config_file.repo?os=centos&dist=7&source=script
done.
Installing pygpgme to verify GPG signatures...
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.lug.mtu.edu
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: linux-mirrors.fnal.gov
 * updates: mirror.genesishosting.com
StackStorm_stable-source/signature                                                                                                                         |  819 B  00:00:00
Retrieving key from https://packagecloud.io/StackStorm/stable/gpgkey
Importing GPG key 0xF6C28448:
 Userid     : "https://packagecloud.io/StackStorm/stable (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: 2664 b321 ca26 c6be fe81 aa46 723c b7a7 f6c2 8448
 From       : https://packagecloud.io/StackStorm/stable/gpgkey
StackStorm_stable-source/signature                                                                                                                         |  951 B  00:00:02 !!!
StackStorm_stable-source/primary
```

Suggestion for the future, do it in Docker?

**Comment by mamercad** [comment]
```shell
[root@6e3bf2dcadfb /]# curl --location --silent https://packagecloud.io/StackStorm/stable/gpgkey
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.11 (GNU/Linux)

mQINBFu7nTUBEACdCuGzc/L7qVF1GIn7Mu1X+KtrX1jZFX9SkpefOib34hEQLqTi
C/Im7vPLHpIo7BxaqIsyFAGn/YmxO3iVNDMFXVx6+XmDxY1s4I97nR9RTbtuvSe1
1nPotThzjXvxivPw5zSGuVKLog8JFPzu+G1bXHOgQgOuPzBKTrqDzFHKzm698SED
...
```

**Comment by mamercad** [comment]
If the lack of the GPG key is the issue you're seeing, mind closing this?
