### ISSUE TITLE
choice which actionrunner to run the job

### ISSUE THREAD

**Issue by zhenglisai** [StackStorm/st2#5892]
can we define job to execute on which actionrunner ?

our actionrunner run on different servers which have different firewall policy, wo hope some job run on actionrunner-1 and other job run on actionruner-2,

i know actionrunner read jobs from rabbitmq, is this possible for actionrunner to choice message in rabbitmq?

**Comment by rush-skills** [comment]
Hey @zhenglisai 
Currently it is not possible to specify which action runner which pick a specific job.
