### ISSUE TITLE
Stackstorm HA not retriving data

### ISSUE THREAD

**Issue by ManuGeodis** [StackStorm/st2#5915]
@armab 

When I log back in to my HA Environment, which was previously operating, it now displays this problem.

Unable to retrieve history. See details in developer tools console.

Logging in and registering the setups works for me. However I couldn't retrieve any lists.

Please help on this.

**Comment by ManuGeodis** [comment]
st2 pack install sensu
ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by guzzijones** [comment]
take a look at your stackstorm logs and report back any interesting findings please.
