### ISSUE TITLE
Unable to use splunk action

### ISSUE THREAD

**Issue by n0n4m3f0r** [StackStorm/st2#5937]
## SUMMARY

I have a stackstorm installed v3.8.0 and i installed the splunk pack the problem is that after install i cant find the actions of the splunk on user portal, on the pod i can the actions dir is created.
### STACKSTORM VERSION

Paste the output of ``st2 --version``: st2 3.8.0, on Python 3.8.10

##### OS, environment, install method

Stackstorm is running on Kubernetes

## Steps to reproduce the problem
st2 pack install splunk -t TOKEN
st2 action list -t TOKEN

## Expected Results

Expected result after installing splunk pack use available actions

## Actual Results

Using the UI no splunk actions was found, but when i check the directory on the pod i can see the actions directory is created
![image](https://user-images.githubusercontent.com/5504274/225054962-4f18cdb7-1164-4915-900b-417b88a94f4d.png)
I checked if the pack is installed with the command `st2 pack list` and i can see that is there.

![image](https://user-images.githubusercontent.com/5504274/225055349-7cd52b01-8379-4079-b248-d3f6029342f4.png)

Thanks!

**Comment by guzzijones** [comment]
are you installing this on a pod?  If so there is a helm chart for stackstorm you should use.  st2 pack install doesn't work in docker environments due to the nature of pods not saving state.
