### ISSUE TITLE
Action core.local_sudo can't work 

### ISSUE THREAD

**Issue by hgjsj** [StackStorm/st2#5967]
## SUMMARY

Action local_sudo return failure

st2 3.8.0

RHEL 7.9

Company policy doesn't allow "Defaults requiretty" disabled in sudoer file, and there is script to scan and enable it if it is disalbed every week. This caused a lot of workflow failures if it included action "core.local_sudo", For resolved this issue, I added one line in sudoers file what allow user "stanley" invoke sudo command without tty, something like below.

**Defaults requiretty
Defaults:stanley !requiretty**

I hope this can resolve issue, but actullay "local_sudo" still pop error that no tty

**"sudo: sorry, you must have a tty to run sudo"**

What am I missing here?  and how to resolve this?

I guess this is not only for action local_sudo impacted, but a lot of custom python actions which need invoke executable in OS.

**Comment by guzzijones** [comment]
There are a lot of blogs online as to why this essentially does NOTHING for security. 
[stackexchange](https://unix.stackexchange.com/questions/65774/is-it-okay-to-disable-requiretty)

> Furthermore — and more damning for requiretty — no privilege is needed to create a tty, e.g. with [expect](http://en.wikipedia.org/wiki/Expect). So you might as well turn off requiretty: on its own, it does not provide a security advantage. It does provide a mild auditability advantage when executed by users (because the logs give a better idea of who invoked sudo and where they're coming from), but not when executed from a background job.

**Comment by hgjsj** [comment]
Thanks for your reply @guzzijones 

I made a workaroud to address this issue. Just disable root tty in sudoers file, and now action core.local_sudo works well.

> Defaults requiretty
> Defaults:root!requiretty

From this changes, it indicates that stackstorm invokes local command(defined in local_sudo action) with root permission(probably st2actionrunner service), rather than account "stanley" with prefix sudo.  I am courious why stackstorm still use sudo to execute command, even it is already running with root.
