### ISSUE TITLE
{"faultstring":"'ascii' codec can't encode characters in position 153-160: ordinal not in range(128)"}

### ISSUE THREAD

**Issue by PageGitHub6973** [StackStorm/st2#6001]
When I try to access the API endpoint api/v1/actions/ to create an action in StackStorm (st2), I encounter an error: “Failed to create action. Status code: 400. Error: {‘faultstring’: ‘‘ascii’ codec can’t encode characters in position 153-160: ordinal not in range(128)’}”. What could be the cause of this issue? I installed StackStorm (st2) in a Docker container using the command apt install st2 on Ubuntu 18.04 with Python 3.6.9.

**Comment by guzzijones** [comment]
Is your image set to use utf8 encoding?
