### ISSUE TITLE
Response Not Being Compressed

### ISSUE THREAD

**Issue by FileMagic** [StackStorm/st2#6005]
## SUMMARY

The st2 large results seems to not be compressed when I requested for a .tar.gz via st2web.

### STACKSTORM VERSION

Since commit b0dea78.

## Steps to reproduce the problem

1. Create a st2 execution with a large result output.
2. Try downloading both variants (compressed and uncompressed) outputs.
3. Check sizes and they are the same.

## Expected Results

The compressed blob size should be smaller.

## Actual Results

The compressed size is the same.

**Comment by FileMagic** [comment]
On initial glance I thought it was here:

https://github.com/StackStorm/st2/blob/b9aec99fc49507d0b5b199caa2b1c27f7f5e13a6/st2api/st2api/controllers/v1/actionexecutions.py#L463-L469

however, it looks like this is being passed back properly based on the python docs [here](https://docs.python.org/3/library/gzip.html#gzip.compress).

**Comment by guzzijones** [comment]
I am pretty sure this is due to us using an older st2web version.
