### ISSUE TITLE
Query Regarding WebUI Installation in StackStorm

### ISSUE THREAD

**Issue by karthickmardi** [StackStorm/st2#6024]
I'm currently facing challenges with the installation of StackStorm's WebUI on my Red Hat Enterprise Linux version 7.9 system. Previously, I had installed StackStorm but had to uninstall it for specific reasons. Now, as I attempt to reinstall it, I'm encountering some issues.

When I attempt to install the WebUI component, it appears to install successfully with the following message:Installed:
st2web.x86_64 0:3.8.0-1

However, when I check the status of the st2web service using the command:systemctl status st2web.service
I receive the following output:
st2web.service
Loaded: not-found (Reason: No such file or directory)
Active: failed (Result: start-limit) since Mon 2023-07-10 10:27:56 UTC; 1 months 8 days ago
Main PID: 23110 (code=exited, status=203/EXEC)

I would like to highlight that Nginx is installed and in an active state on my machine with the following status:
nginx is installed / Active and running
● nginx.service - nginx - high performance web server
Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
Active: active (running) since Wed 2023-07-26 11:36:32 UTC; 3 weeks 0 days ago

Additionally, both port 80 and port 443 are open on my machine.

Any assistance or guidance on resolving this issue with the st2web service. Your expertise and insights would be invaluable in helping me get StackStorm's WebUI up and running smoothly.

**Comment by nzlosh** [comment]
Closing as duplicate https://github.com/StackStorm/st2/discussions/6023
