### ISSUE TITLE
Unable to find the ActionDB instance

### ISSUE THREAD

**Issue by doing007** [StackStorm/st2#6032]
throught api to get actions parameters by id 
`
curl --request GET \
  --url http://10.xxx.xxx.xxx:8005/v1/actions/views/parameters/6518f9565f9a20c8062779a1 \
  --header 'St2-Api-Key: NjA1ZjI2Y]TFjNTA2MA' \
  --header 'X-Token: 12c8edafe8f' \
  --header 'content-type: application/json'
`

Get a error : 
`
{
	"faultstring": "Database lookup for id=\"6518f9565f9a20c8062779a1\" resulted in exception. Unable to find the ActionDB instance. {'id': '6518f9565f9a20c8062779a1'}"
}
`

**Comment by nzlosh** [comment]
You've leaked your StackStorm API token.  You should probably regenerate a new one.

Why do you think this id should exist?
