### ISSUE TITLE
st2 pack install failed cause by a six error

### ISSUE THREAD

**Issue by Laxiss-UwU** [StackStorm/st2#6033]
## Problem explications

I'm looking for installing st2 pack on my stackstorm server but i met some trouble when installing it cause by a six eror :

st2 pack install st2

For the "st2" pack, the following content will be registered:

actions   |  24
rules     |  0
sensors   |  0
aliases   |  12
triggers  |  0

Installation may take a while for packs with many items.

        [ succeeded ] init_task
        [ succeeded ] download_pack
        [ succeeded ] make_a_prerun
        [ succeeded ] get_pack_dependencies
        [ succeeded ] check_dependency_and_conflict_list
        [  failed   ] install_pack_requirements

id: 65266096caba51a13f177f2c
action.ref: packs.install
parameters:
  packs:
  - st2
status: failed
start_timestamp: Wed, 11 Oct 2023 08:45:10 UTC
end_timestamp: Wed, 11 Oct 2023 08:45:16 UTC
log:
  - status: requested
    timestamp: '2023-10-11T08:45:10.790000Z'
  - status: scheduled
    timestamp: '2023-10-11T08:45:10.866000Z'
  - status: running
    timestamp: '2023-10-11T08:45:10.899000Z'
  - status: failed
    timestamp: '2023-10-11T08:45:16.140000Z'
result:
  errors:
  - message: Execution failed. See result for details.
    result:
      exit_code: 1
      result: None
      stderr: "st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Setting up virtualenv for pack "st2" (/opt/stackstorm/packs/st2)
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Removing virtualenv in "/opt/stackstorm/virtualenvs/st2"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Virtualenv successfully removed.
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv for pack "st2" in "/opt/stackstorm/virtualenvs/st2"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv in "/opt/stackstorm/virtualenvs/st2" using Python binary "/opt/stackstorm/st2/bin/python"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Running command "/opt/stackstorm/st2/bin/virtualenv -p /opt/stackstorm/st2/bin/python --always-copy --verbose --no-download /opt/stackstorm/virtualenvs/st2" to create virtualenv.
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing base requirements
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing requirement six>=1.9.0,<2.0 with command /opt/stackstorm/virtualenvs/st2/bin/pip install six>=1.9.0,<2.0.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 214, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/setup_virtualenv.py", line 93, in run
    setup_pack_virtualenv(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/virtualenvs.py", line 118, in setup_pack_virtualenv
    install_requirement(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/virtualenvs.py", line 348, in install_requirement
    raise Exception(
**Exception: Failed to install requirement "six>=1.9.0,<2.0":**
"
      stdout: ''
    task_id: install_pack_requirements
    type: error
  output:
    conflict_list: []
    message: ''
    packs_list:
    - st2
    warning_list: null
+--------------------------+------------------------+-----------------------+-----------------------+--------------------+
| id                       | status                 | task                  | action                | start_timestamp    |
+--------------------------+------------------------+-----------------------+-----------------------+--------------------+
| 65266097216a8eddceb02bd5 | succeeded (0s elapsed) | init_task             | core.noop             | Wed, 11 Oct 2023   |
|                          |                        |                       |                       | 08:45:11 UTC       |
| 65266097216a8eddceb02be5 | succeeded (1s elapsed) | download_pack         | packs.download        | Wed, 11 Oct 2023   |
|                          |                        |                       |                       | 08:45:11 UTC       |
| 65266099216a8eddceb02bf5 | succeeded (0s elapsed) | make_a_prerun         | packs.virtualenv_prer | Wed, 11 Oct 2023   |
|                          |                        |                       | un                    | 08:45:13 UTC       |
| 65266099216a8eddceb02c05 | succeeded (1s elapsed) | get_pack_dependencies | packs.get_pack_depend | Wed, 11 Oct 2023   |
|                          |                        |                       | encies                | 08:45:13 UTC       |
| 6526609a216a8eddceb02c15 | succeeded (0s elapsed) | check_dependency_and_ | core.noop             | Wed, 11 Oct 2023   |
|                          |                        | conflict_list         |                       | 08:45:14 UTC       |
| 6526609a216a8eddceb02c25 | failed (2s elapsed)    | install_pack_requirem | packs.setup_virtualen | Wed, 11 Oct 2023   |
|                          |                        | ents                  | v                     | 08:45:14 UTC       |
+--------------------------+------------------------+-----------------------+-----------------------+--------------------+

(no proxy use on my infrastructure)

### STACKSTORM VERSION

st2 3.8.0, on Python 3.8.10

##### OS, environment, install method

Stackstorm is running on debian 11
I install st2 manually packets one by one

If you want to reproduce the problem install st2 like the method bellow and do the st2 pack install st2 command :

sudo apt-get install gnupg2 wget software-properties-common curl apt-transport-https debian-archive-keyring build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev libbz2-dev nginx git -y

sudo apt update &&  sudo apt upgrade -y

wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
sudo apt-get update -y
sudo apt-get install mongodb-org -y

sudo systemctl enable mongod.service
sudo systemctl start mongod.service
sudo apt update -y

wget https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_23.1.5-1~debian~stretch_amd64.deb
sudo dpkg -i esl-erlang_23.1.5-1~debian~stretch_amd64.deb
sudo apt --fix-broken install -y
sudo dpkg -i esl-erlang_23.1.5-1~debian~stretch_amd64.deb
sudo apt-get update -y
sudo apt-get install erlang erlang-nox -y

wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | sudo apt-key add -
sudo apt-get install rabbitmq-server -y

sudo systemctl enable rabbitmq-server.service
sudo systemctl start rabbitmq-server.service
sudo apt update -y

sudo apt-get install redis-server -y

sudo systemctl enable redis.service
sudo systemctl start redis.service
sudo apt update -y

curl -s https://packagecloud.io/install/repositories/StackStorm/stable/script.deb.sh | sudo bash
curl -fsSL https://packagecloud.io/StackStorm/stable/gpgkey | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/stackstorm.gpg
echo "deb https://packagecloud.io/StackStorm/stable/ubuntu/ focal main" > StackStorm_stable.list
sudo mv StackStorm_stable.list /etc/apt/sources.list.d/
sudo apt-get update -y
sudo apt-get install -y st2

sudo apt install  -y
wget https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tar.xz
tar -xf Python-3.8.10.tar.xz
sudo mv Python-3.8.10 /opt/Python-3.8.10

cd /opt/Python-3.8.10
sudo ./configure --enable-optimizations --enable-shared
sudo make altinstall
sudo ldconfig /opt/Python-3.8.10
sudo apt-get update -y

sudo /opt/stackstorm/st2/bin/python 'import st2common; print(st2common.__version__)'
cd ..
sudo mv Python-3.8.10 /usr/local/share/python3.8
sudo update-alternatives --install /usr/bin/python3 python3 /opt/stackstorm/st2/bin/python3.8 2

sudo cp -Rf /usr/local/lib/python3.8 /usr/lib/

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
source ~/.bashrc
nvm install v14.19.3 -y

cd
touch nodejs
chmod 700 nodejs
echo "Package: nodejs
Pin: origin deb.debian.org
Pin-Priority: 1001" > nodejs

sudo mv nodejs /etc/apt/preferences.d/
sudo apt update -y

sudo apt-get install st2chatops -y

sudo st2ctl start

sudo apt-get install st2web=3.7.0-1 -y
sudo apt-get install -y apache2-utils -y
sudo mkdir -p /etc/ssl/st2
sudo openssl req -x509 -newkey rsa:2048 -keyout /etc/ssl/st2/st2.key -out /etc/ssl/st2/st2.crt -days 999 -nodes -subj "/C=XXX/L=XXX/O=XXX/OU=XXX\ XXX/CN=$(hostname)"
sudo rm /etc/nginx/conf.d/default.conf
sudo rm -f /etc/nginx/sites-enabled/default
sudo cp /usr/share/doc/st2/conf/nginx/st2.conf /etc/nginx/conf.d/
sudo service nginx restart

sudo echo 'Ch@ngeMe' | sudo htpasswd -i /etc/st2/htpasswd adminUser
cd
sudo echo '# System-wide configuration

[api]
###Host and port to bind the API server.
host = 127.0.0.1
port = 9101
logging = /etc/st2/logging.api.gunicorn.conf
mask_secrets = True
###allow_origin is required for handling CORS in st2 web UI.
###allow_origin = http://myhost1.example.com:3000,http://myhost2.example.com:3000

[stream]
logging = /etc/st2/logging.stream.gunicorn.conf

[sensorcontainer]
logging = /etc/st2/logging.sensorcontainer.conf

[rulesengine]
logging = /etc/st2/logging.rulesengine.conf

[actionrunner]
logging = /etc/st2/logging.actionrunner.conf
virtualenv_opts = --always-copy

[notifier]
logging = /etc/st2/logging.notifier.conf

[garbagecollector]
logging = /etc/st2/logging.garbagecollector.conf

[timersengine]
logging = /etc/st2/logging.timersengine.conf

[auth]
host = 127.0.0.1
port = 9100
use_ssl = False
debug = False
enable = True
logging = /etc/st2/logging.auth.gunicorn.conf

mode = standalone

###Note: Settings below are only used in "standalone" mode
backend = flat_file
backend_kwargs = {"file_path": "/etc/st2/htpasswd"}

###Base URL to the API endpoint excluding the version (e.g. http://myhost.net:9101/)
api_url =

[system]
base_path = /opt/stackstorm

[webui]
###webui_base_url = https://mywebhost.domain

[syslog]
host = 127.0.0.1
port = 514
facility = local7
protocol = udp

[log]
excludes = requests,paramiko
redirect_stderr = False
mask_secrets = True

[system_user]
user = stanley
ssh_key_file = /home/stanley/.ssh/stanley_rsa

[messaging]
url = amqp://guest:guest@127.0.0.1:5672/

[ssh_runner]
remote_dir = /tmp
[workflow_engine]
logging = /etc/st2/logging.workflowengine.conf

[scheduler]
logging = /etc/st2/logging.scheduler.conf

[coordination]
url = redis://127.0.0.1:6379' > st2.conf
cd /etc/st2
sudo rm st2.conf
cd
sudo mv st2.conf /etc/st2/

sudo st2ctl restart-component st2api

sudo st2ctl reload
st2 action list --pack=core
st2 run core.local -- date -R

st2 login adminUser

**Comment by guzzijones** [comment]
format as code please so we can easily read the issue.

**Comment by guzzijones** [comment]
mongo 5.0 is definitely not supported.

**Comment by guzzijones** [comment]
it looks like you aren't able to pull six from pypi or other internal registry
```
Exception: Failed to install requirement "six>=1.9.0,<2.0":
```
