### ISSUE TITLE
''utf-8'' codec can''t decode byte 0x82 in position XX: invalid start byte'

### ISSUE THREAD

**Issue by Karthick31** [StackStorm/st2#6034]
Stackstorm winrm_ps_script action failure to stdout the non ascii characters
st2 version - 3.8.0
OS environment - RHEL 7

[root@server1 actions]# st2 run default.Ad_user_validation
..
id: 652788a0aec49d1752a2aaf0
action.ref: default.Ad_user_validation
context.user: st2admin
parameters:
  password: '********'
  username: svc_user
status: failed
start_timestamp: Thu, 12 Oct 2023 05:48:16 UTC
end_timestamp: Thu, 12 Oct 2023 05:48:18 UTC
result:
  error: '''utf-8'' codec can''t decode byte 0x82 in position 36: invalid start byte'
  traceback: "  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2actions/container/base.py", line 132, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/winrm_runner/winrm_ps_script_runner.py", line 47, in run
    return self.run_ps(ps_script, ps_params)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/winrm_runner/winrm_base.py", line 381, in run_ps
    return self._run_ps(encoded_ps, is_b64=True)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/winrm_runner/winrm_base.py", line 396, in _run_ps
    return self._translate_response(response)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/winrm_runner/winrm_base.py", line 261, in _translate_response
    result["stdout"] = result["stdout"].decode("utf-8")
"

**Comment by guzzijones** [comment]
This looks like old 2.7 code.  remove the `.decode` and you should be good to go.

**Comment by guzzijones** [comment]
if this is in st2 core, we will need to fix it actually.

**Comment by Karthick31** [comment]
@guzzijones - Could you please elaborate the steps. On which file, .decode should be removed ?

**Comment by Karthick31** [comment]
Thanks @Stealthii.

Replaced the below code in winrm_base.py & issue is fixed.

<         shell_id = session.protocol.open_shell(env_vars=env, working_directory=cwd, codepage=65001)
---
>         shell_id = session.protocol.open_shell(env_vars=env, working_directory=cwd)
