### ISSUE TITLE
Fix CI / Unit Tests Failing

### ISSUE THREAD

**Issue by FileMagic** [StackStorm/st2#6035]
## SUMMARY

There are currently failing tests in the StackStorm/st2 repo. This issue is going along with the MR to fix this issue and explain some of the decisions made while fixing the issue.

## Steps to reproduce the problem

Push to a branch on the StackStorm/st2 project and you will see the following failures currently.

![Screenshot from 2023-10-15 18-05-59](https://github.com/StackStorm/st2/assets/22534836/cb30447e-c397-4ea3-821a-1e17e103e810)

These errors seem to occurring due to the coverage being frozen as seen in `./scripts/ci/submit-codecov-coverage.sh`

![image](https://github.com/StackStorm/st2/assets/22534836/cbf37eda-81dc-4c98-a915-b3a9578b981f)

**Comment by FileMagic** [comment]
So it looks like [codecov](https://github.com/codecov/codecov-python) was actually deprecated as of February 1, 2022.

> This uploader is being deprecated by the Codecov team. We recommend migrating to our [new uploader](https://docs.codecov.com/docs/codecov-uploader) as soon as possible to prevent any lapses in coverage. [The new uploader is open source](https://github.com/codecov/uploader), and we highly encourage submitting Issues and Pull Requests.


So I am going to take a look at using the new uploader to get stuff going. I haven't ever used this so I'll take a look and see what I can do as I have some time here over the next week.

**Comment by armab** [comment]
> deprecated

Thanks for research!
