### ISSUE TITLE
JIRA SUBTASK action in JIRA pack

### ISSUE THREAD

**Issue by zsmanjot** [StackStorm/st2#6126]
Currently we have the JIRA actions  to create a JIRA ticket, to update JIRA fields , to link one issue with the other issue but could not see any action where in we can have the option to create a subtask under the same ticket. 

Could we have it in the pack please?

**Comment by nzlosh** [comment]
This isn't the correct repository for this issue and I'm unable to transfer it to the right one.  Can you please create a new one under the Jira pack repository.  https://github.com/StackStorm-Exchange/stackstorm-jira/issues
