### ISSUE TITLE
Slack Channel Community Sign-Up Link seems to be broken

### ISSUE THREAD

**Issue by gloriotech3** [StackStorm/st2#6132]
The Slack channel community signup link in the official website seems to be broken.

I could not access this link. Its throwing this error. Attached the screenshot for the same.

<img width="1129" alt="Screenshot 2024-02-12 at 4 41 55 PM" src="https://github.com/StackStorm/st2/assets/85011524/eb70c108-2a32-4b30-8b9e-b81e5bbdb4cf">
 [Slack Channel Sign-Up](https://stackstorm.com/community-signup)

**Comment by cognifloyd** [comment]
Closed by https://github.com/StackStorm/stackstorm.com/pull/23
