### ISSUE TITLE
Renew test SSL CA + Cert

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2#6137]
Our test SSL CA+cert just expired. We need to renew it and document how to do so.

https://github.com/StackStorm/st2/tree/master/st2tests/st2tests/fixtures/ssl_certs

Since this is for testing, I think we could do something like a 15 year duration.

**Comment by nzlosh** [comment]
Is it better to make it a once of task every 15 years or automate it and have it renew every 3 months?  There is no security consideration here, just a question of practicality.  If it breaks after 3 months, our memories may be fresh enough to know what to fix.

**Comment by cognifloyd** [comment]
I probably won't remember all of this in 3 months... so, in #6138 I did both:
- a script that takes care of running `openssl` (this can be the thing that helps me remember how)
- 15 year cert expiration (because its a test cert, so who cares?)
