### ISSUE TITLE
REFACTOR: st2reactor/container/utils needs some refactor love.

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#913]
Sensor model creation code is all in container/utils.py. These should be moved to st2common/services/sensor.py just like triggers. This way container/utils.py is smaller and focuses on high level APIs.

**Comment by enykeev** [comment]
Looks pretty refactored to me: https://github.com/StackStorm/st2/commit/a1d814dac2f7b1cda649906c37f89acef29c8485

Closing.
